import {
  campaignNodeSchema,
  combatConfigSchema,
  dialogueSequenceSchema,
  type CampaignNode,
  type CombatConfig,
} from './types';

type RawCombatConfig = Omit<CombatConfig, 'enemyVisualIds' | 'escortVisualIds'> &
  Partial<Pick<CombatConfig, 'enemyVisualIds' | 'escortVisualIds'>>;

const rawNodes: CampaignNode[] = [
  { id: 'lion-camp', type: 'start', x: -9.4, z: 0, icon: '◆', label: 'Camp du Lion', links: ['lion-audience'] },
  { id: 'lion-audience', type: 'story', x: -8.1, z: 0, icon: '♛', label: 'Audience d\u2019Alaric', links: ['lion-opening-ambush'], dialogueId: 'lion_briefing' },
  { id: 'lion-opening-ambush', type: 'random-combat', x: -6.9, z: 0, icon: '⚔', label: 'Piste des bêtes', links: ['lion-nomad-crossroads'], combatId: 'forest_ambush' },
  { id: 'lion-nomad-crossroads', type: 'mystery', x: -6.2, z: 0, icon: '◇', label: 'Croisement du rôdeur', links: ['lion-refugees'], dialogueId: 'mystery_recruit' },
  { id: 'lion-refugees', type: 'mystery', x: -5.6, z: 0, icon: '◇', label: 'Route des réfugiés', links: ['lion-first-trial-event', 'lion-first-trial-combat'], dialogueId: 'refugee_trial' },
  { id: 'lion-first-trial-event', type: 'mystery', x: -4.4, z: -1.1, icon: '◇', label: 'Rencontre sur la route', links: ['lion-first-refuge'], dialogueId: 'mystery_help' },
  { id: 'lion-first-trial-combat', type: 'random-combat', x: -4.4, z: 1.1, icon: '⚔', label: 'Patrouille Serpent', links: ['lion-first-refuge'], combatId: 'forest_patrol' },
  { id: 'lion-first-refuge', type: 'story', x: -3.1, z: 0, icon: '⌂', label: 'Refuge du Lion', links: ['lion-reserve-trail'] },
  { id: 'lion-reserve-trail', type: 'mystery', x: -1.9, z: 0, icon: '◇', label: 'Chemin des réserves', links: ['lion-valmir-road'], dialogueId: 'reserve_trail' },
  { id: 'lion-valmir-road', type: 'random-combat', x: -0.6, z: 0, icon: '⚔', label: 'Route de Bois-Clair', links: ['lion-second-trial-event', 'lion-second-trial-combat'], combatId: 'road_to_valmir' },
  { id: 'lion-second-trial-event', type: 'mystery', x: 0.6, z: -1.1, icon: '◇', label: 'Vieux sanctuaire', links: ['lion-village-choice'], dialogueId: 'old_shrine_event' },
  { id: 'lion-second-trial-combat', type: 'random-combat', x: 0.6, z: 1.1, icon: '⚔', label: 'Barrage renforcé', links: ['lion-village-choice'], combatId: 'serpent_checkpoint' },
  { id: 'lion-village-choice', type: 'story', x: 1.9, z: 0, icon: '⌂', label: 'Bois-Clair assiégé', links: ['lion-second-refuge'], dialogueId: 'village_choice' },
  { id: 'lion-second-refuge', type: 'story', x: 3.1, z: 0, icon: '⌂', label: 'Dernier feu du Lion', links: ['lion-witnesses'] },
  { id: 'lion-witnesses', type: 'mystery', x: 4.4, z: 0, icon: '◇', label: 'Témoins de Bois-Clair', links: ['lion-final-trial-event', 'lion-final-trial-combat'], dialogueId: 'witnesses_on_road' },
  { id: 'lion-final-trial-event', type: 'mystery', x: 5.6, z: -1.1, icon: '◇', label: 'Nid du jeune dragon', links: ['lion-shadow-signs'], dialogueId: 'mystery_dragon_roost' },
  { id: 'lion-final-trial-combat', type: 'random-combat', x: 5.6, z: 1.1, icon: '⚔', label: 'Ruines infestées', links: ['lion-shadow-signs'], combatId: 'ruins_guardians' },
  { id: 'lion-shadow-signs', type: 'mystery', x: 6.9, z: 0, icon: '?', label: 'Signes des Ombres', links: ['lion-final-refuge'], dialogueId: 'shadow_signs' },
  { id: 'lion-final-refuge', type: 'story', x: 7.5, z: 0, icon: '⌂', label: 'Refuge avant le Sceau', links: ['lion-final-judgement'], dialogueId: 'final_refuge' },
  { id: 'lion-final-judgement', type: 'boss', x: 8.1, z: 0, icon: '♛', label: 'Jugement du Sceau', links: [], dialogueId: 'lion_finale_judgement' },
];

const rawCombats: RawCombatConfig[] = [
  { id: 'village_defense', sceneId: 'bois_clair_burning', objective: 'Repoussez les pillards et protégez les habitants de Bois-Clair.', encounterLabel: 'Défense de Bois-Clair', encounterRank: 'elite', maxPlayerUnits: 4, preCombatDialogueId: 'pre_village_defense', postCombatDialogueId: 'village_defense_aftermath', rewards: { gold: 160, reputation: 10, materials: { red_gem: 2, iron_ore: 2 } } },
  { id: 'village_raid', sceneId: 'bois_clair_burning', objective: 'Sécurisez les coffres pendant que les Serpents dispersent les témoins.', encounterLabel: 'Raid sur Bois-Clair', encounterRank: 'elite', maxPlayerUnits: 4, preCombatDialogueId: 'pre_village_raid', postCombatDialogueId: 'village_raid_aftermath', rewards: { gold: 260, reputation: -15, materials: { red_gem: 3, iron_ore: 2 } } },
  { id: 'forest_patrol', sceneId: 'forest_route', objective: 'Éliminez la patrouille Serpent avant qu’elle ne donne l’alerte.', encounterLabel: 'Patrouille Serpent', encounterRank: 'normal', maxPlayerUnits: 4, rewards: { gold: 85, reputation: 1, materials: { red_gem: 1, iron_ore: 1 } } },
  { id: 'forest_ambush', sceneId: 'forest_route', objective: 'Défaites les créatures qui tendent l’embuscade sur la piste.', encounterLabel: 'Embuscade', encounterRank: 'normal', maxPlayerUnits: 4, rewards: { gold: 80, reputation: 1, materials: { red_gem: 1, iron_ore: 1 } } },
  { id: 'wolf_pack', sceneId: 'forest_route', objective: 'Repoussez la meute qui encercle la compagnie.', encounterLabel: 'Meute affamée', encounterRank: 'normal', maxPlayerUnits: 4, rewards: { gold: 80, reputation: 1, materials: { red_gem: 1, iron_ore: 1 } } },
  { id: 'spider_nest', sceneId: 'forest_route', objective: 'Détruisez le nid venimeux avant que la piste ne soit condamnée.', encounterLabel: 'Nid venimeux', encounterRank: 'normal', maxPlayerUnits: 4, rewards: { gold: 85, reputation: 1, materials: { red_gem: 1, iron_ore: 1 } } },
  { id: 'marsh_crossing', sceneId: 'forest_route', objective: 'Traversez les eaux infestées qui coupent la route de Bois-Clair.', encounterLabel: 'Passage des marais', encounterRank: 'normal', maxPlayerUnits: 4, rewards: { gold: 90, reputation: 1, materials: { red_gem: 1, iron_ore: 1 } } },
  { id: 'serpent_reprisals', sceneId: 'forest_route', objective: 'Brisez la troupe envoyée pour punir les actes de la compagnie.', encounterLabel: 'Représailles Serpent', encounterRank: 'normal', maxPlayerUnits: 4, rewards: { gold: 100, reputation: 0, materials: { red_gem: 1, iron_ore: 2 } } },
  { id: 'serpent_checkpoint', sceneId: 'forest_route', objective: 'Forcez le barrage Serpent sans laisser de messager s’échapper.', encounterLabel: 'Barrage des Serpents', encounterRank: 'normal', maxPlayerUnits: 4, rewards: { gold: 120, reputation: 1, materials: { red_gem: 2, iron_ore: 2 } } },
  { id: 'road_to_valmir', sceneId: 'forest_route', objective: 'Ouvrez la route de Bois-Clair avant que le village ne tombe.', encounterLabel: 'Route de Bois-Clair', encounterRank: 'normal', maxPlayerUnits: 4, rewards: { gold: 90, reputation: 1, materials: { red_gem: 1, iron_ore: 1 } } },
  { id: 'ruins_guardians', sceneId: 'lion_sanctum', objective: 'Éliminez les créatures qui infestent les ruines des Ombres.', encounterLabel: 'Ruines infestées', encounterRank: 'normal', maxPlayerUnits: 4, rewards: { gold: 110, reputation: 1, materials: { red_gem: 1, iron_ore: 2 } } },
  { id: 'serpent_hunters', sceneId: 'lion_sanctum', objective: 'Survivez aux chasseurs Serpent lancés sur votre piste.', encounterLabel: 'Chasseurs Serpent', encounterRank: 'normal', maxPlayerUnits: 4, preCombatDialogueId: 'pre_serpent_hunters', rewards: { gold: 125, reputation: 0, materials: { red_gem: 2, iron_ore: 2 } } },
  { id: 'serpent_duelist_trial', sceneId: 'forest_route', objective: 'Défaites le duelliste Serpent avant qu’il ne coupe la retraite.', encounterLabel: 'Duel sous les pins', encounterRank: 'elite', maxPlayerUnits: 4, preCombatDialogueId: 'pre_serpent_duelist_trial', rewards: { gold: 160, reputation: 2, materials: { red_gem: 3, iron_ore: 2 } } },
  { id: 'troll_crossing', sceneId: 'forest_route', objective: 'Forcez le passage gardé par le troll des pierres moussues.', encounterLabel: 'Passage du troll', encounterRank: 'elite', maxPlayerUnits: 4, preCombatDialogueId: 'pre_troll_crossing', rewards: { gold: 180, reputation: 2, materials: { red_gem: 3, iron_ore: 2 } } },
  { id: 'young_dragon_roost', sceneId: 'lion_sanctum', objective: 'Approchez le nid du jeune dragon et survivez à son courroux.', encounterLabel: 'Nid du jeune dragon', encounterRank: 'elite', maxPlayerUnits: 4, preCombatDialogueId: 'pre_young_dragon_roost', rewards: { gold: 260, reputation: 2, materials: { red_gem: 3, iron_ore: 2 } } },
  { id: 'serpent_captain', sceneId: 'lion_sanctum', objective: 'Traquez le général Serpent et exposez l’artefact des Ombres.', encounterLabel: 'Général Serpent', encounterRank: 'boss', maxPlayerUnits: 4, isBoss: true, preCombatDialogueId: 'serpent_pursuit_pre_combat', postCombatDialogueId: 'serpent_general_aftermath', rewards: { gold: 300, reputation: 12, materials: { red_gem: 5, iron_ore: 2 } } },
  { id: 'lion_chief', sceneId: 'lion_sanctum', objective: 'Défaites le champion du Lion et réclamez le Sceau.', encounterLabel: 'Duel pour le Sceau', encounterRank: 'boss', maxPlayerUnits: 4, isBoss: true, preCombatDialogueId: 'pre_lion_chief', postCombatDialogueId: 'lion_trial_aftermath', rewards: { gold: 200, reputation: 0, materials: { red_gem: 5, iron_ore: 2 } } },
];

const combatVisualComposition: Record<string, Partial<Pick<CombatConfig, 'enemyVisualIds' | 'bossVisualId' | 'escortVisualIds'>>> = {
  village_defense: { enemyVisualIds: ['serpent_raider', 'serpent_brute', 'serpent_raider'] },
  village_raid: { enemyVisualIds: ['serpent_raider', 'serpent_brute', 'serpent_raider', 'serpent_oracle'] },
  forest_patrol: { enemyVisualIds: ['serpent_raider', 'serpent_raider', 'serpent_brute'] },
  forest_ambush: { enemyVisualIds: ['wolf', 'cave_rat', 'forest_spider'] },
  wolf_pack: { enemyVisualIds: ['wolf', 'wolf', 'forest_badger'] },
  spider_nest: { enemyVisualIds: ['forest_spider', 'forest_spider', 'venom_serpent'] },
  marsh_crossing: { enemyVisualIds: ['marsh_toad', 'wild_boar', 'cave_rat'] },
  serpent_reprisals: { enemyVisualIds: ['serpent_raider', 'serpent_brute', 'serpent_raider'] },
  serpent_checkpoint: { enemyVisualIds: ['serpent_raider', 'serpent_brute', 'serpent_oracle'] },
  road_to_valmir: { enemyVisualIds: ['wild_boar', 'venom_serpent', 'forest_badger'] },
  ruins_guardians: { enemyVisualIds: ['goblin', 'skeleton', 'cave_rat'] },
  serpent_hunters: { enemyVisualIds: ['serpent_raider', 'serpent_brute', 'serpent_oracle', 'serpent_raider'] },
  serpent_duelist_trial: { enemyVisualIds: ['serpent_duelist_elite'] },
  troll_crossing: { enemyVisualIds: ['forest_troll_elite'] },
  young_dragon_roost: { enemyVisualIds: ['young_dragon_elite'] },
  serpent_captain: {
    bossVisualId: 'serpent_general_boss',
    escortVisualIds: [],
  },
  lion_chief: {
    bossVisualId: 'lion_champion',
    escortVisualIds: [],
  },
};

const rawDialogues = [
  {
    id: 'acte_ouverture',
    sceneArtId: 'acte_ouverture',
    steps: [
      {
        id: '1',
        speaker: 'Sage Séraphine',
        actorId: 'sage_seraphine',
        expression: 'neutral',
        tag: 'Lignée brisée',
        text: 'Votre clan est tombé. Le nom de votre père ne pèse plus qu’un murmure dans les salles où il régnait. Vous êtes le dernier fil d’une lignée effilée.',
        side: 'left',
        next: '2',
        effects: [],
        choices: [],
      },
      {
        id: '2',
        speaker: 'Intendant Maelor',
        actorId: 'maelor',
        expression: 'neutral',
        tag: 'Quête des Sceaux',
        text: 'Quatre Sceaux. Quatre clans. Le Tournoi des Grands n’ouvre ses portes qu’à ceux qui portent les marques de quatre seigneurs. Le premier se dresse devant nous : le Sceau du Lion.',
        side: 'left',
        next: '3',
        effects: [],
        choices: [],
      },
      {
        id: '3',
        speaker: 'Alistair',
        actorId: 'alistair',
        expression: 'neutral',
        tag: 'Le bouclier',
        text: 'Mon épée est à vous. Quand le clan est tombé, j’aurais pu fuir. Mais un bouclier ne sert à rien sans quelqu’un à protéger.',
        side: 'left',
        next: '4',
        effects: [],
        choices: [],
      },
      {
        id: '4',
        speaker: 'Marian',
        actorId: 'marian',
        expression: 'neutral',
        tag: 'La foi',
        text: 'Mes prières ramèneront les blessés. Tant que je tiendrai mon staff, aucun de nous ne tombera sans espoir de se relever.',
        side: 'left',
        next: '5',
        effects: [],
        choices: [],
      },
      {
        id: '5',
        speaker: 'Kestrel',
        actorId: 'kestrel',
        expression: 'neutral',
        tag: 'Les flèches',
        text: 'Mes flèches marqueront le chemin. Les Serpents ont des yeux partout — mais ils ne voient pas dans l’ombre d’un arbre.',
        side: 'left',
        next: '6',
        effects: [],
        choices: [],
      },
      {
        id: '6',
        speaker: 'Elara',
        actorId: 'elara',
        expression: 'neutral',
        tag: 'L’arcane',
        text: 'Et moi, je veillerai au-delà des routes. Les routes cachent plus que des Serpents — il y a des choses anciennes qui se réveillent. Mais c’est une autre histoire.',
        side: 'left',
        next: '7',
        effects: [],
        choices: [],
      },
      {
        id: '7',
        speaker: 'Intendant Maelor',
        actorId: 'maelor',
        expression: 'neutral',
        tag: 'En route',
        text: 'Le Lion, c’est Alaric. Un vieux loup qui ne donne rien sans retour. Son village, Bois-Clair, brûle sous les torches des Serpents. Sauvez-le, et le Sceau est à vous. Marchons.',
        side: 'left',
        next: null,
        effects: [],
        choices: [],
      },
    ],
  },
  {
    id: 'camp_departure',
    sceneArtId: 'lion_briefing',
    steps: [
      {
        id: '1',
        speaker: 'Intendant Maelor',
        actorId: 'maelor',
        expression: 'neutral',
        tag: 'Préparation',
        text: 'Le plateau du Lion ne pardonne pas les clans qui avancent sans provisions. Achetez ce qui manque, gardez vos matériaux, et ne gaspillez pas vos forces.',
        side: 'left',
        next: '2',
        effects: [],
        choices: [],
      },
      {
        id: '2',
        speaker: 'Sage Séraphine',
        actorId: 'sage_seraphine',
        expression: 'neutral',
        tag: 'Peu de moyens',
        text: 'Alors nous avançons avec peu. Des armes novices, quelques remèdes, et ce qu\u2019il faudra arracher à la route.',
        side: 'left',
        next: '3',
        effects: [],
        choices: [],
      },
      {
        id: '3',
        speaker: 'Intendant Maelor',
        actorId: 'maelor',
        expression: 'neutral',
        tag: 'Ancrage',
        text: 'Exactement. Les refuges seront vos points d\u2019ancrage. Entre eux, chaque combat, chaque choix et chaque fragment de minerai comptera.',
        side: 'left',
        next: null,
        effects: [],
        choices: [],
      },
    ],
  },
  {
    id: 'lion_briefing',
    sceneArtId: 'lion_briefing',
    steps: [
      {
        id: '1',
        speaker: 'Chef Alaric',
        actorId: 'alaric',
        expression: 'stern',
        tag: 'Vieux Lion',
        text: 'Votre clan réclame une place parmi les grands. Alors prouvez-le. Bois-Clair brûle sous les torches des Serpents. Sauvez ce qui peut encore l’être, et le Sceau du Lion entendra votre nom.',
        side: 'right',
        next: '2',
        effects: [],
        choices: [],
      },
      {
        id: '2',
        speaker: 'Sage Séraphine',
        actorId: 'sage_seraphine',
        expression: 'mystical',
        tag: 'Sage',
        text: 'Secourir les faibles restaurera plus que votre nom. Mais les Serpents ne frappent jamais sans un second piège.',
        side: 'left',
        next: '3',
        effects: [],
        choices: [],
      },
      {
        id: '3',
        speaker: 'Intendant Maelor',
        actorId: 'maelor',
        expression: 'neutral',
        tag: 'Intendant',
        text: 'Ou bien laissez les coffres parler. Un clan ruiné ne rachète pas son honneur avec de belles paroles.',
        side: 'left',
        effects: [],
        choices: [
          { text: 'Accepter la mission d’Alaric.', next: '4', effects: [{ type: 'setFlag', key: 'lionMissionAccepted', value: true }, { type: 'setFlag', key: 'lionMandateHonour', value: true }, { type: 'addReputation', amount: 3 }], outcomePreview: { mode: 'soft', hints: ['Serment clair devant le Lion', 'Alaric observe votre conduite'] } },
          { text: 'Accepter, mais réclamer une avance.', next: '5', effects: [{ type: 'setFlag', key: 'lionMissionAccepted', value: true }, { type: 'setFlag', key: 'lionMandateAdvance', value: true }, { type: 'addGold', amount: 60 }, { type: 'addReputation', amount: -3 }], outcomePreview: { mode: 'soft', hints: ['Soutien matériel immédiat', 'Chaque pièce pèsera dans le jugement'] } },
        ],
      },
      {
        id: '4',
        speaker: 'Chef Alaric',
        actorId: 'alaric',
        expression: 'stern',
        tag: 'Serment',
        text: 'Alors marchez. Revenez avec Bois-Clair debout, et le Sceau du Lion entendra votre nom.',
        side: 'right',
        next: null,
        effects: [{ type: 'setFlag', key: 'chapterStarted', value: true }],
        choices: [],
      },
      {
        id: '5',
        speaker: 'Chef Alaric',
        actorId: 'alaric',
        expression: 'stern',
        tag: 'Serment fragile',
        text: 'Vous négociez vite pour un clan qui demande confiance. Prenez l’or. Mais chaque pièce pèsera dans mon jugement.',
        side: 'right',
        next: null,
        effects: [{ type: 'setFlag', key: 'chapterStarted', value: true }, { type: 'setFlag', key: 'alaricDoubt', value: true }],
        choices: [],
      },
    ],
  },
  {
    id: 'refugee_trial',
    sceneArtId: 'refugee_trial',
    steps: [
      {
        id: '1',
        speaker: 'Mère réfugiée',
        actorId: 'refugee_mother',
        expression: 'fearful',
        tag: 'Route des réfugiés',
        text: 'Les Serpents ont pris nos vivres. Les enfants ne tiendront pas jusqu’au refuge. Partagerez-vous vos réserves ?',
        side: 'left',
        effects: [],
        choices: [
          { text: 'Partager vos réserves — 40 or.', next: '2', requiresGold: 40, effects: [{ type: 'addGold', amount: -40 }, { type: 'addReputation', amount: 8 }, { type: 'setFlag', key: 'helpedRefugees', value: true }], outcomePreview: { mode: 'soft', hints: ['Le clan gagne en respect', 'Les vivants passent avant les coffres'] } },
          { text: 'Prendre l’information et continuer.', next: '3', effects: [{ type: 'addGold', amount: 40 }, { type: 'addReputation', amount: -8 }, { type: 'setFlag', key: 'exploitedRefugees', value: true }], outcomePreview: { mode: 'soft', hints: ['Gain matériel modéré', 'Votre conduite sera jugée'] } },
        ],
      },
      {
        id: '2',
        speaker: 'Mère réfugiée',
        actorId: 'refugee_mother',
        expression: 'grateful',
        tag: 'Gratitude',
        text: 'Que le Lion se souvienne de vous. Une piste évite les guetteurs au nord.',
        side: 'left',
        next: null,
        effects: [{ type: 'addItem', itemId: 'potion', quantity: 1 }],
        choices: [],
      },
      {
        id: '3',
        speaker: 'Intendant Maelor',
        actorId: 'maelor',
        expression: 'neutral',
        tag: 'Calcul',
        text: 'Ils survivront peut-être. Vous, au moins, avez gagné de quoi survivre sûrement.',
        side: 'left',
        next: null,
        effects: [],
        choices: [],
      },
    ],
  },
  {
    id: 'reserve_trail',
    sceneArtId: 'reserve_trail',
    steps: [
      {
        id: '1',
        speaker: 'Intendant Maelor',
        actorId: 'maelor',
        expression: 'neutral',
        tag: 'Chemin des réserves',
        text: 'Un convoi Serpent transporte les coffres de Bois-Clair. L’intercepter enrichira la compagnie, mais retardera le secours.',
        side: 'left',
        effects: [],
        choices: [
          { text: 'Frapper le convoi et saisir les réserves.', next: '2', effects: [{ type: 'addGold', amount: 120 }, { type: 'addReputation', amount: -6 }, { type: 'setFlag', key: 'prioritizedLoot', value: true }], outcomePreview: { mode: 'soft', hints: ['Gain matériel important', 'Maelor approuve ce calcul'] } },
          { text: 'Marquer le convoi et continuer vers le village.', next: '3', effects: [{ type: 'addReputation', amount: 4 }, { type: 'setFlag', key: 'prioritizedVillage', value: true }], outcomePreview: { mode: 'soft', hints: ['Le clan gagne en respect', 'Les vivants passent avant les coffres'] } },
        ],
      },
      {
        id: '2',
        speaker: 'Intendant Maelor',
        actorId: 'maelor',
        expression: 'neutral',
        tag: 'Butin',
        text: 'Une bourse pleine vaut parfois mieux qu’une chanson de gratitude.',
        side: 'left',
        next: null,
        effects: [{ type: 'addItem', itemId: 'bomb', quantity: 1 }, { type: 'addItem', itemId: 'iron_ore', quantity: 1 }],
        choices: [],
      },
      {
        id: '3',
        speaker: 'Sage Séraphine',
        actorId: 'sage_seraphine',
        expression: 'stern',
        tag: 'Urgence',
        text: 'Les coffres peuvent attendre. Les vivants, non.',
        side: 'left',
        next: null,
        effects: [],
        choices: [],
      },
    ],
  },
  {
    id: 'village_choice',
    sceneArtId: 'village_choice',
    steps: [
      { id: '1', speaker: 'Villageoise de Bois-Clair', actorId: 'villageoise', expression: 'fearful', tag: 'En détresse', text: 'Ils emmènent les enfants vers le nord. Les coffres du village brûlent déjà. Aidez-nous — ils reviendront avant la nuit.', side: 'left', next: '2', effects: [], choices: [] },
      { id: '2', speaker: 'Pillard Serpent', actorId: 'serpent_raider', expression: 'hostile', tag: 'Menace', text: 'Le Lion n’est pas là. Personne ne vient pour Bois-Clair. Ceux qui prennent les armes meurent les premiers.', side: 'right', next: '3', effects: [], choices: [] },
      { id: '3', speaker: 'Sage Séraphine', actorId: 'sage_seraphine', expression: 'stern', tag: 'Urgence', text: 'Les enfants d’abord. Si nous perdons les vivants, le Sceau ne vaut rien.', side: 'left', next: '4', effects: [], choices: [] },
      { id: '4', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'neutral', tag: 'Survie', text: 'Un clan mort n’a pas d’honneur. Les réserves nous garderont en vie pour en gagner.', side: 'left', next: '5', effects: [], choices: [] },
      {
        id: '5',
        speaker: 'Villageoise de Bois-Clair',
        actorId: 'villageoise',
        expression: 'fearful',
        tag: 'Le choix',
        text: 'Qu’allez-vous sauver ?',
        side: 'left',
        effects: [],
        choices: [
          { text: 'Sauver les habitants.', next: '6', effects: [{ type: 'setFlag', key: 'missionSuccess', value: true }, { type: 'addReputation', amount: 10 }, { type: 'startCombat', combatId: 'village_defense' }], outcomePreview: { mode: 'soft', hints: ['Les vivants passent avant les coffres', 'Le village s\u2019en souviendra'] } },
          { text: 'Sécuriser les réserves.', next: '7', effects: [{ type: 'setFlag', key: 'missionSuccess', value: false }, { type: 'setFlag', key: 'missionGreed', value: true }, { type: 'addGold', amount: 200 }, { type: 'addReputation', amount: -10 }, { type: 'startCombat', combatId: 'village_raid' }], outcomePreview: { mode: 'soft', hints: ['Gain matériel important', 'Votre nom sera terni'] } },
        ],
      },
      { id: '6', speaker: 'Villageoise de Bois-Clair', actorId: 'villageoise', expression: 'grateful', tag: 'Bois-Clair', text: 'Merci. Le vieux pont mène directement à leurs positions.', side: 'left', next: null, effects: [], choices: [] },
      { id: '7', speaker: 'Villageoise de Bois-Clair', actorId: 'villageoise', expression: 'wounded', tag: 'Bois-Clair', text: 'Prenez l’or si vous le voulez… mais ne prétendez plus être nos protecteurs.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'mystery_recruit',
    sceneArtId: 'mystery_recruit',
    steps: [
      {
        id: '1',
        speaker: 'Cedric',
        actorId: 'cedric',
        expression: 'neutral',
        tag: 'Éclaireur nomade',
        text: 'Je connais les passages des Serpents. Mes dagues et mes yeux sont à vous. Cinquante pièces, et je rejoins votre compagnie.',
        side: 'right',
        effects: [],
        choices: [
          { text: 'Recruter Cedric — 50 or.', next: '2', requiresGold: 50, requiresReputationMin: 20, blockedText: 'Réputation insuffisante — Cedric ne suit pas les clans sans honneur.', effects: [{ type: 'addGold', amount: -50 }, { type: 'recruitUnit', unitId: 'rogue' }, { type: 'addReputation', amount: 3 }, { type: 'setFlag', key: 'recruitedCedric', value: true }] },
          { text: 'Décliner.', next: '3', effects: [] },
        ],
      },
      { id: '2', speaker: 'Cedric', actorId: 'cedric', expression: 'grateful', tag: 'Nouvel allié', text: 'Marché conclu. L’ombre et moi, nous vieillissons ensemble. Je vous montrerai où frapper — et où ne pas regarder.', side: 'right', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Cedric', actorId: 'cedric', expression: 'stern', tag: 'Éclaireur nomade', text: 'Alors évitez les lanternes vertes. Elles marquent leurs embuscades.', side: 'right', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'mystery_help',
    sceneArtId: 'mystery_help',
    steps: [
      {
        id: '1',
        speaker: 'Marchand blessé',
        actorId: 'survivor',
        expression: 'wounded',
        tag: 'Quête secondaire',
        text: 'Mon chariot est brisé et les loups approchent. Pouvez-vous partager quelques provisions ?',
        side: 'left',
        effects: [],
        choices: [
          { text: 'L’aider — 30 or.', next: '2', requiresGold: 30, effects: [{ type: 'addGold', amount: -30 }, { type: 'addReputation', amount: 8 }, { type: 'setFlag', key: 'helpedMerchant', value: true }] },
          { text: 'Continuer la route.', next: '3', effects: [{ type: 'addReputation', amount: -2 }, { type: 'setFlag', key: 'abandonedMerchant', value: true }] },
        ],
      },
      { id: '2', speaker: 'Marchand blessé', actorId: 'survivor', expression: 'grateful', tag: 'Allié', text: 'Je ferai parvenir des potions au refuge. Vous avez ma parole.', side: 'left', next: null, effects: [{ type: 'addItem', itemId: 'potion', quantity: 1 }], choices: [] },
      { id: '3', speaker: 'Marchand blessé', actorId: 'survivor', expression: 'wounded', tag: 'Abandonné', text: 'Allez… Je trouverai bien une autre âme charitable.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'mystery_ambush',
    sceneArtId: 'mystery_ambush',
    steps: [
      { id: '1', speaker: 'Pillard Serpent', actorId: 'serpent_raider', expression: 'hostile', tag: 'Embuscade', text: 'Vous avez suivi exactement le chemin que nous avions préparé.', side: 'right', next: null, effects: [{ type: 'startCombat', combatId: 'serpent_reprisals' }], choices: [] },
    ],
  },
  {
    id: 'serpent_duelist_trial',
    sceneArtId: 'serpent_duelist_trial',
    steps: [
      {
        id: '1',
        speaker: 'Duelliste Serpent',
        actorId: 'serpent_duelist_elite',
        expression: 'hostile',
        tag: 'Élite Serpent',
        text: 'Un guerrier masqué attend au milieu du sentier. Ses lames sont basses, patientes, déjà prêtes à punir la moindre hésitation.',
        side: 'right',
        effects: [],
        choices: [
          { text: 'Accepter le duel et briser son barrage.', next: '2', effects: [{ type: 'addReputation', amount: 2 }, { type: 'startCombat', combatId: 'serpent_duelist_trial' }] },
          { text: 'Contourner par les ronces — 60 or.', next: '3', requiresGold: 60, effects: [{ type: 'addGold', amount: -60 }, { type: 'addReputation', amount: -2 }] },
        ],
      },
      { id: '2', speaker: 'Sage Séraphine', actorId: 'sage_seraphine', expression: 'stern', tag: 'Défi', text: 'Les Serpents testent notre résolution. Que ce masque tombe devant le Lion.', side: 'left', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'neutral', tag: 'Détour', text: 'La route se referme derrière vous. Le duelliste ne tombe pas, mais nous gagnons quelques heures de vie.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'mystery_troll_crossing',
    sceneArtId: 'mystery_troll_crossing',
    steps: [
      {
        id: '1',
        speaker: 'Troll des pierres',
        actorId: 'forest_troll_elite',
        expression: 'hostile',
        tag: 'Défi secondaire',
        text: 'Le pont de mousse craque sous un troll énorme. Derrière lui, des sacs volés portent encore les sceaux de Bois-Clair.',
        side: 'right',
        effects: [],
        choices: [
          { text: 'Le défier et récupérer les sacs.', next: '2', effects: [{ type: 'addReputation', amount: 3 }, { type: 'startCombat', combatId: 'troll_crossing' }] },
          { text: 'Lui abandonner une bourse — 80 or.', next: '3', requiresGold: 80, effects: [{ type: 'addGold', amount: -80 }, { type: 'addReputation', amount: -1 }] },
        ],
      },
      { id: '2', speaker: 'Sage Séraphine', actorId: 'sage_seraphine', expression: 'stern', tag: 'Passage', text: 'S’il tombe, toute la vallée saura que la route n’appartient plus aux brutes.', side: 'left', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'neutral', tag: 'Tribut', text: 'Un prix laid, mais moins laid qu’un cercueil. Nous reviendrons plus lourds de fer.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'mystery_dragon_roost',
    sceneArtId: 'mystery_dragon_roost',
    steps: [
      {
        id: '1',
        speaker: 'Jeune dragon',
        actorId: 'young_dragon_elite',
        expression: 'hostile',
        tag: 'Rencontre rare',
        text: 'Une chaleur verte rampe entre les pierres. Au-dessus du vieux sanctuaire, un jeune dragon protège un nid de gemmes brutes.',
        side: 'right',
        effects: [],
        choices: [
          { text: 'Affronter la bête pour les gemmes.', next: '2', effects: [{ type: 'setFlag', key: 'challengedYoungDragon', value: true }, { type: 'startCombat', combatId: 'young_dragon_roost' }] },
          { text: 'Sceller l’accès et marquer le lieu.', next: '3', effects: [{ type: 'addReputation', amount: 4 }, { type: 'setFlag', key: 'sparedYoungDragon', value: true }] },
        ],
      },
      { id: '2', speaker: 'Sage Séraphine', actorId: 'sage_seraphine', expression: 'mystical', tag: 'Gemme vive', text: 'Ses écailles résonnent avec les Sceaux. Ce combat peut nous enrichir, ou nous annoncer aux Ombres.', side: 'left', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'neutral', tag: 'Marque', text: 'Vous laissez une balise discrète. Certains trésors valent mieux lorsqu’ils attendent le bon serment.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'mystery_treasure',
    sceneArtId: 'mystery_treasure',
    steps: [
      {
        id: '1',
        speaker: 'Intendant Maelor',
        actorId: 'maelor',
        expression: 'neutral',
        tag: 'Chariot abandonné',
        text: 'Ce chariot porte la marque des réfugiés. Personne ne nous a vus le trouver, et ses provisions couvriraient plusieurs jours de marche.',
        side: 'left',
        effects: [],
        choices: [
          { text: 'Rendre les provisions aux réfugiés.', next: '2', effects: [{ type: 'addReputation', amount: 4 }, { type: 'setFlag', key: 'returnedLostTreasure', value: true }], outcomePreview: { mode: 'soft', hints: ['Le clan gagne en respect', 'Le village s\u2019en souviendra'] } },
          { text: 'Prendre l’or et les provisions.', next: '3', effects: [{ type: 'addGold', amount: 100 }, { type: 'addItem', itemId: 'potion', quantity: 1 }, { type: 'addItem', itemId: 'iron_ore', quantity: 2 }, { type: 'addItem', itemId: 'grenade_incendiaire', quantity: 1 }, { type: 'addReputation', amount: -4 }, { type: 'setFlag', key: 'claimedLostTreasure', value: true }], outcomePreview: { mode: 'soft', hints: ['Gain matériel important', 'Votre conduite sera jugée'] } },
        ],
      },
      { id: '2', speaker: 'Sage Séraphine', actorId: 'sage_seraphine', expression: 'grateful', tag: 'Restitution', text: 'Un bien rendu vaut davantage qu’un coffre gagné sans témoin. La route se souviendra de ce geste.', side: 'left', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'stern', tag: 'Butin', text: 'Le clan mangera mieux ce soir. Ceux à qui appartenait ce chariot, beaucoup moins.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'mystery_shrine',
    sceneArtId: 'mystery_shrine',
    steps: [
      {
        id: '1',
        speaker: 'Apparition du sanctuaire',
        actorId: 'shrine_apparition',
        expression: 'mystical',
        tag: 'Autel des voyageurs',
        text: 'Une offrande repose devant le sceau gravé. La prendre financerait votre retour, mais priverait les prochains voyageurs de sa protection.',
        side: 'center',
        effects: [],
        choices: [
          { text: 'Préserver l’offrande et raviver l’autel.', next: '2', effects: [{ type: 'addReputation', amount: 3 }, { type: 'setFlag', key: 'preservedShrine', value: true }], outcomePreview: { mode: 'soft', hints: ['Les anciens rites sont respectés', 'Séraphine approuve ce choix'] } },
          { text: 'Briser le reliquaire et prendre l’offrande.', next: '3', effects: [{ type: 'addGold', amount: 80 }, { type: 'addReputation', amount: -4 }, { type: 'setFlag', key: 'desecratedShrine', value: true }], outcomePreview: { mode: 'soft', hints: ['Gain matériel modéré', 'Séraphine désapprouve ce choix'] } },
        ],
      },
      { id: '2', speaker: 'Sage Séraphine', actorId: 'sage_seraphine', expression: 'mystical', tag: 'Protection', text: 'La flamme reprend. D’autres survivront ici parce que nous avons choisi de laisser quelque chose derrière nous.', side: 'left', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'neutral', tag: 'Dernier profit', text: 'L’or servira au clan. Quant à la protection du lieu, elle devra désormais se passer de nous.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'serpent_informant',
    sceneArtId: 'mystery_ambush',
    steps: [
      {
        id: '1',
        speaker: 'Oracle Serpent',
        actorId: 'serpent_oracle',
        expression: 'fearful',
        tag: 'Informateur traqué',
        text: 'J’ai vu qui commande réellement les raids. Mes frères me traquent déjà. Protégez-moi jusqu’au camp, ou vendez-leur ma route et prenez leur or.',
        side: 'right',
        effects: [],
        choices: [
          { text: 'Protéger l’informateur et affronter ses chasseurs.', next: '2', effects: [{ type: 'addReputation', amount: 4 }, { type: 'setFlag', key: 'protectedInformant', value: true }, { type: 'startCombat', combatId: 'serpent_hunters' }], outcomePreview: { mode: 'soft', hints: ['Les témoins parleront', 'Les Serpents perdront du temps'] } },
          { text: 'Vendre sa route aux Serpents.', next: '3', effects: [{ type: 'addGold', amount: 120 }, { type: 'addReputation', amount: -6 }, { type: 'setFlag', key: 'betrayedInformant', value: true }], outcomePreview: { mode: 'soft', hints: ['Gain matériel important', 'Votre nom sera terni'] } },
        ],
      },
      { id: '2', speaker: 'Sage Séraphine', actorId: 'sage_seraphine', expression: 'stern', tag: 'Protection', text: 'Sa parole peut encore sauver des vies. Les chasseurs devront nous traverser pour l’atteindre.', side: 'left', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'neutral', tag: 'Marché', text: 'Ils paient pour récupérer un traître. Nous venons seulement de leur indiquer où regarder.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'witnesses_on_road',
    sceneArtId: 'witnesses_on_road',
    steps: [
      {
        id: '1',
        speaker: 'Survivant de Bois-Clair',
        actorId: 'survivor',
        expression: 'wounded',
        tag: 'Témoins',
        text: 'Nous avons vu ce que vous avez choisi au village. Nos mots vous précéderont devant Alaric.',
        side: 'left',
        effects: [],
        choices: [
          { text: 'Protéger les témoins jusqu’au camp.', next: '2', requiresReputationMin: 45, blockedText: 'Ils refusent votre escorte.', effects: [{ type: 'addReputation', amount: 5 }, { type: 'setFlag', key: 'protectedWitnesses', value: true }], contest: { kind: 'persuade', risk: 'high', truthState: 'suspected', hint: 'Les témoins doutent de votre protection.', success: { next: '2', effects: [{ type: 'addReputation', amount: 5 }, { type: 'setFlag', key: 'protectedWitnesses', value: true }] }, failure: { next: '4', effects: [{ type: 'addReputation', amount: -2 }] } } },
          { text: 'Faire taire les témoins, quel qu’en soit le prix.', next: '3', effects: [{ type: 'addGold', amount: -80 }, { type: 'addReputation', amount: -5 }, { type: 'setFlag', key: 'silencedWitnesses', value: true }] },
        ],
      },
      { id: '2', speaker: 'Survivant de Bois-Clair', actorId: 'survivor', expression: 'grateful', tag: 'Parole sauvée', text: 'Alors nous parlerons. Pas pour vous flatter, mais parce que la vérité doit survivre.', side: 'left', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'neutral', tag: 'Silence', text: 'La vérité coûte cher. Heureusement, le silence a un prix plus simple.', side: 'left', next: null, effects: [], choices: [] },
      { id: '4', speaker: 'Survivant de Bois-Clair', actorId: 'survivor', expression: 'fearful', tag: 'Refus', text: 'Vos actes parlent plus fort que vos promesses. Nous trouverons notre propre chemin jusqu’au camp.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'shadow_signs',
    sceneArtId: 'shadow_signs',
    steps: [
      {
        id: '1',
        speaker: 'Sage Séraphine',
        actorId: 'sage_seraphine',
        expression: 'mystical',
        tag: 'Ombres silencieuses',
        text: 'Ces marques ne sont pas du Serpent. Quelqu’un guide leurs raids avec une magie ancienne, plus vieille que les Sceaux eux-mêmes.',
        side: 'left',
        effects: [],
        choices: [
          { text: 'Préserver les preuves pour Alaric.', next: '2', effects: [{ type: 'addReputation', amount: 5 }, { type: 'setFlag', key: 'shadowEvidence', value: true }], outcomePreview: { mode: 'soft', hints: ['Les preuves seront préservées', 'Le Lion s’en souviendra'] } },
          { text: 'Briser l’autel et récupérer les fragments.', next: '3', effects: [{ type: 'addItem', itemId: 'iron_ore', quantity: 2 }, { type: 'addItem', itemId: 'grenade_entravante', quantity: 1 }, { type: 'addReputation', amount: -2 }, { type: 'setFlag', key: 'shadowFragments', value: true }], outcomePreview: { mode: 'soft', hints: ['Gain matériel modéré', 'Séraphine désapprouve ce choix'] } },
        ],
      },
      { id: '2', speaker: 'Sage Séraphine', actorId: 'sage_seraphine', expression: 'stern', tag: 'Preuve', text: 'Avec ceci, Alaric verra que son conflit dépasse les frontières du Lion. Ce que nous avons trouvé n’est pas une simple guerre de clan.', side: 'left', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'neutral', tag: 'Artefact', text: 'La preuve convainc les chefs. Les fragments arment les survivants.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'old_shrine_event',
    sceneArtId: 'old_shrine_event',
    steps: [
      {
        id: '1',
        speaker: 'Sage S\u00e9raphine',
        actorId: 'sage_seraphine',
        expression: 'mystical',
        tag: 'Sanctuaire',
        text: 'Un vieux sanctuaire oubli\u00e9 des b\u00fbcherons. La pierre est encore chaude. On y sent une pr\u00e9sence calme \u2014 ou quelque chose qui dort.',
        side: 'left',
        next: null,
        effects: [],
        choices: [
          { text: 'Se recueillir et pr\u00e9server le sanctuaire.', next: '2', effects: [{ type: 'addReputation', amount: 2 }, { type: 'setFlag', key: 'shrineRested', value: true }], outcomePreview: { mode: 'soft', hints: ['Le clan gagne en respect', 'S\u00e9raphine approuve ce respect'] } },
          { text: 'Fouiller le sanctuaire pour des reliques.', next: '3', effects: [{ type: 'addGold', amount: 50 }, { type: 'addItem', itemId: 'iron_ore', quantity: 1 }, { type: 'addReputation', amount: -3 }, { type: 'setFlag', key: 'shrineLooted', value: true }], outcomePreview: { mode: 'soft', hints: ['Gain mat\u00e9riel mod\u00e9r\u00e9', 'S\u00e9raphine d\u00e9sapprouve ce choix'] } },
        ],
      },
      { id: '2', speaker: 'Sage S\u00e9raphine', actorId: 'sage_seraphine', expression: 'neutral', tag: 'Repos', text: 'La chaleur de la pierre apaise les esprits. Nous repartons sans avoir profan\u00e9 ce refuge.', side: 'left', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'neutral', tag: 'Reliques', text: 'Quelques pi\u00e8ces anciennes et un fragment de gemme. Rien de sacr\u00e9, mais utile. Le sanctuaire ne nous en voudra pas\u2026 j\u2019esp\u00e8re.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'lion_finale_judgement',
    sceneArtId: 'lion_finale_judgement',
    steps: [
      { id: '1', speaker: 'Chef Alaric', actorId: 'alaric', expression: 'stern', tag: 'Jugement', text: 'Le Lion pèsera votre dossier complet : Bois-Clair, votre conduite, les témoins et les preuves. Choisissez seulement la manière dont vous assumerez ce verdict.', side: 'right', next: null, effects: [], choices: [
        { text: 'Assumer nos actes et réclamer le Sceau.', next: null, effects: [{ type: 'resolveLionFinale', intent: 'claim_recognition' }], outcomePreview: { mode: 'hidden', hints: [] } },
        { text: 'Demander l’épreuve du Lion.', next: null, effects: [{ type: 'resolveLionFinale', intent: 'request_trial' }], outcomePreview: { mode: 'soft', hints: ['Le Sceau sera jugé par la loi martiale du Lion'] } },
      ] },
    ],
  },
  {
    id: 'serpent_general_aftermath',
    sceneArtId: 'lion_finale_judgement',
    steps: [
      { id: '1', speaker: 'Sage Séraphine', actorId: 'sage_seraphine', expression: 'mystical', tag: 'Artefact récupéré', text: 'Le général Serpent est vaincu. Son artefact livre enfin une preuve entière de l’intervention des Ombres.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'lion_trial_aftermath',
    sceneArtId: 'lion_finale_judgement',
    steps: [
      { id: '1', speaker: 'Chef Alaric', actorId: 'alaric', expression: 'grateful', tag: 'Sceau gagné', text: 'Mon champion est vaincu. La loi du Lion est sans appel : le Sceau est à vous et j’accepte son jugement.', side: 'right', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'pre_serpent_hunters',
    sceneArtId: 'mystery_ambush',
    steps: [
      { id: '1', speaker: 'Chasseur Serpent', actorId: 'serpent_raider', expression: 'hostile', tag: 'Traque', text: 'L’Oracle a parlé. Un traître parmi nous a vendu notre route à des étrangers. Nous avons suivi ses pas jusqu’ici — et les vôtres avec.', side: 'right', next: '2', effects: [], choices: [] },
      { id: '2', speaker: 'Sage Séraphine', actorId: 'sage_seraphine', expression: 'stern', tag: 'Riposte', text: 'L’informateur est sous notre protection. Si vous voulez sa tête, il faudra passer par nos lames d’abord.', side: 'left', next: '3', effects: [], choices: [] },
      { id: '3', speaker: 'Chasseur Serpent', actorId: 'serpent_raider', expression: 'hostile', tag: 'Menace', text: 'Le général veut ce traître mort ou silencieux. Vous ne savez pas ce qu’il a vu — et ce que ça coûte à ceux qui le protègent.', side: 'right', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'serpent_pursuit_pre_combat',
    sceneArtId: 'lion_finale_judgement',
    steps: [
      { id: '1', speaker: 'Chef Alaric', actorId: 'alaric', expression: 'stern', tag: 'Verdict', text: 'Le Lion vous reconnaît. Poursuivez le général Serpent et ramenez l’artefact qu’il emporte.', side: 'right', next: '2', effects: [], choices: [] },
      { id: '2', speaker: 'Général Serpent', actorId: 'serpent_general_boss', expression: 'hostile', tag: 'Confrontation', text: 'Venez donc reprendre l’artefact — et découvrir ce qui vous observe derrière nos bannières.', side: 'right', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'village_defense_aftermath',
    sceneArtId: 'village_choice',
    steps: [
      {
        id: '1',
        speaker: 'Villageoise de Bois-Clair',
        actorId: 'villageoise',
        expression: 'grateful',
        tag: 'Bois-Clair sauvé',
        text: 'Les Serpents fuient. Les enfants sont sains et saufs. Vous avez fait ce que le Lion n’a pas eu le courage de faire.',
        side: 'left',
        next: null,
        effects: [],
        choices: [
          { text: 'Refuser toute récompense.', next: '2', effects: [{ type: 'addReputation', amount: 5 }, { type: 'setFlag', key: 'protectedWitnesses', value: true }], outcomePreview: { mode: 'soft', hints: ['Le village s\u2019en souviendra', 'Le clan gagne en respect'] } },
          { text: 'Accepter leur gratitude et leurs provisions.', next: '3', effects: [{ type: 'addItem', itemId: 'potion', quantity: 2 }, { type: 'setFlag', key: 'protectedWitnesses', value: true }], outcomePreview: { mode: 'soft', hints: ['Le village s\u2019en souviendra', 'Le clan reçoit l\u2019aide promise'] } },
        ],
      },
      { id: '2', speaker: 'Villageoise de Bois-Clair', actorId: 'villageoise', expression: 'grateful', tag: 'Générosité', text: 'Alors nous parlerons de vous à tous ceux qui passeront. Le nom de votre clan sera béni sur cette route.', side: 'left', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Villageoise de Bois-Clair', actorId: 'villageoise', expression: 'grateful', tag: 'Reconnaissance', text: 'Prenez ces provisions. Et sachez que Bois-Clair n’oubliera pas. Nos témoins parleront pour vous devant Alaric.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'village_raid_aftermath',
    sceneArtId: 'village_choice',
    steps: [
      {
        id: '1',
        speaker: 'Intendant Maelor',
        actorId: 'maelor',
        expression: 'neutral',
        tag: 'Butin',
        text: 'Les coffres sont à nous. Les Serpents sont dispersés. Mais les villageois… ils ne nous maudiront pas à voix haute. Ils n’osent plus.',
        side: 'left',
        next: null,
        effects: [],
        choices: [
          { text: 'Laisser quelques provisions aux villageois.', next: '2', effects: [{ type: 'addGold', amount: -40 }, { type: 'addReputation', amount: 3 }], outcomePreview: { mode: 'soft', hints: ['Votre conduite sera jugée', 'Une part d\u2019honneur demeure'] } },
          { text: 'Partir avec tout. Ils ne sont pas notre problème.', next: '3', effects: [{ type: 'addReputation', amount: -5 }, { type: 'setFlag', key: 'silencedWitnesses', value: true }], outcomePreview: { mode: 'soft', hints: ['Votre nom sera terni', 'Maelor approuve ce calcul'] } },
        ],
      },
      { id: '2', speaker: 'Villageoise de Bois-Clair', actorId: 'villageoise', expression: 'wounded', tag: 'Reste de dignité', text: 'Vous prenez nos coffres et vous nous laissez des miettes. Ce n’est pas de la générosité — c’est de la pitié. Mais au moins, nous ne mourrons pas de faim.', side: 'left', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'neutral', tag: 'Rationalisation', text: 'Ils survivront. Ils ont survécu à pire. Et nous avons ce qu’il nous faut pour le Sceau.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'mystery_lancer_recruit',
    sceneArtId: 'mystery_lancer_recruit',
    steps: [
      {
        id: '1',
        speaker: 'Garen',
        actorId: 'lancer',
        expression: 'neutral',
        tag: 'Volontaire de Bois-Clair',
        text: 'Bois-Clair parle encore de votre passage. Certains y voient une dette. D’autres, une blessure. Moi, je veux savoir quel clan vous bâtirez avec le Sceau.',
        side: 'right',
        effects: [],
        choices: [
          { text: 'Accueillir Garen dans la compagnie.', next: '2', requiresReputationMin: 15, blockedText: 'Garen ne suit pas les clans sans honneur.', effects: [{ type: 'recruitUnit', unitId: 'lancer' }, { type: 'addReputation', amount: 3 }, { type: 'setFlag', key: 'recruitedLancer', value: true }], contest: { kind: 'persuade', risk: 'moderate', truthState: 'suspected', hint: 'Garen pèse votre conduite avant de se lier.', success: { next: '2', effects: [{ type: 'recruitUnit', unitId: 'lancer' }, { type: 'addReputation', amount: 3 }, { type: 'setFlag', key: 'recruitedLancer', value: true }] }, failure: { next: '4', effects: [] } } },
          { text: 'Lui demander de rester protéger Bois-Clair.', next: '3', effects: [{ type: 'addReputation', amount: 2 }] },
        ],
      },
      { id: '2', speaker: 'Garen', actorId: 'lancer', expression: 'grateful', tag: 'Nouvel allié', text: 'Je ne vous décevrai pas. Ma lance suivra votre bannière — et jugera ce que vous en ferez.', side: 'right', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Garen', actorId: 'lancer', expression: 'stern', tag: 'Fidélité', text: 'Alors je resterai. Bois-Clair a encore besoin de lances, quel que soit ce qui s’est passé.', side: 'right', next: null, effects: [], choices: [] },
      { id: '4', speaker: 'Garen', actorId: 'lancer', expression: 'stern', tag: 'Refus', text: 'Je ne peux pas lier ma lance à votre bannière. Pas encore. Les actes pèsent plus lourd que les promesses.', side: 'right', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'epilogue',
    sceneArtId: 'epilogue',
    steps: [
      { id: '1', speaker: 'Sage Séraphine', actorId: 'sage_seraphine', expression: 'mystical', tag: 'Bilan', text: 'Le Sceau du Lion repose entre vos mains. La voie qui vous l’a donné déterminera désormais la forme de cette alliance.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'ate_alaric_reports',
    title: 'Camp du Lion',
    perspective: 'alaric',
    sceneArtId: 'lion_briefing',
    steps: [
      { id: '1', speaker: 'Champion du Lion', actorId: 'lion_champion', expression: 'stern', tag: 'Rapport', text: 'Ils ont pris la piste des bêtes. L’embuscade les a frappés au col — et ils en sont sortis. Nos éclaireurs ont compté leurs pas : ni pause ni retraite.', side: 'right', next: '2', effects: [], choices: [] },
      { id: '2', speaker: 'Chef Alaric', actorId: 'alaric', expression: 'neutral', tag: 'Jugement', text: 'Soit ils sont courageux, soit ils sont fous. À Bois-Clair, on a besoin des deux. Mais le courage sans discipline devient un incendie.', side: 'left', next: '3', effects: [], choices: [] },
      { id: '3', speaker: 'Chef Alaric', actorId: 'alaric', expression: 'stern', tag: 'Décision', text: 'Ne pas les arrêter. Laissez-les arriver. S’ils tiennent la route jusqu’au village, on saura ce qu’ils valent. Sinon… les Serpents feront le travail pour nous.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'ate_serpent_scout_report',
    title: 'Lignes Serpent',
    perspective: 'serpent_scout',
    sceneArtId: 'shadow_signs',
    steps: [
      { id: '1', speaker: 'Pillard Serpent', actorId: 'serpent_raider', expression: 'fearful', tag: 'Reconnaissance', text: 'Général. La compagnie franchit le carrefour. Un rôdeur leur a montré où nos lanternes vertes guident les embuscades.', side: 'right', next: '2', effects: [], choices: [] },
      { id: '2', speaker: 'Oracle Serpent', actorId: 'serpent_oracle', expression: 'fearful', tag: 'Pressentiment', text: 'S’ils connaissent les lanternes, nos passages ne sont plus sûrs. Il faut frapper avant qu’ils ne révèlent tout au Lion.', side: 'left', next: '3', effects: [], choices: [] },
      { id: '3', speaker: 'Général Serpent', actorId: 'serpent_general_boss', expression: 'hostile', tag: 'Ordre', text: 'Un rôdeur. Bien. Envoyez les brutes au pont. S’il connaît nos passages, il connaît aussi nos pièges. On verra s’il sait les éviter.', side: 'right', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'ate_village_fear',
    title: 'Bois-Clair',
    perspective: 'villageoise',
    sceneArtId: 'village_choice',
    steps: [
      { id: '1', speaker: 'Villageoise', actorId: 'villageoise', expression: 'fearful', tag: 'Rumeurs', text: 'Des réfugiés sont revenus de la route. Ils parlaient de gens armés — pas des Serpents, pas des bandits. Quelqu’un d’autre.', side: 'left', next: '2', effects: [], choices: [] },
      { id: '2', speaker: 'Mère réfugiée', actorId: 'refugee_mother', expression: 'fearful', tag: 'Témoignage', text: 'Certains disent qu’ils aident. D’autres disent qu’ils prennent. Difficile de savoir qui protège et qui pille, quand tout le monde porte une arme.', side: 'right', next: '3', effects: [], choices: [] },
      { id: '3', speaker: 'Villageoise', actorId: 'villageoise', expression: 'fearful', tag: 'Inquiétude', text: 'Le Lion ? Les Serpents ? Comment on fait la différence quand tout brûle ? On n’a plus qu’à prier pour que ce soit le bon camp qui arrive le premier.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'ate_serpent_general_warning',
    title: 'Lignes Serpent',
    perspective: 'serpent_general',
    sceneArtId: 'shadow_signs',
    steps: [
      { id: '1', speaker: 'Oracle Serpent', actorId: 'serpent_oracle', expression: 'fearful', tag: 'Rapport', text: 'Général. La compagnie a franchi le barrage de Valmir. Nos pillards n’ont pas tenu une charge. Ils se battent en formation — pas comme des bandits.', side: 'left', next: '2', effects: [], choices: [] },
      { id: '2', speaker: 'Général Serpent', actorId: 'serpent_general_boss', expression: 'stern', tag: 'Évaluation', text: 'Une compagnie organisée. Avec un rôdeur pour guide. Ils apprennent vite — trop vite pour des mercenaires. Qui les envoie ?', side: 'right', next: '3', effects: [], choices: [] },
      { id: '3', speaker: 'Général Serpent', actorId: 'serpent_general_boss', expression: 'hostile', tag: 'Ordre', text: 'S’ils atteignent le village, tout notre dispositif s’effondre. Renforcez le barrage. Et dites aux brutes de ne pas attendre — frappez avant qu’ils ne s’organisent.', side: 'right', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'ate_maelor_seal_analysis',
    title: 'Ailleurs…',
    perspective: 'maelor',
    sceneArtId: 'acte_ouverture',
    steps: [
      { id: '1', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'neutral', tag: 'Étude', text: 'Le Sceau du Lion résonne. Pas comme un objet de pouvoir — comme une porte. Chaque combat le rapproche de s’ouvrir.', side: 'left', next: '2', effects: [], choices: [] },
      { id: '2', speaker: 'Sage Séraphine', actorId: 'sage_seraphine', expression: 'mystical', tag: 'Écho lointain', text: 'Même d’ici, je le sens. Le Sceau ne choisit pas le plus fort — il choisit celui qui porte le poids des autres. Si la compagnie a tenu la route, le Sceau le sait déjà.', side: 'right', next: '3', effects: [], choices: [] },
      { id: '3', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'mystical', tag: 'Pressentiment', text: 'Quelque chose de l’autre côté commence à pousser. Ce n’est pas le Serpent qui devrait nous inquiéter. C’est ce qui attend derrière la porte.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'ate_lion_council_doubt',
    title: 'Camp du Lion',
    perspective: 'lion_council',
    sceneArtId: 'lion_briefing',
    steps: [
      { id: '1', speaker: 'Champion du Lion', actorId: 'lion_champion', expression: 'stern', tag: 'Doute', text: 'Des étrangers qui se disent envoyés par le clan déchu. Et on devrait les croire ? Le Sceau n’est pas un prix qu’on remporte pour avoir tué quelques pillards.', side: 'right', next: '2', effects: [], choices: [] },
      { id: '2', speaker: 'Chef Alaric', actorId: 'alaric', expression: 'stern', tag: 'Réponse', text: 'Je ne crois personne. Mais Bois-Clair a vu ce qu’ils ont fait. Les actes parlent. Pas les noms, pas les serments.', side: 'left', next: '3', effects: [], choices: [] },
      { id: '3', speaker: 'Champion du Lion', actorId: 'lion_champion', expression: 'hostile', tag: 'Défi', text: 'Et s’ils échouent ? S’ils prennent l’or et fuient ? Le Sceau tombe dans des mains vides, et le Lion perd la seule chose qui le tient debout.', side: 'right', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'ate_ruins_awaken',
    title: 'Pendant ce temps…',
    perspective: 'maelor',
    sceneArtId: 'shadow_signs',
    steps: [
      { id: '1', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'mystical', tag: 'Observation', text: 'Les ruines s’éclairent. Les inscriptions anciennes brillent sans feu ni lune. La pierre froide depuis des siècles est tiède sous mes doigts.', side: 'left', next: '2', effects: [], choices: [] },
      { id: '2', speaker: 'Sage Séraphine', actorId: 'sage_seraphine', expression: 'mystical', tag: 'Résonance', text: 'Même d’ici, je sens la pierre chanter. Les vieilles choses ne dorment plus — elles écoutent. Elles attendent de voir qui porte le Sceau.', side: 'right', next: '3', effects: [], choices: [] },
      { id: '3', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'mystical', tag: 'Révélation', text: 'C’est le Sceau. Plus il s’approche, plus les vieilles choses se souviennent de ce qu’elles étaient. Et certaines… n’avaient pas besoin qu’on les réveille.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'ate_serpent_retreat_order',
    title: 'Lignes Serpent',
    perspective: 'serpent_general',
    sceneArtId: 'shadow_signs',
    steps: [
      { id: '1', speaker: 'Général Serpent', actorId: 'serpent_general_boss', expression: 'hostile', tag: 'Constat', text: 'Ils ont trouvé les signes. Les marques des Ombres. Trop tôt. Trop vite. Quelqu’un parmi eux lit ce que nous cachons.', side: 'right', next: '2', effects: [], choices: [] },
      { id: '2', speaker: 'Oracle Serpent', actorId: 'serpent_oracle', expression: 'fearful', tag: 'Question', text: 'Général, s’ils révèlent les marques au Lion, tout le dispositif… On devrait les frapper maintenant. Tant qu’ils sont sur la route.', side: 'left', next: '3', effects: [], choices: [] },
      { id: '3', speaker: 'Général Serpent', actorId: 'serpent_general_boss', expression: 'stern', tag: 'Ordre de repli', text: 'Non. Toutes les unités en arrière. Laissez-les venir à moi. Si le Sceau s’ouvre ici, autant que ce soit sous mon contrôle. Pas le Lion. Pas les Ombres. Moi.', side: 'right', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'pre_village_defense',
    sceneArtId: 'village_choice',
    steps: [
      { id: '1', speaker: 'Pillard Serpent', actorId: 'serpent_raider', expression: 'hostile', tag: 'Ultimatum', text: 'Le village brûle déjà. Ceux qui prennent les armes meurent les premiers.', side: 'right', next: '2', effects: [], choices: [] },
      { id: '2', speaker: 'Pillard Serpent', actorId: 'serpent_raider', expression: 'hostile', tag: 'Menace', text: 'Vous voulez défendre ces paysans ? Montrez-moi ce que vaut le sang du Lion.', side: 'right', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'pre_village_raid',
    sceneArtId: 'village_choice',
    steps: [
      { id: '1', speaker: 'Brute Serpent', actorId: 'serpent_brute', expression: 'hostile', tag: 'Moquerie', text: 'Regardez-les. Ils croient que leurs murs les protègent.', side: 'right', next: '2', effects: [], choices: [] },
      { id: '2', speaker: 'Brute Serpent', actorId: 'serpent_brute', expression: 'hostile', tag: 'Provocation', text: 'Le Lion n\u2019est pas l\u00e0. Personne ne vient pour Bois-Clair. Prenez ce que vous voulez, et frappez ceux qui regardent.', side: 'right', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'pre_serpent_duelist_trial',
    sceneArtId: 'serpent_duelist_trial',
    steps: [
      { id: '1', speaker: 'Duelliste Serpent', actorId: 'serpent_duelist_elite', expression: 'stern', tag: 'Défi', text: 'Vous avez coup\u00e9 la route. Vous avez dispers\u00e9 mes \u00e9claireurs. Mais ici, c\u2019est entre nous.', side: 'right', next: '2', effects: [], choices: [] },
      { id: '2', speaker: 'Duelliste Serpent', actorId: 'serpent_duelist_elite', expression: 'stern', tag: 'Provocation', text: 'Une lame. Un adversaire. Pas de tactique, pas de retraite. Si vous survivez, la route est \u00e0 vous.', side: 'right', next: '3', effects: [], choices: [] },
      { id: '3', speaker: 'Duelliste Serpent', actorId: 'serpent_duelist_elite', expression: 'hostile', tag: 'Engagement', text: 'En garde. Le Lion n\u2019apprendra rien de votre d\u00e9faite.', side: 'right', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'pre_troll_crossing',
    sceneArtId: 'mystery_troll_crossing',
    steps: [
      { id: '1', speaker: 'Troll des pierres', actorId: 'forest_troll_elite', expression: 'hostile', tag: 'Territoire', text: 'GROOORR. Le pont. À moi. Vous pas passer.', side: 'right', next: '2', effects: [], choices: [] },
      { id: '2', speaker: 'Troll des pierres', actorId: 'forest_troll_elite', expression: 'hostile', tag: 'Intimidation', text: 'Vous sentir faible. Vous sentir peur. Bon. Peur bon pour troll.', side: 'right', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'pre_young_dragon_roost',
    sceneArtId: 'mystery_dragon_roost',
    steps: [
      { id: '1', speaker: 'Jeune dragon', actorId: 'young_dragon_elite', expression: 'hostile', tag: 'R\u00e9veil', text: 'GRRRRR\u2026 Qui entre dans mon nid ? Qui ose r\u00e9veiller ce qui dormait ?', side: 'right', next: '2', effects: [], choices: [] },
      { id: '2', speaker: 'Jeune dragon', actorId: 'young_dragon_elite', expression: 'hostile', tag: 'Avertissement', text: 'Vous sentez la peur des autres. Vous sentez le feu aussi. Partez\u2026 ou br\u00fblez avec eux.', side: 'right', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'rep_event_roadside_intimidation',
    title: 'Pression sur la route',
    sceneArtId: 'mystery_help',
    steps: [
      {
        id: '1',
        speaker: 'Chef de bande',
        actorId: 'serpent_raider',
        expression: 'hostile',
        tag: 'Réputation publique',
        text: 'Votre bannière attire les regards. Sur cette route, toute compagnie visible devient une cible. Payez le passage, ou défendez votre nom devant ceux qui regardent.',
        side: 'right',
        effects: [],
        choices: [
          { text: 'Refuser le tribut sans menacer les témoins.', next: '2', effects: [{ type: 'addReputation', amount: 1 }, { type: 'setFlag', key: 'r4FacedRoadsidePressure', value: true }], outcomePreview: { mode: 'soft', hints: ['Réponse publique', 'Votre réputation peut évoluer'] } },
          { text: 'Payer 20 or et poursuivre la route.', next: '3', requiresGold: 20, effects: [{ type: 'addGold', amount: -20 }, { type: 'setFlag', key: 'r4PaidRoadsideTribute', value: true }], outcomePreview: { mode: 'exact', hints: ['20 or', 'Évite une confrontation'] } },
        ],
      },
      { id: '2', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'stern', tag: 'Position tenue', text: 'Ils reculent parce que la route les observe. Le récit de cette rencontre voyagera plus vite que nous.', side: 'left', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'neutral', tag: 'Passage acheté', text: 'Le passage est libre. La bourse est plus légère, et chacun ici sait désormais quel prix nous avons accepté.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'rep_event_brokered_information',
    title: 'Un renseignement à vendre',
    sceneArtId: 'mystery_recruit',
    steps: [
      {
        id: '1',
        speaker: 'Courtière des routes',
        actorId: 'survivor',
        expression: 'neutral',
        tag: 'Occasion',
        text: 'Je vends une piste sûre et le nom du guetteur qui l’utilise. Votre réputation ne change pas le prix : vingt-cinq pièces, ou je garde mon renseignement.',
        side: 'right',
        effects: [],
        choices: [
          { text: 'Acheter le renseignement — 25 or.', next: '2', requiresGold: 25, effects: [{ type: 'addGold', amount: -25 }, { type: 'setFlag', key: 'r4BoughtRoadInformation', value: true }], outcomePreview: { mode: 'exact', hints: ['25 or', 'Renseignement mémorisé'] } },
          { text: 'Décliner sans la menacer.', next: '3', effects: [{ type: 'setFlag', key: 'r4DeclinedRoadInformation', value: true }], outcomePreview: { mode: 'soft', hints: ['Aucun coût', 'L’occasion est perdue'] } },
        ],
      },
      { id: '2', speaker: 'Courtière des routes', actorId: 'survivor', expression: 'grateful', tag: 'Marché conclu', text: 'Suivez les pierres blanches jusqu’au vieux chêne, puis quittez la piste. Vous verrez le guetteur avant qu’il vous voie.', side: 'right', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Courtière des routes', actorId: 'survivor', expression: 'neutral', tag: 'Occasion refusée', text: 'Alors nous ne nous devons rien. Que la route juge lequel de nous deux avait le plus besoin de cet accord.', side: 'right', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'rep_event_public_petition',
    title: 'Le poids d’un nom',
    sceneArtId: 'refugee_trial',
    steps: [
      {
        id: '1',
        speaker: 'Porte-parole des réfugiés',
        actorId: 'refugee_mother',
        expression: 'stern',
        tag: 'Attente publique',
        text: 'Votre passage attire les regards. Nos familles ont besoin de provisions pour franchir la route. Votre compagnie a les moyens d’agir : accepterez-vous d’en porter le coût ?',
        side: 'right',
        effects: [],
        choices: [
          { text: 'Financer les provisions — 35 or.', next: '2', requiresGold: 35, effects: [{ type: 'addGold', amount: -35 }, { type: 'addReputation', amount: 3 }, { type: 'setFlag', key: 'r4FundedPublicPetition', value: true }], outcomePreview: { mode: 'exact', hints: ['35 or', 'Réputation +3'] } },
          { text: 'Refuser publiquement.', next: '3', effects: [{ type: 'addReputation', amount: -1 }, { type: 'setFlag', key: 'r4RefusedPublicPetition', value: true }], outcomePreview: { mode: 'exact', hints: ['Réputation -1', 'Refus mémorisé'] } },
        ],
      },
      { id: '2', speaker: 'Porte-parole des réfugiés', actorId: 'refugee_mother', expression: 'grateful', tag: 'Engagement tenu', text: 'Nous n’oublierons ni les provisions ni ceux qui les ont offertes. Votre nom voyagera avec nos familles.', side: 'right', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Porte-parole des réfugiés', actorId: 'refugee_mother', expression: 'wounded', tag: 'Attente déçue', text: 'Alors les récits étaient plus riches que votre bourse — ou que votre volonté. Nous trouverons une autre route.', side: 'right', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'rep_event_bois_clair_denunciation',
    title: 'La mémoire de Bois-Clair',
    sceneArtId: 'village_choice',
    steps: [
      {
        id: '1',
        speaker: 'Survivante de Bois-Clair',
        actorId: 'refugee_mother',
        expression: 'stern',
        tag: 'Conséquence historique',
        text: 'Je porte une accusation née de vos actes, pas de votre renommée. Répondez devant ceux qui ont survécu à Bois-Clair.',
        side: 'right',
        effects: [],
        choices: [
          { text: 'Faire face à l’accusation sans la nier.', next: '2', effects: [{ type: 'addReputation', amount: 1 }, { type: 'setFlag', key: 'r4FacedBoisClairAccusation', value: true }], outcomePreview: { mode: 'soft', hints: ['Réponse publique', 'Le fait historique demeure'] } },
          { text: 'Verser 50 or aux survivants.', next: '3', requiresGold: 50, effects: [{ type: 'addGold', amount: -50 }, { type: 'addReputation', amount: 2 }, { type: 'setFlag', key: 'r4PaidBoisClairReparations', value: true }], outcomePreview: { mode: 'exact', hints: ['50 or', 'Réputation +2', 'Le fait historique demeure'] } },
        ],
      },
      { id: '2', speaker: 'Survivante de Bois-Clair', actorId: 'refugee_mother', expression: 'stern', tag: 'Réponse entendue', text: 'Au moins, vous n’avez pas fui notre regard. Nous porterons votre réponse avec le souvenir de ce qui s’est passé.', side: 'right', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Survivante de Bois-Clair', actorId: 'refugee_mother', expression: 'neutral', tag: 'Réparation limitée', text: 'Cet or aidera des familles. Il ne rachète pas le passé, et personne ici ne prétendra le contraire.', side: 'right', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'final_refuge',
    sceneArtId: 'lion_finale_judgement',
    steps: [
      { id: '1', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'stern', tag: 'Préparation', text: 'Le camp du Lion est en vue. Avant de franchir ces portes, chacun doit savoir ce qu’il porte — et ce qu’il risque. Le Sceau ne se donne pas, et Alaric ne pardonne pas.', side: 'left', next: '2', effects: [], choices: [] },
      { id: '2', speaker: 'Sage Séraphine', actorId: 'sage_seraphine', expression: 'mystical', tag: 'Pressentiment', text: 'Les ruines chantent encore. Les Ombres se réveillent. Ce jugement ne concernera pas seulement le Lion et le Serpent — quelque chose de plus ancien nous observe.', side: 'right', next: '3', effects: [], choices: [] },
      { id: '3', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'neutral', tag: 'Rappel', text: 'Alaric pèsera tout le dossier : Bois-Clair, les réfugiés, les témoins, le convoi, notre conduite et les preuves que nous portons. Notre renommée ouvrira peut-être des oreilles ; elle ne réécrira aucun de ces faits.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'pre_lion_chief',
    sceneArtId: 'lion_finale_judgement',
    steps: [
      { id: '1', speaker: 'Chef Alaric', actorId: 'alaric', expression: 'stern', tag: 'Confrontation', text: 'L’épreuve a été demandée ou imposée selon la loi du Lion. Dans les deux cas, son résultat décidera du Sceau.', side: 'right', next: '2', effects: [], choices: [] },
      { id: '2', speaker: 'Chef Alaric', actorId: 'alaric', expression: 'stern', tag: 'Mise en garde', text: 'Mon bras n’est plus ce qu’il était, mais mon champion porte le poids du Lion dans sa lame. Si vous gagnez, j’accepterai le résultat.', side: 'right', next: '3', effects: [], choices: [] },
      { id: '3', speaker: 'Champion du Lion', actorId: 'lion_champion', expression: 'hostile', tag: 'Défi', text: 'Je suis la lame du Lion. Si vous tombez, le clan meurt avec vous. Si vous tenez, le Sceau est à vous. Prouvez que vous méritez de le porter.', side: 'right', next: '4', effects: [], choices: [] },
      { id: '4', speaker: 'Champion du Lion', actorId: 'lion_champion', expression: 'stern', tag: 'Engagement', text: 'Le Lion ne c\u00e8de pas sans verser le sang. En garde.', side: 'right', next: null, effects: [], choices: [] },
    ],
  },
];

export const campaignNodes = rawNodes.map((node) => campaignNodeSchema.parse(node));
export const combatConfigs = new Map(rawCombats.map((combat) => {
  const parsed = combatConfigSchema.parse({ ...combat, ...combatVisualComposition[combat.id] });
  return [parsed.id, parsed];
}));
export const dialogues = new Map(rawDialogues.map((dialogue) => {
  const parsed = dialogueSequenceSchema.parse(dialogue);
  return [parsed.id, parsed];
}));

export const POST_NODE_ATE: Readonly<Record<string, string[]>> = {
  'lion-opening-ambush': ['ate_alaric_reports'],
  'lion-nomad-crossroads': ['ate_serpent_scout_report'],
  'lion-refugees': ['ate_village_fear'],
  'lion-valmir-road': ['ate_serpent_general_warning'],
  'lion-village-choice': ['ate_maelor_seal_analysis'],
  'lion-witnesses': ['ate_lion_council_doubt'],
  'lion-shadow-signs': ['ate_ruins_awaken', 'ate_serpent_retreat_order'],
};
