import {
  campaignNodeSchema,
  combatConfigSchema,
  dialogueSequenceSchema,
  type CampaignNode,
  type CombatConfig,
} from './types';

type RawCombatConfig = Omit<CombatConfig, 'enemyVisualIds' | 'escortVisualIds'> &
  Partial<Pick<CombatConfig, 'enemyVisualIds' | 'escortVisualIds'>>;

const rawNodes: CampaignNode[] = [
  { id: 'lion-camp', type: 'start', x: -7, z: 0, icon: '◆', label: 'Camp du Lion', links: ['lion-audience'], dialogueId: 'camp_departure' },
  { id: 'lion-audience', type: 'story', x: -5.2, z: 0, icon: '♛', label: 'Audience d’Alaric', links: ['lion-refugees', 'lion-veiled-path'], dialogueId: 'lion_briefing' },
  { id: 'lion-refugees', type: 'mystery', x: -3.7, z: -1.1, icon: '◇', label: 'Route des réfugiés', links: ['lion-first-refuge'], dialogueId: 'refugee_trial' },
  { id: 'lion-veiled-path', type: 'mystery', x: -3.7, z: 1.1, icon: '?', label: 'Sentier voilé', links: ['lion-first-refuge'], mysteryPoolId: 'lion' },
  { id: 'lion-first-refuge', type: 'story', x: -1.9, z: 0, icon: '⌂', label: 'Refuge du Lion', links: ['lion-valmir-road', 'lion-reserve-trail'] },
  { id: 'lion-valmir-road', type: 'random-combat', x: -0.8, z: -0.8, icon: '⚔', label: 'Route de Bois-Clair', links: ['lion-village-choice'], combatId: 'road_to_valmir' },
  { id: 'lion-reserve-trail', type: 'mystery', x: -0.8, z: 0.8, icon: '◇', label: 'Chemin des réserves', links: ['lion-village-choice'], dialogueId: 'reserve_trail' },
  { id: 'lion-village-choice', type: 'story', x: 0, z: 0, icon: '⌂', label: 'Bois-Clair assiégé', links: ['lion-second-refuge'], dialogueId: 'village_choice' },
  { id: 'lion-second-refuge', type: 'story', x: 1.9, z: 0, icon: '⌂', label: 'Dernier feu du Lion', links: ['lion-witnesses', 'lion-shadow-signs'] },
  { id: 'lion-witnesses', type: 'mystery', x: 3.1, z: -0.8, icon: '◇', label: 'Témoins de Valmir', links: ['lion-final-judgement'], dialogueId: 'witnesses_on_road' },
  { id: 'lion-shadow-signs', type: 'mystery', x: 3.1, z: 0.8, icon: '?', label: 'Signes des Ombres', links: ['lion-final-judgement'], dialogueId: 'shadow_signs' },
  { id: 'lion-final-judgement', type: 'boss', x: 4.2, z: 0, icon: '♛', label: 'Jugement du Sceau', links: [], dialogueId: 'lion_finale_judgement' },
];

const rawCombats: RawCombatConfig[] = [
  { id: 'village_defense', sceneId: 'bois_clair_burning', objective: 'Repoussez les pillards et protégez les habitants de Bois-Clair.', encounterLabel: 'Défense de Bois-Clair', encounterRank: 'elite', maxPlayerUnits: 4, rewards: { gold: 160, reputation: 10, materials: { red_gem: 2 } } },
  { id: 'village_raid', sceneId: 'bois_clair_burning', objective: 'Sécurisez les coffres pendant que les Serpents dispersent les témoins.', encounterLabel: 'Raid sur Bois-Clair', encounterRank: 'elite', maxPlayerUnits: 4, rewards: { gold: 260, reputation: -15, materials: { red_gem: 3 } } },
  { id: 'forest_patrol', sceneId: 'forest_route', objective: 'Éliminez la patrouille Serpent avant qu’elle ne donne l’alerte.', encounterLabel: 'Patrouille Serpent', encounterRank: 'normal', maxPlayerUnits: 4, rewards: { gold: 80, reputation: 2, materials: { red_gem: 1 } } },
  { id: 'forest_ambush', sceneId: 'forest_route', objective: 'Survivez à l’embuscade dans le sous-bois.', encounterLabel: 'Embuscade', encounterRank: 'normal', maxPlayerUnits: 4, rewards: { gold: 70, reputation: 4, materials: { red_gem: 1 } } },
  { id: 'serpent_checkpoint', sceneId: 'forest_route', objective: 'Forcez le barrage Serpent sans laisser de messager s’échapper.', encounterLabel: 'Barrage des Serpents', encounterRank: 'elite', maxPlayerUnits: 4, rewards: { gold: 130, reputation: 3, materials: { red_gem: 2 } } },
  { id: 'road_to_valmir', sceneId: 'forest_route', objective: 'Ouvrez la route de Bois-Clair avant que le village ne tombe.', encounterLabel: 'Route de Bois-Clair', encounterRank: 'normal', maxPlayerUnits: 4, rewards: { gold: 90, reputation: 4, materials: { red_gem: 1 } } },
  { id: 'serpent_duelist_trial', sceneId: 'forest_route', objective: 'Défaites le duelliste Serpent avant qu’il ne coupe la retraite.', encounterLabel: 'Duel sous les pins', encounterRank: 'elite', maxPlayerUnits: 4, rewards: { gold: 160, reputation: 4, materials: { red_gem: 3 } } },
  { id: 'troll_crossing', sceneId: 'forest_route', objective: 'Forcez le passage gardé par le troll des pierres moussues.', encounterLabel: 'Passage du troll', encounterRank: 'elite', maxPlayerUnits: 4, rewards: { gold: 180, reputation: 5, materials: { red_gem: 3 } } },
  { id: 'young_dragon_roost', sceneId: 'lion_sanctum', objective: 'Approchez le nid du jeune dragon et survivez à son courroux.', encounterLabel: 'Nid du jeune dragon', encounterRank: 'elite', maxPlayerUnits: 4, rewards: { gold: 260, reputation: 6, materials: { red_gem: 3 } } },
  { id: 'serpent_captain', sceneId: 'lion_sanctum', objective: 'Traquez le général Serpent et exposez l’artefact des Ombres.', encounterLabel: 'Général Serpent', encounterRank: 'boss', maxPlayerUnits: 4, isBoss: true, postCombatDialogueId: 'lion_finale_aftermath', rewards: { gold: 300, reputation: 12, materials: { red_gem: 5 } } },
  { id: 'lion_chief', sceneId: 'lion_sanctum', objective: 'Survivez à l’épreuve du Vieux Lion.', encounterLabel: 'Duel pour le Sceau', encounterRank: 'boss', maxPlayerUnits: 4, isBoss: true, postCombatDialogueId: 'lion_finale_aftermath', rewards: { gold: 200, reputation: -10, materials: { red_gem: 5 } } },
];

const combatVisualComposition: Record<string, Partial<Pick<CombatConfig, 'enemyVisualIds' | 'bossVisualId' | 'escortVisualIds'>>> = {
  village_defense: { enemyVisualIds: ['serpent_raider', 'serpent_brute', 'serpent_raider'] },
  village_raid: { enemyVisualIds: ['serpent_raider', 'serpent_brute', 'serpent_raider', 'serpent_oracle'] },
  forest_patrol: { enemyVisualIds: ['serpent_raider', 'serpent_raider', 'serpent_brute'] },
  forest_ambush: { enemyVisualIds: ['wolf', 'cave_rat', 'forest_spider'] },
  serpent_checkpoint: { enemyVisualIds: ['serpent_raider', 'serpent_brute', 'serpent_oracle'] },
  road_to_valmir: { enemyVisualIds: ['wild_boar', 'venom_serpent', 'forest_badger'] },
  serpent_duelist_trial: { enemyVisualIds: ['serpent_duelist_elite', 'serpent_raider', 'serpent_oracle'] },
  troll_crossing: { enemyVisualIds: ['forest_troll_elite', 'cave_rat', 'forest_spider'] },
  young_dragon_roost: { enemyVisualIds: ['young_dragon_elite', 'venom_serpent', 'marsh_toad'] },
  serpent_captain: {
    bossVisualId: 'serpent_general_boss',
    escortVisualIds: ['serpent_duelist_elite', 'serpent_raider', 'serpent_oracle'],
  },
  lion_chief: {
    bossVisualId: 'alaric',
    escortVisualIds: ['lion_champion', 'seal_guardian'],
  },
};

const rawDialogues = [
  {
    id: 'camp_departure',
    sceneArtId: 'camp_departure',
    steps: [
      {
        id: '1',
        speaker: 'Chroniqueur',
        actorId: 'chroniqueur',
        expression: 'neutral',
        tag: 'Camp du Lion',
        text: 'La compagnie attend l’aube. Le souvenir du clan déchu pèse encore sur chaque épaule. Mais les Sceaux jugent les actes, non le sang. Au-delà des feux, les routes se divisent déjà entre honneur, profit et survie.',
        side: 'center',
        next: null,
        effects: [],
        choices: [],
      },
    ],
  },
  {
    id: 'lion_briefing',
    sceneArtId: 'lion_briefing',
    steps: [
      {
        id: '1',
        speaker: 'Chef Alaric',
        actorId: 'alaric',
        expression: 'stern',
        tag: 'Vieux Lion',
        text: 'Votre clan réclame une place parmi les grands. Alors prouvez-le. Bois-Clair brûle sous les torches des Serpents. Sauvez ce qui peut encore l’être, et le Sceau du Lion entendra votre nom.',
        side: 'right',
        next: '2',
        effects: [],
        choices: [],
      },
      {
        id: '2',
        speaker: 'Conseillère Elara',
        actorId: 'elara',
        expression: 'mystical',
        tag: 'Sage',
        text: 'Secourir les faibles restaurera plus que votre nom. Mais les Serpents ne frappent jamais sans un second piège.',
        side: 'left',
        next: '3',
        effects: [],
        choices: [],
      },
      {
        id: '3',
        speaker: 'Intendant Maelor',
        actorId: 'maelor',
        expression: 'neutral',
        tag: 'Intendant',
        text: 'Ou bien laissez les coffres parler. Un clan ruiné ne rachète pas son honneur avec de belles paroles.',
        side: 'left',
        effects: [],
        choices: [
          { text: 'Accepter la mission d’Alaric.', next: '4', effects: [{ type: 'setFlag', key: 'lionMissionAccepted', value: true }, { type: 'addReputation', amount: 3 }] },
          { text: 'Accepter, mais réclamer une avance.', next: '5', effects: [{ type: 'setFlag', key: 'lionMissionAccepted', value: true }, { type: 'addGold', amount: 60 }, { type: 'addReputation', amount: -3 }] },
        ],
      },
      {
        id: '4',
        speaker: 'Chef Alaric',
        actorId: 'alaric',
        expression: 'stern',
        tag: 'Serment',
        text: 'Alors marchez. Revenez avec Bois-Clair debout, et le Sceau du Lion entendra votre nom.',
        side: 'right',
        next: null,
        effects: [{ type: 'setFlag', key: 'chapterStarted', value: true }],
        choices: [],
      },
      {
        id: '5',
        speaker: 'Chef Alaric',
        actorId: 'alaric',
        expression: 'stern',
        tag: 'Serment fragile',
        text: 'Vous négociez vite pour un clan qui demande confiance. Prenez l’or. Mais chaque pièce pèsera dans mon jugement.',
        side: 'right',
        next: null,
        effects: [{ type: 'setFlag', key: 'chapterStarted', value: true }, { type: 'setFlag', key: 'alaricDoubt', value: true }],
        choices: [],
      },
    ],
  },
  {
    id: 'refugee_trial',
    sceneArtId: 'refugee_trial',
    steps: [
      {
        id: '1',
        speaker: 'Mère réfugiée',
        actorId: 'refugee_mother',
        expression: 'fearful',
        tag: 'Route des réfugiés',
        text: 'Les Serpents ont pris nos vivres. Les enfants ne tiendront pas jusqu’au refuge. Partagerez-vous vos réserves ?',
        side: 'left',
        effects: [],
        choices: [
          { text: 'Partager vos réserves — 40 or.', next: '2', requiresGold: 40, effects: [{ type: 'addGold', amount: -40 }, { type: 'addReputation', amount: 8 }, { type: 'setFlag', key: 'helpedRefugees', value: true }] },
          { text: 'Prendre l’information et continuer.', next: '3', effects: [{ type: 'addGold', amount: 40 }, { type: 'addReputation', amount: -8 }, { type: 'setFlag', key: 'exploitedRefugees', value: true }] },
        ],
      },
      {
        id: '2',
        speaker: 'Mère réfugiée',
        actorId: 'refugee_mother',
        expression: 'grateful',
        tag: 'Gratitude',
        text: 'Que le Lion se souvienne de vous. Une piste évite les guetteurs au nord.',
        side: 'left',
        next: null,
        effects: [{ type: 'addItem', itemId: 'potion', quantity: 1 }],
        choices: [],
      },
      {
        id: '3',
        speaker: 'Intendant Maelor',
        actorId: 'maelor',
        expression: 'neutral',
        tag: 'Calcul',
        text: 'Ils survivront peut-être. Vous, au moins, avez gagné de quoi survivre sûrement.',
        side: 'left',
        next: null,
        effects: [],
        choices: [],
      },
    ],
  },
  {
    id: 'reserve_trail',
    sceneArtId: 'reserve_trail',
    steps: [
      {
        id: '1',
        speaker: 'Cedric',
        actorId: 'cedric',
        expression: 'neutral',
        tag: 'Chemin des réserves',
        text: 'Un convoi Serpent transporte les coffres de Bois-Clair. L’intercepter enrichira la compagnie, mais retardera le secours.',
        side: 'right',
        effects: [],
        choices: [
          { text: 'Frapper le convoi et saisir les réserves.', next: '2', effects: [{ type: 'addGold', amount: 120 }, { type: 'addReputation', amount: -6 }, { type: 'setFlag', key: 'prioritizedLoot', value: true }] },
          { text: 'Marquer le convoi et continuer vers le village.', next: '3', effects: [{ type: 'addReputation', amount: 4 }, { type: 'setFlag', key: 'prioritizedVillage', value: true }] },
        ],
      },
      {
        id: '2',
        speaker: 'Intendant Maelor',
        actorId: 'maelor',
        expression: 'neutral',
        tag: 'Butin',
        text: 'Une bourse pleine vaut parfois mieux qu’une chanson de gratitude.',
        side: 'left',
        next: null,
        effects: [{ type: 'addItem', itemId: 'bomb', quantity: 1 }],
        choices: [],
      },
      {
        id: '3',
        speaker: 'Conseillère Elara',
        actorId: 'elara',
        expression: 'stern',
        tag: 'Urgence',
        text: 'Les coffres peuvent attendre. Les vivants, non.',
        side: 'left',
        next: null,
        effects: [],
        choices: [],
      },
    ],
  },
  {
    id: 'village_choice',
    sceneArtId: 'village_choice',
    steps: [
      {
        id: '1',
        speaker: 'Villageoise de Bois-Clair',
        actorId: 'villageoise',
        expression: 'fearful',
        tag: 'En détresse',
        text: 'Ils emmènent les enfants vers le nord. Les coffres du village brûlent déjà. Qu’allez-vous sauver ?',
        side: 'left',
        effects: [],
        choices: [
          { text: 'Sauver les habitants.', next: '2', effects: [{ type: 'setFlag', key: 'missionSuccess', value: true }, { type: 'addReputation', amount: 10 }, { type: 'startCombat', combatId: 'village_defense' }] },
          { text: 'Sécuriser les réserves.', next: '3', effects: [{ type: 'setFlag', key: 'missionSuccess', value: false }, { type: 'setFlag', key: 'missionGreed', value: true }, { type: 'addGold', amount: 200 }, { type: 'addReputation', amount: -10 }, { type: 'startCombat', combatId: 'village_raid' }] },
        ],
      },
      {
        id: '2',
        speaker: 'Villageoise de Bois-Clair',
        actorId: 'villageoise',
        expression: 'grateful',
        tag: 'Bois-Clair',
        text: 'Merci. Le vieux pont mène directement à leurs positions.',
        side: 'left',
        next: null,
        effects: [],
        choices: [],
      },
      {
        id: '3',
        speaker: 'Villageoise de Bois-Clair',
        actorId: 'villageoise',
        expression: 'wounded',
        tag: 'Bois-Clair',
        text: 'Prenez l’or si vous le voulez... mais ne prétendez plus être nos protecteurs.',
        side: 'left',
        next: null,
        effects: [],
        choices: [],
      },
    ],
  },
  {
    id: 'mystery_recruit',
    sceneArtId: 'mystery_recruit',
    steps: [
      {
        id: '1',
        speaker: 'Cedric',
        actorId: 'cedric',
        expression: 'neutral',
        tag: 'Éclaireur nomade',
        text: 'Je connais les passages des Serpents. Cinquante pièces, et mon arc rejoint votre compagnie.',
        side: 'right',
        effects: [],
        choices: [
          { text: 'Recruter Cedric — 50 or.', next: '2', requiresGold: 50, effects: [{ type: 'addGold', amount: -50 }, { type: 'recruitUnit', unitId: 'cedric' }, { type: 'addReputation', amount: 3 }] },
          { text: 'Décliner.', next: '3', effects: [] },
        ],
      },
      { id: '2', speaker: 'Cedric', actorId: 'cedric', expression: 'grateful', tag: 'Nouvel allié', text: 'Marché conclu. Je vous montrerai où frapper.', side: 'right', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Cedric', actorId: 'cedric', expression: 'stern', tag: 'Éclaireur nomade', text: 'Alors évitez les lanternes vertes. Elles marquent leurs embuscades.', side: 'right', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'mystery_help',
    sceneArtId: 'mystery_help',
    steps: [
      {
        id: '1',
        speaker: 'Marchand blessé',
        actorId: 'wounded_merchant',
        expression: 'wounded',
        tag: 'Quête secondaire',
        text: 'Mon chariot est brisé et les loups approchent. Pouvez-vous partager quelques provisions ?',
        side: 'left',
        effects: [],
        choices: [
          { text: 'L’aider — 30 or.', next: '2', requiresGold: 30, effects: [{ type: 'addGold', amount: -30 }, { type: 'addReputation', amount: 8 }, { type: 'setFlag', key: 'helpedMerchant', value: true }] },
          { text: 'Continuer la route.', next: '3', effects: [{ type: 'addReputation', amount: -2 }] },
        ],
      },
      { id: '2', speaker: 'Marchand blessé', actorId: 'wounded_merchant', expression: 'grateful', tag: 'Allié', text: 'Je ferai parvenir des potions au refuge. Vous avez ma parole.', side: 'left', next: null, effects: [{ type: 'addItem', itemId: 'potion', quantity: 1 }], choices: [] },
      { id: '3', speaker: 'Marchand blessé', actorId: 'wounded_merchant', expression: 'wounded', tag: 'Abandonné', text: 'Allez... Je trouverai bien une autre âme charitable.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'mystery_ambush',
    sceneArtId: 'mystery_ambush',
    steps: [
      { id: '1', speaker: 'Pillard Serpent', actorId: 'serpent_raider', expression: 'hostile', tag: 'Embuscade', text: 'Vous avez suivi exactement le chemin que nous avions préparé.', side: 'right', next: null, effects: [{ type: 'startCombat', combatId: 'forest_ambush' }], choices: [] },
    ],
  },
  {
    id: 'serpent_duelist_trial',
    sceneArtId: 'serpent_duelist_trial',
    steps: [
      {
        id: '1',
        speaker: 'Duelliste Serpent',
        actorId: 'serpent_duelist_elite',
        expression: 'hostile',
        tag: 'Élite Serpent',
        text: 'Un guerrier masqué attend au milieu du sentier. Ses lames sont basses, patientes, déjà prêtes à punir la moindre hésitation.',
        side: 'right',
        effects: [],
        choices: [
          { text: 'Accepter le duel et briser son barrage.', next: '2', effects: [{ type: 'addReputation', amount: 2 }, { type: 'startCombat', combatId: 'serpent_duelist_trial' }] },
          { text: 'Contourner par les ronces — 60 or.', next: '3', requiresGold: 60, effects: [{ type: 'addGold', amount: -60 }, { type: 'addReputation', amount: -2 }] },
        ],
      },
      { id: '2', speaker: 'Conseillère Elara', actorId: 'elara', expression: 'stern', tag: 'Défi', text: 'Les Serpents testent notre résolution. Que ce masque tombe devant le Lion.', side: 'left', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Chroniqueur', actorId: 'chroniqueur', expression: 'neutral', tag: 'Détour', text: 'La route se referme derrière vous. Le duelliste ne tombe pas, mais vous gagnez quelques heures de vie.', side: 'center', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'mystery_troll_crossing',
    sceneArtId: 'mystery_troll_crossing',
    steps: [
      {
        id: '1',
        speaker: 'Troll des pierres',
        actorId: 'forest_troll_elite',
        expression: 'hostile',
        tag: 'Défi secondaire',
        text: 'Le pont de mousse craque sous un troll énorme. Derrière lui, des sacs volés portent encore les sceaux de Bois-Clair.',
        side: 'right',
        effects: [],
        choices: [
          { text: 'Le défier et récupérer les sacs.', next: '2', effects: [{ type: 'addReputation', amount: 3 }, { type: 'startCombat', combatId: 'troll_crossing' }] },
          { text: 'Lui abandonner une bourse — 80 or.', next: '3', requiresGold: 80, effects: [{ type: 'addGold', amount: -80 }, { type: 'addReputation', amount: -1 }] },
        ],
      },
      { id: '2', speaker: 'Cedric', actorId: 'cedric', expression: 'stern', tag: 'Passage', text: 'S’il tombe, toute la vallée saura que la route n’appartient plus aux brutes.', side: 'right', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'neutral', tag: 'Tribut', text: 'Un prix laid, mais moins laid qu’un cercueil. Nous reviendrons plus lourds de fer.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'mystery_dragon_roost',
    sceneArtId: 'mystery_dragon_roost',
    steps: [
      {
        id: '1',
        speaker: 'Jeune dragon',
        actorId: 'young_dragon_elite',
        expression: 'hostile',
        tag: 'Rencontre rare',
        text: 'Une chaleur verte rampe entre les pierres. Au-dessus du vieux sanctuaire, un jeune dragon protège un nid de gemmes brutes.',
        side: 'right',
        effects: [],
        choices: [
          { text: 'Affronter la bête pour les gemmes.', next: '2', effects: [{ type: 'setFlag', key: 'challengedYoungDragon', value: true }, { type: 'startCombat', combatId: 'young_dragon_roost' }] },
          { text: 'Sceller l’accès et marquer le lieu.', next: '3', effects: [{ type: 'addReputation', amount: 4 }, { type: 'setFlag', key: 'sparedYoungDragon', value: true }] },
        ],
      },
      { id: '2', speaker: 'Conseillère Elara', actorId: 'elara', expression: 'mystical', tag: 'Gemme vive', text: 'Ses écailles résonnent avec les Sceaux. Ce combat peut nous enrichir, ou nous annoncer aux Ombres.', side: 'left', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Chroniqueur', actorId: 'chroniqueur', expression: 'neutral', tag: 'Marque', text: 'Vous laissez une balise discrète. Certains trésors valent mieux lorsqu’ils attendent le bon serment.', side: 'center', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'mystery_treasure',
    sceneArtId: 'mystery_treasure',
    steps: [
      { id: '1', speaker: 'Chroniqueur', actorId: 'chroniqueur', expression: 'neutral', tag: 'Trésor', text: 'Sous les racines, vous découvrez une bourse intacte et une potion scellée.', side: 'center', next: null, effects: [{ type: 'addGold', amount: 100 }, { type: 'addItem', itemId: 'potion', quantity: 1 }], choices: [] },
    ],
  },
  {
    id: 'mystery_shrine',
    sceneArtId: 'mystery_shrine',
    steps: [
      { id: '1', speaker: 'Apparition du sanctuaire', actorId: 'shrine_apparition', expression: 'mystical', tag: 'Mystère', text: 'Le sceau gravé dans la pierre réagit à votre présence. Une chaleur calme traverse la compagnie.', side: 'center', next: null, effects: [{ type: 'addReputation', amount: 4 }, { type: 'setFlag', key: 'shrineBlessing', value: true }], choices: [] },
    ],
  },
  {
    id: 'witnesses_on_road',
    sceneArtId: 'witnesses_on_road',
    steps: [
      {
        id: '1',
        speaker: 'Survivant de Bois-Clair',
        actorId: 'survivor',
        expression: 'wounded',
        tag: 'Témoins',
        text: 'Nous avons vu ce que vous avez choisi au village. Nos mots vous précéderont devant Alaric.',
        side: 'left',
        effects: [],
        choices: [
          { text: 'Protéger les témoins jusqu’au camp.', next: '2', requiresReputationMin: 45, blockedText: 'Ils refusent votre escorte.', effects: [{ type: 'addReputation', amount: 5 }, { type: 'setFlag', key: 'protectedWitnesses', value: true }] },
          { text: 'Acheter leur silence.', next: '3', requiresGold: 80, effects: [{ type: 'addGold', amount: -80 }, { type: 'addReputation', amount: -5 }, { type: 'setFlag', key: 'silencedWitnesses', value: true }] },
        ],
      },
      { id: '2', speaker: 'Survivant de Bois-Clair', actorId: 'survivor', expression: 'grateful', tag: 'Parole sauvée', text: 'Alors nous parlerons. Pas pour vous flatter, mais parce que la vérité doit survivre.', side: 'left', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'neutral', tag: 'Silence', text: 'La vérité coûte cher. Heureusement, le silence a un prix plus simple.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'shadow_signs',
    sceneArtId: 'shadow_signs',
    steps: [
      {
        id: '1',
        speaker: 'Conseillère Elara',
        actorId: 'elara',
        expression: 'mystical',
        tag: 'Ombres silencieuses',
        text: 'Ces marques ne sont pas du Serpent. Quelqu’un guide leurs raids avec une magie ancienne, plus vieille que les Sceaux eux-mêmes.',
        side: 'left',
        effects: [],
        choices: [
          { text: 'Préserver les preuves pour Alaric.', next: '2', effects: [{ type: 'addReputation', amount: 5 }, { type: 'setFlag', key: 'shadowEvidence', value: true }] },
          { text: 'Briser l’autel et récupérer les fragments.', next: '3', effects: [{ type: 'addItem', itemId: 'iron_ore', quantity: 2 }, { type: 'addReputation', amount: -2 }, { type: 'setFlag', key: 'shadowFragments', value: true }] },
        ],
      },
      { id: '2', speaker: 'Conseillère Elara', actorId: 'elara', expression: 'stern', tag: 'Preuve', text: 'Avec ceci, Alaric verra que son conflit dépasse les frontières du Lion. Ce que nous avons trouvé n’est pas une simple guerre de clan.', side: 'left', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Intendant Maelor', actorId: 'maelor', expression: 'neutral', tag: 'Artefact', text: 'La preuve convainc les chefs. Les fragments arment les survivants.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'lion_finale_judgement',
    sceneArtId: 'lion_finale_judgement',
    steps: [
      {
        id: '1',
        speaker: 'Chef Alaric',
        actorId: 'alaric',
        expression: 'stern',
        tag: 'Audience',
        text: 'Votre clan est jeune. Peu de bouches portent encore votre nom, et celles qui le font hésitent entre gratitude et méfiance. Avant de parler du Sceau, parlons de la route. Les réfugiés de Bois-Clair — que disent-ils de vous ?',
        side: 'right',
        next: null,
        effects: [],
        choices: [
          { text: 'Ils bénissent votre nom.', next: '2', requiresFlag: 'helpedRefugees', effects: [{ type: 'addReputation', amount: 5 }] },
          { text: 'Ils ne vous mentionnent pas.', next: '2', excludesFlag: 'helpedRefugees', effects: [] },
        ],
      },
      {
        id: '2',
        speaker: 'Chef Alaric',
        actorId: 'alaric',
        expression: 'neutral',
        tag: 'Témoins',
        text: 'Et les survivants de Bois-Clair ? Ont-ils parlé pour vous, ou se sont-ils tus ?',
        side: 'right',
        next: null,
        effects: [],
        choices: [
          { text: 'Ils ont parlé en votre faveur.', next: '3', requiresFlag: 'protectedWitnesses', effects: [{ type: 'addReputation', amount: 5 }] },
          { text: 'Ils se sont tus.', next: '3', excludesFlag: 'protectedWitnesses', effects: [] },
        ],
      },
      {
        id: '3',
        speaker: 'Chef Alaric',
        actorId: 'alaric',
        expression: 'neutral',
        tag: 'Routes',
        text: 'Un marchand m’a dit que vous l’aviez aidé sur la route. Est-ce vrai, ou cherche-t-il seulement votre faveur ?',
        side: 'right',
        next: null,
        effects: [],
        choices: [
          { text: 'Nous l’avons aidé sans contrepartie.', next: '4', requiresFlag: 'helpedMerchant', effects: [{ type: 'addReputation', amount: 3 }] },
          { text: 'Rien de marquant sur les routes.', next: '4', excludesFlag: 'helpedMerchant', effects: [] },
        ],
      },
      {
        id: '4',
        speaker: 'Chef Alaric',
        actorId: 'alaric',
        expression: 'neutral',
        tag: 'Convoi',
        text: 'Le convoi que vous avez croisé — l’avez-vous marqué pour le village, ou frappé pour les réserves ?',
        side: 'right',
        next: null,
        effects: [],
        choices: [
          { text: 'Nous l’avons marqué pour le village.', next: '5', requiresFlag: 'prioritizedVillage', effects: [{ type: 'addReputation', amount: 3 }] },
          { text: 'Nous avons pris ce dont nous avions besoin.', next: '5', excludesFlag: 'prioritizedVillage', effects: [] },
        ],
      },
      {
        id: '5',
        speaker: 'Chef Alaric',
        actorId: 'alaric',
        expression: 'neutral',
        tag: 'Sanctuaire',
        text: 'Le sanctuaire dans les collines — y avez-vous trouvé quelque chose ?',
        side: 'right',
        next: null,
        effects: [],
        choices: [
          { text: 'Une bénédiction, rien de plus.', next: '6', requiresFlag: 'shrineBlessing', effects: [{ type: 'addReputation', amount: 3 }] },
          { text: 'Nous n’avons rien trouvé.', next: '6', excludesFlag: 'shrineBlessing', effects: [] },
        ],
      },
      {
        id: '6',
        speaker: 'Chef Alaric',
        actorId: 'alaric',
        expression: 'neutral',
        tag: 'Cimes',
        text: 'Et les cimes du Lion ? On dit qu’un jeune dragon y veille. L’avez-vous affronté, ou scellé l’accès ?',
        side: 'right',
        next: null,
        effects: [],
        choices: [
          { text: 'Nous l’avons affronté pour les gemmes.', next: '7', requiresFlag: 'challengedYoungDragon', effects: [] },
          { text: 'Nous avons scellé l’accès.', next: '7', excludesFlag: 'challengedYoungDragon', effects: [] },
        ],
      },
      {
        id: '7',
        speaker: 'Chef Alaric',
        actorId: 'alaric',
        expression: 'stern',
        tag: 'Accusation',
        text: 'Mais certains murmurent contre vous. Les réfugiés de Bois-Clair disent que vous avez pris leurs vivres. Qu’avez-vous à dire ?',
        side: 'right',
        next: null,
        effects: [],
        choices: [
          { text: 'Ils maudissent votre nom.', next: '8', requiresFlag: 'exploitedRefugees', effects: [{ type: 'addReputation', amount: -5 }] },
          { text: 'Aucun murmure contre vous.', next: '8', excludesFlag: 'exploitedRefugees', effects: [] },
        ],
      },
      {
        id: '8',
        speaker: 'Chef Alaric',
        actorId: 'alaric',
        expression: 'stern',
        tag: 'Silence',
        text: 'Et les témoins de Bois-Clair ? On dit que vous avez acheté leur silence plutôt que de les protéger.',
        side: 'right',
        next: null,
        effects: [],
        choices: [
          { text: 'Ils se sont tus par votre faute.', next: '9', requiresFlag: 'silencedWitnesses', effects: [{ type: 'addReputation', amount: -5 }] },
          { text: 'Rien de tel ne s’est passé.', next: '9', excludesFlag: 'silencedWitnesses', effects: [] },
        ],
      },
      {
        id: '9',
        speaker: 'Chef Alaric',
        actorId: 'alaric',
        expression: 'stern',
        tag: 'Réserves',
        text: 'Le convoi des réserves — certains disent que vous avez pris le butin avant les villageois.',
        side: 'right',
        next: null,
        effects: [],
        choices: [
          { text: 'Nous avons pris notre part.', next: '10', requiresFlag: 'prioritizedLoot', effects: [{ type: 'addReputation', amount: -3 }] },
          { text: 'Le convoi est intact.', next: '10', excludesFlag: 'prioritizedLoot', effects: [] },
        ],
      },
      {
        id: '10',
        speaker: 'Chef Alaric',
        actorId: 'alaric',
        expression: 'stern',
        tag: 'Doute',
        text: 'Lors de notre première audience, j’ai exprimé des doutes sur votre clan. Sont-ils fondés ?',
        side: 'right',
        next: null,
        effects: [],
        choices: [
          { text: 'Vos doutes étaient justifiés.', next: '11', requiresFlag: 'alaricDoubt', effects: [{ type: 'addReputation', amount: -3 }] },
          { text: 'Vos doutes étaient infondés.', next: '11', excludesFlag: 'alaricDoubt', effects: [] },
        ],
      },
      {
        id: '11',
        speaker: 'Chef Alaric',
        actorId: 'alaric',
        expression: 'stern',
        tag: 'Jugement du Lion',
        text: 'Bois-Clair a vu votre réponse. Les survivants chantent votre nom ou le maudissent. Dites-moi maintenant, sans détour, comment votre clan réclame le Sceau du Lion.',
        side: 'right',
        effects: [],
        choices: [
          { text: 'Présenter les survivants et les preuves.', next: '12', requiresFlag: 'missionSuccess', excludesFlag: 'missionGreed', requiresReputationMin: 45, blockedText: 'Vos actes à Bois-Clair parlent contre vous.', effects: [{ type: 'addReputation', amount: 8 }, { type: 'setFlag', key: 'lionSealHonour', value: true }, { type: 'startCombat', combatId: 'serpent_captain' }] },
          { text: 'Demander l’épreuve du Lion.', next: '13', effects: [{ type: 'addReputation', amount: -6 }, { type: 'setFlag', key: 'lionTrialRequested', value: true }, { type: 'startCombat', combatId: 'lion_chief' }] },
        ],
      },
      { id: '12', speaker: 'Chef Alaric', actorId: 'alaric', expression: 'grateful', tag: 'Respect', text: 'Alors le Lion vous reconnaît. Le général Serpent fuit avec un artefact des Ombres. Finissez ce que vous avez commencé.', side: 'right', next: null, effects: [], choices: [] },
      { id: '13', speaker: 'Chef Alaric', actorId: 'alaric', expression: 'hostile', tag: 'Défi', text: 'Vous demandez le Sceau sans être certain que l’honneur vous le donne. Alors prenez-le si votre lame le mérite.', side: 'right', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'lion_finale_aftermath',
    sceneArtId: 'lion_finale_judgement',
    steps: [
      {
        id: '1',
        speaker: 'Conseillère Elara',
        actorId: 'elara',
        expression: 'mystical',
        tag: 'Révélation',
        text: 'Le combat est fini. Mais ce que portait l’ennemi n’était pas une arme ordinaire — c’est une marque des Ombres. Ceux qui ont brisé l’autel en ont vu les fragments.',
        side: 'left',
        next: null,
        effects: [],
        choices: [
          { text: 'Révéler les preuves des Ombres à Alaric.', next: '2', requiresFlag: 'shadowEvidence', effects: [{ type: 'addReputation', amount: 10 }, { type: 'setFlag', key: 'shadowRevealed', value: true }] },
          { text: 'Garder le silence sur les Ombres.', next: '3', effects: [{ type: 'addReputation', amount: -3 }] },
        ],
      },
      { id: '2', speaker: 'Chef Alaric', actorId: 'alaric', expression: 'fearful', tag: 'Vérité', text: 'Des Ombres… Alors ce que nous voyions n’était pas de la folie. Merci d’avoir parlé. Le Lion se souviendra de cette vérité.', side: 'right', next: null, effects: [], choices: [] },
      { id: '3', speaker: 'Conseillère Elara', actorId: 'elara', expression: 'neutral', tag: 'Silence', text: 'Vous gardez le secret. Peut-être pour protéger le clan, peut-être par peur. Mais les Ombres n’oublient pas ceux qui les ignorent.', side: 'left', next: null, effects: [], choices: [] },
    ],
  },
  {
    id: 'epilogue',
    sceneArtId: 'epilogue',
    steps: [
      {
        id: '1',
        speaker: 'Chroniqueur',
        actorId: 'chroniqueur',
        expression: 'neutral',
        tag: 'Épilogue',
        text: 'Le premier Sceau répond enfin à votre appel. Les chemins du Lion se ferment derrière vous. Mais au-delà des montagnes, le Serpent rassemble déjà ses armées.',
        side: 'center',
        next: null,
        effects: [],
        choices: [
          { text: 'Parler de ce que vous avez vu.', next: '2', requiresFlag: 'shadowRevealed', effects: [{ type: 'finishChapter', endingId: 'lion-seal-truth' }] },
          { text: 'Partir avec le Sceau en silence.', next: '3', effects: [{ type: 'finishChapter', endingId: 'lion-seal' }] },
        ],
      },
      {
        id: '2',
        speaker: 'Chroniqueur',
        actorId: 'chroniqueur',
        expression: 'neutral',
        tag: 'Vérité',
        text: 'Alaric a entendu la vérité sur les Ombres. Le Lion prépare ses défenses. Et dans l’ombre, quelque chose de plus ancien sait désormais votre nom.',
        side: 'center',
        next: '4',
        effects: [],
        choices: [],
      },
      {
        id: '3',
        speaker: 'Chroniqueur',
        actorId: 'chroniqueur',
        expression: 'neutral',
        tag: 'Silence',
        text: 'Vous emportez le Sceau et ses secrets. Les Ombres restent dans l’ombre — pour l’instant. Mais quelque chose de plus ancien a retenu votre nom.',
        side: 'center',
        next: '4',
        effects: [],
        choices: [],
      },
      {
        id: '4',
        speaker: 'Chroniqueur',
        actorId: 'chroniqueur',
        expression: 'neutral',
        tag: 'Les cimes',
        text: 'Avant de partir, vous regardez une dernière fois les cimes du Lion.',
        side: 'center',
        next: null,
        effects: [],
        choices: [
          { text: 'Le jeune dragon veille toujours.', next: '5', requiresFlag: 'sparedYoungDragon', effects: [] },
          { text: 'Les cimes sont silencieuses.', next: '5', excludesFlag: 'sparedYoungDragon', effects: [] },
        ],
      },
      {
        id: '5',
        speaker: 'Chroniqueur',
        actorId: 'chroniqueur',
        expression: 'neutral',
        tag: 'Le Sceau',
        text: 'Le Sceau du Lion repose en vos mains. Mais comment l’avez-vous obtenu ?',
        side: 'center',
        next: null,
        effects: [],
        choices: [
          { text: 'Il vous a été donné avec respect.', next: null, requiresFlag: 'lionSealHonour', effects: [] },
          { text: 'Il a été pris, non donné.', next: null, excludesFlag: 'lionSealHonour', effects: [] },
        ],
      },
    ],
  },
];

export const campaignNodes = rawNodes.map((node) => campaignNodeSchema.parse(node));
export const combatConfigs = new Map(rawCombats.map((combat) => {
  const parsed = combatConfigSchema.parse({ ...combat, ...combatVisualComposition[combat.id] });
  return [parsed.id, parsed];
}));
export const dialogues = new Map(rawDialogues.map((dialogue) => {
  const parsed = dialogueSequenceSchema.parse(dialogue);
  return [parsed.id, parsed];
}));
