import type { SkillDefinition } from './types';

export const skills: SkillDefinition[] = [
// WARRIOR
{id:'w_break_guard',name:'Brise-Garde',description:'P9, monocible, réduit l\'END 1 tour.',ap:2,icon:'⚔',type:'phys',power:9,range:[1,1],offensive:true,acc:0.95,status:'curse',statusTurns:1,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'2 tours',statusTurnsBonus:1}},
{id:'w_charge',name:'Charge',description:'Avance 2-3 cases et frappe P11.',ap:3,icon:'↟',type:'move',mode:'dash',dest:true,range:[2,3],power:11,impact:{status:'stun',statusTurns:1},upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Étourdit cible finale'}},
{id:'w_whirl',name:'Tourbillon d\'Acier',description:'P16 contre ennemis adjacents.',ap:4,icon:'⚔',type:'phys',power:16,range:[0,0],radius:1,self:true,offensive:true,acc:0.95,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Rayon+',radiusBonus:0.25}},
{id:'w_lion_surge',name:'Déferlement du Lion',description:'Déchaîne une ligne P30, ignore 30% END, étourdit la cible finale.',ap:5,icon:'⚔',type:'phys',power:30,range:[1,3],radius:1,shape:'line',offensive:true,acc:0.9,penetration:0.3,damageMultiplier:1.3,impact:{status:'stun',statusTurns:1},upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Ignore 60% END',penetrationBonus:0.3}},
// PALADIN
{id:'p_holy_strike',name:'Frappe Consacrée',description:'P9 et Barrière au Paladin.',ap:2,icon:'✚',type:'phys',power:9,range:[1,1],offensive:true,acc:0.95,effects:[{kind:'damage',target:'enemies',damageType:'phys',power:9},{kind:'status',target:'caster',status:'barrier',statusTurns:1}],upgradeLevel1:{description:'Barrière 2 tours',statusTurnsBonus:1},upgradeLevel2:{description:'Soigne 10% PV',selfHealPercent:0.1}},
{id:'p_interpose',name:'Interposition',description:'Bondit sur une case libre et protège les alliés proches.',ap:3,icon:'✚',type:'move',mode:'leap',dest:true,movePhase:'before',range:[2,3],radius:1,support:true,effects:[{kind:'status',target:'allies',status:'barrier',statusTurns:2}],upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Provoque ennemis voisins',additionalStatus:'taunt',additionalStatusTurns:2,additionalStatusTarget:'enemies'}},
{id:'p_oathwall',name:'Rempart du Serment',description:'Barrière de zone + Provocation sur Paladin.',ap:4,icon:'✚',type:'buff',power:0,range:[0,0],radius:1.3,self:true,support:true,status:'barrier',statusTurns:3,effects:[{kind:'status',target:'self',status:'taunt',statusTurns:2},{kind:'status',target:'allies',status:'barrier',statusTurns:3}],upgradeLevel1:{description:'Rayon+',radiusBonus:0.25},upgradeLevel2:{description:'Retire altération alliés',dispelAllies:true}},
{id:'p_radiant_judgement',name:'Jugement Radieux',description:'P26 zone ennemis + soin alliés.',ap:5,icon:'✚',type:'phys',power:26,range:[1,3],radius:1.5,offensive:true,acc:0.9,damageMultiplier:1.3,effects:[{kind:'damage',target:'enemies',damageType:'phys',power:26},{kind:'heal',target:'allies',flatHeal:20}],upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Barrière alliés',additionalStatus:'barrier',additionalStatusTurns:2,additionalStatusTarget:'allies'}},
// DARK KNIGHT
{id:'d_cursed_blade',name:'Lame Maudite',description:'P10 et Malédiction 1 tour.',ap:2,icon:'⚔',type:'phys',power:10,range:[1,1],offensive:true,acc:0.95,status:'curse',statusTurns:1,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'2 tours',statusTurnsBonus:1}},
{id:'d_void_step',name:'Pas du Néant',description:'Téléportation 2-3 cases.',ap:3,icon:'✦',type:'move',mode:'teleport',dest:true,movePhase:'before',range:[2,3],radius:1,effects:[],upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Affaiblit adjacents',additionalStatus:'weak',additionalStatusTurns:1,additionalStatusTarget:'enemies'}},
{id:'d_blood_pact',name:'Pacte de Sang',description:'Sacrifie 15% PV, Force+ et vol de vie.',ap:4,icon:'⚔',type:'buff',power:0,range:[0,0],self:true,support:true,effects:[{kind:'hp_cost',target:'caster',hpCostPercent:0.15},{kind:'status',target:'caster',status:'boost',statusTurns:2},{kind:'lifesteal',target:'caster',lifestealPercent:0.5}],upgradeLevel1:{description:'Coût 10%',hpCostReduction:0.05},upgradeLevel2:{description:'Vol de vie+',lifestealBonus:0.25,statusTurnsBonus:1}},
{id:'d_devouring_eclipse',name:'Éclipse Dévorante',description:'P30 zone, Malédiction, soigne 30% dégâts.',ap:5,icon:'⚔',type:'mag',power:30,range:[1,3],radius:1.5,offensive:true,acc:0.85,status:'curse',statusTurns:2,damageMultiplier:1.3,effects:[{kind:'damage',target:'enemies',damageType:'mag',power:30,status:'curse',statusTurns:2},{kind:'lifesteal',target:'caster',lifestealPercent:0.30}],upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Rayon+ et vol+',radiusBonus:0.25,lifestealBonus:0.1}},
// LANCER
{id:'l_long_thrust',name:'Estoc Long',description:'P10 à 2 cases, ignore 20% END.',ap:2,icon:'↟',type:'phys',power:10,range:[2,2],offensive:true,acc:0.95,penetration:0.2,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Aussi à 1 case',minRangeReduction:1}},
{id:'l_haft_recoil',name:'Repli de Hampe',description:'P10 puis recule vers une case libre.',ap:3,icon:'↟',type:'phys',power:10,range:[1,1],offensive:true,targetMode:'enemy',mode:'retreat',movePhase:'after',acc:0.9,upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Ralentissement',additionalStatus:'slow',additionalStatusTurns:2,additionalStatusTarget:'selected'}},
{id:'l_griffon_jump',name:'Saut du Griffon',description:'Bond 3 cases, impact zone P16.',ap:4,icon:'↟',type:'phys',power:16,range:[2,3],radius:1,mode:'leap',dest:true,movePhase:'before',offensive:true,acc:0.9,upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Étourdit centre',additionalStatus:'stun',additionalStatusTurns:1,additionalStatusTarget:'enemies'}},
{id:'l_firmament_lance',name:'Lance du Firmament',description:'P32 ligne longue, 60% pénétration, bonus vs boss.',ap:5,icon:'↟',type:'phys',power:32,range:[2,4],radius:2,shape:'line',offensive:true,acc:0.95,penetration:0.6,damageMultiplier:1.2,bonusVsSize:1.3,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'+25% vs 2×2',penetrationBonus:0.25}},
// MAGE NOIR
{id:'n_dark_bolt',name:'Éclair Noir',description:'P13 magique, portée 4.',ap:2,icon:'✦',type:'mag',power:13,range:[1,4],offensive:true,acc:0.9,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Malédiction 1 tour',additionalStatus:'curse',additionalStatusTurns:1}},
{id:'n_teleport',name:'Téléportation',description:'Déplacement instantané 3 cases.',ap:3,icon:'✦',type:'move',mode:'teleport',dest:true,range:[2,3],upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Barrière arrivée',additionalStatus:'barrier',additionalStatusTurns:1,additionalStatusTarget:'self'}},
{id:'n_flame_wave',name:'Vague de Flammes',description:'Cône P17, Brûlure 2 tours, dégâts alliés.',ap:4,icon:'✦',type:'mag',power:17,range:[1,1],radius:1.6,shape:'cone',offensive:true,acc:0.9,status:'burn',statusTurns:2,allowSelfDamage:true,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Cône+ et 3 tours',radiusBonus:0.3,statusTurnsBonus:1}},
{id:'n_dark_meteor',name:'Météore Obscur',description:'Zone P30, Brûlure, Malédiction, alliés touchés.',ap:5,icon:'✦',type:'mag',power:30,range:[2,4],radius:1.5,offensive:true,acc:0.85,status:'burn',statusTurns:2,allowSelfDamage:true,damageMultiplier:1.3,effects:[{kind:'damage',target:'all',damageType:'mag',power:30,status:'burn',statusTurns:2},{kind:'status',target:'enemies',status:'curse',statusTurns:2}],upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Rayon+',radiusBonus:0.25}},
// MAGE BLANC
{id:'w_salvation',name:'Lumière Salvatrice',description:'Soin monocible à distance.',ap:2,icon:'✚',type:'heal',power:1.2,range:[0,3],targetMode:'ally',support:true,upgradeLevel1:{description:'Soins+15%',healMultiplier:0.15},upgradeLevel2:{description:'Purifie le clan',dispelAllies:true}},
{id:'w_purify',name:'Purification',description:'Soin + dissipe altérations négatives.',ap:3,icon:'✚',type:'heal',power:0.8,range:[0,3],radius:0,targetMode:'ally',support:true,effects:[{kind:'heal',target:'allies',targetSource:'selected',power:0.8},{kind:'dispel',target:'allies',targetSource:'selected',dispelType:'negative'}],upgradeLevel1:{description:'Soin+',healMultiplier:0.15},upgradeLevel2:{description:'Petite zone',radiusBonus:1}},
{id:'w_sanctuary',name:'Sanctuaire',description:'Soin zone + Régénération 3 tours.',ap:4,icon:'✚',type:'buff',power:0.8,range:[0,2],radius:1.3,support:true,status:'regen',statusTurns:3,effects:[{kind:'heal',target:'allies',flatHeal:15},{kind:'status',target:'allies',status:'regen',statusTurns:3}],upgradeLevel1:{description:'Rayon+',radiusBonus:0.25},upgradeLevel2:{description:'Barrière 2 tours',additionalStatus:'barrier',additionalStatusTurns:2,additionalStatusTarget:'allies'}},
{id:'w_miracle',name:'Miracle',description:'Relève allié 75% PV, soigne, purifie et régénère proches.',ap:5,icon:'✚',type:'revive',power:0.75,range:[1,2],radius:1,support:true,effects:[{kind:'revive',target:'allies',targetSource:'selected'},{kind:'heal',target:'allies',flatHeal:25},{kind:'dispel',target:'allies',dispelType:'negative'},{kind:'status',target:'allies',status:'regen',statusTurns:2}],upgradeLevel1:{description:'Résurrection 85%',revivePercent:0.85},upgradeLevel2:{description:'Rayon+ et Barrière',radiusBonus:0.25,additionalStatus:'barrier',additionalStatusTurns:1,additionalStatusTarget:'allies'}},
// MAGE ROUGE
{id:'r_arcane_blade',name:'Lame Arcanique',description:'P10, meilleure FOR/MAG.',ap:2,icon:'✦',type:'phys',power:10,range:[1,1],offensive:true,acc:0.95,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Force+ 1 tour',additionalStatus:'boost',additionalStatusTurns:1}},
{id:'r_rune_step',name:'Pas Runique',description:'Téléportation + Force+ 1 tour.',ap:3,icon:'✦',type:'move',mode:'teleport',dest:true,movePhase:'before',range:[2,3],effects:[{kind:'status',target:'caster',status:'boost',statusTurns:1}],upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Barrière courte',additionalStatus:'barrier',additionalStatusTurns:1,additionalStatusTarget:'self'}},
{id:'r_scarlet_circle',name:'Cercle Écarlate',description:'P16 ennemis + soin alliés zone.',ap:4,icon:'✦',type:'mag',power:16,range:[1,3],radius:1.2,offensive:true,acc:0.9,effects:[{kind:'damage',target:'enemies',damageType:'mag',power:16},{kind:'heal',target:'allies',flatHeal:12}],upgradeLevel1:{description:'P+2 et soin+',powerBonus:2},upgradeLevel2:{description:'Rayon+',radiusBonus:0.25}},
{id:'r_perfect_duality',name:'Dualité Parfaite',description:'P28 grande zone + soin alliés + Barrière lanceur.',ap:5,icon:'✦',type:'mag',power:28,range:[1,3],radius:2,offensive:true,acc:0.85,damageMultiplier:1.2,effects:[{kind:'damage',target:'enemies',damageType:'mag',power:28},{kind:'heal',target:'allies',flatHeal:25},{kind:'status',target:'caster',status:'barrier',statusTurns:2}],upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Purifie alliés',dispelAllies:true}},
// ENCHANTER
{id:'e_vigor_rune',name:'Rune de Vigueur',description:'Force+ sur allié 3 tours.',ap:2,icon:'✦',type:'buff',power:0,range:[0,3],targetMode:'ally',support:true,status:'boost',statusTurns:3,upgradeLevel1:{description:'Portée+',rangeBonus:1},upgradeLevel2:{description:'4 tours',statusTurnsBonus:1}},
{id:'e_transpose',name:'Transposition',description:'Échange position avec un allié.',ap:3,icon:'✦',type:'move',mode:'swap',dest:true,movePhase:'before',targetMode:'ally',range:[1,3],support:true,effects:[],upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Barrière deux unités',additionalStatus:'barrier',additionalStatusTurns:1,additionalStatusTarget:'casterAndSelected'}},
{id:'e_binding_seal',name:'Sceau d\'Entrave',description:'Zone immobilise ennemis 2 tours.',ap:4,icon:'✦',type:'debuff',power:0,range:[1,3],radius:1.2,offensive:true,acc:1,status:'root',statusTurns:2,upgradeLevel1:{description:'Rayon+',radiusBonus:0.25},upgradeLevel2:{description:'Affaibli 1 tour',additionalStatus:'weak',additionalStatusTurns:1}},
{id:'e_absolute_harmony',name:'Harmonie Absolue',description:'Force+, Barrière et Régénération tous alliés 3 tours.',ap:5,icon:'✦',type:'buff',power:0,range:[0,3],radius:2,support:true,effects:[{kind:'status',target:'allies',status:'boost',statusTurns:3},{kind:'status',target:'allies',status:'barrier',statusTurns:3},{kind:'status',target:'allies',status:'regen',statusTurns:2}],upgradeLevel1:{description:'Portée+',rangeBonus:1},upgradeLevel2:{description:'Purification et 4 tours',statusTurnsBonus:1,dispelAllies:true}},
// ARCHER
{id:'a_precise_shot',name:'Tir Précis',description:'P11, portée 2-4, critique accru.',ap:2,icon:'⌁',type:'phys',power:11,range:[2,4],offensive:true,acc:0.95,crit:0.15,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Ignore 30% END',penetrationBonus:0.3}},
{id:'a_hawk_leap',name:'Bond du Faucon',description:'Bond 2-3 cases + améliore prochain tir.',ap:3,icon:'⌁',type:'move',mode:'leap',dest:true,movePhase:'before',range:[2,3],effects:[{kind:'status',target:'caster',status:'boost',statusTurns:1}],upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Barrière à l’arrivée',additionalStatus:'barrier',additionalStatusTurns:1,additionalStatusTarget:'self'}},
{id:'a_arrow_rain',name:'Pluie de Flèches',description:'Zone P14 longue portée, Ralentissement.',ap:4,icon:'⌁',type:'phys',power:14,range:[2,4],radius:1.2,offensive:true,acc:0.9,status:'slow',statusTurns:2,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Rayon+',radiusBonus:0.25}},
{id:'a_zenith_arrow',name:'Flèche du Zénith',description:'P34 monocible, 70% pénétration, bonus vs cible affaiblie.',ap:5,icon:'⌁',type:'phys',power:34,range:[2,4],offensive:true,acc:0.99,penetration:0.7,crit:0.1,damageMultiplier:1.2,bonusVsAfflicted:1.2,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Critique garanti si isolé',critBonus:0.9}},
// NINJA
{id:'ni_venom_blade',name:'Lame Venimeuse',description:'P9 et Poison 2 tours.',ap:2,icon:'†',type:'phys',power:9,range:[1,1],offensive:true,acc:0.95,status:'poison',statusTurns:2,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Poison 3 tours',statusTurnsBonus:1}},
{id:'ni_shadow_step',name:'Pas d\'Ombre',description:'Téléporte derrière cible, P11.',ap:3,icon:'†',type:'move',mode:'strike',dest:true,movePhase:'before',targetMode:'enemy',range:[1,2],power:11,offensive:true,acc:0.9,effects:[{kind:'damage',target:'enemies',targetSource:'selected',damageType:'phys',power:11}],upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Aveuglé 1 tour',additionalStatus:'blind',additionalStatusTurns:1,additionalStatusTarget:'selected'}},
{id:'ni_smoke_bomb',name:'Bombe Fumigène',description:'Zone Aveuglement 2 tours + Barrière Ninja.',ap:4,icon:'†',type:'debuff',power:0,range:[0,1],radius:1.5,offensive:true,acc:1,status:'blind',statusTurns:2,effects:[{kind:'status',target:'enemies',status:'blind',statusTurns:2},{kind:'status',target:'caster',status:'barrier',statusTurns:1}],upgradeLevel1:{description:'Rayon+',radiusBonus:0.25},upgradeLevel2:{description:'Affaiblit ennemis',additionalStatus:'weak',additionalStatusTurns:1}},
{id:'ni_silent_assassin',name:'Assassinat Silencieux',description:'Téléporte, P32, bonus vs cible affaiblie.',ap:5,icon:'†',type:'phys',mode:'strike',dest:true,movePhase:'before',targetMode:'enemy',power:32,range:[1,3],offensive:true,acc:0.95,damageMultiplier:1.3,bonusVsAfflicted:1.3,effects:[{kind:'damage',target:'enemies',targetSource:'selected',damageType:'phys',power:32}],upgradeLevel1:{description:'Bonus sous 70% PV',powerBonus:4},upgradeLevel2:{description:'Poison si survit',additionalStatus:'poison',additionalStatusTurns:2,additionalStatusTarget:'selected'}},
// ROGUE
{id:'ro_sneak_attack',name:'Coup Sournois',description:'P10, critique élevé, fort depuis dos.',ap:2,icon:'†',type:'phys',power:10,range:[1,1],offensive:true,acc:0.9,crit:0.2,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Critique garanti dos',critBonus:0.8}},
{id:'ro_tumble',name:'Roulade',description:'Bond 2-3 cases + bonus critique.',ap:3,icon:'†',type:'move',mode:'leap',dest:true,movePhase:'before',range:[2,3],effects:[{kind:'status',target:'caster',status:'boost',statusTurns:1}],upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Barrière courte',additionalStatus:'barrier',additionalStatusTurns:1,additionalStatusTarget:'self'}},
{id:'ro_jaw_trap',name:'Mâchoire à Ressort',description:'P16 et immobilise 2 tours.',ap:4,icon:'†',type:'phys',power:16,range:[1,2],offensive:true,acc:1,status:'root',statusTurns:2,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Zone petite',radiusBonus:0.5}},
{id:'ro_fault_breaker',name:'Casse-Faille',description:'P30, retire buffs, ignore 50% END, bonus vs cible affaiblie.',ap:5,icon:'†',type:'phys',power:30,range:[1,1],offensive:true,acc:0.95,penetration:0.5,damageMultiplier:1.2,bonusVsAfflicted:1.2,effects:[{kind:'damage',target:'enemies',damageType:'phys',power:30},{kind:'dispel',target:'enemies',dispelType:'positive'}],upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Vole buff retiré',stealBuffs:true}},
// ARTILLEUR
{id:'ar_calibrated_shot',name:'Tir Calibré',description:'P10 moyenne/longue portée, précision.',ap:2,icon:'⌁',type:'phys',power:10,range:[2,4],offensive:true,acc:0.95,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Ignore 25% END',penetrationBonus:0.25}},
{id:'ar_explosive_retreat',name:'Repli Explosif',description:'Bond arrière + explosion P10 sur la case quittée.',ap:3,icon:'⌁',type:'phys',mode:'retreat',movePhase:'after',power:10,range:[0,0],radius:1,self:true,offensive:true,acc:0.9,effects:[{kind:'damage',target:'enemies',damageType:'phys',power:10}],upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Brûlure',additionalStatus:'burn',additionalStatusTurns:2,additionalStatusTarget:'enemies'}},
{id:'ar_incendiary_grenade',name:'Grenade Incendiaire',description:'Zone P15, Brûlure 2 tours, alliés touchés.',ap:4,icon:'⌁',type:'phys',power:15,range:[2,4],radius:1.2,offensive:true,acc:0.9,status:'burn',statusTurns:2,allowSelfDamage:true,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Rayon+',radiusBonus:0.25}},
{id:'ar_artillery_barrage',name:'Barrage d\'Artillerie',description:'3 impacts grande zone, P28 total, Brûlure.',ap:5,icon:'⌁',type:'phys',power:28,range:[2,4],radius:2,offensive:true,acc:0.85,status:'burn',statusTurns:2,allowSelfDamage:true,damageMultiplier:1.3,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Dernier impact étourdit',additionalStatus:'stun',additionalStatusTurns:1}},
// BOSS
{id:'boss_slam',name:'Frappe Sismique',description:'Coup de zone dévastateur, portée toute la grille, étourdit.',ap:5,icon:'◆',type:'phys',power:20,range:[1,7],radius:1.2,offensive:true,acc:0.95,status:'stun',statusTurns:1},
{id:'boss_roar',name:'Rugissement',description:'Affaiblit tous les ennemis sur la grille.',ap:5,icon:'◆',type:'debuff',power:0,range:[0,7],radius:4,offensive:true,acc:1,status:'weak',statusTurns:3},
{id:'boss_quake',name:'Onde de Choc',description:'Frappe physique monocible qui étourdit, portée toute la grille.',ap:4,icon:'◆',type:'phys',power:18,range:[0,7],radius:0,offensive:true,acc:0.85,status:'stun',statusTurns:1},
{id:'boss_guard',name:'Garde',description:'Se protège d\'une barrière.',ap:3,icon:'◆',type:'buff',power:0,range:[0,0],self:true,support:true,status:'barrier',statusTurns:3},
{id:'boss_apocalypse',name:'Apocalypse',description:'Déchaîne une apocalypse magique sur toute la grille, étourdit.',ap:5,icon:'☠',type:'mag',power:24,range:[0,7],radius:4,offensive:true,acc:0.8,status:'stun',statusTurns:1},
{id:'boss_regen',name:'Régénération',description:'Récupère des PV chaque tour (3 tours).',ap:3,icon:'✦',type:'buff',power:0,range:[0,0],self:true,support:true,status:'regen',statusTurns:3},
{id:'boss_fortify',name:'Fortification',description:'Augmente sa force et sa magie (3 tours).',ap:3,icon:'◆',type:'buff',power:0,range:[0,0],self:true,support:true,status:'boost',statusTurns:3},
{id:'boss_freeze',name:'Gel',description:'Frappe magique monocible qui étourdit, portée toute la grille.',ap:4,icon:'✦',type:'mag',power:16,range:[0,7],radius:0,offensive:true,acc:0.85,status:'stun',statusTurns:1},
{id:'boss_pin',name:'Transpercement',description:'Frappe physique monocible qui étourdit, longue portée.',ap:4,icon:'†',type:'phys',power:14,range:[1,7],radius:0,offensive:true,acc:0.9,status:'stun',statusTurns:1},
{id:'boss_execution',name:'Exécution',description:'Frappe physique dévastatrice, ignore 50% END, étourdit.',ap:5,icon:'⚔',type:'phys',power:22,range:[1,7],radius:0,offensive:true,acc:0.95,penetration:0.5,status:'stun',statusTurns:1},
{id:'boss_flurry',name:'Rafale Mortelle',description:'Salve physique monocible, critique élevé, étourdit.',ap:5,icon:'†',type:'phys',power:26,range:[1,7],radius:0,offensive:true,acc:0.9,crit:0.25,status:'stun',statusTurns:1},
{id:'boss_inferno',name:'Brasier Infernal',description:'Explosion magique en zone, Brûlure 2 tours, étourdit.',ap:5,icon:'✦',type:'mag',power:22,range:[0,7],radius:2.5,offensive:true,acc:0.85,status:'burn',statusTurns:2,additionalStatus:'stun',additionalStatusTurns:1},
{id:'boss_titan_slam',name:'Frappe du Titan',description:'Coup physique titanesque en zone, étourdit toute la grille.',ap:5,icon:'◆',type:'phys',power:24,range:[1,7],radius:2.5,offensive:true,acc:0.9,status:'stun',statusTurns:1},
// ENEMY
{id:'enemy_heavy_strike',name:'Frappe Lourde',description:'P10, étourdit 1 tour.',ap:2,icon:'⚔',type:'phys',power:10,range:[1,1],offensive:true,acc:0.85,status:'stun',statusTurns:1},
{id:'enemy_crush',name:'Écrasement',description:'P14 zone adjacente.',ap:3,icon:'◆',type:'phys',power:14,range:[0,0],radius:1,self:true,offensive:true,acc:0.8},
{id:'enemy_dark_bolt',name:'Éclair Sombre',description:'P8 magique, portée 3.',ap:2,icon:'✦',type:'mag',power:8,range:[1,3],offensive:true,acc:0.85},
{id:'enemy_hex',name:'Maléfice',description:'Malédiction 2 tours à distance.',ap:2,icon:'✦',type:'debuff',power:0,range:[1,3],offensive:true,acc:1,status:'curse',statusTurns:2},
{id:'enemy_venom_strike',name:'Frappe Venimeuse',description:'P7 et Poison 2 tours.',ap:2,icon:'†',type:'phys',power:7,range:[1,1],offensive:true,acc:0.9,status:'poison',statusTurns:2},
{id:'enemy_binding_shot',name:'Tir Entravant',description:'Immobilise 1 tour à distance.',ap:2,icon:'⌁',type:'debuff',power:0,range:[2,3],offensive:true,acc:1,status:'root',statusTurns:1},
{id:'enemy_smoke_veil',name:'Voile de Fumée',description:'Aveugle zone 1 tour.',ap:3,icon:'†',type:'debuff',power:0,range:[0,1],radius:1.2,offensive:true,acc:1,status:'blind',statusTurns:1},
{id:'enemy_taunt',name:'Provocation',description:'Provocation 2 tours, monocible.',ap:2,icon:'◆',type:'debuff',power:0,range:[1,3],offensive:true,acc:1,status:'taunt',statusTurns:2},
{id:'enemy_battle_cry',name:'Cri de Guerre',description:'Affaiblit zone 2 tours.',ap:3,icon:'◆',type:'debuff',power:0,range:[0,2],radius:1.5,offensive:true,acc:1,status:'weak',statusTurns:2},
{id:'enemy_dragon_breath',name:'Souffle de Dragon',description:'P15 zone, Brûlure 2 tours.',ap:3,icon:'✦',type:'mag',power:15,range:[1,3],radius:1.5,offensive:true,acc:0.85,status:'burn',statusTurns:2},
];

export const skillById = new Map(skills.map(s => [s.id, s]));
