import type { SkillDefinition } from './types';

export const skills: SkillDefinition[] = [
// WARRIOR
{id:'w_break_guard',name:'Brise-Garde',description:'Frappe une cible et réduit temporairement sa défense.',ap:2,icon:'⚔',type:'phys',power:10,range:[1,1],offensive:true,acc:0.95,status:'curse',statusTurns:1,upgradeLevel1:{description:'Dégâts augmentés',powerBonus:2},upgradeLevel2:{description:'Effet prolongé',statusTurnsBonus:1}},
{id:'w_charge',name:'Charge',description:'Charge vers une cible et inflige des dégâts modérés.',ap:3,icon:'↟',type:'move',mode:'dash',dest:true,range:[2,3],power:11,damageMultiplier:1.10,impact:{status:'stun',statusTurns:1},upgradeLevel1:{description:'Portée améliorée',rangeBonus:1},upgradeLevel2:{description:'Étourdit la cible au contact'}},
{id:'w_whirl',name:'Tourbillon d\'Acier',description:'Tournoie et frappe tous les ennemis autour du lanceur.',ap:4,icon:'⚔',type:'phys',power:18,range:[0,0],radius:1,self:true,offensive:true,acc:0.95,upgradeLevel1:{description:'Dégâts augmentés',powerBonus:2},upgradeLevel2:{description:'Zone élargie',radiusBonus:0.25}},
{id:'w_lion_surge',name:'Déferlement du Lion',description:'Déchaîne une percée en ligne, perce la défense et étourdit la cible principale.',ap:5,icon:'⚔',type:'phys',power:30,range:[1,3],radius:1,shape:'line',offensive:true,acc:0.9,penetration:0.3,damageMultiplier:1.4,impact:{status:'stun',statusTurns:1},upgradeLevel1:{description:'Portée améliorée',rangeBonus:1},upgradeLevel2:{description:'Perce beaucoup plus la défense',penetrationBonus:0.3}},
// PALADIN
{id:'p_holy_strike',name:'Frappe Consacrée',description:'Frappe une cible et se protège d\'une barrière.',ap:2,icon:'✚',type:'phys',power:9,range:[1,1],offensive:true,acc:0.95,effects:[{kind:'damage',target:'enemies',damageType:'phys',power:9},{kind:'status',target:'caster',status:'barrier',statusTurns:1}],upgradeLevel1:{description:'Barrière prolongée',statusTurnsBonus:1},upgradeLevel2:{description:'Soigne le lanceur',selfHealPercent:0.1}},
{id:'p_interpose',name:'Interposition',description:'Bondit sur une case libre et accorde une barrière aux alliés proches.',ap:3,icon:'✚',type:'move',mode:'leap',dest:true,movePhase:'before',range:[2,3],radius:1,support:true,effects:[{kind:'status',target:'allies',status:'barrier',statusTurns:2}],upgradeLevel1:{description:'Portée améliorée',rangeBonus:1},upgradeLevel2:{description:'Provoque les ennemis voisins',additionalStatus:'taunt',additionalStatusTurns:2,additionalStatusTarget:'enemies'}},
{id:'p_oathwall',name:'Rempart du Serment',description:'Accorde une barrière aux alliés proches et provoque les ennemis.',ap:4,icon:'✚',type:'buff',power:0,range:[0,0],radius:1.3,self:true,support:true,status:'barrier',statusTurns:3,effects:[{kind:'status',target:'self',status:'taunt',statusTurns:2},{kind:'status',target:'allies',status:'barrier',statusTurns:3}],upgradeLevel1:{description:'Zone élargie',radiusBonus:0.25},upgradeLevel2:{description:'Dissipe les altérations alliés',dispelAllies:true}},
{id:'p_radiant_judgement',name:'Jugement Radieux',description:'Frappe les ennemis dans une zone, soigne les alliés proches.',ap:5,icon:'✚',type:'phys',power:26,range:[1,3],radius:1.5,offensive:true,acc:0.9,damageMultiplier:1.3,effects:[{kind:'damage',target:'enemies',damageType:'phys',power:26},{kind:'heal',target:'allies',flatHeal:20}],upgradeLevel1:{description:'Soin renforcé',flatHealBonus:10},upgradeLevel2:{description:'Barrière pour les alliés',additionalStatus:'barrier',additionalStatusTurns:2,additionalStatusTarget:'allies'}},
// DARK KNIGHT
{id:'d_cursed_blade',name:'Lame Maudite',description:'Frappe une cible et la maudit.',ap:2,icon:'⚔',type:'phys',power:10,range:[1,1],offensive:true,acc:0.95,status:'curse',statusTurns:1,upgradeLevel1:{description:'Dégâts augmentés',powerBonus:2},upgradeLevel2:{description:'Effet prolongé',statusTurnsBonus:1}},
{id:'d_void_step',name:'Pas du Néant',description:'Téléportation instantanée à distance.',ap:3,icon:'✦',type:'move',mode:'teleport',dest:true,movePhase:'before',range:[2,3],radius:1,effects:[],upgradeLevel1:{description:'Portée améliorée',rangeBonus:1},upgradeLevel2:{description:'Affaiblit les ennemis adjacents',additionalStatus:'weak',additionalStatusTurns:1,additionalStatusTarget:'enemies'}},
{id:'d_blood_pact',name:'Pacte de Sang',description:'Sacrifie des PV, se renforce et vole la vie de ses ennemis.',ap:4,icon:'⚔',type:'buff',power:0,range:[0,0],self:true,support:true,effects:[{kind:'hp_cost',target:'caster',hpCostPercent:0.15},{kind:'status',target:'caster',status:'boost',statusTurns:2},{kind:'lifesteal',target:'caster',lifestealPercent:0.5}],upgradeLevel1:{description:'Coût réduit',hpCostReduction:0.05},upgradeLevel2:{description:'Vol de vie renforcé',lifestealBonus:0.25,statusTurnsBonus:1}},
{id:'d_devouring_eclipse',name:'Éclipse Dévorante',description:'Déchaîne des dégâts dévastateurs en zone, maudit les ennemis et vole leur vie.',ap:5,icon:'⚔',type:'mag',power:30,range:[1,3],radius:1.5,offensive:true,acc:0.85,status:'curse',statusTurns:2,damageMultiplier:1.3,effects:[{kind:'damage',target:'enemies',damageType:'mag',power:30,status:'curse',statusTurns:2},{kind:'lifesteal',target:'caster',lifestealPercent:0.30}],upgradeLevel1:{description:'Vol de vie renforcé',lifestealBonus:0.10},upgradeLevel2:{description:'Zone élargie et vol renforcé',radiusBonus:0.25,lifestealBonus:0.1}},
// LANCER
{id:'l_long_thrust',name:'Estoc Long',description:'Frappe une cible à distance et perce une partie de sa défense.',ap:2,icon:'↟',type:'phys',power:10,range:[2,2],offensive:true,acc:0.95,penetration:0.2,upgradeLevel1:{description:'Dégâts augmentés',powerBonus:2},upgradeLevel2:{description:'Utilisable à courte portée',minRangeReduction:1}},
{id:'l_haft_recoil',name:'Repli de Hampe',description:'Frappe une cible puis recule vers une case libre.',ap:3,icon:'↟',type:'phys',power:10,range:[1,1],offensive:true,targetMode:'enemy',mode:'retreat',movePhase:'after',acc:0.9,damageMultiplier:1.10,upgradeLevel1:{description:'Portée améliorée',rangeBonus:1},upgradeLevel2:{description:'Ralentit la cible',additionalStatus:'slow',additionalStatusTurns:2,additionalStatusTarget:'selected'}},
{id:'l_griffon_jump',name:'Saut du Griffon',description:'Bondit sur les ennemis et inflige des dégâts modérés en zone.',ap:4,icon:'↟',type:'phys',power:16,range:[2,3],radius:1,mode:'leap',dest:true,movePhase:'before',offensive:true,acc:0.9,upgradeLevel1:{description:'Portée améliorée',rangeBonus:1},upgradeLevel2:{description:'Étourdit la cible centrale',additionalStatus:'stun',additionalStatusTurns:1,additionalStatusTarget:'enemies'}},
{id:'l_firmament_lance',name:'Lance du Firmament',description:'Déchaîne une percée en ligne qui perce fortement la défense. Plus efficace contre les grandes cibles.',ap:5,icon:'↟',type:'phys',power:32,range:[2,4],radius:2,shape:'line',offensive:true,acc:0.95,penetration:0.6,damageMultiplier:1.2,bonusVsSize:1.3,upgradeLevel1:{description:'Dégâts augmentés',powerBonus:2},upgradeLevel2:{description:'Perce encore plus les grandes cibles',penetrationBonus:0.25}},
// MAGE NOIR
{id:'n_dark_bolt',name:'Éclair Noir',description:'Projette un éclair magique à distance.',ap:2,icon:'✦',type:'mag',power:13,range:[1,4],offensive:true,acc:0.9,upgradeLevel1:{description:'Dégâts augmentés',powerBonus:2},upgradeLevel2:{description:'Maudit la cible',additionalStatus:'curse',additionalStatusTurns:1}},
{id:'n_teleport',name:'Téléportation',description:'Déplacement instantané à distance.',ap:3,icon:'✦',type:'move',mode:'teleport',dest:true,range:[2,3],upgradeLevel1:{description:'Portée améliorée',rangeBonus:1},upgradeLevel2:{description:'Barrière à l\'arrivée',additionalStatus:'barrier',additionalStatusTurns:1,additionalStatusTarget:'self'}},
{id:'n_flame_wave',name:'Vague de Flammes',description:'Projette un cône de flammes qui brûle les cibles touchées. Attention : peut toucher les alliés.',ap:4,icon:'✦',type:'mag',power:17,range:[1,1],radius:1.6,shape:'cone',offensive:true,acc:0.9,status:'burn',statusTurns:2,allowSelfDamage:true,upgradeLevel1:{description:'Dégâts augmentés',powerBonus:2},upgradeLevel2:{description:'Cône élargi et brûlure prolongée',radiusBonus:0.3,statusTurnsBonus:1}},
{id:'n_dark_meteor',name:'Météore Obscur',description:'Invoque un météore dévastateur en zone, brûle et maudit les ennemis. Attention : peut toucher les alliés.',ap:5,icon:'✦',type:'mag',power:30,range:[2,4],radius:1.5,offensive:true,acc:0.85,status:'burn',statusTurns:2,allowSelfDamage:true,damageMultiplier:1.3,effects:[{kind:'damage',target:'all',damageType:'mag',power:30,status:'burn',statusTurns:2},{kind:'status',target:'enemies',status:'curse',statusTurns:2}],upgradeLevel1:{description:'Brûlure prolongée',statusTurnsBonus:1},upgradeLevel2:{description:'Zone élargie',radiusBonus:0.25}},
// MAGE BLANC
{id:'w_salvation',name:'Lumière Salvatrice',description:'Soigne un allié à distance.',ap:2,icon:'✚',type:'heal',power:1.2,range:[0,3],targetMode:'ally',support:true,upgradeLevel1:{description:'Soin renforcé',healMultiplier:0.15},upgradeLevel2:{description:'Purifie le clan',dispelAllies:true}},
{id:'w_purify',name:'Purification',description:'Soigne un allié et dissipe ses altérations négatives.',ap:3,icon:'✚',type:'heal',power:0.8,range:[0,3],radius:0,targetMode:'ally',support:true,effects:[{kind:'heal',target:'allies',targetSource:'selected',power:0.8},{kind:'dispel',target:'allies',targetSource:'selected',dispelType:'negative'}],upgradeLevel1:{description:'Soin renforcé',healMultiplier:0.15},upgradeLevel2:{description:'Soin en petite zone',radiusBonus:1}},
{id:'w_sanctuary',name:'Sanctuaire',description:'Soigne les alliés dans une zone et les régénère.',ap:4,icon:'✚',type:'buff',power:0.8,range:[0,2],radius:1.3,support:true,status:'regen',statusTurns:3,effects:[{kind:'heal',target:'allies',flatHeal:15},{kind:'status',target:'allies',status:'regen',statusTurns:3}],upgradeLevel1:{description:'Zone élargie',radiusBonus:0.25},upgradeLevel2:{description:'Barrière pour les alliés',additionalStatus:'barrier',additionalStatusTurns:2,additionalStatusTarget:'allies'}},
{id:'w_miracle',name:'Miracle',description:'Relève un allié tombé, soigne, purifie et régénère les alliés proches.',ap:5,icon:'✚',type:'revive',power:0.75,range:[1,2],radius:1,support:true,effects:[{kind:'revive',target:'allies',targetSource:'selected'},{kind:'heal',target:'allies',flatHeal:25},{kind:'dispel',target:'allies',dispelType:'negative'},{kind:'status',target:'allies',status:'regen',statusTurns:2}],upgradeLevel1:{description:'Résurrection améliorée',revivePercent:0.85},upgradeLevel2:{description:'Zone élargie et barrière',radiusBonus:0.25,additionalStatus:'barrier',additionalStatusTurns:1,additionalStatusTarget:'allies'}},
// MAGE ROUGE
{id:'r_arcane_blade',name:'Lame Arcanique',description:'Frappe une cible avec un coup critique accru.',ap:2,icon:'✦',type:'phys',power:10,range:[1,1],offensive:true,acc:0.95,crit:0.10,upgradeLevel1:{description:'Dégâts augmentés',powerBonus:2},upgradeLevel2:{description:'Renforce le lanceur',additionalStatus:'boost',additionalStatusTurns:1}},
{id:'r_rune_step',name:'Pas Runique',description:'Téléportation qui renforce le lanceur.',ap:3,icon:'✦',type:'move',mode:'teleport',dest:true,movePhase:'before',range:[2,3],effects:[{kind:'status',target:'caster',status:'boost',statusTurns:1}],upgradeLevel1:{description:'Portée améliorée',rangeBonus:1},upgradeLevel2:{description:'Barrière à l\'arrivée',additionalStatus:'barrier',additionalStatusTurns:1,additionalStatusTarget:'self'}},
{id:'r_scarlet_circle',name:'Cercle Écarlate',description:'Frappe les ennemis dans une zone et soigne les alliés proches.',ap:4,icon:'✦',type:'mag',power:16,range:[1,3],radius:1.2,offensive:true,acc:0.9,effects:[{kind:'damage',target:'enemies',damageType:'mag',power:16},{kind:'heal',target:'allies',flatHeal:12}],upgradeLevel1:{description:'Dégâts et soin améliorés',powerBonus:2},upgradeLevel2:{description:'Zone élargie',radiusBonus:0.25}},
{id:'r_perfect_duality',name:'Dualité Parfaite',description:'Frappe les ennemis dans une large zone, soigne les alliés et protège le lanceur.',ap:5,icon:'✦',type:'mag',power:28,range:[1,3],radius:2,offensive:true,acc:0.85,damageMultiplier:1.2,effects:[{kind:'damage',target:'enemies',damageType:'mag',power:28},{kind:'heal',target:'allies',flatHeal:25},{kind:'status',target:'caster',status:'barrier',statusTurns:2}],upgradeLevel1:{description:'Soin renforcé',flatHealBonus:10},upgradeLevel2:{description:'Purifie les alliés',dispelAllies:true}},
// ENCHANTER
{id:'e_vigor_rune',name:'Rune de Vigueur',description:'Renforce un allié à distance.',ap:2,icon:'✦',type:'buff',power:0,range:[0,3],targetMode:'ally',support:true,status:'boost',statusTurns:3,upgradeLevel1:{description:'Portée améliorée',rangeBonus:1},upgradeLevel2:{description:'Effet prolongé',statusTurnsBonus:1}},
{id:'e_transpose',name:'Transposition',description:'Échange sa position avec un allié.',ap:3,icon:'✦',type:'move',mode:'swap',dest:true,movePhase:'before',targetMode:'ally',range:[1,3],support:true,effects:[],upgradeLevel1:{description:'Portée améliorée',rangeBonus:1},upgradeLevel2:{description:'Barrière pour les deux unités',additionalStatus:'barrier',additionalStatusTurns:1,additionalStatusTarget:'casterAndSelected'}},
{id:'e_binding_seal',name:'Sceau d\'Entrave',description:'Immobilise les ennemis dans une zone.',ap:4,icon:'✦',type:'debuff',power:0,range:[1,3],radius:1.2,offensive:true,acc:1,status:'root',statusTurns:2,upgradeLevel1:{description:'Zone élargie',radiusBonus:0.25},upgradeLevel2:{description:'Affaiblit les ennemis',additionalStatus:'weak',additionalStatusTurns:1}},
{id:'e_absolute_harmony',name:'Harmonie Absolue',description:'Renforce, protège et régénère tous les alliés proches.',ap:5,icon:'✦',type:'buff',power:0,range:[0,3],radius:2,support:true,effects:[{kind:'status',target:'allies',status:'boost',statusTurns:3},{kind:'status',target:'allies',status:'barrier',statusTurns:3},{kind:'status',target:'allies',status:'regen',statusTurns:2}],upgradeLevel1:{description:'Portée améliorée',rangeBonus:1},upgradeLevel2:{description:'Purifie et prolonge les effets',statusTurnsBonus:1,dispelAllies:true}},
// ARCHER
{id:'a_precise_shot',name:'Tir Précis',description:'Décoche un tir précis à distance avec critique accru.',ap:2,icon:'⌁',type:'phys',power:11,range:[2,4],offensive:true,acc:0.95,crit:0.15,upgradeLevel1:{description:'Dégâts augmentés',powerBonus:2},upgradeLevel2:{description:'Perce une partie de la défense',penetrationBonus:0.3}},
{id:'a_hawk_leap',name:'Bond du Faucon',description:'Bondit vers une case et renforce son prochain tir.',ap:3,icon:'⌁',type:'move',mode:'leap',dest:true,movePhase:'before',range:[2,3],effects:[{kind:'status',target:'caster',status:'boost',statusTurns:1}],upgradeLevel1:{description:'Portée améliorée',rangeBonus:1},upgradeLevel2:{description:'Barrière à l\'arrivée',additionalStatus:'barrier',additionalStatusTurns:1,additionalStatusTarget:'self'}},
{id:'a_arrow_rain',name:'Pluie de Flèches',description:'Décoche une volée de flèches en zone à longue portée, ralentit les ennemis.',ap:4,icon:'⌁',type:'phys',power:16,range:[2,4],radius:1.2,offensive:true,acc:0.9,status:'slow',statusTurns:2,upgradeLevel1:{description:'Dégâts augmentés',powerBonus:2},upgradeLevel2:{description:'Zone élargie',radiusBonus:0.25}},
{id:'a_zenith_arrow',name:'Flèche du Zénith',description:'Décoche un tir dévastateur qui perce fortement la défense. Plus dangereux contre une cible déjà affaiblie.',ap:5,icon:'⌁',type:'phys',power:34,range:[2,4],offensive:true,acc:0.99,penetration:0.7,crit:0.1,damageMultiplier:1.2,bonusVsAfflicted:1.2,upgradeLevel1:{description:'Dégâts augmentés',powerBonus:2},upgradeLevel2:{description:'Coup critique assuré contre une cible isolée',critBonus:0.9}},
// NINJA
{id:'ni_venom_blade',name:'Lame Venimeuse',description:'Frappe une cible et l\'empoisonne.',ap:2,icon:'†',type:'phys',power:9,range:[1,1],offensive:true,acc:0.95,status:'poison',statusTurns:2,upgradeLevel1:{description:'Dégâts augmentés',powerBonus:2},upgradeLevel2:{description:'Poison prolongé',statusTurnsBonus:1}},
{id:'ni_shadow_step',name:'Pas d\'Ombre',description:'Téléporte derrière une cible et lui inflige des dégâts modérés.',ap:3,icon:'†',type:'move',mode:'strike',dest:true,movePhase:'before',targetMode:'enemy',range:[1,2],power:11,offensive:true,acc:0.9,damageMultiplier:1.15,effects:[{kind:'damage',target:'enemies',targetSource:'selected',damageType:'phys',power:11}],upgradeLevel1:{description:'Portée améliorée',rangeBonus:1},upgradeLevel2:{description:'Aveugle la cible',additionalStatus:'blind',additionalStatusTurns:1,additionalStatusTarget:'selected'}},
{id:'ni_smoke_bomb',name:'Bombe Fumigène',description:'Aveugle les ennemis dans une zone et se protège d\'une barrière.',ap:4,icon:'†',type:'debuff',power:0,range:[0,1],radius:1.5,offensive:true,acc:1,status:'blind',statusTurns:2,effects:[{kind:'status',target:'enemies',status:'blind',statusTurns:2},{kind:'status',target:'caster',status:'barrier',statusTurns:1}],upgradeLevel1:{description:'Zone élargie',radiusBonus:0.25},upgradeLevel2:{description:'Affaiblit les ennemis',additionalStatus:'weak',additionalStatusTurns:1}},
{id:'ni_silent_assassin',name:'Assassinat Silencieux',description:'Téléporte vers une cible et inflige des dégâts dévastateurs. Plus dangereux contre une cible déjà affaiblie.',ap:5,icon:'†',type:'phys',mode:'strike',dest:true,movePhase:'before',targetMode:'enemy',power:32,range:[1,3],offensive:true,acc:0.95,damageMultiplier:1.3,bonusVsAfflicted:1.3,effects:[{kind:'damage',target:'enemies',targetSource:'selected',damageType:'phys',power:32}],upgradeLevel1:{description:'Dégâts augmentés',powerBonus:4},upgradeLevel2:{description:'Empoisonne si la cible survit',additionalStatus:'poison',additionalStatusTurns:2,additionalStatusTarget:'selected'}},
// ROGUE
{id:'ro_sneak_attack',name:'Coup Sournois',description:'Frappe une cible avec un critique élevé. Plus fort en l\'attaquant par derrière.',ap:2,icon:'†',type:'phys',power:10,range:[1,1],offensive:true,acc:0.9,crit:0.2,upgradeLevel1:{description:'Dégâts augmentés',powerBonus:2},upgradeLevel2:{description:'Critique garanti par derrière',critBonus:0.8}},
{id:'ro_tumble',name:'Roulade',description:'Bondit vers une case et renforce son prochain coup.',ap:3,icon:'†',type:'move',mode:'leap',dest:true,movePhase:'before',range:[2,3],effects:[{kind:'status',target:'caster',status:'boost',statusTurns:1}],upgradeLevel1:{description:'Portée améliorée',rangeBonus:1},upgradeLevel2:{description:'Barrière à l\'arrivée',additionalStatus:'barrier',additionalStatusTurns:1,additionalStatusTarget:'self'}},
{id:'ro_jaw_trap',name:'Mâchoire à Ressort',description:'Frappe une cible à distance et l\'immobilise.',ap:4,icon:'†',type:'phys',power:16,range:[1,2],offensive:true,acc:1,status:'root',statusTurns:2,upgradeLevel1:{description:'Dégâts augmentés',powerBonus:2},upgradeLevel2:{description:'Petite zone autour de la cible',radiusBonus:0.5}},
{id:'ro_fault_breaker',name:'Casse-Faille',description:'Frappe dévastatrice qui dissipe les buffs, perce fortement la défense. Plus dangereux contre une cible déjà affaiblie.',ap:5,icon:'†',type:'phys',power:30,range:[1,1],offensive:true,acc:0.95,penetration:0.5,damageMultiplier:1.3,bonusVsAfflicted:1.2,effects:[{kind:'damage',target:'enemies',damageType:'phys',power:30},{kind:'dispel',target:'enemies',dispelType:'positive'}],upgradeLevel1:{description:'Dégâts augmentés',powerBonus:2},upgradeLevel2:{description:'Vole le buff dissipé',stealBuffs:true}},
// ARTILLEUR
{id:'ar_calibrated_shot',name:'Tir Calibré',description:'Décoche un tir précis à moyenne portée avec critique accru.',ap:2,icon:'⌁',type:'phys',power:10,range:[2,4],offensive:true,acc:0.95,crit:0.10,upgradeLevel1:{description:'Dégâts augmentés',powerBonus:2},upgradeLevel2:{description:'Perce une partie de la défense',penetrationBonus:0.25}},
{id:'ar_explosive_retreat',name:'Repli Explosif',description:'Recule et laisse une explosion sur la case quittée.',ap:3,icon:'⌁',type:'phys',mode:'retreat',movePhase:'after',power:10,range:[0,0],radius:1,self:true,offensive:true,acc:0.9,damageMultiplier:1.10,effects:[{kind:'damage',target:'enemies',damageType:'phys',power:10}],upgradeLevel1:{description:'Dégâts augmentés',powerBonus:2},upgradeLevel2:{description:'Brûle les ennemis touchés',additionalStatus:'burn',additionalStatusTurns:2,additionalStatusTarget:'enemies'}},
{id:'ar_incendiary_grenade',name:'Grenade Incendiaire',description:'Lance une grenade en zone qui brûle les ennemis. Attention : peut toucher les alliés.',ap:4,icon:'⌁',type:'phys',power:15,range:[2,4],radius:1.2,offensive:true,acc:0.9,status:'burn',statusTurns:2,allowSelfDamage:true,upgradeLevel1:{description:'Dégâts augmentés',powerBonus:2},upgradeLevel2:{description:'Zone élargie',radiusBonus:0.25}},
{id:'ar_artillery_barrage',name:'Barrage d\'Artillerie',description:'Déchaîne trois impacts dévastateurs en large zone, brûle les ennemis. Attention : peut toucher les alliés.',ap:5,icon:'⌁',type:'phys',power:28,range:[2,4],radius:2,offensive:true,acc:0.85,status:'burn',statusTurns:2,allowSelfDamage:true,damageMultiplier:1.3,upgradeLevel1:{description:'Zone élargie',radiusBonus:0.25},upgradeLevel2:{description:'Dernier impact étourdit',additionalStatus:'stun',additionalStatusTurns:1}},
// BOSS
{id:'boss_slam',name:'Frappe Sismique',description:'Coup de zone dévastateur, portée toute la grille, étourdit.',ap:5,icon:'◆',type:'phys',power:20,damageMultiplier:1.3,range:[1,7],radius:1.2,offensive:true,acc:0.95,status:'stun',statusTurns:1},
{id:'boss_roar',name:'Rugissement',description:'Affaiblit tous les ennemis sur la grille.',ap:5,icon:'◆',type:'debuff',power:0,range:[0,7],radius:4,offensive:true,acc:1,status:'weak',statusTurns:3},
{id:'boss_quake',name:'Onde de Choc',description:'Frappe physique monocible qui étourdit, portée toute la grille.',ap:4,icon:'◆',type:'phys',power:18,damageMultiplier:1.2,range:[0,7],radius:0,offensive:true,acc:0.85,status:'stun',statusTurns:1},
{id:'boss_guard',name:'Garde',description:'Se protège d\'une barrière.',ap:3,icon:'◆',type:'buff',power:0,range:[0,0],self:true,support:true,status:'barrier',statusTurns:3},
{id:'boss_apocalypse',name:'Apocalypse',description:'Déchaîne une apocalypse magique sur toute la grille, étourdit.',ap:5,icon:'☠',type:'mag',power:24,damageMultiplier:1.2,range:[0,7],radius:4,offensive:true,acc:0.8,status:'stun',statusTurns:1},
{id:'boss_regen',name:'Régénération',description:'Récupère des PV chaque tour (3 tours).',ap:3,icon:'✦',type:'buff',power:0,range:[0,0],self:true,support:true,status:'regen',statusTurns:3},
{id:'boss_fortify',name:'Fortification',description:'Augmente sa force et sa magie (3 tours).',ap:3,icon:'◆',type:'buff',power:0,range:[0,0],self:true,support:true,status:'boost',statusTurns:3},
{id:'boss_freeze',name:'Gel',description:'Frappe magique monocible qui étourdit, portée toute la grille.',ap:4,icon:'✦',type:'mag',power:16,damageMultiplier:1.2,range:[0,7],radius:0,offensive:true,acc:0.85,status:'stun',statusTurns:1},
{id:'boss_pin',name:'Transpercement',description:'Frappe physique monocible qui étourdit, longue portée.',ap:4,icon:'†',type:'phys',power:16,range:[1,7],radius:0,offensive:true,acc:0.9,status:'stun',statusTurns:1},
{id:'boss_execution',name:'Exécution',description:'Exécution brutale qui perce fortement la défense et étourdit.',ap:5,icon:'⚔',type:'phys',power:22,damageMultiplier:1.3,range:[1,7],radius:0,offensive:true,acc:0.95,penetration:0.5,status:'stun',statusTurns:1},
{id:'boss_flurry',name:'Rafale Mortelle',description:'Salve physique monocible, critique élevé, étourdit.',ap:5,icon:'†',type:'phys',power:26,damageMultiplier:1.2,range:[1,7],radius:0,offensive:true,acc:0.9,crit:0.25,status:'stun',statusTurns:1},
{id:'boss_inferno',name:'Brasier Infernal',description:'Explosion magique en zone, Brûlure 2 tours, étourdit.',ap:5,icon:'✦',type:'mag',power:22,damageMultiplier:1.3,range:[0,7],radius:2.5,offensive:true,acc:0.85,status:'burn',statusTurns:2,additionalStatus:'stun',additionalStatusTurns:1},
{id:'boss_titan_slam',name:'Frappe du Titan',description:'Coup physique titanesque en zone, étourdit toute la grille.',ap:5,icon:'◆',type:'phys',power:24,damageMultiplier:1.3,range:[1,7],radius:2.5,offensive:true,acc:0.9,status:'stun',statusTurns:1},
// ENEMY
{id:'enemy_heavy_strike',name:'Frappe Lourde',description:'Frappe lourde qui peut étourdir.',ap:2,icon:'⚔',type:'phys',power:10,range:[1,1],offensive:true,acc:0.85,status:'stun',statusTurns:1},
{id:'enemy_crush',name:'Écrasement',description:'Écrase les ennemis autour du lanceur.',ap:3,icon:'◆',type:'phys',power:16,range:[0,0],radius:1,self:true,offensive:true,acc:0.8},
{id:'enemy_dark_bolt',name:'Éclair Sombre',description:'Sort sombre à distance.',ap:2,icon:'✦',type:'mag',power:10,range:[1,3],offensive:true,acc:0.85},
{id:'enemy_hex',name:'Maléfice',description:'Maudit une cible à distance.',ap:2,icon:'✦',type:'debuff',power:0,range:[1,3],offensive:true,acc:1,status:'curse',statusTurns:2},
{id:'enemy_venom_strike',name:'Frappe Venimeuse',description:'Attaque venimeuse qui empoisonne.',ap:2,icon:'†',type:'phys',power:9,range:[1,1],offensive:true,acc:0.9,status:'poison',statusTurns:2},
{id:'enemy_binding_shot',name:'Tir Entravant',description:'Tir à distance qui immobilise.',ap:2,icon:'⌁',type:'debuff',power:0,range:[2,3],offensive:true,acc:1,status:'root',statusTurns:1},
{id:'enemy_smoke_veil',name:'Voile de Fumée',description:'Aveugle les ennemis dans une zone.',ap:3,icon:'†',type:'debuff',power:0,range:[0,1],radius:1.2,offensive:true,acc:1,status:'blind',statusTurns:1},
{id:'enemy_taunt',name:'Provocation',description:'Provoque une cible à distance.',ap:2,icon:'◆',type:'debuff',power:0,range:[1,3],offensive:true,acc:1,status:'taunt',statusTurns:2},
{id:'enemy_battle_cry',name:'Cri de Guerre',description:'Affaiblit les ennemis dans une zone.',ap:3,icon:'◆',type:'debuff',power:0,range:[0,2],radius:1.5,offensive:true,acc:1,status:'weak',statusTurns:2},
{id:'enemy_dragon_breath',name:'Souffle de Dragon',description:'Souffle en zone qui brûle les cibles touchées.',ap:3,icon:'✦',type:'mag',power:15,range:[1,3],radius:1.5,offensive:true,acc:0.85,status:'burn',statusTurns:2},
];

export const skillById = new Map(skills.map(s => [s.id, s]));
