import type { SkillDefinition } from './types';

export const skills: SkillDefinition[] = [
// WARRIOR
{id:'w_break_guard',name:'Brise-Garde',description:'P8, monocible, réduit l\'END 1 tour.',ap:2,icon:'⚔',type:'phys',power:8,range:[1,1],offensive:true,acc:0.95,status:'curse',statusTurns:1,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'2 tours',statusTurnsBonus:1}},
{id:'w_charge',name:'Charge',description:'Avance 2-3 cases et frappe P8.',ap:3,icon:'↟',type:'move',mode:'dash',dest:true,range:[2,3],power:8,impact:{status:'stun',statusTurns:1},upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Étourdit cible finale'}},
{id:'w_whirl',name:'Tourbillon d\'Acier',description:'P12 contre ennemis adjacents.',ap:4,icon:'⚔',type:'phys',power:12,range:[0,0],radius:1,self:true,offensive:true,acc:0.95,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Rayon+',radiusBonus:0.25}},
{id:'w_lion_surge',name:'Déferlement du Lion',description:'Traverse ligne, P18, étourdit cible finale.',ap:5,icon:'⚔',type:'phys',power:18,range:[1,3],radius:1,shape:'line',offensive:true,acc:0.9,impact:{status:'stun',statusTurns:1},upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Ignore 50% END',penetrationBonus:0.5}},
// PALADIN
{id:'p_holy_strike',name:'Frappe Consacrée',description:'P8 et Barrière au Paladin.',ap:2,icon:'✚',type:'phys',power:8,range:[1,1],offensive:true,acc:0.95,effects:[{kind:'status',target:'caster',status:'barrier',statusTurns:1}],upgradeLevel1:{description:'Barrière 2 tours',statusTurnsBonus:1},upgradeLevel2:{description:'Soigne 10% PV',selfHealPercent:0.1}},
{id:'p_interpose',name:'Interposition',description:'Bondit près d\'un allié, Barrière aux deux.',ap:3,icon:'✚',type:'move',mode:'leap',dest:true,range:[2,3],support:true,effects:[{kind:'status',target:'allies',status:'barrier',statusTurns:2}],upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Provoque ennemis voisins',additionalStatus:'taunt',additionalStatusTurns:2}},
{id:'p_oathwall',name:'Rempart du Serment',description:'Barrière de zone + Provocation sur Paladin.',ap:4,icon:'✚',type:'buff',power:0,range:[0,0],radius:1.3,self:true,support:true,status:'barrier',statusTurns:3,effects:[{kind:'status',target:'self',status:'taunt',statusTurns:2},{kind:'status',target:'allies',status:'barrier',statusTurns:3}],upgradeLevel1:{description:'Rayon+',radiusBonus:0.25},upgradeLevel2:{description:'Retire altération alliés',dispelAllies:true}},
{id:'p_radiant_judgement',name:'Jugement Radieux',description:'P16 zone ennemis + soin alliés.',ap:5,icon:'✚',type:'phys',power:16,range:[1,3],radius:1.5,offensive:true,acc:0.9,effects:[{kind:'damage',target:'enemies',damageType:'phys',power:16},{kind:'heal',target:'allies',flatHeal:20}],upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Barrière alliés',additionalStatus:'barrier',additionalStatusTurns:2}},
// DARK KNIGHT
{id:'d_cursed_blade',name:'Lame Maudite',description:'P9 et Malédiction 1 tour.',ap:2,icon:'⚔',type:'phys',power:9,range:[1,1],offensive:true,acc:0.95,status:'curse',statusTurns:1,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'2 tours',statusTurnsBonus:1}},
{id:'d_void_step',name:'Pas du Néant',description:'Téléportation 2-3 cases.',ap:3,icon:'✦',type:'move',mode:'teleport',dest:true,range:[2,3],upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Affaiblit adjacents',additionalStatus:'weak',additionalStatusTurns:1}},
{id:'d_blood_pact',name:'Pacte de Sang',description:'Sacrifie 15% PV, Force+ et vol de vie.',ap:4,icon:'⚔',type:'buff',power:0,range:[0,0],self:true,support:true,effects:[{kind:'hp_cost',target:'caster',hpCostPercent:0.15},{kind:'status',target:'caster',status:'boost',statusTurns:2},{kind:'lifesteal',target:'caster',lifestealPercent:0.5}],upgradeLevel1:{description:'Coût 10%',hpCostReduction:0.05},upgradeLevel2:{description:'Vol de vie+',lifestealBonus:0.25,statusTurnsBonus:1}},
{id:'d_devouring_eclipse',name:'Éclipse Dévorante',description:'P18 zone, Malédiction, soigne 25% dégâts.',ap:5,icon:'⚔',type:'mag',power:18,range:[1,3],radius:1.5,offensive:true,acc:0.85,status:'curse',statusTurns:2,effects:[{kind:'damage',target:'enemies',damageType:'mag',power:18,status:'curse',statusTurns:2},{kind:'lifesteal',target:'caster',lifestealPercent:0.25}],upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Rayon+ et vol+',radiusBonus:0.25,lifestealBonus:0.1}},
// LANCER
{id:'l_long_thrust',name:'Estoc Long',description:'P9 à 2 cases, ignore 20% END.',ap:2,icon:'↟',type:'phys',power:9,range:[2,2],offensive:true,acc:0.95,penetration:0.2,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Aussi à 1 case',minRangeReduction:1}},
{id:'l_haft_recoil',name:'Repli de Hampe',description:'P7 puis recule d\'une case.',ap:3,icon:'↟',type:'phys',power:7,range:[1,1],offensive:true,acc:0.9,effects:[{kind:'damage',target:'enemies',damageType:'phys',power:7},{kind:'move',target:'caster',moveMode:'leap'}],upgradeLevel1:{description:'Recul 2 cases',rangeBonus:1},upgradeLevel2:{description:'Ralentissement',additionalStatus:'slow',additionalStatusTurns:2}},
{id:'l_griffon_jump',name:'Saut du Griffon',description:'Bond 3 cases, impact zone P12.',ap:4,icon:'↟',type:'phys',power:12,range:[2,3],radius:1,mode:'leap',dest:true,offensive:true,acc:0.9,upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Étourdit centre',additionalStatus:'stun',additionalStatusTurns:1}},
{id:'l_firmament_lance',name:'Lance du Firmament',description:'P20 ligne longue, 60% pénétration.',ap:5,icon:'↟',type:'phys',power:20,range:[2,4],radius:2,shape:'line',offensive:true,acc:0.95,penetration:0.6,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'+25% vs 2×2',penetrationBonus:0.25}},
// MAGE NOIR
{id:'n_dark_bolt',name:'Éclair Noir',description:'P9 magique, portée 4.',ap:2,icon:'✦',type:'mag',power:9,range:[1,4],offensive:true,acc:0.9,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Malédiction 1 tour',additionalStatus:'curse',additionalStatusTurns:1}},
{id:'n_teleport',name:'Téléportation',description:'Déplacement instantané 3 cases.',ap:3,icon:'✦',type:'move',mode:'teleport',dest:true,range:[2,3],upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Barrière arrivée',additionalStatus:'barrier',additionalStatusTurns:1}},
{id:'n_flame_wave',name:'Vague de Flammes',description:'Cône P13, Brûlure 2 tours, dégâts alliés.',ap:4,icon:'✦',type:'mag',power:13,range:[1,1],radius:1.6,shape:'cone',offensive:true,acc:0.9,status:'burn',statusTurns:2,allowSelfDamage:true,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Cône+ et 3 tours',radiusBonus:0.3,statusTurnsBonus:1}},
{id:'n_dark_meteor',name:'Météore Obscur',description:'Zone P18, Brûlure, Malédiction, alliés touchés.',ap:5,icon:'✦',type:'mag',power:18,range:[2,4],radius:1.5,offensive:true,acc:0.85,status:'burn',statusTurns:2,allowSelfDamage:true,effects:[{kind:'damage',target:'all',damageType:'mag',power:18,status:'burn',statusTurns:2},{kind:'status',target:'enemies',status:'curse',statusTurns:2}],upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Rayon+',radiusBonus:0.25}},
// MAGE BLANC
{id:'w_salvation',name:'Lumière Salvatrice',description:'Soin monocible à distance.',ap:2,icon:'✚',type:'heal',power:1.2,range:[0,3],support:true,upgradeLevel1:{description:'Soins+15%',healMultiplier:0.15},upgradeLevel2:{description:'Retire altération'}},
{id:'w_purify',name:'Purification',description:'Soin + dissipe altérations négatives.',ap:3,icon:'✚',type:'heal',power:0.8,range:[0,3],support:true,cure:true,upgradeLevel1:{description:'Soin+',healMultiplier:0.15},upgradeLevel2:{description:'Petite zone',radiusBonus:1}},
{id:'w_sanctuary',name:'Sanctuaire',description:'Soin zone + Régénération 3 tours.',ap:4,icon:'✚',type:'buff',power:0.8,range:[0,2],radius:1.3,support:true,status:'regen',statusTurns:3,effects:[{kind:'heal',target:'allies',flatHeal:15},{kind:'status',target:'allies',status:'regen',statusTurns:3}],upgradeLevel1:{description:'Rayon+',radiusBonus:0.25},upgradeLevel2:{description:'Barrière 2 tours',additionalStatus:'barrier',additionalStatusTurns:2}},
{id:'w_miracle',name:'Miracle',description:'Relève allié 70% PV, soigne et purifie proches.',ap:5,icon:'✚',type:'revive',power:0.7,range:[1,2],radius:1,support:true,effects:[{kind:'revive',target:'allies'},{kind:'heal',target:'allies',flatHeal:20},{kind:'dispel',target:'allies',dispelType:'negative'}],upgradeLevel1:{description:'Résurrection 80%',revivePercent:0.8},upgradeLevel2:{description:'Rayon+ et Barrière',radiusBonus:0.25,additionalStatus:'barrier',additionalStatusTurns:1}},
// MAGE ROUGE
{id:'r_arcane_blade',name:'Lame Arcanique',description:'P9, meilleure FOR/MAG.',ap:2,icon:'✦',type:'phys',power:9,range:[1,1],offensive:true,acc:0.95,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Force+ 1 tour',additionalStatus:'boost',additionalStatusTurns:1}},
{id:'r_rune_step',name:'Pas Runique',description:'Téléportation + Force+ 1 tour.',ap:3,icon:'✦',type:'move',mode:'teleport',dest:true,range:[2,3],effects:[{kind:'status',target:'caster',status:'boost',statusTurns:1}],upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Barrière courte',additionalStatus:'barrier',additionalStatusTurns:1}},
{id:'r_scarlet_circle',name:'Cercle Écarlate',description:'P11 ennemis + soin alliés zone.',ap:4,icon:'✦',type:'mag',power:11,range:[1,3],radius:1.2,offensive:true,acc:0.9,effects:[{kind:'damage',target:'enemies',damageType:'mag',power:11},{kind:'heal',target:'allies',flatHeal:12}],upgradeLevel1:{description:'P+2 et soin+',powerBonus:2},upgradeLevel2:{description:'Rayon+',radiusBonus:0.25}},
{id:'r_perfect_duality',name:'Dualité Parfaite',description:'P17 grande zone + soin alliés + Barrière lanceur.',ap:5,icon:'✦',type:'mag',power:17,range:[1,3],radius:2,offensive:true,acc:0.85,effects:[{kind:'damage',target:'enemies',damageType:'mag',power:17},{kind:'heal',target:'allies',flatHeal:25},{kind:'status',target:'caster',status:'barrier',statusTurns:2}],upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Purifie alliés',dispelAllies:true}},
// ENCHANTER
{id:'e_vigor_rune',name:'Rune de Vigueur',description:'Force+ sur allié 3 tours.',ap:2,icon:'✦',type:'buff',power:0,range:[0,3],support:true,status:'boost',statusTurns:3,upgradeLevel1:{description:'Portée+',rangeBonus:1},upgradeLevel2:{description:'4 tours',statusTurnsBonus:1}},
{id:'e_transpose',name:'Transposition',description:'Échange position avec un allié.',ap:3,icon:'✦',type:'move',mode:'teleport',dest:true,range:[1,3],support:true,upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Barrière deux unités',additionalStatus:'barrier',additionalStatusTurns:1}},
{id:'e_binding_seal',name:'Sceau d\'Entrave',description:'Zone immobilise ennemis 2 tours.',ap:4,icon:'✦',type:'debuff',power:0,range:[1,3],radius:1.2,offensive:true,acc:1,status:'root',statusTurns:2,upgradeLevel1:{description:'Rayon+',radiusBonus:0.25},upgradeLevel2:{description:'Affaibli 1 tour',additionalStatus:'weak',additionalStatusTurns:1}},
{id:'e_absolute_harmony',name:'Harmonie Absolue',description:'Force+ et Barrière tous alliés 3 tours.',ap:5,icon:'✦',type:'buff',power:0,range:[0,3],radius:2,support:true,effects:[{kind:'status',target:'allies',status:'boost',statusTurns:3},{kind:'status',target:'allies',status:'barrier',statusTurns:3}],upgradeLevel1:{description:'Portée+',rangeBonus:1},upgradeLevel2:{description:'Purification et 4 tours',statusTurnsBonus:1,dispelAllies:true}},
// ARCHER
{id:'a_precise_shot',name:'Tir Précis',description:'P9, portée 2-4, critique accru.',ap:2,icon:'⌁',type:'phys',power:9,range:[2,4],offensive:true,acc:0.95,crit:0.15,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Ignore 30% END',penetrationBonus:0.3}},
{id:'a_hawk_leap',name:'Bond du Faucon',description:'Bond 2-3 cases + améliore prochain tir.',ap:3,icon:'⌁',type:'move',mode:'leap',dest:true,range:[2,3],effects:[{kind:'status',target:'caster',status:'boost',statusTurns:1}],upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Tir ignore 30% END',penetrationBonus:0.3}},
{id:'a_arrow_rain',name:'Pluie de Flèches',description:'Zone P11 longue portée, Ralentissement.',ap:4,icon:'⌁',type:'phys',power:11,range:[2,4],radius:1.2,offensive:true,acc:0.9,status:'slow',statusTurns:2,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Rayon+',radiusBonus:0.25}},
{id:'a_zenith_arrow',name:'Flèche du Zénith',description:'P21 monocible, 70% pénétration.',ap:5,icon:'⌁',type:'phys',power:21,range:[2,4],offensive:true,acc:0.99,penetration:0.7,crit:0.1,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Critique garanti si isolé',critBonus:0.9}},
// NINJA
{id:'ni_venom_blade',name:'Lame Venimeuse',description:'P8 et Poison 2 tours.',ap:2,icon:'†',type:'phys',power:8,range:[1,1],offensive:true,acc:0.95,status:'poison',statusTurns:2,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Poison 3 tours',statusTurnsBonus:1}},
{id:'ni_shadow_step',name:'Pas d\'Ombre',description:'Téléporte derrière cible, P7.',ap:3,icon:'†',type:'move',mode:'teleport',dest:true,range:[1,2],power:7,offensive:true,acc:0.9,effects:[{kind:'move',target:'caster',moveMode:'teleport'},{kind:'damage',target:'enemies',damageType:'phys',power:7}],upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Aveuglé 1 tour',additionalStatus:'blind',additionalStatusTurns:1}},
{id:'ni_smoke_bomb',name:'Bombe Fumigène',description:'Zone Aveuglement 2 tours + Barrière Ninja.',ap:4,icon:'†',type:'debuff',power:0,range:[0,1],radius:1.5,offensive:true,acc:1,status:'blind',statusTurns:2,effects:[{kind:'status',target:'enemies',status:'blind',statusTurns:2},{kind:'status',target:'caster',status:'barrier',statusTurns:1}],upgradeLevel1:{description:'Rayon+',radiusBonus:0.25},upgradeLevel2:{description:'Affaiblit ennemis',additionalStatus:'weak',additionalStatusTurns:1}},
{id:'ni_silent_assassin',name:'Assassinat Silencieux',description:'Téléporte, P20, bonus sous 50% PV.',ap:5,icon:'†',type:'phys',power:20,range:[1,3],offensive:true,acc:0.95,effects:[{kind:'move',target:'caster',moveMode:'teleport'},{kind:'damage',target:'enemies',damageType:'phys',power:20}],upgradeLevel1:{description:'Bonus sous 70% PV',powerBonus:4},upgradeLevel2:{description:'Poison si survit',additionalStatus:'poison',additionalStatusTurns:2}},
// ROGUE
{id:'ro_sneak_attack',name:'Coup Sournois',description:'P8, critique élevé, fort depuis dos.',ap:2,icon:'†',type:'phys',power:8,range:[1,1],offensive:true,acc:0.9,crit:0.2,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Critique garanti dos',critBonus:0.8}},
{id:'ro_tumble',name:'Roulade',description:'Bond 2-3 cases + bonus critique.',ap:3,icon:'†',type:'move',mode:'leap',dest:true,range:[2,3],effects:[{kind:'status',target:'caster',status:'boost',statusTurns:1}],upgradeLevel1:{description:'Portée+1',rangeBonus:1},upgradeLevel2:{description:'Barrière courte',additionalStatus:'barrier',additionalStatusTurns:1}},
{id:'ro_jaw_trap',name:'Piège à Mâchoires',description:'Piège P11 + Immobilisation 2 tours.',ap:4,icon:'†',type:'phys',power:11,range:[1,2],offensive:true,acc:1,status:'root',statusTurns:2,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Zone petite',radiusBonus:0.5}},
{id:'ro_fault_breaker',name:'Casse-Faille',description:'P18, retire buffs, ignore 50% END.',ap:5,icon:'†',type:'phys',power:18,range:[1,1],offensive:true,acc:0.95,penetration:0.5,effects:[{kind:'damage',target:'enemies',damageType:'phys',power:18},{kind:'dispel',target:'enemies',dispelType:'positive'}],upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Vole buff retiré',stealBuffs:true}},
// ARTILLEUR
{id:'ar_calibrated_shot',name:'Tir Calibré',description:'P9 moyenne/longue portée, précision.',ap:2,icon:'⌁',type:'phys',power:9,range:[2,4],offensive:true,acc:0.95,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Ignore 25% END',penetrationBonus:0.25}},
{id:'ar_explosive_retreat',name:'Repli Explosif',description:'Bond arrière + explosion P7 case quittée.',ap:3,icon:'⌁',type:'phys',power:7,range:[0,0],radius:1,self:true,offensive:true,acc:0.9,effects:[{kind:'move',target:'caster',moveMode:'leap'},{kind:'damage',target:'enemies',damageType:'phys',power:7}],upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Brûlure',additionalStatus:'burn',additionalStatusTurns:2}},
{id:'ar_incendiary_grenade',name:'Grenade Incendiaire',description:'Zone P12, Brûlure 2 tours, alliés touchés.',ap:4,icon:'⌁',type:'phys',power:12,range:[2,4],radius:1.2,offensive:true,acc:0.9,status:'burn',statusTurns:2,allowSelfDamage:true,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Rayon+',radiusBonus:0.25}},
{id:'ar_artillery_barrage',name:'Barrage d\'Artillerie',description:'3 impacts grande zone, P18 total, Brûlure.',ap:5,icon:'⌁',type:'phys',power:18,range:[2,4],radius:2,offensive:true,acc:0.85,status:'burn',statusTurns:2,allowSelfDamage:true,upgradeLevel1:{description:'P+2',powerBonus:2},upgradeLevel2:{description:'Dernier impact étourdit',additionalStatus:'stun',additionalStatusTurns:1}},
// BOSS
{id:'boss_slam',name:'Frappe Sismique',description:'Coup de zone dévastateur.',ap:4,icon:'◆',type:'phys',power:16,range:[1,2],radius:1.2,offensive:true,acc:0.95},
{id:'boss_roar',name:'Rugissement',description:'Affaiblit tous les ennemis.',ap:5,icon:'◆',type:'debuff',power:0,range:[0,3],radius:2,offensive:true,acc:1,status:'weak',statusTurns:3},
{id:'boss_quake',name:'Onde de Choc',description:'Explosion magique qui étourdit.',ap:5,icon:'◆',type:'mag',power:14,range:[2,4],radius:1.5,offensive:true,acc:0.85,status:'stun',statusTurns:1},
{id:'boss_guard',name:'Garde',description:'Se protège d\'une barrière.',ap:3,icon:'◆',type:'buff',power:0,range:[0,0],self:true,support:true,status:'barrier',statusTurns:3},
// ENEMY
{id:'enemy_heavy_strike',name:'Frappe Lourde',description:'P10, étourdit 1 tour.',ap:2,icon:'⚔',type:'phys',power:10,range:[1,1],offensive:true,acc:0.85,status:'stun',statusTurns:1},
{id:'enemy_crush',name:'Écrasement',description:'P14 zone adjacente.',ap:3,icon:'◆',type:'phys',power:14,range:[0,0],radius:1,self:true,offensive:true,acc:0.8},
{id:'enemy_dark_bolt',name:'Éclair Sombre',description:'P8 magique, portée 3.',ap:2,icon:'✦',type:'mag',power:8,range:[1,3],offensive:true,acc:0.85},
{id:'enemy_hex',name:'Maléfice',description:'Malédiction 2 tours à distance.',ap:2,icon:'✦',type:'debuff',power:0,range:[1,3],offensive:true,acc:1,status:'curse',statusTurns:2},
{id:'enemy_venom_strike',name:'Frappe Venimeuse',description:'P7 et Poison 2 tours.',ap:2,icon:'†',type:'phys',power:7,range:[1,1],offensive:true,acc:0.9,status:'poison',statusTurns:2},
{id:'enemy_binding_shot',name:'Tir Entravant',description:'Immobilise 1 tour à distance.',ap:2,icon:'⌁',type:'debuff',power:0,range:[2,3],offensive:true,acc:1,status:'root',statusTurns:1},
{id:'enemy_smoke_veil',name:'Voile de Fumée',description:'Aveugle zone 1 tour.',ap:3,icon:'†',type:'debuff',power:0,range:[0,1],radius:1.2,offensive:true,acc:1,status:'blind',statusTurns:1},
{id:'enemy_taunt',name:'Provocation',description:'Provocation 2 tours, monocible.',ap:2,icon:'◆',type:'debuff',power:0,range:[1,3],offensive:true,acc:1,status:'taunt',statusTurns:2},
{id:'enemy_battle_cry',name:'Cri de Guerre',description:'Affaiblit zone 2 tours.',ap:3,icon:'◆',type:'debuff',power:0,range:[0,2],radius:1.5,offensive:true,acc:1,status:'weak',statusTurns:2},
{id:'enemy_dragon_breath',name:'Souffle de Dragon',description:'P15 zone, Brûlure 2 tours.',ap:3,icon:'✦',type:'mag',power:15,range:[1,3],radius:1.5,offensive:true,acc:0.85,status:'burn',statusTurns:2},
];

export const skillById = new Map(skills.map(s => [s.id, s]));
