const travelDefaultBackdrop = '/assets/backdrops/travel_default.png';
const travelCityBackdrop = '/assets/backdrops/travel_city.png';
const travelCastleBackdrop = '/assets/backdrops/travel_castle.png';

export const assets = {
  models: {
    forestKit: '/assets/3d/forest-kit.glb',
  },
  materials: {
    forestGrass: '/assets/3d/forest-kit/materials/grass.webp',
    forestStone: '/assets/3d/forest-kit/materials/stone.webp',
    forestBark: '/assets/3d/forest-kit/materials/bark.webp',
    forestFoliage: '/assets/3d/forest-kit/materials/foliage.webp',
  },
  world: {
    forestFar: '/assets/generated/forest-pilot/forest-dawn-far.webp',
    forestMid: '/assets/generated/forest-pilot/forest-mid.webp',
    forestFore: '/assets/generated/forest-pilot/forest-fore.webp',
  },
  portraits: {
    alistair: '/assets/characters/pixel/full/alistair.png',
    marian: '/assets/characters/pixel/full/marian.png',
    elara: '/assets/characters/pixel/full/elara.png',
    kestrel: '/assets/characters/pixel/full/kestrel.png',
    cedric: '/assets/characters/pixel/full/cedric.png',
    lancer: '/assets/characters/pixel/full/lancer.png',
  },
  pixelCharactersFull: {
    alistair: '/assets/characters/pixel/full/alistair.png',
    marian: '/assets/characters/pixel/full/marian.png',
    elara: '/assets/characters/pixel/full/elara.png',
    kestrel: '/assets/characters/pixel/full/kestrel.png',
    cedric: '/assets/characters/pixel/full/cedric.png',
    lancer: '/assets/characters/pixel/full/lancer.png',
    alaric: '/assets/characters/pixel/full/alaric.png',
    maelor: '/assets/characters/pixel/full/maelor.png',
    villageoise: '/assets/characters/pixel/full/villageoise.png',
    refugee_mother: '/assets/characters/pixel/full/refugee_mother.png',
    wounded_merchant: '/assets/characters/pixel/full/wounded_merchant.png',
    survivor: '/assets/characters/pixel/full/survivor.png',
    chroniqueur: '/assets/characters/pixel/full/chroniqueur.png',
    seraphine: '/assets/characters/pixel/full/seraphine.png',
    serpent_raider: '/assets/characters/pixel/full/serpent_raider.png',
    serpent_brute: '/assets/characters/pixel/full/serpent_brute.png',
    serpent_oracle: '/assets/characters/pixel/full/serpent_oracle.png',
    serpent_elite_raider: '/assets/characters/pixel/full/serpent_elite_raider.png',
    serpent_elite_brute: '/assets/characters/pixel/full/serpent_elite_brute.png',
    serpent_captain: '/assets/characters/pixel/full/boss_serpent_captain.png',
    serpent_general_boss: '/assets/characters/pixel/full/serpent_general_boss.png',
    serpent_duelist_elite: '/assets/characters/pixel/full/serpent_duelist_elite.png',
    lion_champion: '/assets/characters/pixel/full/lion_champion.png',
    seal_guardian: '/assets/characters/pixel/full/seal_guardian.png',
    wolf: '/assets/characters/pixel/full/wolf.png',
    venom_serpent: '/assets/characters/pixel/full/venom_serpent.png',
    forest_spider: '/assets/characters/pixel/full/forest_spider.png',
    forest_badger: '/assets/characters/pixel/full/forest_badger.png',
    marsh_toad: '/assets/characters/pixel/full/marsh_toad.png',
    cave_rat: '/assets/characters/pixel/full/cave_rat.png',
    wild_boar: '/assets/characters/pixel/full/wild_boar.png',
    goblin: '/assets/characters/pixel/full/goblin.png',
    skeleton: '/assets/characters/pixel/full/skeleton.png',
    troll: '/assets/characters/pixel/full/troll.png',
    young_wyrm: '/assets/characters/pixel/full/young_wyrm.png',
    undead_champion: '/assets/characters/pixel/full/undead_champion.png',
    forest_troll_elite: '/assets/characters/pixel/full/forest_troll_elite.png',
    young_dragon_elite: '/assets/characters/pixel/full/young_dragon_elite.png',
    shrine_apparition: '/assets/characters/pixel/full/shrine_apparition.png',
    shadow_omen: '/assets/characters/pixel/full/shadow_omen.png',
    fallback_hero: '/assets/characters/pixel/full/fallback_hero.png',
  },
  pixelCharactersDialogue: {
    alistair: '/assets/characters/pixel/dialogue/alistair.png',
    marian: '/assets/characters/pixel/dialogue/marian.png',
    elara: '/assets/characters/pixel/dialogue/elara.png',
    kestrel: '/assets/characters/pixel/dialogue/kestrel.png',
    cedric: '/assets/characters/pixel/dialogue/cedric.png',
    lancer: '/assets/characters/pixel/dialogue/lancer.png',
    alaric: '/assets/characters/pixel/dialogue/alaric.png',
    maelor: '/assets/characters/pixel/dialogue/maelor.png',
    villageoise: '/assets/characters/pixel/dialogue/villageoise.png',
    refugee_mother: '/assets/characters/pixel/dialogue/refugee_mother.png',
    wounded_merchant: '/assets/characters/pixel/dialogue/wounded_merchant.png',
    survivor: '/assets/characters/pixel/dialogue/survivor.png',
    chroniqueur: '/assets/characters/pixel/dialogue/chroniqueur.png',
    seraphine: '/assets/characters/pixel/dialogue/seraphine.png',
    serpent_raider: '/assets/characters/pixel/dialogue/serpent_raider.png',
    serpent_brute: '/assets/characters/pixel/dialogue/serpent_brute.png',
    serpent_oracle: '/assets/characters/pixel/dialogue/serpent_oracle.png',
    serpent_elite_raider: '/assets/characters/pixel/dialogue/serpent_elite_raider.png',
    serpent_elite_brute: '/assets/characters/pixel/dialogue/serpent_elite_brute.png',
    serpent_captain: '/assets/characters/pixel/dialogue/serpent_captain.png',
    serpent_general_boss: '/assets/characters/pixel/dialogue/serpent_general_boss.png',
    serpent_duelist_elite: '/assets/characters/pixel/dialogue/serpent_duelist_elite.png',
    lion_champion: '/assets/characters/pixel/dialogue/lion_champion.png',
    seal_guardian: '/assets/characters/pixel/dialogue/seal_guardian.png',
    wolf: '/assets/characters/pixel/dialogue/wolf.png',
    venom_serpent: '/assets/characters/pixel/dialogue/venom_serpent.png',
    forest_spider: '/assets/characters/pixel/dialogue/forest_spider.png',
    forest_badger: '/assets/characters/pixel/dialogue/forest_badger.png',
    marsh_toad: '/assets/characters/pixel/dialogue/marsh_toad.png',
    cave_rat: '/assets/characters/pixel/dialogue/cave_rat.png',
    wild_boar: '/assets/characters/pixel/dialogue/wild_boar.png',
    goblin: '/assets/characters/pixel/dialogue/goblin.png',
    skeleton: '/assets/characters/pixel/dialogue/skeleton.png',
    troll: '/assets/characters/pixel/dialogue/troll.png',
    young_wyrm: '/assets/characters/pixel/dialogue/young_wyrm.png',
    undead_champion: '/assets/characters/pixel/dialogue/undead_champion.png',
    forest_troll_elite: '/assets/characters/pixel/dialogue/forest_troll_elite.png',
    young_dragon_elite: '/assets/characters/pixel/dialogue/young_dragon_elite.png',
    shrine_apparition: '/assets/characters/pixel/dialogue/shrine_apparition.png',
    shadow_omen: '/assets/characters/pixel/dialogue/shadow_omen.png',
    fallback_hero: '/assets/characters/pixel/dialogue/fallback_hero.png',
  },
  pixelCharactersUi: {
    alistair: '/assets/characters/pixel/ui/alistair.png',
    marian: '/assets/characters/pixel/ui/marian.png',
    elara: '/assets/characters/pixel/ui/elara.png',
    kestrel: '/assets/characters/pixel/ui/kestrel.png',
    cedric: '/assets/characters/pixel/ui/cedric.png',
    lancer: '/assets/characters/pixel/ui/lancer.png',
    alaric: '/assets/characters/pixel/ui/alaric.png',
    maelor: '/assets/characters/pixel/ui/maelor.png',
    villageoise: '/assets/characters/pixel/ui/villageoise.png',
    refugee_mother: '/assets/characters/pixel/ui/refugee_mother.png',
    wounded_merchant: '/assets/characters/pixel/ui/wounded_merchant.png',
    survivor: '/assets/characters/pixel/ui/survivor.png',
    chroniqueur: '/assets/characters/pixel/ui/chroniqueur.png',
    seraphine: '/assets/characters/pixel/ui/seraphine.png',
    serpent_raider: '/assets/characters/pixel/ui/serpent_raider.png',
    serpent_brute: '/assets/characters/pixel/ui/serpent_brute.png',
    serpent_oracle: '/assets/characters/pixel/ui/serpent_oracle.png',
    serpent_elite_raider: '/assets/characters/pixel/ui/serpent_elite_raider.png',
    serpent_elite_brute: '/assets/characters/pixel/ui/serpent_elite_brute.png',
    serpent_captain: '/assets/characters/pixel/ui/serpent_captain.png',
    serpent_general_boss: '/assets/characters/pixel/ui/serpent_general_boss.png',
    serpent_duelist_elite: '/assets/characters/pixel/ui/serpent_duelist_elite.png',
    lion_champion: '/assets/characters/pixel/ui/lion_champion.png',
    seal_guardian: '/assets/characters/pixel/ui/seal_guardian.png',
    wolf: '/assets/characters/pixel/ui/wolf.png',
    venom_serpent: '/assets/characters/pixel/ui/venom_serpent.png',
    forest_spider: '/assets/characters/pixel/ui/forest_spider.png',
    forest_badger: '/assets/characters/pixel/ui/forest_badger.png',
    marsh_toad: '/assets/characters/pixel/ui/marsh_toad.png',
    cave_rat: '/assets/characters/pixel/ui/cave_rat.png',
    wild_boar: '/assets/characters/pixel/ui/wild_boar.png',
    goblin: '/assets/characters/pixel/ui/goblin.png',
    skeleton: '/assets/characters/pixel/ui/skeleton.png',
    troll: '/assets/characters/pixel/ui/troll.png',
    young_wyrm: '/assets/characters/pixel/ui/young_wyrm.png',
    undead_champion: '/assets/characters/pixel/ui/undead_champion.png',
    forest_troll_elite: '/assets/characters/pixel/ui/forest_troll_elite.png',
    young_dragon_elite: '/assets/characters/pixel/ui/young_dragon_elite.png',
    shrine_apparition: '/assets/characters/pixel/ui/shrine_apparition.png',
    shadow_omen: '/assets/characters/pixel/ui/shadow_omen.png',
    fallback_hero: '/assets/characters/pixel/ui/fallback_hero.png',
  },
  characterProfiles: {
    alistair: { full: '/assets/characters/pixel/full/alistair.png', dialogue: '/assets/characters/pixel/dialogue/alistair.png', ui: '/assets/characters/pixel/ui/alistair.png', fallback: '/assets/characters/pixel/full/alistair.png', dialogueScale: 1, dialogueSideOffset: '-4px', combatHeight: 2.14, uiCropMode: 'contain' },
    marian: { full: '/assets/characters/pixel/full/marian.png', dialogue: '/assets/characters/pixel/dialogue/marian.png', ui: '/assets/characters/pixel/ui/marian.png', fallback: '/assets/characters/pixel/full/marian.png', dialogueScale: 1, dialogueSideOffset: '-2px', combatHeight: 2.16, uiCropMode: 'contain' },
    elara: { full: '/assets/characters/pixel/full/elara.png', dialogue: '/assets/characters/pixel/dialogue/elara.png', ui: '/assets/characters/pixel/ui/elara.png', fallback: '/assets/characters/pixel/full/elara.png', dialogueScale: 1.02, dialogueSideOffset: '0px', combatHeight: 2.18, uiCropMode: 'contain' },
    kestrel: { full: '/assets/characters/pixel/full/kestrel.png', dialogue: '/assets/characters/pixel/dialogue/kestrel.png', ui: '/assets/characters/pixel/ui/kestrel.png', fallback: '/assets/characters/pixel/full/kestrel.png', dialogueScale: 0.98, dialogueSideOffset: '6px', combatHeight: 2.08, uiCropMode: 'contain' },
    cedric: { full: '/assets/characters/pixel/full/cedric.png', dialogue: '/assets/characters/pixel/dialogue/cedric.png', ui: '/assets/characters/pixel/ui/cedric.png', fallback: '/assets/characters/pixel/full/cedric.png', dialogueScale: 0.96, dialogueSideOffset: '4px', combatHeight: 2.08, uiCropMode: 'contain' },
    lancer: { full: '/assets/characters/pixel/full/lancer.png', dialogue: '/assets/characters/pixel/dialogue/lancer.png', ui: '/assets/characters/pixel/ui/lancer.png', fallback: '/assets/characters/pixel/full/lancer.png', dialogueScale: 0.98, dialogueSideOffset: '0px', combatHeight: 2.12, uiCropMode: 'contain' },
    alaric: { full: '/assets/characters/pixel/full/alaric.png', dialogue: '/assets/characters/pixel/dialogue/alaric.png', ui: '/assets/characters/pixel/ui/alaric.png', fallback: '/assets/characters/pixel/full/alaric.png', dialogueScale: 1.04, dialogueSideOffset: '0px', combatHeight: 2.25, uiCropMode: 'contain' },
    maelor: { full: '/assets/characters/pixel/full/maelor.png', dialogue: '/assets/characters/pixel/dialogue/maelor.png', ui: '/assets/characters/pixel/ui/maelor.png', fallback: '/assets/characters/pixel/full/maelor.png', dialogueScale: 0.98, dialogueSideOffset: '0px', combatHeight: 2.08, uiCropMode: 'contain' },
    villageoise: { full: '/assets/characters/pixel/full/villageoise.png', dialogue: '/assets/characters/pixel/dialogue/villageoise.png', ui: '/assets/characters/pixel/ui/villageoise.png', fallback: '/assets/characters/pixel/full/villageoise.png', dialogueScale: 0.92, dialogueSideOffset: '0px', combatHeight: 1.96, uiCropMode: 'contain' },
    refugee_mother: { full: '/assets/characters/pixel/full/refugee_mother.png', dialogue: '/assets/characters/pixel/dialogue/refugee_mother.png', ui: '/assets/characters/pixel/ui/refugee_mother.png', fallback: '/assets/characters/pixel/full/refugee_mother.png', dialogueScale: 0.94, dialogueSideOffset: '0px', combatHeight: 1.98, uiCropMode: 'contain' },
    wounded_merchant: { full: '/assets/characters/pixel/full/wounded_merchant.png', dialogue: '/assets/characters/pixel/dialogue/wounded_merchant.png', ui: '/assets/characters/pixel/ui/wounded_merchant.png', fallback: '/assets/characters/pixel/full/wounded_merchant.png', dialogueScale: 0.92, dialogueSideOffset: '0px', combatHeight: 1.96, uiCropMode: 'contain' },
    survivor: { full: '/assets/characters/pixel/full/survivor.png', dialogue: '/assets/characters/pixel/dialogue/survivor.png', ui: '/assets/characters/pixel/ui/survivor.png', fallback: '/assets/characters/pixel/full/survivor.png', dialogueScale: 0.92, dialogueSideOffset: '0px', combatHeight: 1.96, uiCropMode: 'contain' },
    chroniqueur: { full: '/assets/characters/pixel/full/chroniqueur.png', dialogue: '/assets/characters/pixel/dialogue/chroniqueur.png', ui: '/assets/characters/pixel/ui/chroniqueur.png', fallback: '/assets/characters/pixel/full/chroniqueur.png', dialogueScale: 0.98, dialogueSideOffset: '0px', combatHeight: 2.08, uiCropMode: 'contain' },
    sage_seraphine: { full: '/assets/characters/pixel/full/seraphine.png', dialogue: '/assets/characters/pixel/dialogue/seraphine.png', ui: '/assets/characters/pixel/ui/seraphine.png', fallback: '/assets/characters/pixel/full/seraphine.png', dialogueScale: 1, dialogueSideOffset: '0px', combatHeight: 2.1, uiCropMode: 'contain' },
    serpent_raider: { full: '/assets/characters/pixel/full/serpent_raider.png', dialogue: '/assets/characters/pixel/dialogue/serpent_raider.png', ui: '/assets/characters/pixel/ui/serpent_raider.png', fallback: '/assets/characters/pixel/full/serpent_raider.png', dialogueScale: 0.98, dialogueSideOffset: '2px', combatHeight: 2.06, uiCropMode: 'contain' },
    serpent_brute: { full: '/assets/characters/pixel/full/serpent_brute.png', dialogue: '/assets/characters/pixel/dialogue/serpent_brute.png', ui: '/assets/characters/pixel/ui/serpent_brute.png', fallback: '/assets/characters/pixel/full/serpent_brute.png', dialogueScale: 1, dialogueSideOffset: '0px', combatHeight: 2.18, uiCropMode: 'contain' },
    serpent_oracle: { full: '/assets/characters/pixel/full/serpent_oracle.png', dialogue: '/assets/characters/pixel/dialogue/serpent_oracle.png', ui: '/assets/characters/pixel/ui/serpent_oracle.png', fallback: '/assets/characters/pixel/full/serpent_oracle.png', dialogueScale: 1, dialogueSideOffset: '0px', combatHeight: 2.12, uiCropMode: 'contain' },
    serpent_elite_raider: { full: '/assets/characters/pixel/full/serpent_elite_raider.png', dialogue: '/assets/characters/pixel/dialogue/serpent_elite_raider.png', ui: '/assets/characters/pixel/ui/serpent_elite_raider.png', fallback: '/assets/characters/pixel/full/serpent_elite_raider.png', dialogueScale: 1, dialogueSideOffset: '2px', combatHeight: 2.04, uiCropMode: 'contain' },
    serpent_elite_brute: { full: '/assets/characters/pixel/full/serpent_elite_brute.png', dialogue: '/assets/characters/pixel/dialogue/serpent_elite_brute.png', ui: '/assets/characters/pixel/ui/serpent_elite_brute.png', fallback: '/assets/characters/pixel/full/serpent_elite_brute.png', dialogueScale: 1.02, dialogueSideOffset: '0px', combatHeight: 2.2, uiCropMode: 'contain' },
    serpent_captain: { full: '/assets/characters/pixel/full/boss_serpent_captain.png', dialogue: '/assets/characters/pixel/dialogue/serpent_captain.png', ui: '/assets/characters/pixel/ui/serpent_captain.png', fallback: '/assets/characters/pixel/full/boss_serpent_captain.png', dialogueScale: 1.04, dialogueSideOffset: '0px', combatHeight: 3.25, uiCropMode: 'contain' },
    serpent_general_boss: { full: '/assets/characters/pixel/full/serpent_general_boss.png', dialogue: '/assets/characters/pixel/dialogue/serpent_general_boss.png', ui: '/assets/characters/pixel/ui/serpent_general_boss.png', fallback: '/assets/characters/pixel/full/serpent_general_boss.png', dialogueScale: 1.04, dialogueSideOffset: '0px', combatHeight: 3.28, uiCropMode: 'contain' },
    serpent_duelist_elite: { full: '/assets/characters/pixel/full/serpent_duelist_elite.png', dialogue: '/assets/characters/pixel/dialogue/serpent_duelist_elite.png', ui: '/assets/characters/pixel/ui/serpent_duelist_elite.png', fallback: '/assets/characters/pixel/full/serpent_duelist_elite.png', dialogueScale: 1, dialogueSideOffset: '0px', combatHeight: 2.16, uiCropMode: 'contain' },
    lion_champion: { full: '/assets/characters/pixel/full/lion_champion.png', dialogue: '/assets/characters/pixel/dialogue/lion_champion.png', ui: '/assets/characters/pixel/ui/lion_champion.png', fallback: '/assets/characters/pixel/full/lion_champion.png', dialogueScale: 1, dialogueSideOffset: '0px', combatHeight: 2.14, uiCropMode: 'contain' },
    seal_guardian: { full: '/assets/characters/pixel/full/seal_guardian.png', dialogue: '/assets/characters/pixel/dialogue/seal_guardian.png', ui: '/assets/characters/pixel/ui/seal_guardian.png', fallback: '/assets/characters/pixel/full/seal_guardian.png', dialogueScale: 1, dialogueSideOffset: '0px', combatHeight: 2.2, uiCropMode: 'contain' },
    wolf: { full: '/assets/characters/pixel/full/wolf.png', dialogue: '/assets/characters/pixel/dialogue/wolf.png', ui: '/assets/characters/pixel/ui/wolf.png', fallback: '/assets/characters/pixel/full/wolf.png', dialogueScale: 0.92, dialogueSideOffset: '0px', combatHeight: 1.65, uiCropMode: 'contain' },
    venom_serpent: { full: '/assets/characters/pixel/full/venom_serpent.png', dialogue: '/assets/characters/pixel/dialogue/venom_serpent.png', ui: '/assets/characters/pixel/ui/venom_serpent.png', fallback: '/assets/characters/pixel/full/venom_serpent.png', dialogueScale: 0.92, dialogueSideOffset: '0px', combatHeight: 1.75, uiCropMode: 'contain' },
    forest_spider: { full: '/assets/characters/pixel/full/forest_spider.png', dialogue: '/assets/characters/pixel/dialogue/forest_spider.png', ui: '/assets/characters/pixel/ui/forest_spider.png', fallback: '/assets/characters/pixel/full/forest_spider.png', dialogueScale: 0.9, dialogueSideOffset: '0px', combatHeight: 1.46, uiCropMode: 'contain' },
    forest_badger: { full: '/assets/characters/pixel/full/forest_badger.png', dialogue: '/assets/characters/pixel/dialogue/forest_badger.png', ui: '/assets/characters/pixel/ui/forest_badger.png', fallback: '/assets/characters/pixel/full/forest_badger.png', dialogueScale: 0.9, dialogueSideOffset: '0px', combatHeight: 1.42, uiCropMode: 'contain' },
    marsh_toad: { full: '/assets/characters/pixel/full/marsh_toad.png', dialogue: '/assets/characters/pixel/dialogue/marsh_toad.png', ui: '/assets/characters/pixel/ui/marsh_toad.png', fallback: '/assets/characters/pixel/full/marsh_toad.png', dialogueScale: 0.9, dialogueSideOffset: '0px', combatHeight: 1.38, uiCropMode: 'contain' },
    cave_rat: { full: '/assets/characters/pixel/full/cave_rat.png', dialogue: '/assets/characters/pixel/dialogue/cave_rat.png', ui: '/assets/characters/pixel/ui/cave_rat.png', fallback: '/assets/characters/pixel/full/cave_rat.png', dialogueScale: 0.88, dialogueSideOffset: '0px', combatHeight: 1.32, uiCropMode: 'contain' },
    wild_boar: { full: '/assets/characters/pixel/full/wild_boar.png', dialogue: '/assets/characters/pixel/dialogue/wild_boar.png', ui: '/assets/characters/pixel/ui/wild_boar.png', fallback: '/assets/characters/pixel/full/wild_boar.png', dialogueScale: 0.9, dialogueSideOffset: '0px', combatHeight: 1.5, uiCropMode: 'contain' },
    goblin: { full: '/assets/characters/pixel/full/goblin.png', dialogue: '/assets/characters/pixel/dialogue/goblin.png', ui: '/assets/characters/pixel/ui/goblin.png', fallback: '/assets/characters/pixel/full/goblin.png', dialogueScale: 0.9, dialogueSideOffset: '0px', combatHeight: 1.82, uiCropMode: 'contain' },
    skeleton: { full: '/assets/characters/pixel/full/skeleton.png', dialogue: '/assets/characters/pixel/dialogue/skeleton.png', ui: '/assets/characters/pixel/ui/skeleton.png', fallback: '/assets/characters/pixel/full/skeleton.png', dialogueScale: 0.94, dialogueSideOffset: '0px', combatHeight: 1.95, uiCropMode: 'contain' },
    troll: { full: '/assets/characters/pixel/full/troll.png', dialogue: '/assets/characters/pixel/dialogue/troll.png', ui: '/assets/characters/pixel/ui/troll.png', fallback: '/assets/characters/pixel/full/troll.png', dialogueScale: 1, dialogueSideOffset: '0px', combatHeight: 2.55, uiCropMode: 'contain' },
    young_wyrm: { full: '/assets/characters/pixel/full/young_wyrm.png', dialogue: '/assets/characters/pixel/dialogue/young_wyrm.png', ui: '/assets/characters/pixel/ui/young_wyrm.png', fallback: '/assets/characters/pixel/full/young_wyrm.png', dialogueScale: 0.98, dialogueSideOffset: '0px', combatHeight: 2.4, uiCropMode: 'contain' },
    undead_champion: { full: '/assets/characters/pixel/full/undead_champion.png', dialogue: '/assets/characters/pixel/dialogue/undead_champion.png', ui: '/assets/characters/pixel/ui/undead_champion.png', fallback: '/assets/characters/pixel/full/undead_champion.png', dialogueScale: 1, dialogueSideOffset: '0px', combatHeight: 2.38, uiCropMode: 'contain' },
    forest_troll_elite: { full: '/assets/characters/pixel/full/forest_troll_elite.png', dialogue: '/assets/characters/pixel/dialogue/forest_troll_elite.png', ui: '/assets/characters/pixel/ui/forest_troll_elite.png', fallback: '/assets/characters/pixel/full/forest_troll_elite.png', dialogueScale: 1, dialogueSideOffset: '0px', combatHeight: 2.62, uiCropMode: 'contain' },
    young_dragon_elite: { full: '/assets/characters/pixel/full/young_dragon_elite.png', dialogue: '/assets/characters/pixel/dialogue/young_dragon_elite.png', ui: '/assets/characters/pixel/ui/young_dragon_elite.png', fallback: '/assets/characters/pixel/full/young_dragon_elite.png', dialogueScale: 0.98, dialogueSideOffset: '0px', combatHeight: 2.68, uiCropMode: 'contain' },
    shrine_apparition: { full: '/assets/characters/pixel/full/shrine_apparition.png', dialogue: '/assets/characters/pixel/dialogue/shrine_apparition.png', ui: '/assets/characters/pixel/ui/shrine_apparition.png', fallback: '/assets/characters/pixel/full/shrine_apparition.png', dialogueScale: 1.04, dialogueSideOffset: '0px', combatHeight: 2.22, uiCropMode: 'contain' },
    shadow_omen: { full: '/assets/characters/pixel/full/shadow_omen.png', dialogue: '/assets/characters/pixel/dialogue/shadow_omen.png', ui: '/assets/characters/pixel/ui/shadow_omen.png', fallback: '/assets/characters/pixel/full/shadow_omen.png', dialogueScale: 1.03, dialogueSideOffset: '0px', combatHeight: 2.24, uiCropMode: 'contain' },
    fallback_hero: { full: '/assets/characters/pixel/full/fallback_hero.png', dialogue: '/assets/characters/pixel/dialogue/fallback_hero.png', ui: '/assets/characters/pixel/ui/fallback_hero.png', fallback: '/assets/characters/pixel/full/fallback_hero.png', dialogueScale: 0.98, dialogueSideOffset: '0px', combatHeight: 2.08, uiCropMode: 'contain' },
  },
  visualProfiles: {
    alistair: { category: 'playable_hero', factionId: 'lion', rarity: 'unique', recruitTier: 'core', colorPalette: ['emerald', 'steel', 'gold'], silhouetteNotes: 'Frontline knight, wide defensive stance.' },
    marian: { category: 'playable_hero', factionId: 'lion', rarity: 'unique', recruitTier: 'core', colorPalette: ['white', 'gold', 'silver'], silhouetteNotes: 'Sacred cleric with staff and protective robes.' },
    elara: { category: 'playable_hero', factionId: 'lion', rarity: 'unique', recruitTier: 'core', colorPalette: ['arcane blue', 'cyan', 'gold'], silhouetteNotes: 'Arcane caster with pointed hat and glowing staff.' },
    kestrel: { category: 'playable_hero', factionId: 'lion', rarity: 'unique', recruitTier: 'core', colorPalette: ['forest green', 'leather brown', 'night blue'], silhouetteNotes: 'Mobile hooded archer.' },
    cedric: { category: 'playable_hero', factionId: 'neutral', rarity: 'unique', recruitTier: 'optional', colorPalette: ['sand', 'muted green', 'light leather'], silhouetteNotes: 'Nomad scout, lighter than Kestrel.' },
    lancer: { category: 'playable_hero', factionId: 'lion', rarity: 'unique', recruitTier: 'optional', colorPalette: ['steel', 'emerald', 'gold'], silhouetteNotes: 'Young Lion militiaman with spear and shield.' },
    alaric: { category: 'boss', factionId: 'lion', rarity: 'boss', colorPalette: ['royal blue', 'gold', 'ivory'], silhouetteNotes: 'Giant lion-chief boss, 2x2 board presence.' },
    maelor: { category: 'story_npc', factionId: 'lion', rarity: 'unique', colorPalette: ['dark gold', 'black', 'wine'], silhouetteNotes: 'Political steward, not a battle mage.' },
    villageoise: { category: 'story_npc', factionId: 'lion', rarity: 'unique', colorPalette: ['linen', 'brown', 'muted blue'], silhouetteNotes: 'Civilian villager silhouette for moral choices.' },
    refugee_mother: { category: 'story_npc', factionId: 'neutral', rarity: 'unique', colorPalette: ['earth', 'blue', 'wool'], silhouetteNotes: 'Protective refugee silhouette, non-combatant.' },
    wounded_merchant: { category: 'story_npc', factionId: 'neutral', rarity: 'unique', colorPalette: ['tan', 'green', 'leather'], silhouetteNotes: 'Injured merchant with travel gear.' },
    survivor: { category: 'story_npc', factionId: 'neutral', rarity: 'unique', colorPalette: ['ragged brown', 'grey'], silhouetteNotes: 'Road survivor, readable as vulnerable witness.' },
    chroniqueur: { category: 'story_npc', factionId: 'neutral', rarity: 'unique', colorPalette: ['deep blue', 'parchment', 'silver'], silhouetteNotes: 'Narrative chronicler with book and quill.' },
    sage_seraphine: { category: 'story_npc', factionId: 'lion', rarity: 'unique', colorPalette: ['ivory', 'gold', 'arcane blue'], silhouetteNotes: 'Sage advisor with mystical aura, distinct from Elara.' },
    serpent_raider: { category: 'faction_enemy', factionId: 'serpent', rarity: 'generic', artStatus: 'approved', colorPalette: ['dark green', 'black', 'copper'], silhouetteNotes: 'Anonymous masked Serpent skirmisher for reusable standard encounters.' },
    serpent_brute: { category: 'faction_enemy', factionId: 'serpent', rarity: 'generic', artStatus: 'approved', colorPalette: ['dark green', 'black', 'copper'], silhouetteNotes: 'Anonymous masked Serpent heavy guard for reusable standard encounters.' },
    serpent_oracle: { category: 'faction_enemy', factionId: 'serpent', rarity: 'generic', artStatus: 'approved', colorPalette: ['dark green', 'black', 'copper'], silhouetteNotes: 'Anonymous masked Serpent caster for reusable standard encounters.' },
    serpent_elite_raider: { category: 'faction_enemy', factionId: 'serpent', rarity: 'elite', visualTier: 'elite', baseArchetype: 'light_raider', recolorFamily: 'serpent_unique', colorPalette: ['dark green', 'black', 'copper'], silhouetteNotes: 'Detailed duelist/ambusher reserved for elite or sub-boss encounters.' },
    serpent_elite_brute: { category: 'faction_enemy', factionId: 'serpent', rarity: 'elite', visualTier: 'elite', baseArchetype: 'heavy_guard', recolorFamily: 'serpent_unique', colorPalette: ['dark green', 'black', 'copper'], silhouetteNotes: 'Detailed heavy bruiser reserved for elite or sub-boss encounters.' },
    serpent_captain: { category: 'boss', factionId: 'serpent', rarity: 'boss', colorPalette: ['dark green', 'black', 'copper'], silhouetteNotes: 'Serpent commander, 2x2 board presence.' },
    serpent_general_boss: { category: 'boss', factionId: 'serpent', rarity: 'boss', artStatus: 'approved', colorPalette: ['dark green', 'black', 'copper'], silhouetteNotes: 'Main Serpent general, masked and imposing, 2x2 board presence.' },
    serpent_duelist_elite: { category: 'faction_enemy', factionId: 'serpent', rarity: 'elite', artStatus: 'approved', colorPalette: ['dark green', 'black', 'copper'], silhouetteNotes: 'Fast masked Serpent duelist for impactful elite trials.' },
    lion_champion: { category: 'faction_enemy', factionId: 'lion', rarity: 'elite', colorPalette: ['royal blue', 'gold', 'ivory'], silhouetteNotes: 'Elite guard distinct from Alaric.' },
    seal_guardian: { category: 'faction_enemy', factionId: 'lion', rarity: 'elite', colorPalette: ['ivory', 'blue', 'gold'], silhouetteNotes: 'Mystical guardian of the seal.' },
    wolf: { category: 'monster', species: 'beast', rarity: 'generic', colorPalette: ['grey', 'charcoal'], silhouetteNotes: 'Low, fast quadruped.' },
    venom_serpent: { category: 'monster', species: 'serpent', rarity: 'generic', colorPalette: ['poison green', 'tan'], silhouetteNotes: 'Coiled venom beast.' },
    forest_spider: { category: 'monster', species: 'arachnid', rarity: 'generic', colorPalette: ['moss green', 'ochre', 'amber'], silhouetteNotes: 'Low forest spider, readable as a natural route hazard.' },
    forest_badger: { category: 'monster', species: 'beast', rarity: 'generic', colorPalette: ['brown', 'cream', 'black'], silhouetteNotes: 'Compact clawing beast for forest skirmishes.' },
    marsh_toad: { category: 'monster', species: 'amphibian', rarity: 'generic', colorPalette: ['moss green', 'yellow', 'orange'], silhouetteNotes: 'Heavy poisonous toad for wetland or shrine paths.' },
    cave_rat: { category: 'monster', species: 'vermin', rarity: 'generic', colorPalette: ['grey', 'pink', 'orange'], silhouetteNotes: 'Small aggressive vermin for ambush filler.' },
    wild_boar: { category: 'monster', species: 'beast', rarity: 'generic', colorPalette: ['russet', 'brown', 'ivory'], silhouetteNotes: 'Charging boar, broader than wolf but still basic.' },
    goblin: { category: 'monster', species: 'goblin', rarity: 'generic', colorPalette: ['green', 'leather brown'], silhouetteNotes: 'Small spear monster.' },
    skeleton: { category: 'monster', species: 'undead', rarity: 'generic', colorPalette: ['bone', 'rust', 'black'], silhouetteNotes: 'Undead warrior.' },
    troll: { category: 'elite_monster', species: 'troll', rarity: 'elite', colorPalette: ['moss green', 'stone grey'], silhouetteNotes: 'Large brute monster.' },
    young_wyrm: { category: 'elite_monster', species: 'dragon', rarity: 'elite', colorPalette: ['teal', 'cream'], silhouetteNotes: 'Young dragon/wyrm elite.' },
    undead_champion: { category: 'elite_monster', species: 'undead', rarity: 'elite', colorPalette: ['purple', 'black', 'bone'], silhouetteNotes: 'Armored undead champion.' },
    forest_troll_elite: { category: 'elite_monster', species: 'troll', rarity: 'elite', artStatus: 'approved', colorPalette: ['moss green', 'stone grey', 'leather brown'], silhouetteNotes: 'Massive forest troll used as a secondary high-risk challenge.' },
    young_dragon_elite: { category: 'elite_monster', species: 'dragon', rarity: 'elite', artStatus: 'approved', colorPalette: ['emerald', 'gold', 'cream'], silhouetteNotes: 'Rare young dragon challenge, large silhouette without boss footprint.' },
    shrine_apparition: { category: 'story_npc', factionId: 'shadows', rarity: 'unique', colorPalette: ['ivory', 'gold', 'spectral light'], silhouetteNotes: 'Mystical apparition tied to ancient shrines.' },
    shadow_omen: { category: 'boss', factionId: 'shadows', species: 'omen', rarity: 'boss', colorPalette: ['black', 'violet', 'cyan'], silhouetteNotes: 'Major shadow omen silhouette, reserved for supernatural threats.' },
    fallback_hero: { category: 'playable_hero', factionId: 'neutral', rarity: 'unique', recruitTier: 'late', colorPalette: ['neutral'], silhouetteNotes: 'Fallback only; never used as a canonical hero.' },
  },
  dialogueActors: {
    alistair: '/assets/characters/pixel/dialogue/alistair.png',
    marian: '/assets/characters/pixel/dialogue/marian.png',
    kestrel: '/assets/characters/pixel/dialogue/kestrel.png',
    alaric: '/assets/characters/pixel/dialogue/alaric.png',
    elara: '/assets/characters/pixel/dialogue/elara.png',
    maelor: '/assets/characters/pixel/dialogue/maelor.png',
    villageoise: '/assets/characters/pixel/dialogue/villageoise.png',
    refugee_mother: '/assets/characters/pixel/dialogue/refugee_mother.png',
    cedric: '/assets/characters/pixel/dialogue/cedric.png',
    lancer: '/assets/characters/pixel/dialogue/lancer.png',
    wounded_merchant: '/assets/characters/pixel/dialogue/wounded_merchant.png',
    survivor: '/assets/characters/pixel/dialogue/survivor.png',
    serpent_raider: '/assets/characters/pixel/dialogue/serpent_raider.png',
    serpent_brute: '/assets/characters/pixel/dialogue/serpent_brute.png',
    serpent_oracle: '/assets/characters/pixel/dialogue/serpent_oracle.png',
    serpent_elite_raider: '/assets/characters/pixel/dialogue/serpent_elite_raider.png',
    serpent_duelist_elite: '/assets/characters/pixel/dialogue/serpent_duelist_elite.png',
    serpent_general_boss: '/assets/characters/pixel/dialogue/serpent_general_boss.png',
    forest_troll_elite: '/assets/characters/pixel/dialogue/forest_troll_elite.png',
    young_dragon_elite: '/assets/characters/pixel/dialogue/young_dragon_elite.png',
    chroniqueur: '/assets/characters/pixel/dialogue/chroniqueur.png',
    sage_seraphine: '/assets/characters/pixel/dialogue/seraphine.png',
    shrine_apparition: '/assets/characters/pixel/dialogue/shrine_apparition.png',
    shadow_omen: '/assets/characters/pixel/dialogue/shadow_omen.png',
  },
  dialogueScenes: {
    acte_ouverture: '/assets/generated/lion-phase/dialogue/camp_departure.webp',
    lion_briefing: '/assets/generated/lion-phase/dialogue/lion_briefing.webp',
    refugee_trial: '/assets/generated/lion-phase/dialogue/refugee_trial.webp',
    reserve_trail: '/assets/generated/lion-phase/dialogue/reserve_trail.webp',
    village_choice: '/assets/generated/lion-phase/dialogue/village_choice.webp',
    mystery_recruit: '/assets/generated/lion-phase/dialogue/mystery_recruit.webp',
    mystery_lancer_recruit: '/assets/generated/lion-phase/dialogue/witnesses_on_road.webp',
    mystery_help: '/assets/generated/lion-phase/dialogue/mystery_help.webp',
    mystery_ambush: '/assets/generated/lion-phase/dialogue/mystery_ambush.webp',
    mystery_treasure: '/assets/generated/lion-phase/dialogue/mystery_treasure.webp',
    mystery_shrine: '/assets/generated/lion-phase/dialogue/mystery_shrine.webp',
    old_shrine_event: '/assets/generated/lion-phase/dialogue/mystery_shrine.webp',
    serpent_duelist_trial: '/assets/generated/lion-phase/dialogue/mystery_ambush.webp',
    mystery_troll_crossing: '/assets/generated/lion-phase/dialogue/forest_fork.webp',
    mystery_dragon_roost: '/assets/generated/lion-phase/dialogue/shadow_signs.webp',
    witnesses_on_road: '/assets/generated/lion-phase/dialogue/witnesses_on_road.webp',
    shadow_signs: '/assets/generated/lion-phase/dialogue/shadow_signs.webp',
    lion_finale_judgement: '/assets/generated/lion-phase/dialogue/lion_finale_judgement.webp',
    epilogue: '/assets/generated/lion-phase/dialogue/epilogue.webp',
    lion_refuge: '/assets/generated/lion-phase/dialogue/lion_refuge.webp',
    forest_fork: '/assets/generated/lion-phase/dialogue/forest_fork.webp',
  },
  prologueScenes: {
    prologue_fall: '/assets/generated/lion-phase/dialogue/epilogue.webp',
    prologue_seals: '/assets/generated/lion-phase/dialogue/lion_finale_judgement.webp',
    prologue_lion: '/assets/generated/lion-phase/dialogue/lion_briefing.webp',
    prologue_shadow: '/assets/generated/lion-phase/dialogue/shadow_signs.webp',
    prologue_departure: '/assets/generated/lion-phase/dialogue/camp_departure.webp',
  },
  combatScenes: {
    forest_route: '/assets/generated/lion-phase/combat/forest_route.webp',
    bois_clair_burning: '/assets/generated/lion-phase/combat/bois_clair_burning.webp',
    lion_sanctum: '/assets/generated/lion-phase/combat/lion_sanctum.webp',
  },
  // Named per-screen background slots.
  screens: {
    title: {
      background: '/assets/generated/forest-pilot/forest-dawn-far.webp',
    },
    travel: {
      background: travelDefaultBackdrop,
      sky: travelDefaultBackdrop,
      mist: '/assets/generated/forest-pilot/forest-mid.webp',
      backdrops: {
        default: travelDefaultBackdrop,
        city: travelCityBackdrop,
        castle: travelCastleBackdrop,
      },
    },
    dialogue: {
      background: '/assets/generated/forest-pilot/forest-dawn-far.webp',
    },
    exploration: {
      background: '/assets/generated/forest-pilot/forest-dawn-far.webp',
    },
    management: {
      background: '/assets/generated/forest-pilot/forest-dawn-far.webp',
    },
    combat: {
      background: '/assets/generated/lion-phase/combat/forest_route.webp',
      forestRuinsBackdrop: '/assets/generated/combat-painted/forest-ruins-backdrop.png',
      sky: '/assets/generated/forest-pilot/forest-dawn-far.webp',
      distance: '/assets/generated/forest-pilot/forest-mid.webp',
      mist: '/assets/generated/forest-pilot/forest-fore.webp',
    },
  },
} as const;
