const travelDefaultBackdrop = new URL('../../assets-source/backdrop/travel_default.png', import.meta.url).href;
const travelCityBackdrop = new URL('../../assets-source/backdrop/travel_city.png', import.meta.url).href;
const travelCastleBackdrop = new URL('../../assets-source/backdrop/travel_castle.png', import.meta.url).href;

export const assets = {
  models: {
    forestKit: '/assets/3d/forest-kit.glb',
  },
  materials: {
    forestGrass: '/assets/3d/forest-kit/materials/grass.webp',
    forestStone: '/assets/3d/forest-kit/materials/stone.webp',
    forestBark: '/assets/3d/forest-kit/materials/bark.webp',
    forestFoliage: '/assets/3d/forest-kit/materials/foliage.webp',
  },
  world: {
    forestFar: '/assets/generated/forest-pilot/forest-dawn-far.webp',
    forestMid: '/assets/generated/forest-pilot/forest-mid.webp',
    forestFore: '/assets/generated/forest-pilot/forest-fore.webp',
  },
  portraits: {
    alistair: '/assets/characters/pixel/full/alistair.png',
    marian: '/assets/characters/pixel/full/marian.png',
    elara: '/assets/characters/pixel/full/elara.png',
    kestrel: '/assets/characters/pixel/full/kestrel.png',
    cedric: '/assets/characters/pixel/full/cedric.png',
  },
  pixelCharactersFull: {
    alistair: '/assets/characters/pixel/full/alistair.png',
    marian: '/assets/characters/pixel/full/marian.png',
    elara: '/assets/characters/pixel/full/elara.png',
    kestrel: '/assets/characters/pixel/full/kestrel.png',
    cedric: '/assets/characters/pixel/full/cedric.png',
    alaric: '/assets/characters/pixel/full/alaric.png',
    maelor: '/assets/characters/pixel/full/maelor.png',
    villageoise: '/assets/characters/pixel/full/villageoise.png',
    refugee_mother: '/assets/characters/pixel/full/refugee_mother.png',
    wounded_merchant: '/assets/characters/pixel/full/wounded_merchant.png',
    survivor: '/assets/characters/pixel/full/survivor.png',
    chroniqueur: '/assets/characters/pixel/full/chroniqueur.png',
    serpent_elite_raider: '/assets/characters/pixel/full/serpent_elite_raider.png',
    serpent_elite_brute: '/assets/characters/pixel/full/serpent_elite_brute.png',
    serpent_captain: '/assets/characters/pixel/full/boss_serpent_captain.png',
    lion_champion: '/assets/characters/pixel/full/lion_champion.png',
    seal_guardian: '/assets/characters/pixel/full/seal_guardian.png',
    wolf: '/assets/characters/pixel/full/wolf.png',
    venom_serpent: '/assets/characters/pixel/full/venom_serpent.png',
    goblin: '/assets/characters/pixel/full/goblin.png',
    skeleton: '/assets/characters/pixel/full/skeleton.png',
    troll: '/assets/characters/pixel/full/troll.png',
    young_wyrm: '/assets/characters/pixel/full/young_wyrm.png',
    undead_champion: '/assets/characters/pixel/full/undead_champion.png',
    shrine_apparition: '/assets/characters/pixel/full/shrine_apparition.png',
    shadow_omen: '/assets/characters/pixel/full/shadow_omen.png',
    fallback_hero: '/assets/characters/pixel/full/fallback_hero.png',
  },
  pixelCharactersDialogue: {
    alistair: '/assets/characters/pixel/dialogue/alistair.png',
    marian: '/assets/characters/pixel/dialogue/marian.png',
    elara: '/assets/characters/pixel/dialogue/elara.png',
    kestrel: '/assets/characters/pixel/dialogue/kestrel.png',
    cedric: '/assets/characters/pixel/dialogue/cedric.png',
    alaric: '/assets/characters/pixel/dialogue/alaric.png',
    maelor: '/assets/characters/pixel/dialogue/maelor.png',
    villageoise: '/assets/characters/pixel/dialogue/villageoise.png',
    refugee_mother: '/assets/characters/pixel/dialogue/refugee_mother.png',
    wounded_merchant: '/assets/characters/pixel/dialogue/wounded_merchant.png',
    survivor: '/assets/characters/pixel/dialogue/survivor.png',
    chroniqueur: '/assets/characters/pixel/dialogue/chroniqueur.png',
    serpent_elite_raider: '/assets/characters/pixel/dialogue/serpent_elite_raider.png',
    serpent_elite_brute: '/assets/characters/pixel/dialogue/serpent_elite_brute.png',
    serpent_captain: '/assets/characters/pixel/dialogue/serpent_captain.png',
    lion_champion: '/assets/characters/pixel/dialogue/lion_champion.png',
    seal_guardian: '/assets/characters/pixel/dialogue/seal_guardian.png',
    wolf: '/assets/characters/pixel/dialogue/wolf.png',
    venom_serpent: '/assets/characters/pixel/dialogue/venom_serpent.png',
    goblin: '/assets/characters/pixel/dialogue/goblin.png',
    skeleton: '/assets/characters/pixel/dialogue/skeleton.png',
    troll: '/assets/characters/pixel/dialogue/troll.png',
    young_wyrm: '/assets/characters/pixel/dialogue/young_wyrm.png',
    undead_champion: '/assets/characters/pixel/dialogue/undead_champion.png',
    shrine_apparition: '/assets/characters/pixel/dialogue/shrine_apparition.png',
    shadow_omen: '/assets/characters/pixel/dialogue/shadow_omen.png',
    fallback_hero: '/assets/characters/pixel/dialogue/fallback_hero.png',
  },
  pixelCharactersUi: {
    alistair: '/assets/characters/pixel/ui/alistair.png',
    marian: '/assets/characters/pixel/ui/marian.png',
    elara: '/assets/characters/pixel/ui/elara.png',
    kestrel: '/assets/characters/pixel/ui/kestrel.png',
    cedric: '/assets/characters/pixel/ui/cedric.png',
    alaric: '/assets/characters/pixel/ui/alaric.png',
    maelor: '/assets/characters/pixel/ui/maelor.png',
    villageoise: '/assets/characters/pixel/ui/villageoise.png',
    refugee_mother: '/assets/characters/pixel/ui/refugee_mother.png',
    wounded_merchant: '/assets/characters/pixel/ui/wounded_merchant.png',
    survivor: '/assets/characters/pixel/ui/survivor.png',
    chroniqueur: '/assets/characters/pixel/ui/chroniqueur.png',
    serpent_elite_raider: '/assets/characters/pixel/ui/serpent_elite_raider.png',
    serpent_elite_brute: '/assets/characters/pixel/ui/serpent_elite_brute.png',
    serpent_captain: '/assets/characters/pixel/ui/serpent_captain.png',
    lion_champion: '/assets/characters/pixel/ui/lion_champion.png',
    seal_guardian: '/assets/characters/pixel/ui/seal_guardian.png',
    wolf: '/assets/characters/pixel/ui/wolf.png',
    venom_serpent: '/assets/characters/pixel/ui/venom_serpent.png',
    goblin: '/assets/characters/pixel/ui/goblin.png',
    skeleton: '/assets/characters/pixel/ui/skeleton.png',
    troll: '/assets/characters/pixel/ui/troll.png',
    young_wyrm: '/assets/characters/pixel/ui/young_wyrm.png',
    undead_champion: '/assets/characters/pixel/ui/undead_champion.png',
    shrine_apparition: '/assets/characters/pixel/ui/shrine_apparition.png',
    shadow_omen: '/assets/characters/pixel/ui/shadow_omen.png',
    fallback_hero: '/assets/characters/pixel/ui/fallback_hero.png',
  },
  characterProfiles: {
    alistair: { full: '/assets/characters/pixel/full/alistair.png', dialogue: '/assets/characters/pixel/dialogue/alistair.png', ui: '/assets/characters/pixel/ui/alistair.png', fallback: '/assets/characters/pixel/full/alistair.png', dialogueScale: 1, dialogueSideOffset: '-4px', combatHeight: 2.14, uiCropMode: 'contain' },
    marian: { full: '/assets/characters/pixel/full/marian.png', dialogue: '/assets/characters/pixel/dialogue/marian.png', ui: '/assets/characters/pixel/ui/marian.png', fallback: '/assets/characters/pixel/full/marian.png', dialogueScale: 1, dialogueSideOffset: '-2px', combatHeight: 2.16, uiCropMode: 'contain' },
    elara: { full: '/assets/characters/pixel/full/elara.png', dialogue: '/assets/characters/pixel/dialogue/elara.png', ui: '/assets/characters/pixel/ui/elara.png', fallback: '/assets/characters/pixel/full/elara.png', dialogueScale: 1.02, dialogueSideOffset: '0px', combatHeight: 2.18, uiCropMode: 'contain' },
    kestrel: { full: '/assets/characters/pixel/full/kestrel.png', dialogue: '/assets/characters/pixel/dialogue/kestrel.png', ui: '/assets/characters/pixel/ui/kestrel.png', fallback: '/assets/characters/pixel/full/kestrel.png', dialogueScale: 0.98, dialogueSideOffset: '6px', combatHeight: 2.08, uiCropMode: 'contain' },
    cedric: { full: '/assets/characters/pixel/full/cedric.png', dialogue: '/assets/characters/pixel/dialogue/cedric.png', ui: '/assets/characters/pixel/ui/cedric.png', fallback: '/assets/characters/pixel/full/cedric.png', dialogueScale: 0.96, dialogueSideOffset: '4px', combatHeight: 2.08, uiCropMode: 'contain' },
    alaric: { full: '/assets/characters/pixel/full/alaric.png', dialogue: '/assets/characters/pixel/dialogue/alaric.png', ui: '/assets/characters/pixel/ui/alaric.png', fallback: '/assets/characters/pixel/full/alaric.png', dialogueScale: 1.04, dialogueSideOffset: '0px', combatHeight: 2.25, uiCropMode: 'contain' },
    maelor: { full: '/assets/characters/pixel/full/maelor.png', dialogue: '/assets/characters/pixel/dialogue/maelor.png', ui: '/assets/characters/pixel/ui/maelor.png', fallback: '/assets/characters/pixel/full/maelor.png', dialogueScale: 0.98, dialogueSideOffset: '0px', combatHeight: 2.08, uiCropMode: 'contain' },
    villageoise: { full: '/assets/characters/pixel/full/villageoise.png', dialogue: '/assets/characters/pixel/dialogue/villageoise.png', ui: '/assets/characters/pixel/ui/villageoise.png', fallback: '/assets/characters/pixel/full/villageoise.png', dialogueScale: 0.92, dialogueSideOffset: '0px', combatHeight: 1.96, uiCropMode: 'contain' },
    refugee_mother: { full: '/assets/characters/pixel/full/refugee_mother.png', dialogue: '/assets/characters/pixel/dialogue/refugee_mother.png', ui: '/assets/characters/pixel/ui/refugee_mother.png', fallback: '/assets/characters/pixel/full/refugee_mother.png', dialogueScale: 0.94, dialogueSideOffset: '0px', combatHeight: 1.98, uiCropMode: 'contain' },
    wounded_merchant: { full: '/assets/characters/pixel/full/wounded_merchant.png', dialogue: '/assets/characters/pixel/dialogue/wounded_merchant.png', ui: '/assets/characters/pixel/ui/wounded_merchant.png', fallback: '/assets/characters/pixel/full/wounded_merchant.png', dialogueScale: 0.92, dialogueSideOffset: '0px', combatHeight: 1.96, uiCropMode: 'contain' },
    survivor: { full: '/assets/characters/pixel/full/survivor.png', dialogue: '/assets/characters/pixel/dialogue/survivor.png', ui: '/assets/characters/pixel/ui/survivor.png', fallback: '/assets/characters/pixel/full/survivor.png', dialogueScale: 0.92, dialogueSideOffset: '0px', combatHeight: 1.96, uiCropMode: 'contain' },
    chroniqueur: { full: '/assets/characters/pixel/full/chroniqueur.png', dialogue: '/assets/characters/pixel/dialogue/chroniqueur.png', ui: '/assets/characters/pixel/ui/chroniqueur.png', fallback: '/assets/characters/pixel/full/chroniqueur.png', dialogueScale: 0.98, dialogueSideOffset: '0px', combatHeight: 2.08, uiCropMode: 'contain' },
    serpent_elite_raider: { full: '/assets/characters/pixel/full/serpent_elite_raider.png', dialogue: '/assets/characters/pixel/dialogue/serpent_elite_raider.png', ui: '/assets/characters/pixel/ui/serpent_elite_raider.png', fallback: '/assets/characters/pixel/full/serpent_elite_raider.png', dialogueScale: 1, dialogueSideOffset: '2px', combatHeight: 2.04, uiCropMode: 'contain' },
    serpent_elite_brute: { full: '/assets/characters/pixel/full/serpent_elite_brute.png', dialogue: '/assets/characters/pixel/dialogue/serpent_elite_brute.png', ui: '/assets/characters/pixel/ui/serpent_elite_brute.png', fallback: '/assets/characters/pixel/full/serpent_elite_brute.png', dialogueScale: 1.02, dialogueSideOffset: '0px', combatHeight: 2.2, uiCropMode: 'contain' },
    serpent_captain: { full: '/assets/characters/pixel/full/boss_serpent_captain.png', dialogue: '/assets/characters/pixel/dialogue/serpent_captain.png', ui: '/assets/characters/pixel/ui/serpent_captain.png', fallback: '/assets/characters/pixel/full/boss_serpent_captain.png', dialogueScale: 1.04, dialogueSideOffset: '0px', combatHeight: 3.25, uiCropMode: 'contain' },
    lion_champion: { full: '/assets/characters/pixel/full/lion_champion.png', dialogue: '/assets/characters/pixel/dialogue/lion_champion.png', ui: '/assets/characters/pixel/ui/lion_champion.png', fallback: '/assets/characters/pixel/full/lion_champion.png', dialogueScale: 1, dialogueSideOffset: '0px', combatHeight: 2.14, uiCropMode: 'contain' },
    seal_guardian: { full: '/assets/characters/pixel/full/seal_guardian.png', dialogue: '/assets/characters/pixel/dialogue/seal_guardian.png', ui: '/assets/characters/pixel/ui/seal_guardian.png', fallback: '/assets/characters/pixel/full/seal_guardian.png', dialogueScale: 1, dialogueSideOffset: '0px', combatHeight: 2.2, uiCropMode: 'contain' },
    wolf: { full: '/assets/characters/pixel/full/wolf.png', dialogue: '/assets/characters/pixel/dialogue/wolf.png', ui: '/assets/characters/pixel/ui/wolf.png', fallback: '/assets/characters/pixel/full/wolf.png', dialogueScale: 0.92, dialogueSideOffset: '0px', combatHeight: 1.65, uiCropMode: 'contain' },
    venom_serpent: { full: '/assets/characters/pixel/full/venom_serpent.png', dialogue: '/assets/characters/pixel/dialogue/venom_serpent.png', ui: '/assets/characters/pixel/ui/venom_serpent.png', fallback: '/assets/characters/pixel/full/venom_serpent.png', dialogueScale: 0.92, dialogueSideOffset: '0px', combatHeight: 1.75, uiCropMode: 'contain' },
    goblin: { full: '/assets/characters/pixel/full/goblin.png', dialogue: '/assets/characters/pixel/dialogue/goblin.png', ui: '/assets/characters/pixel/ui/goblin.png', fallback: '/assets/characters/pixel/full/goblin.png', dialogueScale: 0.9, dialogueSideOffset: '0px', combatHeight: 1.82, uiCropMode: 'contain' },
    skeleton: { full: '/assets/characters/pixel/full/skeleton.png', dialogue: '/assets/characters/pixel/dialogue/skeleton.png', ui: '/assets/characters/pixel/ui/skeleton.png', fallback: '/assets/characters/pixel/full/skeleton.png', dialogueScale: 0.94, dialogueSideOffset: '0px', combatHeight: 1.95, uiCropMode: 'contain' },
    troll: { full: '/assets/characters/pixel/full/troll.png', dialogue: '/assets/characters/pixel/dialogue/troll.png', ui: '/assets/characters/pixel/ui/troll.png', fallback: '/assets/characters/pixel/full/troll.png', dialogueScale: 1, dialogueSideOffset: '0px', combatHeight: 2.55, uiCropMode: 'contain' },
    young_wyrm: { full: '/assets/characters/pixel/full/young_wyrm.png', dialogue: '/assets/characters/pixel/dialogue/young_wyrm.png', ui: '/assets/characters/pixel/ui/young_wyrm.png', fallback: '/assets/characters/pixel/full/young_wyrm.png', dialogueScale: 0.98, dialogueSideOffset: '0px', combatHeight: 2.4, uiCropMode: 'contain' },
    undead_champion: { full: '/assets/characters/pixel/full/undead_champion.png', dialogue: '/assets/characters/pixel/dialogue/undead_champion.png', ui: '/assets/characters/pixel/ui/undead_champion.png', fallback: '/assets/characters/pixel/full/undead_champion.png', dialogueScale: 1, dialogueSideOffset: '0px', combatHeight: 2.38, uiCropMode: 'contain' },
    shrine_apparition: { full: '/assets/characters/pixel/full/shrine_apparition.png', dialogue: '/assets/characters/pixel/dialogue/shrine_apparition.png', ui: '/assets/characters/pixel/ui/shrine_apparition.png', fallback: '/assets/characters/pixel/full/shrine_apparition.png', dialogueScale: 1.04, dialogueSideOffset: '0px', combatHeight: 2.22, uiCropMode: 'contain' },
    shadow_omen: { full: '/assets/characters/pixel/full/shadow_omen.png', dialogue: '/assets/characters/pixel/dialogue/shadow_omen.png', ui: '/assets/characters/pixel/ui/shadow_omen.png', fallback: '/assets/characters/pixel/full/shadow_omen.png', dialogueScale: 1.03, dialogueSideOffset: '0px', combatHeight: 2.24, uiCropMode: 'contain' },
    fallback_hero: { full: '/assets/characters/pixel/full/fallback_hero.png', dialogue: '/assets/characters/pixel/dialogue/fallback_hero.png', ui: '/assets/characters/pixel/ui/fallback_hero.png', fallback: '/assets/characters/pixel/full/fallback_hero.png', dialogueScale: 0.98, dialogueSideOffset: '0px', combatHeight: 2.08, uiCropMode: 'contain' },
  },
  visualProfiles: {
    alistair: { category: 'playable_hero', factionId: 'lion', rarity: 'unique', recruitTier: 'core', colorPalette: ['emerald', 'steel', 'gold'], silhouetteNotes: 'Frontline knight, wide defensive stance.' },
    marian: { category: 'playable_hero', factionId: 'lion', rarity: 'unique', recruitTier: 'core', colorPalette: ['white', 'gold', 'silver'], silhouetteNotes: 'Sacred cleric with staff and protective robes.' },
    elara: { category: 'playable_hero', factionId: 'lion', rarity: 'unique', recruitTier: 'core', colorPalette: ['arcane blue', 'cyan', 'gold'], silhouetteNotes: 'Arcane caster with pointed hat and glowing staff.' },
    kestrel: { category: 'playable_hero', factionId: 'lion', rarity: 'unique', recruitTier: 'core', colorPalette: ['forest green', 'leather brown', 'night blue'], silhouetteNotes: 'Mobile hooded archer.' },
    cedric: { category: 'playable_hero', factionId: 'neutral', rarity: 'unique', recruitTier: 'optional', colorPalette: ['sand', 'muted green', 'light leather'], silhouetteNotes: 'Nomad scout, lighter than Kestrel.' },
    alaric: { category: 'boss', factionId: 'lion', rarity: 'boss', colorPalette: ['royal blue', 'gold', 'ivory'], silhouetteNotes: 'Giant lion-chief boss, 2x2 board presence.' },
    maelor: { category: 'story_npc', factionId: 'lion', rarity: 'unique', colorPalette: ['dark gold', 'black', 'wine'], silhouetteNotes: 'Political steward, not a battle mage.' },
    villageoise: { category: 'story_npc', factionId: 'lion', rarity: 'unique', colorPalette: ['linen', 'brown', 'muted blue'], silhouetteNotes: 'Civilian villager silhouette for moral choices.' },
    refugee_mother: { category: 'story_npc', factionId: 'neutral', rarity: 'unique', colorPalette: ['earth', 'blue', 'wool'], silhouetteNotes: 'Protective refugee silhouette, non-combatant.' },
    wounded_merchant: { category: 'story_npc', factionId: 'neutral', rarity: 'unique', colorPalette: ['tan', 'green', 'leather'], silhouetteNotes: 'Injured merchant with travel gear.' },
    survivor: { category: 'story_npc', factionId: 'neutral', rarity: 'unique', colorPalette: ['ragged brown', 'grey'], silhouetteNotes: 'Road survivor, readable as vulnerable witness.' },
    chroniqueur: { category: 'story_npc', factionId: 'neutral', rarity: 'unique', colorPalette: ['deep blue', 'parchment', 'silver'], silhouetteNotes: 'Narrative chronicler with book and quill.' },
    serpent_elite_raider: { category: 'faction_enemy', factionId: 'serpent', rarity: 'elite', visualTier: 'elite', baseArchetype: 'light_raider', recolorFamily: 'serpent_unique', colorPalette: ['dark green', 'black', 'copper'], silhouetteNotes: 'Detailed duelist/ambusher reserved for elite or sub-boss encounters.' },
    serpent_elite_brute: { category: 'faction_enemy', factionId: 'serpent', rarity: 'elite', visualTier: 'elite', baseArchetype: 'heavy_guard', recolorFamily: 'serpent_unique', colorPalette: ['dark green', 'black', 'copper'], silhouetteNotes: 'Detailed heavy bruiser reserved for elite or sub-boss encounters.' },
    serpent_captain: { category: 'boss', factionId: 'serpent', rarity: 'boss', colorPalette: ['dark green', 'black', 'copper'], silhouetteNotes: 'Serpent commander, 2x2 board presence.' },
    lion_champion: { category: 'faction_enemy', factionId: 'lion', rarity: 'elite', colorPalette: ['royal blue', 'gold', 'ivory'], silhouetteNotes: 'Elite guard distinct from Alaric.' },
    seal_guardian: { category: 'faction_enemy', factionId: 'lion', rarity: 'elite', colorPalette: ['ivory', 'blue', 'gold'], silhouetteNotes: 'Mystical guardian of the seal.' },
    wolf: { category: 'monster', species: 'beast', rarity: 'generic', colorPalette: ['grey', 'charcoal'], silhouetteNotes: 'Low, fast quadruped.' },
    venom_serpent: { category: 'monster', species: 'serpent', rarity: 'generic', colorPalette: ['poison green', 'tan'], silhouetteNotes: 'Coiled venom beast.' },
    goblin: { category: 'monster', species: 'goblin', rarity: 'generic', colorPalette: ['green', 'leather brown'], silhouetteNotes: 'Small spear monster.' },
    skeleton: { category: 'monster', species: 'undead', rarity: 'generic', colorPalette: ['bone', 'rust', 'black'], silhouetteNotes: 'Undead warrior.' },
    troll: { category: 'elite_monster', species: 'troll', rarity: 'elite', colorPalette: ['moss green', 'stone grey'], silhouetteNotes: 'Large brute monster.' },
    young_wyrm: { category: 'elite_monster', species: 'dragon', rarity: 'elite', colorPalette: ['teal', 'cream'], silhouetteNotes: 'Young dragon/wyrm elite.' },
    undead_champion: { category: 'elite_monster', species: 'undead', rarity: 'elite', colorPalette: ['purple', 'black', 'bone'], silhouetteNotes: 'Armored undead champion.' },
    shrine_apparition: { category: 'story_npc', factionId: 'shadows', rarity: 'unique', colorPalette: ['ivory', 'gold', 'spectral light'], silhouetteNotes: 'Mystical apparition tied to ancient shrines.' },
    shadow_omen: { category: 'boss', factionId: 'shadows', species: 'omen', rarity: 'boss', colorPalette: ['black', 'violet', 'cyan'], silhouetteNotes: 'Major shadow omen silhouette, reserved for supernatural threats.' },
    fallback_hero: { category: 'playable_hero', factionId: 'neutral', rarity: 'unique', recruitTier: 'late', colorPalette: ['neutral'], silhouetteNotes: 'Fallback only; never used as a canonical hero.' },
  },
  dialogueActors: {
    alaric: '/assets/characters/pixel/dialogue/alaric.png',
    elara: '/assets/characters/pixel/dialogue/elara.png',
    maelor: '/assets/characters/pixel/dialogue/maelor.png',
    villageoise: '/assets/characters/pixel/dialogue/villageoise.png',
    refugee_mother: '/assets/characters/pixel/dialogue/refugee_mother.png',
    cedric: '/assets/characters/pixel/dialogue/cedric.png',
    wounded_merchant: '/assets/characters/pixel/dialogue/wounded_merchant.png',
    survivor: '/assets/characters/pixel/dialogue/survivor.png',
    serpent_elite_raider: '/assets/characters/pixel/dialogue/serpent_elite_raider.png',
    chroniqueur: '/assets/characters/pixel/dialogue/chroniqueur.png',
    shrine_apparition: '/assets/characters/pixel/dialogue/shrine_apparition.png',
    shadow_omen: '/assets/characters/pixel/dialogue/shadow_omen.png',
  },
  dialogueScenes: {
    camp_departure: '/assets/generated/lion-phase/dialogue/camp_departure.webp',
    lion_briefing: '/assets/generated/lion-phase/dialogue/lion_briefing.webp',
    refugee_trial: '/assets/generated/lion-phase/dialogue/refugee_trial.webp',
    reserve_trail: '/assets/generated/lion-phase/dialogue/reserve_trail.webp',
    village_choice: '/assets/generated/lion-phase/dialogue/village_choice.webp',
    mystery_recruit: '/assets/generated/lion-phase/dialogue/mystery_recruit.webp',
    mystery_help: '/assets/generated/lion-phase/dialogue/mystery_help.webp',
    mystery_ambush: '/assets/generated/lion-phase/dialogue/mystery_ambush.webp',
    mystery_treasure: '/assets/generated/lion-phase/dialogue/mystery_treasure.webp',
    mystery_shrine: '/assets/generated/lion-phase/dialogue/mystery_shrine.webp',
    witnesses_on_road: '/assets/generated/lion-phase/dialogue/witnesses_on_road.webp',
    shadow_signs: '/assets/generated/lion-phase/dialogue/shadow_signs.webp',
    lion_finale_judgement: '/assets/generated/lion-phase/dialogue/lion_finale_judgement.webp',
    epilogue: '/assets/generated/lion-phase/dialogue/epilogue.webp',
    lion_refuge: '/assets/generated/lion-phase/dialogue/lion_refuge.webp',
    forest_fork: '/assets/generated/lion-phase/dialogue/forest_fork.webp',
  },
  combatScenes: {
    forest_route: '/assets/generated/lion-phase/combat/forest_route.webp',
    bois_clair_burning: '/assets/generated/lion-phase/combat/bois_clair_burning.webp',
    lion_sanctum: '/assets/generated/lion-phase/combat/lion_sanctum.webp',
  },
  // Named per-screen background slots.
  screens: {
    title: {
      background: '/assets/generated/forest-pilot/forest-dawn-far.webp',
    },
    travel: {
      background: travelDefaultBackdrop,
      sky: travelDefaultBackdrop,
      mist: '/assets/generated/forest-pilot/forest-mid.webp',
      backdrops: {
        default: travelDefaultBackdrop,
        city: travelCityBackdrop,
        castle: travelCastleBackdrop,
      },
    },
    dialogue: {
      background: '/assets/generated/forest-pilot/forest-dawn-far.webp',
    },
    exploration: {
      background: '/assets/generated/forest-pilot/forest-dawn-far.webp',
    },
    management: {
      background: '/assets/generated/forest-pilot/forest-dawn-far.webp',
    },
    combat: {
      background: '/assets/generated/lion-phase/combat/forest_route.webp',
      forestRuinsBackdrop: '/assets/generated/combat-painted/forest-ruins-backdrop.png',
      sky: '/assets/generated/forest-pilot/forest-dawn-far.webp',
      distance: '/assets/generated/forest-pilot/forest-mid.webp',
      mist: '/assets/generated/forest-pilot/forest-fore.webp',
    },
  },
} as const;
