import type { VfxPreset, VfxStep } from './VfxTypes';

const PARTICLE_STEPS = new Set<VfxStep['type']>([
  'particleBurst',
  'projectile',
  'smokePuff',
  'sparkleBurst',
]);

function premiumPreset(definition: Omit<VfxPreset, 'particleBudget'>): VfxPreset {
  return {
    ...definition,
    particleBudget: definition.steps.reduce(
      (total, step) => total + (PARTICLE_STEPS.has(step.type) ? (step.count ?? 1) : 0),
      0,
    ),
  };
}

/**
 * Presentation data only. These presets deliberately use the existing VfxSystem
 * primitives so the premium pass stays compatible with fixed sprites, the
 * tactical grid and reduced graphics mode.
 */
export const PREMIUM_VFX_PRESETS = [
  premiumPreset({
    id: 'ultimate_lion_surge',
    label: 'Ruée du Lion',
    duration: 1.02,
    impactTime: 0.42,
    tags: ['hero', 'ultimate', 'physical', 'golden', 'line'],
    reducedGraphicsScale: 0.45,
    steps: [
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.42, color: '#ffe39a', secondaryColor: '#c98a26', scale: 1.34, opacity: 0.56, rotation: 0.35, reducedGraphicsMultiplier: 0.62 },
      { type: 'lightPulse', anchor: 'source', texture: 'magicGlow', startTime: 0.05, duration: 0.4, color: '#ffd86a', scale: 1.5, opacity: 0.56, reducedGraphicsMultiplier: 0.62 },
      { type: 'slashArc', anchor: 'target', texture: 'slashArc', startTime: 0.3, duration: 0.38, color: '#fffbdc', secondaryColor: '#e8a733', scale: 2.22, opacity: 1, rotation: -0.42 },
      { type: 'shockwave', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.36, duration: 0.48, color: '#ffe8a1', secondaryColor: '#a55d22', scale: 1.72, radius: 1.22, count: 5, opacity: 0.78, reducedGraphicsMultiplier: 0.5 },
      { type: 'particleBurst', anchor: 'target', texture: 'sparkle', startTime: 0.36, duration: 0.52, color: '#fffce7', secondaryColor: '#efb847', scale: 0.2, count: 18, speed: 1.58, rise: 0.76, spread: 1.35, opacity: 0.95, reducedGraphicsMultiplier: 0.48 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.36, duration: 0.28, color: '#ffffff', secondaryColor: '#ffc64f', scale: 1.68, opacity: 1 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.37, duration: 0.14, color: '#ffe5a0', opacity: 0.16, reducedGraphicsMultiplier: 0.52 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.37, duration: 0.3, scale: 0.48, reducedGraphicsMultiplier: 0.48 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.38, duration: 0.1 },
    ],
  }),
  premiumPreset({
    id: 'ultimate_radiant_judgement',
    label: 'Jugement radiant',
    duration: 1.14,
    impactTime: 0.5,
    tags: ['hero', 'ultimate', 'sacred', 'hybrid', 'area'],
    reducedGraphicsScale: 0.46,
    steps: [
      { type: 'magicCircle', anchor: 'groundTarget', texture: 'magicCircle', startTime: 0, duration: 0.78, color: '#fff4bd', secondaryColor: '#75d9ff', scale: 1.72, opacity: 0.62, rotation: -0.52, reducedGraphicsMultiplier: 0.62 },
      { type: 'groundRing', anchor: 'groundTarget', texture: 'ringGradient', startTime: 0.16, duration: 0.78, color: '#fff8d7', secondaryColor: '#7fdcff', scale: 1.9, radius: 1.35, opacity: 0.72, reducedGraphicsMultiplier: 0.58 },
      { type: 'lightPulse', anchor: 'allTargets', texture: 'magicGlow', startTime: 0.28, duration: 0.64, color: '#fff4b0', secondaryColor: '#9de7ff', scale: 1.48, opacity: 0.52, reducedGraphicsMultiplier: 0.58 },
      { type: 'sparkleBurst', anchor: 'allTargets', texture: 'sparkle', startTime: 0.34, duration: 0.64, color: '#fffce8', secondaryColor: '#8edfff', scale: 0.15, count: 6, speed: 0.82, rise: 1.52, spread: 0.66, opacity: 0.92, reducedGraphicsMultiplier: 0.42 },
      { type: 'shockwave', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.44, duration: 0.48, color: '#ffeaa2', secondaryColor: '#6bbce5', scale: 1.62, radius: 1.16, count: 4, opacity: 0.66, reducedGraphicsMultiplier: 0.5 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.44, duration: 0.3, color: '#ffffff', secondaryColor: '#ffd764', scale: 1.54, opacity: 0.92 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.45, duration: 0.16, color: '#fff2b3', opacity: 0.17, reducedGraphicsMultiplier: 0.5 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.46, duration: 0.28, scale: 0.4, reducedGraphicsMultiplier: 0.46 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.46, duration: 0.09 },
    ],
  }),
  premiumPreset({
    id: 'ultimate_devouring_eclipse',
    label: 'Éclipse dévorante',
    duration: 1.14,
    impactTime: 0.5,
    tags: ['hero', 'ultimate', 'dark', 'drain', 'area'],
    reducedGraphicsScale: 0.42,
    steps: [
      { type: 'magicCircle', anchor: 'groundTarget', texture: 'magicCircle', startTime: 0, duration: 0.82, color: '#7a48bd', secondaryColor: '#27bed0', scale: 1.82, opacity: 0.6, rotation: 0.74, reducedGraphicsMultiplier: 0.58 },
      { type: 'groundRing', anchor: 'groundTarget', texture: 'ringGradient', startTime: 0.14, duration: 0.82, color: '#3a174f', secondaryColor: '#39d4d5', scale: 1.92, radius: 1.42, opacity: 0.7, reducedGraphicsMultiplier: 0.52 },
      { type: 'smokePuff', anchor: 'groundTarget', texture: 'smokePuff', startTime: 0.25, duration: 0.7, color: '#281530', secondaryColor: '#5a2a73', scale: 0.42, count: 7, speed: 0.45, rise: 0.68, spread: 1.35, opacity: 0.4, blending: 'normal', reducedGraphicsMultiplier: 0.35 },
      { type: 'particleBurst', anchor: 'allTargets', texture: 'softParticle', startTime: 0.36, duration: 0.58, color: '#b66dff', secondaryColor: '#46d8d4', scale: 0.16, count: 5, speed: 1.05, rise: 0.92, spread: 0.82, opacity: 0.82, reducedGraphicsMultiplier: 0.42 },
      { type: 'projectile', anchor: 'target', targetAnchor: 'source', texture: 'projectileCore', startTime: 0.47, duration: 0.35, color: '#7f55c8', secondaryColor: '#4de1d0', scale: 0.24, count: 5, opacity: 0.82, heightOffset: 0.3, reducedGraphicsMultiplier: 0.4 },
      { type: 'shockwave', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.43, duration: 0.48, color: '#9658d2', secondaryColor: '#1c8492', scale: 1.64, radius: 1.18, count: 4, opacity: 0.68, reducedGraphicsMultiplier: 0.46 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.44, duration: 0.16, color: '#7a45a8', opacity: 0.13, reducedGraphicsMultiplier: 0.48 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.45, duration: 0.3, scale: 0.42, reducedGraphicsMultiplier: 0.45 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.45, duration: 0.1 },
    ],
  }),
  premiumPreset({
    id: 'ultimate_firmament_lance',
    label: 'Lance du firmament',
    duration: 1.04,
    impactTime: 0.56,
    tags: ['hero', 'ultimate', 'piercing', 'anti-boss', 'line'],
    reducedGraphicsScale: 0.45,
    steps: [
      { type: 'spriteSheet', anchor: 'target', spriteSheet: 'thrust_line', startTime: 0.32, duration: 0.58, scale: 1.82, opacity: 1, blending: 'normal', reducedGraphicsMultiplier: 0.72 },
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.46, color: '#9adfff', secondaryColor: '#f5d47c', scale: 1.26, opacity: 0.52, rotation: 0.45, reducedGraphicsMultiplier: 0.6 },
      { type: 'lightPulse', anchor: 'source', texture: 'magicGlow', startTime: 0.05, duration: 0.44, color: '#b6ecff', secondaryColor: '#ffe08b', scale: 1.48, opacity: 0.56, reducedGraphicsMultiplier: 0.62 },
      { type: 'projectile', anchor: 'source', targetAnchor: 'target', texture: 'projectileCore', startTime: 0.18, duration: 0.38, color: '#f7fdff', secondaryColor: '#55cfff', scale: 0.32, count: 14, opacity: 1, heightOffset: 0.28, reducedGraphicsMultiplier: 0.46 },
      { type: 'slashArc', anchor: 'target', texture: 'slashArc', startTime: 0.5, duration: 0.32, color: '#ffffff', secondaryColor: '#73d8ff', scale: 2.05, opacity: 0.96, rotation: -1.12 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.51, duration: 0.27, color: '#ffffff', secondaryColor: '#6ddaff', scale: 1.72, opacity: 1 },
      { type: 'shockwave', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.52, duration: 0.4, color: '#d8f7ff', secondaryColor: '#3f97c7', scale: 1.38, radius: 1.02, count: 3, opacity: 0.62, reducedGraphicsMultiplier: 0.5 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.52, duration: 0.14, color: '#dff8ff', opacity: 0.16, reducedGraphicsMultiplier: 0.52 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.52, duration: 0.28, scale: 0.46, reducedGraphicsMultiplier: 0.46 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.53, duration: 0.11 },
    ],
  }),
  premiumPreset({
    id: 'ultimate_dark_meteor',
    label: 'Météore noir',
    duration: 1.2,
    impactTime: 0.62,
    tags: ['hero', 'ultimate', 'dark', 'fire', 'area'],
    reducedGraphicsScale: 0.4,
    steps: [
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.5, color: '#8d55cf', secondaryColor: '#ff7b3f', scale: 1.46, opacity: 0.58, rotation: -0.65, reducedGraphicsMultiplier: 0.58 },
      { type: 'lightPulse', anchor: 'source', texture: 'magicGlow', startTime: 0.06, duration: 0.48, color: '#9f62e5', secondaryColor: '#ff8c45', scale: 1.62, opacity: 0.52, reducedGraphicsMultiplier: 0.56 },
      { type: 'projectile', anchor: 'source', targetAnchor: 'groundTarget', texture: 'projectileCore', startTime: 0.16, duration: 0.46, color: '#dfb4ff', secondaryColor: '#ff6035', scale: 0.46, count: 12, opacity: 1, heightOffset: 0.88, reducedGraphicsMultiplier: 0.42 },
      { type: 'shockwave', anchor: 'groundTarget', texture: 'ringGradient', startTime: 0.56, duration: 0.54, color: '#d18dff', secondaryColor: '#ff713f', scale: 2.05, radius: 1.46, count: 6, opacity: 0.8, reducedGraphicsMultiplier: 0.45 },
      { type: 'particleBurst', anchor: 'groundTarget', texture: 'softParticle', startTime: 0.56, duration: 0.6, color: '#d99cff', secondaryColor: '#ff653a', scale: 0.24, count: 22, speed: 1.68, rise: 1.02, spread: 1.78, opacity: 0.92, reducedGraphicsMultiplier: 0.4 },
      { type: 'smokePuff', anchor: 'groundTarget', texture: 'smokePuff', startTime: 0.61, duration: 0.56, color: '#332238', secondaryColor: '#703734', scale: 0.46, count: 6, speed: 0.5, rise: 0.8, spread: 1.15, opacity: 0.42, blending: 'normal', reducedGraphicsMultiplier: 0.32 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.56, duration: 0.3, color: '#fff0cf', secondaryColor: '#b86bea', scale: 1.84, opacity: 0.96 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.57, duration: 0.17, color: '#b064d4', opacity: 0.15, reducedGraphicsMultiplier: 0.44 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.57, duration: 0.42, scale: 0.58, reducedGraphicsMultiplier: 0.42 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.58, duration: 0.11 },
    ],
  }),
  premiumPreset({
    id: 'ultimate_miracle',
    label: 'Miracle',
    duration: 1.18,
    impactTime: 0.48,
    tags: ['hero', 'ultimate', 'heal', 'revive', 'support'],
    reducedGraphicsScale: 0.5,
    steps: [
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.92, color: '#fff1b3', secondaryColor: '#9de9ff', scale: 1.7, opacity: 0.58, rotation: 0.62, reducedGraphicsMultiplier: 0.66 },
      { type: 'groundRing', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.1, duration: 0.92, color: '#e9ffd2', secondaryColor: '#f8d886', scale: 1.65, radius: 1.16, opacity: 0.74, reducedGraphicsMultiplier: 0.66 },
      { type: 'sparkleBurst', anchor: 'allTargets', texture: 'sparkle', startTime: 0.2, duration: 0.84, color: '#ffffff', secondaryColor: '#b8f1c5', scale: 0.18, count: 8, speed: 0.74, rise: 1.85, spread: 0.72, opacity: 0.98, reducedGraphicsMultiplier: 0.5 },
      { type: 'lightPulse', anchor: 'allTargets', texture: 'magicGlow', startTime: 0.28, duration: 0.68, color: '#f7ffd9', secondaryColor: '#ffd978', scale: 1.72, opacity: 0.58, reducedGraphicsMultiplier: 0.62 },
      { type: 'particleBurst', anchor: 'allTargets', texture: 'softParticle', startTime: 0.38, duration: 0.56, color: '#e8ffd8', secondaryColor: '#f3d06b', scale: 0.13, count: 4, speed: 0.58, rise: 1.12, spread: 0.58, opacity: 0.8, reducedGraphicsMultiplier: 0.46 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.42, duration: 0.19, color: '#fff7d0', opacity: 0.16, reducedGraphicsMultiplier: 0.58 },
    ],
  }),
  premiumPreset({
    id: 'ultimate_perfect_duality',
    label: 'Dualité parfaite',
    duration: 1.12,
    impactTime: 0.48,
    tags: ['hero', 'ultimate', 'hybrid', 'light', 'shadow'],
    reducedGraphicsScale: 0.44,
    steps: [
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.82, color: '#d95362', secondaryColor: '#ffd77a', scale: 1.66, opacity: 0.58, rotation: -0.66, reducedGraphicsMultiplier: 0.6 },
      { type: 'groundRing', anchor: 'groundTarget', texture: 'ringGradient', startTime: 0.12, duration: 0.82, color: '#77304f', secondaryColor: '#ffe095', scale: 1.82, radius: 1.34, opacity: 0.68, reducedGraphicsMultiplier: 0.54 },
      { type: 'particleBurst', anchor: 'allTargets', texture: 'softParticle', startTime: 0.3, duration: 0.62, color: '#e45766', secondaryColor: '#ffe49e', scale: 0.15, count: 7, speed: 1.0, rise: 1.08, spread: 0.78, opacity: 0.9, reducedGraphicsMultiplier: 0.43 },
      { type: 'sparkleBurst', anchor: 'allTargets', texture: 'sparkle', startTime: 0.32, duration: 0.64, color: '#fff5d0', secondaryColor: '#c8496d', scale: 0.14, count: 6, speed: 0.75, rise: 1.48, spread: 0.68, opacity: 0.9, reducedGraphicsMultiplier: 0.44 },
      { type: 'shockwave', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.42, duration: 0.46, color: '#ef6372', secondaryColor: '#ffd66b', scale: 1.55, radius: 1.12, count: 4, opacity: 0.7, reducedGraphicsMultiplier: 0.48 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.42, duration: 0.28, color: '#fff7d6', secondaryColor: '#d34a67', scale: 1.52, opacity: 0.94 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.43, duration: 0.15, color: '#f3b17e', opacity: 0.14, reducedGraphicsMultiplier: 0.5 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.43, duration: 0.28, scale: 0.38, reducedGraphicsMultiplier: 0.45 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.44, duration: 0.08 },
    ],
  }),
  premiumPreset({
    id: 'ultimate_absolute_harmony',
    label: 'Harmonie absolue',
    duration: 1.16,
    impactTime: 0.46,
    tags: ['hero', 'ultimate', 'team', 'aura', 'barrier'],
    reducedGraphicsScale: 0.5,
    steps: [
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.94, color: '#8ee7dc', secondaryColor: '#f6d77c', scale: 1.75, opacity: 0.58, rotation: 0.48, reducedGraphicsMultiplier: 0.68 },
      { type: 'groundRing', anchor: 'sourceGround', texture: 'ringGradient', startTime: 0.08, duration: 0.94, color: '#aaf4e6', secondaryColor: '#f7dda0', scale: 2.05, radius: 1.45, opacity: 0.68, reducedGraphicsMultiplier: 0.64 },
      { type: 'lightPulse', anchor: 'allTargets', texture: 'magicGlow', startTime: 0.24, duration: 0.72, color: '#c6fff2', secondaryColor: '#ffe39d', scale: 1.5, opacity: 0.5, reducedGraphicsMultiplier: 0.62 },
      { type: 'sparkleBurst', anchor: 'allTargets', texture: 'sparkle', startTime: 0.28, duration: 0.76, color: '#eafff7', secondaryColor: '#f8d879', scale: 0.14, count: 6, speed: 0.7, rise: 1.55, spread: 0.62, opacity: 0.88, reducedGraphicsMultiplier: 0.48 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.4, duration: 0.17, color: '#d7fff4', opacity: 0.12, reducedGraphicsMultiplier: 0.58 },
    ],
  }),
  premiumPreset({
    id: 'ultimate_zenith_arrow',
    label: 'Flèche du zénith',
    duration: 0.98,
    impactTime: 0.54,
    tags: ['hero', 'ultimate', 'ranged', 'piercing', 'critical'],
    reducedGraphicsScale: 0.45,
    steps: [
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.43, color: '#c8f1ff', secondaryColor: '#ffd76a', scale: 1.18, opacity: 0.5, rotation: 0.34, reducedGraphicsMultiplier: 0.62 },
      { type: 'lightPulse', anchor: 'source', texture: 'magicGlow', startTime: 0.04, duration: 0.43, color: '#dcf7ff', secondaryColor: '#ffe27d', scale: 1.38, opacity: 0.56, reducedGraphicsMultiplier: 0.6 },
      { type: 'projectile', anchor: 'source', targetAnchor: 'target', texture: 'projectileCore', startTime: 0.16, duration: 0.38, color: '#ffffff', secondaryColor: '#5ed8ff', scale: 0.29, count: 16, opacity: 1, heightOffset: 0.3, reducedGraphicsMultiplier: 0.45 },
      { type: 'slashArc', anchor: 'target', texture: 'slashArc', startTime: 0.5, duration: 0.28, color: '#ffffff', secondaryColor: '#ffd35d', scale: 1.72, opacity: 0.94, rotation: -1.24 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.5, duration: 0.26, color: '#ffffff', secondaryColor: '#6edfff', scale: 1.86, opacity: 1 },
      { type: 'particleBurst', anchor: 'target', texture: 'sparkle', startTime: 0.5, duration: 0.42, color: '#e9fbff', secondaryColor: '#ffd65f', scale: 0.16, count: 12, speed: 1.65, rise: 0.68, spread: 1.05, opacity: 0.96, reducedGraphicsMultiplier: 0.45 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.51, duration: 0.13, color: '#e9fbff', opacity: 0.16, reducedGraphicsMultiplier: 0.52 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.51, duration: 0.25, scale: 0.43, reducedGraphicsMultiplier: 0.46 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.52, duration: 0.11 },
    ],
  }),
  premiumPreset({
    id: 'ultimate_silent_assassin',
    label: 'Assassin silencieux',
    duration: 0.92,
    impactTime: 0.34,
    tags: ['hero', 'ultimate', 'execution', 'shadow', 'poison'],
    reducedGraphicsScale: 0.42,
    steps: [
      { type: 'spriteSheet', anchor: 'sourceGround', spriteSheet: 'teleport_burst', startTime: 0, duration: 0.54, scale: 1.46, opacity: 1, blending: 'normal', reducedGraphicsMultiplier: 0.72 },
      { type: 'smokePuff', anchor: 'sourceGround', texture: 'smokePuff', startTime: 0, duration: 0.48, color: '#15151d', secondaryColor: '#44254f', scale: 0.38, count: 8, speed: 0.4, rise: 0.7, spread: 0.86, opacity: 0.52, blending: 'normal', reducedGraphicsMultiplier: 0.38 },
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.34, color: '#693b80', secondaryColor: '#67d497', scale: 1.12, opacity: 0.45, rotation: -0.62, reducedGraphicsMultiplier: 0.54 },
      { type: 'slashArc', anchor: 'target', texture: 'slashArc', startTime: 0.25, duration: 0.3, color: '#f5f2ff', secondaryColor: '#8b55ba', scale: 1.82, opacity: 1, rotation: -0.7 },
      { type: 'slashArc', anchor: 'target', texture: 'slashArc', startTime: 0.3, duration: 0.3, color: '#b9ffd7', secondaryColor: '#7250a0', scale: 1.64, opacity: 0.9, rotation: 0.7 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.28, duration: 0.45, color: '#8df0ad', secondaryColor: '#b970e2', scale: 0.16, count: 16, speed: 1.5, rise: 0.72, spread: 1.12, opacity: 0.92, reducedGraphicsMultiplier: 0.42 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.28, duration: 0.23, color: '#ffffff', secondaryColor: '#7ed89b', scale: 1.58, opacity: 1 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.29, duration: 0.11, color: '#8e59aa', opacity: 0.13, reducedGraphicsMultiplier: 0.46 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.29, duration: 0.22, scale: 0.42, reducedGraphicsMultiplier: 0.44 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.29, duration: 0.115 },
    ],
  }),
  premiumPreset({
    id: 'ultimate_fault_breaker',
    label: 'Briseur de faille',
    duration: 1.0,
    impactTime: 0.42,
    tags: ['hero', 'ultimate', 'physical', 'shatter', 'dispel'],
    reducedGraphicsScale: 0.44,
    steps: [
      { type: 'magicCircle', anchor: 'targetGround', texture: 'magicCircle', startTime: 0, duration: 0.52, color: '#f0c365', secondaryColor: '#62d7dc', scale: 1.35, opacity: 0.5, rotation: 0.8, reducedGraphicsMultiplier: 0.58 },
      { type: 'slashArc', anchor: 'target', texture: 'slashArc', startTime: 0.28, duration: 0.34, color: '#fff8db', secondaryColor: '#61dce2', scale: 1.86, opacity: 0.96, rotation: -0.48 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.34, duration: 0.29, color: '#ffffff', secondaryColor: '#5ad6da', scale: 1.82, opacity: 1 },
      { type: 'sparkleBurst', anchor: 'target', texture: 'sparkle', startTime: 0.35, duration: 0.52, color: '#fff0a4', secondaryColor: '#70e0e5', scale: 0.18, count: 18, speed: 1.48, rise: 0.9, spread: 1.32, opacity: 0.96, reducedGraphicsMultiplier: 0.44 },
      { type: 'shockwave', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.36, duration: 0.46, color: '#f3cf72', secondaryColor: '#3b9fa5', scale: 1.5, radius: 1.06, count: 5, opacity: 0.7, reducedGraphicsMultiplier: 0.48 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.36, duration: 0.14, color: '#e7fbef', opacity: 0.15, reducedGraphicsMultiplier: 0.5 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.36, duration: 0.28, scale: 0.46, reducedGraphicsMultiplier: 0.45 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.37, duration: 0.1 },
    ],
  }),
  premiumPreset({
    id: 'ultimate_artillery_barrage',
    label: 'Barrage d’artillerie',
    duration: 0.94,
    impactTime: 0.42,
    tags: ['hero', 'ultimate', 'ranged', 'fire', 'multi-impact'],
    reducedGraphicsScale: 0.4,
    steps: [
      { type: 'magicCircle', anchor: 'groundTarget', texture: 'magicCircle', startTime: 0, duration: 0.54, color: '#e9b55f', secondaryColor: '#df4f32', scale: 1.42, opacity: 0.46, rotation: 0.65, reducedGraphicsMultiplier: 0.55 },
      { type: 'projectile', anchor: 'source', targetAnchor: 'groundTarget', texture: 'projectileCore', startTime: 0.08, duration: 0.34, color: '#fff0b8', secondaryColor: '#ff5635', scale: 0.3, count: 7, opacity: 0.96, heightOffset: 0.74, reducedGraphicsMultiplier: 0.38 },
      { type: 'shockwave', anchor: 'groundTarget', texture: 'ringGradient', startTime: 0.36, duration: 0.45, color: '#ffbf68', secondaryColor: '#9b3329', scale: 1.62, radius: 1.16, count: 4, opacity: 0.72, reducedGraphicsMultiplier: 0.44 },
      { type: 'particleBurst', anchor: 'groundTarget', texture: 'softParticle', startTime: 0.36, duration: 0.5, color: '#ffe0a2', secondaryColor: '#ff4d30', scale: 0.2, count: 17, speed: 1.58, rise: 0.9, spread: 1.36, opacity: 0.9, reducedGraphicsMultiplier: 0.38 },
      { type: 'smokePuff', anchor: 'groundTarget', texture: 'smokePuff', startTime: 0.4, duration: 0.48, color: '#493631', scale: 0.39, count: 4, speed: 0.42, rise: 0.72, spread: 0.76, opacity: 0.38, blending: 'normal', reducedGraphicsMultiplier: 0.3 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.36, duration: 0.25, color: '#fff4c6', secondaryColor: '#ff623b', scale: 1.48, opacity: 0.95 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.37, duration: 0.12, color: '#ffb25f', opacity: 0.12, reducedGraphicsMultiplier: 0.42 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.37, duration: 0.26, scale: 0.43, reducedGraphicsMultiplier: 0.4 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.37, duration: 0.075 },
    ],
  }),
  premiumPreset({
    id: 'enemy_dragon_breath',
    label: 'Souffle draconique',
    duration: 0.84,
    impactTime: 0.46,
    tags: ['enemy', 'fire', 'breath', 'cone'],
    reducedGraphicsScale: 0.42,
    steps: [
      { type: 'lightPulse', anchor: 'source', texture: 'magicGlow', startTime: 0, duration: 0.36, color: '#ffb256', secondaryColor: '#ff5133', scale: 1.24, opacity: 0.5, reducedGraphicsMultiplier: 0.58 },
      { type: 'projectile', anchor: 'source', targetAnchor: 'groundTarget', texture: 'projectileCore', startTime: 0.1, duration: 0.36, color: '#ffd37e', secondaryColor: '#ff3e28', scale: 0.42, count: 14, opacity: 0.88, heightOffset: 0.44, reducedGraphicsMultiplier: 0.4 },
      { type: 'particleBurst', anchor: 'groundTarget', texture: 'softParticle', startTime: 0.4, duration: 0.4, color: '#ffc36c', secondaryColor: '#ed3d2a', scale: 0.2, count: 16, speed: 1.48, rise: 0.76, spread: 1.42, opacity: 0.88, reducedGraphicsMultiplier: 0.4 },
      { type: 'smokePuff', anchor: 'groundTarget', texture: 'smokePuff', startTime: 0.43, duration: 0.39, color: '#493431', scale: 0.36, count: 4, speed: 0.43, rise: 0.67, spread: 0.76, opacity: 0.34, blending: 'normal', reducedGraphicsMultiplier: 0.32 },
      { type: 'shockwave', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.4, duration: 0.36, color: '#ffb25f', secondaryColor: '#8b2e26', scale: 1.32, radius: 0.96, count: 3, opacity: 0.62, reducedGraphicsMultiplier: 0.45 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.41, duration: 0.12, color: '#ff984d', opacity: 0.12, reducedGraphicsMultiplier: 0.46 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.41, duration: 0.22, scale: 0.32, reducedGraphicsMultiplier: 0.44 },
    ],
  }),
  premiumPreset({
    id: 'boss_apocalypse',
    label: 'Apocalypse',
    duration: 1.3,
    impactTime: 0.63,
    tags: ['boss', 'signature', 'dark', 'catastrophe', 'area'],
    reducedGraphicsScale: 0.38,
    steps: [
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.68, color: '#8b4bb7', secondaryColor: '#db5c3b', scale: 2.05, opacity: 0.56, rotation: -0.74, reducedGraphicsMultiplier: 0.52 },
      { type: 'magicCircle', anchor: 'groundTarget', texture: 'magicCircle', startTime: 0.08, duration: 0.86, color: '#5c2a75', secondaryColor: '#e0623e', scale: 2.25, opacity: 0.5, rotation: 0.7, reducedGraphicsMultiplier: 0.48 },
      { type: 'shockwave', anchor: 'groundTarget', texture: 'ringGradient', startTime: 0.55, duration: 0.66, color: '#c978e0', secondaryColor: '#e35e3a', scale: 2.35, radius: 1.72, count: 7, opacity: 0.75, reducedGraphicsMultiplier: 0.42 },
      { type: 'particleBurst', anchor: 'groundTarget', texture: 'softParticle', startTime: 0.56, duration: 0.68, color: '#d68bef', secondaryColor: '#ef6940', scale: 0.25, count: 24, speed: 1.72, rise: 1.04, spread: 2.05, opacity: 0.86, reducedGraphicsMultiplier: 0.34 },
      { type: 'smokePuff', anchor: 'groundTarget', texture: 'smokePuff', startTime: 0.6, duration: 0.66, color: '#2d2031', secondaryColor: '#643432', scale: 0.5, count: 7, speed: 0.47, rise: 0.88, spread: 1.28, opacity: 0.4, blending: 'normal', reducedGraphicsMultiplier: 0.28 },
      { type: 'sparkleBurst', anchor: 'allTargets', texture: 'sparkle', startTime: 0.58, duration: 0.62, color: '#bf72dc', secondaryColor: '#ff8151', scale: 0.16, count: 4, speed: 0.9, rise: 1.1, spread: 0.8, opacity: 0.78, reducedGraphicsMultiplier: 0.34 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.56, duration: 0.18, color: '#8d4ea7', opacity: 0.17, reducedGraphicsMultiplier: 0.42 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.56, duration: 0.58, scale: 0.72, reducedGraphicsMultiplier: 0.38 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.58, duration: 0.12 },
    ],
  }),
  premiumPreset({
    id: 'boss_execution',
    label: 'Exécution',
    duration: 1.08,
    impactTime: 0.5,
    tags: ['boss', 'signature', 'physical', 'execution'],
    reducedGraphicsScale: 0.42,
    steps: [
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.46, color: '#9a2d2d', secondaryColor: '#e0a55a', scale: 1.72, opacity: 0.45, rotation: 0.38, reducedGraphicsMultiplier: 0.54 },
      { type: 'slashArc', anchor: 'target', texture: 'slashArc', startTime: 0.36, duration: 0.4, color: '#fff3d2', secondaryColor: '#be3c32', scale: 2.42, opacity: 1, rotation: -0.52 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.44, duration: 0.3, color: '#ffffff', secondaryColor: '#d64b34', scale: 1.92, opacity: 1 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.44, duration: 0.52, color: '#ffe0a7', secondaryColor: '#c63c32', scale: 0.21, count: 22, speed: 1.7, rise: 0.72, spread: 1.42, opacity: 0.92, reducedGraphicsMultiplier: 0.4 },
      { type: 'shockwave', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.45, duration: 0.46, color: '#e6b060', secondaryColor: '#7a2c2a', scale: 1.62, radius: 1.16, count: 5, opacity: 0.72, reducedGraphicsMultiplier: 0.44 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.45, duration: 0.14, color: '#e5a25c', opacity: 0.16, reducedGraphicsMultiplier: 0.45 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.45, duration: 0.36, scale: 0.62, reducedGraphicsMultiplier: 0.4 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.46, duration: 0.12 },
    ],
  }),
  premiumPreset({
    id: 'boss_flurry',
    label: 'Déluge de lames',
    duration: 1.12,
    impactTime: 0.42,
    tags: ['boss', 'signature', 'physical', 'multi-hit'],
    reducedGraphicsScale: 0.4,
    steps: [
      { type: 'slashArc', anchor: 'target', texture: 'slashArc', startTime: 0.22, duration: 0.3, color: '#f8ffe8', secondaryColor: '#65d595', scale: 1.68, opacity: 0.9, rotation: -0.72 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.28, duration: 0.22, color: '#ffffff', secondaryColor: '#71d99a', scale: 1.18, opacity: 0.9 },
      { type: 'slashArc', anchor: 'target', texture: 'slashArc', startTime: 0.38, duration: 0.3, color: '#fff5d4', secondaryColor: '#d6a34e', scale: 1.82, opacity: 0.94, rotation: 0.7 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.44, duration: 0.22, color: '#ffffff', secondaryColor: '#e1b45b', scale: 1.26, opacity: 0.94 },
      { type: 'slashArc', anchor: 'target', texture: 'slashArc', startTime: 0.55, duration: 0.36, color: '#ffffff', secondaryColor: '#d54a3d', scale: 2.12, opacity: 1, rotation: -0.18 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.61, duration: 0.27, color: '#ffffff', secondaryColor: '#e14f3f', scale: 1.62, opacity: 1 },
      { type: 'particleBurst', anchor: 'target', texture: 'sparkle', startTime: 0.28, duration: 0.62, color: '#e7ffed', secondaryColor: '#f0b75a', scale: 0.16, count: 18, speed: 1.48, rise: 0.75, spread: 1.2, opacity: 0.9, reducedGraphicsMultiplier: 0.36 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.61, duration: 0.13, color: '#f5cf82', opacity: 0.14, reducedGraphicsMultiplier: 0.42 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.61, duration: 0.32, scale: 0.52, reducedGraphicsMultiplier: 0.4 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.62, duration: 0.1 },
    ],
  }),
  premiumPreset({
    id: 'boss_inferno',
    label: 'Inferno',
    duration: 1.22,
    impactTime: 0.6,
    tags: ['boss', 'signature', 'fire', 'area'],
    reducedGraphicsScale: 0.38,
    steps: [
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.62, color: '#ffae4f', secondaryColor: '#d9322c', scale: 1.9, opacity: 0.56, rotation: 0.72, reducedGraphicsMultiplier: 0.52 },
      { type: 'magicCircle', anchor: 'groundTarget', texture: 'magicCircle', startTime: 0.1, duration: 0.72, color: '#e85e34', secondaryColor: '#ffbf5f', scale: 2.1, opacity: 0.48, rotation: -0.68, reducedGraphicsMultiplier: 0.48 },
      { type: 'shockwave', anchor: 'groundTarget', texture: 'ringGradient', startTime: 0.53, duration: 0.58, color: '#ffc36b', secondaryColor: '#b62f28', scale: 2.15, radius: 1.55, count: 6, opacity: 0.78, reducedGraphicsMultiplier: 0.42 },
      { type: 'particleBurst', anchor: 'groundTarget', texture: 'softParticle', startTime: 0.54, duration: 0.62, color: '#ffe09a', secondaryColor: '#f3462e', scale: 0.25, count: 25, speed: 1.8, rise: 1.1, spread: 1.82, opacity: 0.92, reducedGraphicsMultiplier: 0.36 },
      { type: 'smokePuff', anchor: 'groundTarget', texture: 'smokePuff', startTime: 0.59, duration: 0.6, color: '#49322d', scale: 0.48, count: 7, speed: 0.48, rise: 0.86, spread: 1.22, opacity: 0.4, blending: 'normal', reducedGraphicsMultiplier: 0.28 },
      { type: 'sparkleBurst', anchor: 'allTargets', texture: 'sparkle', startTime: 0.58, duration: 0.52, color: '#ffd36e', secondaryColor: '#ff5c38', scale: 0.15, count: 4, speed: 0.95, rise: 1.05, spread: 0.75, opacity: 0.76, reducedGraphicsMultiplier: 0.34 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.55, duration: 0.17, color: '#ff9a4c', opacity: 0.17, reducedGraphicsMultiplier: 0.42 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.55, duration: 0.48, scale: 0.68, reducedGraphicsMultiplier: 0.38 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.57, duration: 0.11 },
    ],
  }),
  premiumPreset({
    id: 'boss_titan_slam',
    label: 'Frappe du titan',
    duration: 1.26,
    impactTime: 0.56,
    tags: ['boss', 'signature', 'physical', 'ground', 'massive'],
    reducedGraphicsScale: 0.38,
    steps: [
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.56, color: '#bd7d4a', secondaryColor: '#efd187', scale: 2.05, opacity: 0.44, rotation: 0.4, reducedGraphicsMultiplier: 0.5 },
      { type: 'shockwave', anchor: 'groundTarget', texture: 'ringGradient', startTime: 0.48, duration: 0.68, color: '#f1cf88', secondaryColor: '#71432e', scale: 2.42, radius: 1.75, count: 8, opacity: 0.82, reducedGraphicsMultiplier: 0.42 },
      { type: 'groundRing', anchor: 'groundTarget', texture: 'ringGradient', startTime: 0.51, duration: 0.66, color: '#ffe5a3', secondaryColor: '#81503a', scale: 2.15, radius: 1.58, opacity: 0.62, reducedGraphicsMultiplier: 0.46 },
      { type: 'particleBurst', anchor: 'groundTarget', texture: 'softParticle', startTime: 0.5, duration: 0.68, color: '#edc57d', secondaryColor: '#72513b', scale: 0.28, count: 25, speed: 1.85, rise: 0.86, spread: 2.0, opacity: 0.84, blending: 'normal', reducedGraphicsMultiplier: 0.34 },
      { type: 'smokePuff', anchor: 'groundTarget', texture: 'smokePuff', startTime: 0.55, duration: 0.66, color: '#756354', scale: 0.5, count: 8, speed: 0.48, rise: 0.82, spread: 1.28, opacity: 0.38, blending: 'normal', reducedGraphicsMultiplier: 0.28 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.5, duration: 0.31, color: '#fff4cf', secondaryColor: '#d49753', scale: 1.92, opacity: 0.96 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.51, duration: 0.16, color: '#d69a5e', opacity: 0.15, reducedGraphicsMultiplier: 0.42 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.5, duration: 0.62, scale: 0.78, reducedGraphicsMultiplier: 0.36 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.52, duration: 0.13 },
    ],
  }),
] as const satisfies readonly VfxPreset[];

export const PREMIUM_VFX_PRESET_IDS = Object.freeze(PREMIUM_VFX_PRESETS.map((preset) => preset.id));
