/**
 * R2C-LAB V1D.2 — Deterministic GIF preview resolver.
 *
 * Uses a pre-built preview index (generated by tools/vfx/build-preview-index.mjs)
 * to map candidateId → exact existing GIF file.
 *
 * The index is authoritative: hasGifPreview is true ONLY when a GIF file
 * was found and resolved during the scan.
 *
 * Does NOT allow arbitrary filesystem paths.
 * Does NOT acquire PNGs.
 * Does NOT use VfxResourceManager.
 */

import type { InventoryJsonRecord } from './CombatVfxLab';
import previewIndexData from '../../../docs/reports/vfx-megapack-preview-index.json';

/** Preview index entry for a single candidate. */
export interface PreviewIndexEntry {
  status: 'RESOLVED' | 'NO_GIF' | 'AMBIGUOUS';
  previewFilename: string | null;
  previewRelativePath: string | null;
  previewFolder: string | null;
  candidates?: string[];
}

/** Shape of the generated preview index JSON. */
interface PreviewIndexJson {
  generatedAt: string;
  totalGifs: number;
  totalCandidates: number;
  counts: { resolved: number; noGif: number; ambiguous: number };
  index: Record<string, PreviewIndexEntry>;
}

const previewIndex = previewIndexData as PreviewIndexJson;

export interface PreviewResolution {
  candidateId: string;
  hasPreview: boolean;
  previewUrl: string;
  previewFilename: string | null;
  status: 'RESOLVED' | 'NO_GIF' | 'AMBIGUOUS';
}

/**
 * Derives the GIF preview filename from a spritesheet source filename.
 * Example: "Arrow_Indicator_V1_spritesheet.png" → "Arrow_Indicator_V1.gif"
 *
 * NOTE: This is a heuristic derivation kept for backward compatibility.
 * The authoritative resolution uses the preview index.
 */
export function deriveGifFilename(sourceFilename: string): string {
  return sourceFilename
    .replace(/_spritesheet\.png$/i, '')
    .replace(/\.png$/i, '') + '.gif';
}

/**
 * Checks whether a collection has a known preview directory.
 * NOTE: This is the old heuristic. Use hasGifPreview for authoritative truth.
 */
export function collectionHasPreviewDir(collection: string): boolean {
  const PREVIEW_DIRS: Record<string, string | null> = {
    'Essentials VFX Spritesheets': '(PREVIEW) GIFs - Essentials VFX',
    'Fire VFX Spritesheets': '(PREVIEW) GIFs - Fire VFX v2.0.0',
    'Lightning VFX Spritesheets': '(PREVIEW) GIFs - Lightning VFX v.2.0.0',
    'Sword Slash VFX Spritesheets': '(PREVIEW) GIFs - Sword Slash VFX',
    'Water VFX Spritesheets': null,
    'Wind VFX Spritesheets': 'Wind VFX GIFs',
  };
  return PREVIEW_DIRS[collection] != null;
}

/**
 * Returns the authoritative preview index entry for a candidateId.
 * Returns undefined if the candidate is not in the index.
 */
export function getPreviewIndexEntry(candidateId: string): PreviewIndexEntry | undefined {
  return previewIndex.index[candidateId];
}

/**
 * Returns true if the candidate has a resolved GIF preview in the index.
 * This is the authoritative truth — not a heuristic.
 */
export function hasGifPreview(candidateId: string): boolean {
  const entry = previewIndex.index[candidateId];
  return entry?.status === 'RESOLVED';
}

/**
 * Resolves the GIF preview for a candidate using the authoritative preview index.
 *
 * hasPreview is true ONLY when the index says RESOLVED.
 * The URL is a DEV-only path: /dev/vfx-preview/<candidateId>
 * The actual GIF file is served by the Vite dev middleware.
 */
export function resolvePreview(
  candidateId: string,
  _record: InventoryJsonRecord | undefined,
): PreviewResolution {
  const entry = previewIndex.index[candidateId];
  if (!entry || entry.status !== 'RESOLVED') {
    return {
      candidateId,
      hasPreview: false,
      previewUrl: '',
      previewFilename: null,
      status: entry?.status ?? 'NO_GIF',
    };
  }

  return {
    candidateId,
    hasPreview: true,
    previewUrl: `/dev/vfx-preview/${candidateId}`,
    previewFilename: entry.previewFilename,
    status: 'RESOLVED',
  };
}

/**
 * Builds a preview map for all inventory records.
 * Key: candidateId, Value: PreviewResolution
 */
export function buildPreviewMap(
  inventory: { results: InventoryJsonRecord[] },
): Map<string, PreviewResolution> {
  const map = new Map<string, PreviewResolution>();
  for (const rec of inventory.results) {
    map.set(rec.assetId, resolvePreview(rec.assetId, rec));
  }
  return map;
}

/**
 * Gets the Mega Pack filesystem path for a candidate's GIF preview.
 * Used by the DEV middleware to serve the file.
 * Returns null if no preview is resolved in the index.
 */
export function getGifFsPath(
  candidateId: string,
  megaPackRoot: string,
): string | null {
  const entry = previewIndex.index[candidateId];
  if (!entry || entry.status !== 'RESOLVED' || !entry.previewRelativePath) {
    return null;
  }
  return `${megaPackRoot}/02_previews/${entry.previewRelativePath.replace(/\\/g, '/')}`;
}

/**
 * Validates a candidateId is safe for path operations.
 * Rejects path traversal attempts.
 */
export function isValidCandidateId(candidateId: string): boolean {
  if (!candidateId || typeof candidateId !== 'string') return false;
  if (candidateId.includes('/') || candidateId.includes('\\') || candidateId.includes('..')) return false;
  return /^r\d+_\d+$/.test(candidateId) || /^[a-zA-Z0-9_-]+$/.test(candidateId);
}

/**
 * Returns the preview index counts for audit/reporting.
 */
export function getPreviewIndexCounts(): { resolved: number; noGif: number; ambiguous: number; total: number } {
  return {
    resolved: previewIndex.counts.resolved,
    noGif: previewIndex.counts.noGif,
    ambiguous: previewIndex.counts.ambiguous,
    total: previewIndex.totalCandidates,
  };
}
