import type { VfxPreset, VfxStepType } from './VfxTypes';

export const VFX_PARTICLE_STEP_TYPES = new Set<VfxStepType>([
  'particleBurst',
  'projectile',
  'smokePuff',
  'sparkleBurst',
]);

const presets = [
  {
    id: 'melee_light',
    label: 'Frappe légère',
    duration: 0.38,
    impactTime: 0.14,
    tags: ['physical', 'melee', 'light'],
    particleBudget: 9,
    reducedGraphicsScale: 0.48,
    steps: [
      { type: 'slashArc', anchor: 'target', texture: 'slashArc', startTime: 0.04, duration: 0.2, color: '#fff2c2', secondaryColor: '#e7b95c', scale: 1.18, opacity: 0.95, rotation: -0.35 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.09, duration: 0.25, color: '#fff1c2', secondaryColor: '#e8ad4f', scale: 0.14, count: 9, speed: 1.08, rise: 0.38, spread: 0.92, opacity: 0.86, reducedGraphicsMultiplier: 0.52 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.09, duration: 0.16, color: '#fff7dc', secondaryColor: '#f0bd55', scale: 0.72, opacity: 0.96 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.1, duration: 0.13, scale: 0.13, reducedGraphicsMultiplier: 0.58 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.1, duration: 0.04 },
    ],
  },
  {
    id: 'melee_heavy',
    label: 'Impact lourd',
    duration: 0.65,
    impactTime: 0.23,
    tags: ['physical', 'melee', 'heavy'],
    particleBudget: 17,
    reducedGraphicsScale: 0.45,
    steps: [
      { type: 'slashArc', anchor: 'target', texture: 'slashArc', startTime: 0.08, duration: 0.27, color: '#ffd68a', secondaryColor: '#d87931', scale: 1.48, opacity: 0.9, rotation: -0.58 },
      { type: 'shockwave', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.16, duration: 0.34, color: '#f0a446', secondaryColor: '#6e452b', scale: 1.28, radius: 1.05, opacity: 0.74, count: 4, reducedGraphicsMultiplier: 0.58 },
      { type: 'particleBurst', anchor: 'targetGround', texture: 'softParticle', startTime: 0.17, duration: 0.4, color: '#eab25d', secondaryColor: '#80603d', scale: 0.18, count: 13, speed: 1.28, rise: 0.5, spread: 1.15, opacity: 0.72, blending: 'normal', reducedGraphicsMultiplier: 0.5 },
      { type: 'smokePuff', anchor: 'targetGround', texture: 'smokePuff', startTime: 0.2, duration: 0.43, color: '#8a725a', scale: 0.34, count: 4, speed: 0.52, rise: 0.62, spread: 0.62, opacity: 0.38, blending: 'normal', reducedGraphicsMultiplier: 0.4 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.17, duration: 0.19, color: '#fff0ba', scale: 0.94, opacity: 0.88 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.18, duration: 0.24, scale: 0.34, reducedGraphicsMultiplier: 0.55 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.18, duration: 0.07 },
    ],
  },
  {
    id: 'fireball',
    label: 'Orbe ardent',
    duration: 0.82,
    impactTime: 0.52,
    tags: ['magic', 'fire', 'projectile'],
    particleBudget: 23,
    reducedGraphicsScale: 0.43,
    steps: [
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.46, color: '#ffc15a', secondaryColor: '#ff693d', scale: 1.15, opacity: 0.72, rotation: 0.7 },
      { type: 'lightPulse', anchor: 'source', texture: 'magicGlow', startTime: 0.04, duration: 0.38, color: '#ffbd54', scale: 1.05, opacity: 0.54, reducedGraphicsMultiplier: 0.68 },
      { type: 'projectile', anchor: 'source', targetAnchor: 'groundTarget', texture: 'projectileCore', startTime: 0.13, duration: 0.38, color: '#fff1a1', secondaryColor: '#ff5a2f', scale: 0.3, count: 6, speed: 1, opacity: 0.96, heightOffset: 0.62, reducedGraphicsMultiplier: 0.5 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.48, duration: 0.3, color: '#ffd45b', secondaryColor: '#ef4d2d', scale: 0.17, count: 14, speed: 1.42, rise: 0.78, spread: 1.15, opacity: 0.9, reducedGraphicsMultiplier: 0.48 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.48, duration: 0.22, color: '#fff4b1', secondaryColor: '#ff6a32', scale: 1.05, opacity: 0.9 },
      { type: 'smokePuff', anchor: 'targetGround', texture: 'smokePuff', startTime: 0.52, duration: 0.29, color: '#6f4a3f', scale: 0.29, count: 3, speed: 0.44, rise: 0.6, spread: 0.55, opacity: 0.32, blending: 'normal', reducedGraphicsMultiplier: 0.34 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.49, duration: 0.15, color: '#ffbc55', opacity: 0.11, reducedGraphicsMultiplier: 0.55 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.49, duration: 0.2, scale: 0.24, reducedGraphicsMultiplier: 0.52 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.49, duration: 0.06 },
    ],
  },
  {
    id: 'heal_burst',
    label: 'Souffle réparateur',
    duration: 0.7,
    impactTime: 0.36,
    tags: ['magic', 'heal', 'support'],
    particleBudget: 20,
    reducedGraphicsScale: 0.5,
    steps: [
      { type: 'groundRing', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.02, duration: 0.6, color: '#9be589', secondaryColor: '#f3d78a', scale: 1.25, radius: 0.92, opacity: 0.72, reducedGraphicsMultiplier: 0.68 },
      { type: 'magicCircle', anchor: 'targetGround', texture: 'magicCircle', startTime: 0.04, duration: 0.54, color: '#b7f1a5', secondaryColor: '#efd287', scale: 0.95, opacity: 0.48, rotation: -0.55, reducedGraphicsMultiplier: 0.6 },
      { type: 'sparkleBurst', anchor: 'targetGround', texture: 'sparkle', startTime: 0.12, duration: 0.53, color: '#e8ffd7', secondaryColor: '#f1cb72', scale: 0.13, count: 16, speed: 0.72, rise: 1.48, spread: 0.68, opacity: 0.9, reducedGraphicsMultiplier: 0.52 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.25, duration: 0.34, color: '#dfffcf', secondaryColor: '#e7c56d', scale: 0.11, count: 4, speed: 0.48, rise: 0.86, spread: 0.46, opacity: 0.72, reducedGraphicsMultiplier: 0.5 },
      { type: 'lightPulse', anchor: 'target', texture: 'magicGlow', startTime: 0.19, duration: 0.42, color: '#baf6a7', secondaryColor: '#f0d386', scale: 1.26, opacity: 0.42, reducedGraphicsMultiplier: 0.65 },
    ],
  },
  {
    id: 'boss_quake',
    label: 'Fracture du colosse',
    duration: 0.96,
    impactTime: 0.36,
    tags: ['boss', 'physical', 'ground', 'aoe'],
    particleBudget: 30,
    reducedGraphicsScale: 0.4,
    steps: [
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.42, color: '#8d3d24', secondaryColor: '#e59942', scale: 1.5, opacity: 0.38, rotation: 0.38, reducedGraphicsMultiplier: 0.45 },
      { type: 'shockwave', anchor: 'groundTarget', texture: 'ringGradient', startTime: 0.21, duration: 0.52, color: '#f2a34c', secondaryColor: '#5a3426', scale: 1.72, radius: 2.05, opacity: 0.82, count: 7, reducedGraphicsMultiplier: 0.5 },
      { type: 'groundRing', anchor: 'groundTarget', texture: 'ringGradient', startTime: 0.25, duration: 0.55, color: '#ffd078', secondaryColor: '#8f4c2d', scale: 1.54, radius: 1.75, opacity: 0.62, reducedGraphicsMultiplier: 0.52 },
      { type: 'particleBurst', anchor: 'groundTarget', texture: 'softParticle', startTime: 0.27, duration: 0.57, color: '#e4a455', secondaryColor: '#6a4a37', scale: 0.22, count: 24, speed: 1.65, rise: 0.74, spread: 1.85, opacity: 0.76, blending: 'normal', reducedGraphicsMultiplier: 0.42 },
      { type: 'smokePuff', anchor: 'groundTarget', texture: 'smokePuff', startTime: 0.3, duration: 0.62, color: '#705748', scale: 0.42, count: 6, speed: 0.55, rise: 0.76, spread: 1.2, opacity: 0.34, blending: 'normal', reducedGraphicsMultiplier: 0.33 },
      { type: 'impactStar', anchor: 'groundTarget', texture: 'impactStar', startTime: 0.26, duration: 0.24, color: '#ffe1a0', secondaryColor: '#dd713a', scale: 1.22, opacity: 0.82 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.27, duration: 0.17, color: '#d87739', opacity: 0.12, reducedGraphicsMultiplier: 0.48 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.26, duration: 0.4, scale: 0.62, reducedGraphicsMultiplier: 0.5 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.27, duration: 0.1 },
    ],
  },
  {
    id: 'generic_hit',
    label: 'Impact générique',
    duration: 0.32,
    impactTime: 0.11,
    tags: ['impact', 'fallback'],
    particleBudget: 6,
    reducedGraphicsScale: 0.52,
    steps: [
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.05, duration: 0.16, color: '#fff5d8', secondaryColor: '#e5b968', scale: 0.62, opacity: 0.92 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.07, duration: 0.22, color: '#fff1bf', secondaryColor: '#dca95c', scale: 0.11, count: 6, speed: 0.9, rise: 0.38, spread: 0.66, opacity: 0.78, reducedGraphicsMultiplier: 0.55 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.08, duration: 0.1, scale: 0.08, reducedGraphicsMultiplier: 0.55 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.08, duration: 0.03 },
    ],
  },
  {
    id: 'sword_slash',
    label: 'Entaille d’acier',
    duration: 0.46,
    impactTime: 0.16,
    tags: ['physical', 'melee', 'blade'],
    particleBudget: 8,
    reducedGraphicsScale: 0.5,
    steps: [
      { type: 'slashArc', anchor: 'target', texture: 'slashArc', startTime: 0.03, duration: 0.24, color: '#fff8dc', secondaryColor: '#e9c46a', scale: 1.28, opacity: 0.94, rotation: -0.42 },
      { type: 'slashArc', anchor: 'target', texture: 'slashArc', startTime: 0.08, duration: 0.21, color: '#f8d98a', secondaryColor: '#d99242', scale: 0.92, opacity: 0.68, rotation: 0.48, reducedGraphicsMultiplier: 0.45 },
      { type: 'particleBurst', anchor: 'target', texture: 'sparkle', startTime: 0.11, duration: 0.28, color: '#fff4c7', secondaryColor: '#e8ad4f', scale: 0.12, count: 8, speed: 1.08, rise: 0.34, spread: 0.9, opacity: 0.82, reducedGraphicsMultiplier: 0.5 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.12, duration: 0.17, color: '#fffbe8', secondaryColor: '#f1c35f', scale: 0.72, opacity: 0.9 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.13, duration: 0.14, scale: 0.14, reducedGraphicsMultiplier: 0.56 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.13, duration: 0.045 },
    ],
  },
  {
    id: 'blunt_impact',
    label: 'Choc contondant',
    duration: 0.62,
    impactTime: 0.23,
    tags: ['physical', 'melee', 'blunt'],
    particleBudget: 13,
    reducedGraphicsScale: 0.44,
    steps: [
      { type: 'shockwave', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.13, duration: 0.32, color: '#e5a652', secondaryColor: '#6b4931', scale: 1.14, radius: 0.94, opacity: 0.7, count: 4, reducedGraphicsMultiplier: 0.54 },
      { type: 'particleBurst', anchor: 'targetGround', texture: 'softParticle', startTime: 0.17, duration: 0.38, color: '#e7b263', secondaryColor: '#765b3e', scale: 0.17, count: 10, speed: 1.3, rise: 0.5, spread: 1.05, opacity: 0.7, blending: 'normal', reducedGraphicsMultiplier: 0.48 },
      { type: 'smokePuff', anchor: 'targetGround', texture: 'smokePuff', startTime: 0.21, duration: 0.38, color: '#75604c', scale: 0.3, count: 3, speed: 0.45, rise: 0.58, spread: 0.58, opacity: 0.3, blending: 'normal', reducedGraphicsMultiplier: 0.35 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.17, duration: 0.18, color: '#ffe7aa', secondaryColor: '#d37b38', scale: 0.92, opacity: 0.84 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.18, duration: 0.22, scale: 0.3, reducedGraphicsMultiplier: 0.52 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.18, duration: 0.07 },
    ],
  },
  {
    id: 'arrow_shot',
    label: 'Trait précis',
    duration: 0.58,
    impactTime: 0.36,
    tags: ['physical', 'ranged', 'projectile'],
    particleBudget: 10,
    reducedGraphicsScale: 0.48,
    steps: [
      { type: 'projectile', anchor: 'source', targetAnchor: 'target', texture: 'projectileCore', startTime: 0.05, duration: 0.3, color: '#fff1b2', secondaryColor: '#c8873f', scale: 0.18, count: 5, speed: 1, opacity: 0.92, reducedGraphicsMultiplier: 0.5 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.32, duration: 0.15, color: '#fff7d7', secondaryColor: '#dc9e4f', scale: 0.56, opacity: 0.9 },
      { type: 'particleBurst', anchor: 'target', texture: 'sparkle', startTime: 0.32, duration: 0.23, color: '#ffe7a1', secondaryColor: '#b96f34', scale: 0.1, count: 5, speed: 0.94, rise: 0.25, spread: 0.6, opacity: 0.78, reducedGraphicsMultiplier: 0.55 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.33, duration: 0.1, scale: 0.08, reducedGraphicsMultiplier: 0.55 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.33, duration: 0.03 },
    ],
  },
  {
    id: 'dark_bolt',
    label: 'Éclair des Ombres',
    duration: 0.76,
    impactTime: 0.47,
    tags: ['magic', 'shadow', 'projectile'],
    particleBudget: 19,
    reducedGraphicsScale: 0.43,
    steps: [
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.36, color: '#56418f', secondaryColor: '#75cddd', scale: 0.94, opacity: 0.54, rotation: -0.62 },
      { type: 'lightPulse', anchor: 'source', texture: 'magicGlow', startTime: 0.03, duration: 0.3, color: '#7761bf', secondaryColor: '#72d1dd', scale: 0.86, opacity: 0.42, reducedGraphicsMultiplier: 0.62 },
      { type: 'projectile', anchor: 'source', targetAnchor: 'target', texture: 'projectileCore', startTime: 0.09, duration: 0.35, color: '#b293ff', secondaryColor: '#62c9d8', scale: 0.25, count: 7, speed: 1, opacity: 0.94, reducedGraphicsMultiplier: 0.48 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.41, duration: 0.3, color: '#a883ee', secondaryColor: '#4aa9c0', scale: 0.14, count: 10, speed: 1.14, rise: 0.52, spread: 0.95, opacity: 0.82, reducedGraphicsMultiplier: 0.46 },
      { type: 'smokePuff', anchor: 'targetGround', texture: 'smokePuff', startTime: 0.45, duration: 0.27, color: '#28213d', scale: 0.25, count: 2, speed: 0.42, rise: 0.52, spread: 0.45, opacity: 0.28, blending: 'normal', reducedGraphicsMultiplier: 0.34 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.42, duration: 0.18, color: '#d9c8ff', secondaryColor: '#58b8ce', scale: 0.84, opacity: 0.84 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.43, duration: 0.12, color: '#7457b9', opacity: 0.08, reducedGraphicsMultiplier: 0.52 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.43, duration: 0.15, scale: 0.16, reducedGraphicsMultiplier: 0.52 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.43, duration: 0.05 },
    ],
  },
  {
    id: 'bless_aura',
    label: 'Aura de bénédiction',
    duration: 0.68,
    impactTime: 0.31,
    tags: ['magic', 'support', 'bless'],
    particleBudget: 18,
    reducedGraphicsScale: 0.5,
    steps: [
      { type: 'groundRing', anchor: 'groundTarget', texture: 'ringGradient', startTime: 0.01, duration: 0.58, color: '#d7e8ff', secondaryColor: '#f1d58a', scale: 1.24, radius: 1, opacity: 0.6, reducedGraphicsMultiplier: 0.66 },
      { type: 'magicCircle', anchor: 'groundTarget', texture: 'magicCircle', startTime: 0.03, duration: 0.54, color: '#c5dcff', secondaryColor: '#f2cf77', scale: 0.9, opacity: 0.42, rotation: 0.48, reducedGraphicsMultiplier: 0.58 },
      { type: 'sparkleBurst', anchor: 'groundTarget', texture: 'sparkle', startTime: 0.1, duration: 0.52, color: '#f4f8ff', secondaryColor: '#efd17d', scale: 0.12, count: 14, speed: 0.68, rise: 1.36, spread: 0.7, opacity: 0.88, reducedGraphicsMultiplier: 0.5 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.22, duration: 0.35, color: '#d8ebff', secondaryColor: '#f0cb72', scale: 0.1, count: 4, speed: 0.5, rise: 0.82, spread: 0.4, opacity: 0.66, reducedGraphicsMultiplier: 0.5 },
      { type: 'lightPulse', anchor: 'target', texture: 'magicGlow', startTime: 0.17, duration: 0.42, color: '#d5e7ff', secondaryColor: '#f1d489', scale: 1.12, opacity: 0.36, reducedGraphicsMultiplier: 0.62 },
    ],
  },
  {
    id: 'curse_pulse',
    label: 'Pulsation maudite',
    duration: 0.7,
    impactTime: 0.34,
    tags: ['magic', 'debuff', 'shadow'],
    particleBudget: 15,
    reducedGraphicsScale: 0.44,
    steps: [
      { type: 'magicCircle', anchor: 'groundTarget', texture: 'magicCircle', startTime: 0.01, duration: 0.5, color: '#5a326f', secondaryColor: '#557fb0', scale: 1.02, opacity: 0.48, rotation: -0.7 },
      { type: 'shockwave', anchor: 'groundTarget', texture: 'ringGradient', startTime: 0.19, duration: 0.38, color: '#7e4b9d', secondaryColor: '#243a5a', scale: 1.3, radius: 1.05, opacity: 0.64, count: 4, reducedGraphicsMultiplier: 0.52 },
      { type: 'particleBurst', anchor: 'groundTarget', texture: 'softParticle', startTime: 0.22, duration: 0.4, color: '#8f5eb2', secondaryColor: '#456b92', scale: 0.13, count: 12, speed: 0.86, rise: 0.54, spread: 1.05, opacity: 0.76, reducedGraphicsMultiplier: 0.46 },
      { type: 'smokePuff', anchor: 'groundTarget', texture: 'smokePuff', startTime: 0.26, duration: 0.4, color: '#251d31', scale: 0.27, count: 3, speed: 0.4, rise: 0.6, spread: 0.58, opacity: 0.26, blending: 'normal', reducedGraphicsMultiplier: 0.34 },
      { type: 'lightPulse', anchor: 'target', texture: 'magicGlow', startTime: 0.2, duration: 0.38, color: '#755095', secondaryColor: '#4f87a3', scale: 1.02, opacity: 0.32, reducedGraphicsMultiplier: 0.56 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.24, duration: 0.12, color: '#4b2c65', opacity: 0.06, reducedGraphicsMultiplier: 0.48 },
    ],
  },
  {
    id: 'poison_bite',
    label: 'Morsure venimeuse',
    duration: 0.46,
    impactTime: 0.17,
    tags: ['physical', 'poison', 'creature'],
    particleBudget: 10,
    reducedGraphicsScale: 0.5,
    steps: [
      { type: 'slashArc', anchor: 'target', texture: 'slashArc', startTime: 0.04, duration: 0.2, color: '#d9df72', secondaryColor: '#82a842', scale: 0.82, opacity: 0.82, rotation: -0.22 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.1, duration: 0.3, color: '#bad351', secondaryColor: '#d49a3a', scale: 0.12, count: 10, speed: 0.92, rise: 0.32, spread: 0.76, opacity: 0.8, reducedGraphicsMultiplier: 0.5 },
      { type: 'groundRing', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.12, duration: 0.3, color: '#9eb744', secondaryColor: '#b5782e', scale: 0.72, radius: 0.74, opacity: 0.46, reducedGraphicsMultiplier: 0.54 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.11, duration: 0.15, color: '#e8ef91', secondaryColor: '#9cb13e', scale: 0.58, opacity: 0.8 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.12, duration: 0.12, scale: 0.1, reducedGraphicsMultiplier: 0.55 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.12, duration: 0.035 },
    ],
  },
  {
    id: 'guard_barrier',
    label: 'Barrière de garde',
    duration: 0.68,
    impactTime: 0.3,
    tags: ['magic', 'support', 'barrier'],
    particleBudget: 14,
    reducedGraphicsScale: 0.5,
    steps: [
      { type: 'groundRing', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.01, duration: 0.58, color: '#b9ddff', secondaryColor: '#f0d18a', scale: 1.15, radius: 0.92, opacity: 0.64, reducedGraphicsMultiplier: 0.66 },
      { type: 'magicCircle', anchor: 'targetGround', texture: 'magicCircle', startTime: 0.04, duration: 0.52, color: '#91c8ee', secondaryColor: '#f2d58d', scale: 0.82, opacity: 0.48, rotation: -0.38, reducedGraphicsMultiplier: 0.6 },
      { type: 'sparkleBurst', anchor: 'targetGround', texture: 'sparkle', startTime: 0.12, duration: 0.48, color: '#e5f4ff', secondaryColor: '#edcf7d', scale: 0.11, count: 10, speed: 0.62, rise: 1.18, spread: 0.58, opacity: 0.82, reducedGraphicsMultiplier: 0.52 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.2, duration: 0.34, color: '#c7e7ff', secondaryColor: '#efd38b', scale: 0.1, count: 4, speed: 0.42, rise: 0.72, spread: 0.34, opacity: 0.66, reducedGraphicsMultiplier: 0.5 },
      { type: 'lightPulse', anchor: 'target', texture: 'magicGlow', startTime: 0.16, duration: 0.42, color: '#a9d9fb', secondaryColor: '#f0d48b', scale: 1.18, opacity: 0.38, reducedGraphicsMultiplier: 0.62 },
    ],
  },
  {
    id: 'boss_slam',
    label: 'Écrasement colossal',
    duration: 0.9,
    impactTime: 0.31,
    tags: ['boss', 'physical', 'ground', 'aoe'],
    particleBudget: 24,
    reducedGraphicsScale: 0.4,
    steps: [
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.34, color: '#6f3426', secondaryColor: '#d48a3d', scale: 1.34, opacity: 0.34, rotation: 0.32, reducedGraphicsMultiplier: 0.46 },
      { type: 'shockwave', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.18, duration: 0.5, color: '#eda14b', secondaryColor: '#60382a', scale: 1.58, radius: 1.54, opacity: 0.78, count: 6, reducedGraphicsMultiplier: 0.5 },
      { type: 'particleBurst', anchor: 'targetGround', texture: 'softParticle', startTime: 0.22, duration: 0.55, color: '#dda054', secondaryColor: '#684a35', scale: 0.2, count: 19, speed: 1.5, rise: 0.68, spread: 1.55, opacity: 0.74, blending: 'normal', reducedGraphicsMultiplier: 0.42 },
      { type: 'smokePuff', anchor: 'targetGround', texture: 'smokePuff', startTime: 0.27, duration: 0.58, color: '#6b5244', scale: 0.38, count: 5, speed: 0.5, rise: 0.72, spread: 1.05, opacity: 0.32, blending: 'normal', reducedGraphicsMultiplier: 0.34 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.23, duration: 0.21, color: '#ffe0a1', secondaryColor: '#d96e37', scale: 1.16, opacity: 0.82 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.24, duration: 0.15, color: '#d67a3a', opacity: 0.1, reducedGraphicsMultiplier: 0.48 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.23, duration: 0.35, scale: 0.54, reducedGraphicsMultiplier: 0.5 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.24, duration: 0.1 },
    ],
  },
  {
    id: 'critical_hit',
    label: 'Impact critique',
    duration: 0.34,
    impactTime: 0.08,
    tags: ['impact', 'critical'],
    particleBudget: 12,
    reducedGraphicsScale: 0.5,
    steps: [
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0, duration: 0.16, color: '#fffbe9', secondaryColor: '#ffd35f', scale: 1.06, opacity: 0.98 },
      { type: 'slashArc', anchor: 'target', texture: 'slashArc', startTime: 0.01, duration: 0.18, color: '#fff4c1', secondaryColor: '#f3b52d', scale: 1.08, opacity: 0.82, rotation: 0.6 },
      { type: 'particleBurst', anchor: 'target', texture: 'sparkle', startTime: 0.02, duration: 0.28, color: '#fffce8', secondaryColor: '#ffc63d', scale: 0.13, count: 12, speed: 1.35, rise: 0.62, spread: 1, opacity: 0.94, reducedGraphicsMultiplier: 0.5 },
      { type: 'lightPulse', anchor: 'target', texture: 'magicGlow', startTime: 0, duration: 0.22, color: '#fff3b0', secondaryColor: '#ffca45', scale: 1.18, opacity: 0.5, reducedGraphicsMultiplier: 0.62 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.03, duration: 0.1, color: '#fff3b0', opacity: 0.13, reducedGraphicsMultiplier: 0.52 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.03, duration: 0.18, scale: 0.28, reducedGraphicsMultiplier: 0.52 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.03, duration: 0.08 },
    ],
  },
  {
    id: 'kill_spark',
    label: 'Éclat de victoire',
    duration: 0.72,
    impactTime: 0.09,
    tags: ['impact', 'knockout', 'reward'],
    particleBudget: 18,
    reducedGraphicsScale: 0.5,
    steps: [
      { type: 'groundRing', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.01, duration: 0.58, color: '#f2d47d', secondaryColor: '#8ccfe5', scale: 1.08, radius: 0.9, opacity: 0.58, reducedGraphicsMultiplier: 0.62 },
      { type: 'sparkleBurst', anchor: 'target', texture: 'sparkle', startTime: 0, duration: 0.55, color: '#fff5c5', secondaryColor: '#7fd0ff', scale: 0.13, count: 14, speed: 0.82, rise: 1.52, spread: 0.76, opacity: 0.9, reducedGraphicsMultiplier: 0.5 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.02, duration: 0.44, color: '#f5d77c', secondaryColor: '#80cce5', scale: 0.11, count: 4, speed: 0.62, rise: 0.92, spread: 0.48, opacity: 0.72, reducedGraphicsMultiplier: 0.5 },
      { type: 'lightPulse', anchor: 'target', texture: 'magicGlow', startTime: 0, duration: 0.42, color: '#f4d77d', secondaryColor: '#8ed7ef', scale: 1.12, opacity: 0.42, reducedGraphicsMultiplier: 0.62 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.04, duration: 0.1, color: '#f6dc8b', opacity: 0.06, reducedGraphicsMultiplier: 0.5 },
    ],
  },
] as const satisfies readonly VfxPreset[];

export const VFX_PRESETS: Readonly<Record<string, VfxPreset>> = Object.freeze(
  Object.fromEntries(presets.map((preset) => [preset.id, preset])),
);

export const VFX_PRESET_IDS = Object.freeze(presets.map((preset) => preset.id));

export function getVfxPreset(id: string): VfxPreset | undefined {
  return VFX_PRESETS[id];
}
