import type { VfxPreset, VfxStepType } from './VfxTypes';
import { PREMIUM_VFX_PRESETS } from './VfxPremiumPresets';

export const VFX_PARTICLE_STEP_TYPES = new Set<VfxStepType>([
  'particleBurst',
  'projectile',
  'smokePuff',
  'sparkleBurst',
]);

const presets = [
  {
    id: 'fireball',
    label: 'Orbe ardent',
    duration: 0.84,
    impactTime: 0.52,
    tags: ['magic', 'fire', 'projectile'],
    particleBudget: 23,
    reducedGraphicsScale: 0.43,
    steps: [
      { type: 'spriteSheet', anchor: 'targetGround', spriteSheet: 'fire_explosion', startTime: 0.34, duration: 0.46, scale: 1.82, opacity: 1, blending: 'normal', reducedGraphicsMultiplier: 0.72 },
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.46, color: '#ffd06a', secondaryColor: '#ff6238', scale: 1.25, opacity: 0.8, rotation: 0.7 },
      { type: 'lightPulse', anchor: 'source', texture: 'magicGlow', startTime: 0.04, duration: 0.38, color: '#ffcb63', scale: 1.18, opacity: 0.62, reducedGraphicsMultiplier: 0.68 },
      { type: 'projectile', anchor: 'source', targetAnchor: 'groundTarget', texture: 'projectileCore', startTime: 0.13, duration: 0.38, color: '#fff8c9', secondaryColor: '#ff4f2f', scale: 0.36, count: 6, speed: 1, opacity: 1, heightOffset: 0.62, reducedGraphicsMultiplier: 0.5 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.48, duration: 0.32, color: '#fff0a3', secondaryColor: '#f04429', scale: 0.22, count: 14, speed: 1.5, rise: 0.84, spread: 1.25, opacity: 0.96, reducedGraphicsMultiplier: 0.48 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.48, duration: 0.24, color: '#fffbe0', secondaryColor: '#ff5b32', scale: 1.32, opacity: 1 },
      { type: 'smokePuff', anchor: 'targetGround', texture: 'smokePuff', startTime: 0.52, duration: 0.31, color: '#6f4a3f', scale: 0.34, count: 3, speed: 0.44, rise: 0.64, spread: 0.6, opacity: 0.34, blending: 'normal', reducedGraphicsMultiplier: 0.34 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.49, duration: 0.15, color: '#ffd06a', opacity: 0.14, reducedGraphicsMultiplier: 0.55 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.49, duration: 0.2, scale: 0.3, reducedGraphicsMultiplier: 0.52 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.49, duration: 0.07 },
    ],
  },
  {
    id: 'heal_burst',
    label: 'Souffle réparateur',
    duration: 0.7,
    impactTime: 0.36,
    tags: ['magic', 'heal', 'support'],
    particleBudget: 20,
    reducedGraphicsScale: 0.5,
    steps: [
      { type: 'spriteSheet', anchor: 'targetGround', spriteSheet: 'heal_touch', startTime: 0.02, duration: 0.6, scale: 1.62, opacity: 1, blending: 'normal', reducedGraphicsMultiplier: 0.76 },
      { type: 'groundRing', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.02, duration: 0.6, color: '#a9f29a', secondaryColor: '#f7dc91', scale: 1.35, radius: 0.98, opacity: 0.8, reducedGraphicsMultiplier: 0.68 },
      { type: 'magicCircle', anchor: 'targetGround', texture: 'magicCircle', startTime: 0.04, duration: 0.54, color: '#c4ffb5', secondaryColor: '#f4d78c', scale: 1.04, opacity: 0.54, rotation: -0.55, reducedGraphicsMultiplier: 0.6 },
      { type: 'sparkleBurst', anchor: 'targetGround', texture: 'sparkle', startTime: 0.12, duration: 0.53, color: '#efffe3', secondaryColor: '#f5d27a', scale: 0.15, count: 16, speed: 0.72, rise: 1.52, spread: 0.72, opacity: 0.96, reducedGraphicsMultiplier: 0.52 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.25, duration: 0.34, color: '#eaffdc', secondaryColor: '#eccc77', scale: 0.12, count: 4, speed: 0.48, rise: 0.9, spread: 0.5, opacity: 0.78, reducedGraphicsMultiplier: 0.5 },
      { type: 'lightPulse', anchor: 'target', texture: 'magicGlow', startTime: 0.19, duration: 0.42, color: '#c8ffb7', secondaryColor: '#f4d88d', scale: 1.4, opacity: 0.5, reducedGraphicsMultiplier: 0.65 },
    ],
  },
  {
    id: 'boss_quake',
    label: 'Fracture du colosse',
    duration: 0.96,
    impactTime: 0.36,
    tags: ['boss', 'physical', 'ground', 'aoe'],
    particleBudget: 30,
    reducedGraphicsScale: 0.4,
    steps: [
      { type: 'spriteSheet', anchor: 'groundTarget', spriteSheet: 'shockwave_ring', startTime: 0.03, duration: 0.66, scale: 2.2, opacity: 1, blending: 'normal', reducedGraphicsMultiplier: 0.7 },
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.42, color: '#a64a2b', secondaryColor: '#f0ad55', scale: 1.75, opacity: 0.48, rotation: 0.38, reducedGraphicsMultiplier: 0.45 },
      { type: 'shockwave', anchor: 'groundTarget', texture: 'ringGradient', startTime: 0.21, duration: 0.52, color: '#ffd98a', secondaryColor: '#8f472e', scale: 2.05, radius: 2.15, opacity: 0.92, count: 7, reducedGraphicsMultiplier: 0.5 },
      { type: 'groundRing', anchor: 'groundTarget', texture: 'ringGradient', startTime: 0.25, duration: 0.55, color: '#ffedb7', secondaryColor: '#a75933', scale: 1.85, radius: 1.9, opacity: 0.78, reducedGraphicsMultiplier: 0.52 },
      { type: 'particleBurst', anchor: 'groundTarget', texture: 'softParticle', startTime: 0.27, duration: 0.57, color: '#ffd180', secondaryColor: '#79513a', scale: 0.28, count: 24, speed: 1.85, rise: 0.82, spread: 2, opacity: 0.84, blending: 'normal', reducedGraphicsMultiplier: 0.42 },
      { type: 'smokePuff', anchor: 'groundTarget', texture: 'smokePuff', startTime: 0.3, duration: 0.62, color: '#705748', scale: 0.48, count: 6, speed: 0.55, rise: 0.8, spread: 1.35, opacity: 0.36, blending: 'normal', reducedGraphicsMultiplier: 0.33 },
      { type: 'impactStar', anchor: 'groundTarget', texture: 'impactStar', startTime: 0.26, duration: 0.26, color: '#fff4cf', secondaryColor: '#ef8141', scale: 1.65, opacity: 0.98 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.27, duration: 0.17, color: '#ed9951', opacity: 0.16, reducedGraphicsMultiplier: 0.48 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.26, duration: 0.4, scale: 0.7, reducedGraphicsMultiplier: 0.5 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.27, duration: 0.11 },
    ],
  },
  {
    id: 'generic_hit',
    label: 'Impact générique',
    duration: 0.32,
    impactTime: 0.11,
    tags: ['impact', 'fallback'],
    particleBudget: 6,
    reducedGraphicsScale: 0.52,
    steps: [
      { type: 'spriteSheet', anchor: 'target', spriteSheet: 'small_impact', startTime: 0, duration: 0.23, scale: 0.92, opacity: 1, blending: 'normal', reducedGraphicsMultiplier: 0.78 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.05, duration: 0.17, color: '#fffdf0', secondaryColor: '#eac36f', scale: 0.78, opacity: 0.98 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.07, duration: 0.22, color: '#fff8d9', secondaryColor: '#dfa95c', scale: 0.14, count: 6, speed: 0.94, rise: 0.4, spread: 0.72, opacity: 0.84, reducedGraphicsMultiplier: 0.55 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.08, duration: 0.1, scale: 0.12, reducedGraphicsMultiplier: 0.55 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.08, duration: 0.04 },
    ],
  },
  {
    id: 'sword_slash',
    label: 'Entaille d’acier',
    duration: 0.46,
    impactTime: 0.16,
    tags: ['physical', 'melee', 'blade'],
    particleBudget: 8,
    reducedGraphicsScale: 0.5,
    steps: [
      { type: 'spriteSheet', anchor: 'target', spriteSheet: 'slash_arc', orientation: 'source_to_target', startTime: 0, duration: 0.34, scale: 1.46, opacity: 1, blending: 'normal', reducedGraphicsMultiplier: 0.76 },
      { type: 'slashArc', anchor: 'target', texture: 'slashArc', orientation: 'source_to_target', startTime: 0.03, duration: 0.24, color: '#fffef0', secondaryColor: '#efcc72', scale: 1.42, opacity: 0.98, rotation: -0.42 },
      { type: 'slashArc', anchor: 'target', texture: 'slashArc', orientation: 'source_to_target', startTime: 0.08, duration: 0.21, color: '#ffe59c', secondaryColor: '#df9b48', scale: 1.04, opacity: 0.76, rotation: 0.48, reducedGraphicsMultiplier: 0.45 },
      { type: 'particleBurst', anchor: 'target', texture: 'sparkle', startTime: 0.11, duration: 0.28, color: '#fffbe0', secondaryColor: '#ecb452', scale: 0.15, count: 8, speed: 1.12, rise: 0.36, spread: 0.96, opacity: 0.9, reducedGraphicsMultiplier: 0.5 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.12, duration: 0.18, color: '#ffffff', secondaryColor: '#f4c762', scale: 0.88, opacity: 0.98 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.13, duration: 0.14, scale: 0.17, reducedGraphicsMultiplier: 0.56 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.13, duration: 0.05 },
    ],
  },
  {
    id: 'blunt_impact',
    label: 'Choc contondant',
    duration: 0.62,
    impactTime: 0.23,
    tags: ['physical', 'melee', 'blunt'],
    particleBudget: 13,
    reducedGraphicsScale: 0.44,
    steps: [
      { type: 'shockwave', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.13, duration: 0.32, color: '#f4bb68', secondaryColor: '#734a30', scale: 1.3, radius: 1, opacity: 0.8, count: 4, reducedGraphicsMultiplier: 0.54 },
      { type: 'particleBurst', anchor: 'targetGround', texture: 'softParticle', startTime: 0.17, duration: 0.38, color: '#f0c078', secondaryColor: '#765b3e', scale: 0.2, count: 10, speed: 1.36, rise: 0.54, spread: 1.12, opacity: 0.78, blending: 'normal', reducedGraphicsMultiplier: 0.48 },
      { type: 'smokePuff', anchor: 'targetGround', texture: 'smokePuff', startTime: 0.21, duration: 0.38, color: '#75604c', scale: 0.34, count: 3, speed: 0.45, rise: 0.6, spread: 0.62, opacity: 0.32, blending: 'normal', reducedGraphicsMultiplier: 0.35 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.17, duration: 0.2, color: '#fff4cf', secondaryColor: '#df8340', scale: 1.12, opacity: 0.94 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.18, duration: 0.22, scale: 0.34, reducedGraphicsMultiplier: 0.52 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.18, duration: 0.07 },
    ],
  },
  {
    id: 'arrow_shot',
    label: 'Trait précis',
    duration: 0.58,
    impactTime: 0.36,
    tags: ['physical', 'ranged', 'projectile'],
    particleBudget: 10,
    reducedGraphicsScale: 0.48,
    steps: [
      { type: 'spriteSheet', anchor: 'source', targetAnchor: 'target', spriteSheet: 'projectile_shot', sheetMode: 'projectile', orientation: 'source_to_target', startTime: 0, duration: 0.54, scale: 0.9, opacity: 1, blending: 'normal', reducedGraphicsMultiplier: 0.76 },
      { type: 'projectile', anchor: 'source', targetAnchor: 'target', texture: 'projectileCore', orientation: 'source_to_target', startTime: 0.05, duration: 0.3, color: '#fffbe0', secondaryColor: '#d99a49', scale: 0.26, count: 5, speed: 1, opacity: 1, reducedGraphicsMultiplier: 0.5 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.32, duration: 0.17, color: '#ffffff', secondaryColor: '#e3a653', scale: 0.76, opacity: 1 },
      { type: 'particleBurst', anchor: 'target', texture: 'sparkle', startTime: 0.32, duration: 0.23, color: '#fff2bd', secondaryColor: '#c67a39', scale: 0.13, count: 5, speed: 1, rise: 0.28, spread: 0.68, opacity: 0.88, reducedGraphicsMultiplier: 0.55 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.33, duration: 0.1, scale: 0.12, reducedGraphicsMultiplier: 0.55 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.33, duration: 0.045 },
    ],
  },
  {
    id: 'dark_bolt',
    label: 'Éclair des Ombres',
    duration: 0.76,
    impactTime: 0.47,
    tags: ['magic', 'shadow', 'projectile'],
    particleBudget: 19,
    reducedGraphicsScale: 0.43,
    steps: [
      { type: 'spriteSheet', anchor: 'source', targetAnchor: 'target', spriteSheet: 'magic_bolt', sheetMode: 'projectile', startTime: 0.02, duration: 0.67, scale: 1.02, opacity: 1, blending: 'normal', reducedGraphicsMultiplier: 0.72 },
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.36, color: '#7650cf', secondaryColor: '#75e5ef', scale: 1.08, opacity: 0.66, rotation: -0.62 },
      { type: 'lightPulse', anchor: 'source', texture: 'magicGlow', startTime: 0.03, duration: 0.3, color: '#9b7bea', secondaryColor: '#75e7ef', scale: 1, opacity: 0.55, reducedGraphicsMultiplier: 0.62 },
      { type: 'projectile', anchor: 'source', targetAnchor: 'target', texture: 'projectileCore', startTime: 0.09, duration: 0.35, color: '#e6d7ff', secondaryColor: '#63ecf2', scale: 0.32, count: 7, speed: 1, opacity: 1, reducedGraphicsMultiplier: 0.48 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.41, duration: 0.3, color: '#c99cff', secondaryColor: '#57cfe0', scale: 0.18, count: 10, speed: 1.2, rise: 0.56, spread: 1.05, opacity: 0.9, reducedGraphicsMultiplier: 0.46 },
      { type: 'smokePuff', anchor: 'targetGround', texture: 'smokePuff', startTime: 0.45, duration: 0.27, color: '#302549', scale: 0.27, count: 2, speed: 0.42, rise: 0.54, spread: 0.48, opacity: 0.3, blending: 'normal', reducedGraphicsMultiplier: 0.34 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.42, duration: 0.2, color: '#f2eaff', secondaryColor: '#65ddea', scale: 1.08, opacity: 0.96 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.43, duration: 0.12, color: '#8b66e8', opacity: 0.1, reducedGraphicsMultiplier: 0.52 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.43, duration: 0.15, scale: 0.19, reducedGraphicsMultiplier: 0.52 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.43, duration: 0.055 },
    ],
  },
  {
    id: 'shadow_lightning_bolt',
    label: 'Foudre des Ombres',
    duration: 0.78,
    impactTime: 0.46,
    tags: ['magic', 'shadow', 'lightning', 'projectile'],
    particleBudget: 19,
    reducedGraphicsScale: 0.46,
    steps: [
      { type: 'spriteSheet', anchor: 'source', targetAnchor: 'target', spriteSheet: 'shadow_lightning_bolt', sheetMode: 'projectile', orientation: 'source_to_target', startTime: 0.02, duration: 0.68, scale: 1.24, opacity: 1, blending: 'additive', reducedGraphicsMultiplier: 0.76 },
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.34, color: '#412070', secondaryColor: '#9f52df', scale: 1.1, opacity: 0.7, rotation: -0.7, reducedGraphicsMultiplier: 0.62 },
      { type: 'lightPulse', anchor: 'source', texture: 'magicGlow', startTime: 0.03, duration: 0.28, color: '#6e3aa5', secondaryColor: '#e0b4ff', scale: 1.04, opacity: 0.62, reducedGraphicsMultiplier: 0.64 },
      { type: 'projectile', anchor: 'source', targetAnchor: 'target', texture: 'projectileCore', orientation: 'source_to_target', startTime: 0.09, duration: 0.34, color: '#b885ff', secondaryColor: '#25113f', scale: 0.34, count: 7, speed: 1.05, opacity: 1, reducedGraphicsMultiplier: 0.52 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.4, duration: 0.31, color: '#d5aaff', secondaryColor: '#342050', scale: 0.2, count: 10, speed: 1.28, rise: 0.58, spread: 1.08, opacity: 0.96, reducedGraphicsMultiplier: 0.5 },
      { type: 'smokePuff', anchor: 'targetGround', texture: 'smokePuff', startTime: 0.44, duration: 0.28, color: '#1c102c', scale: 0.3, count: 2, speed: 0.4, rise: 0.5, spread: 0.52, opacity: 0.32, blending: 'normal', reducedGraphicsMultiplier: 0.36 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.41, duration: 0.2, color: '#f5eaff', secondaryColor: '#9b48f2', scale: 1.16, opacity: 1 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.42, duration: 0.12, color: '#7b3ed1', opacity: 0.12, reducedGraphicsMultiplier: 0.56 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.42, duration: 0.14, scale: 0.18, reducedGraphicsMultiplier: 0.56 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.42, duration: 0.055 },
    ],
  },
  {
    id: 'root_vines',
    label: 'Entraves végétales',
    duration: 0.82,
    impactTime: 0.36,
    tags: ['magic', 'earth', 'root', 'bind', 'status'],
    particleBudget: 10,
    reducedGraphicsScale: 0.56,
    steps: [
      { type: 'spriteSheet', anchor: 'groundTarget', spriteSheet: 'root_vines', orientation: 'center_on_target', startTime: 0.02, duration: 0.7, scale: 1.42, opacity: 1, blending: 'normal', reducedGraphicsMultiplier: 0.84 },
      { type: 'projectile', anchor: 'source', targetAnchor: 'target', texture: 'projectileCore', orientation: 'source_to_target', startTime: 0.04, duration: 0.27, color: '#dcff9b', secondaryColor: '#4c8d37', scale: 0.22, count: 4, speed: 1, opacity: 0.82, reducedGraphicsMultiplier: 0.48 },
      { type: 'groundRing', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.18, duration: 0.5, color: '#bfff74', secondaryColor: '#386c2f', scale: 1.18, radius: 0.96, opacity: 0.68, reducedGraphicsMultiplier: 0.6 },
      { type: 'particleBurst', anchor: 'targetGround', texture: 'softParticle', startTime: 0.28, duration: 0.36, color: '#d9ff9e', secondaryColor: '#437c31', scale: 0.15, count: 4, speed: 0.76, rise: 0.44, spread: 0.76, opacity: 0.78, blending: 'additive', reducedGraphicsMultiplier: 0.42 },
      { type: 'sparkleBurst', anchor: 'targetGround', texture: 'sparkle', startTime: 0.31, duration: 0.32, color: '#efffc6', secondaryColor: '#67aa3c', scale: 0.11, count: 2, speed: 0.52, rise: 0.48, spread: 0.54, opacity: 0.74, reducedGraphicsMultiplier: 0.4 },
      { type: 'lightPulse', anchor: 'target', texture: 'magicGlow', startTime: 0.24, duration: 0.38, color: '#baff77', secondaryColor: '#4d8734', scale: 1.14, opacity: 0.38, reducedGraphicsMultiplier: 0.56 },
    ],
  },
  {
    id: 'frost_bind',
    label: 'Entrave de givre',
    duration: 0.94,
    impactTime: 0.45,
    tags: ['boss', 'magic', 'frost', 'bind'],
    particleBudget: 14,
    reducedGraphicsScale: 0.52,
    steps: [
      { type: 'spriteSheet', anchor: 'groundTarget', spriteSheet: 'frost_bind', orientation: 'center_on_target', startTime: 0.02, duration: 0.84, scale: 1.68, opacity: 1, blending: 'additive', reducedGraphicsMultiplier: 0.86 },
      { type: 'groundRing', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.16, duration: 0.6, color: '#c9f5ff', secondaryColor: '#497ee8', scale: 1.46, radius: 1.15, opacity: 0.74, reducedGraphicsMultiplier: 0.62 },
      { type: 'sparkleBurst', anchor: 'target', texture: 'sparkle', startTime: 0.36, duration: 0.38, color: '#f2fdff', secondaryColor: '#78c8ff', scale: 0.13, count: 8, speed: 0.72, rise: 0.72, spread: 0.92, opacity: 0.92, reducedGraphicsMultiplier: 0.46 },
      { type: 'particleBurst', anchor: 'targetGround', texture: 'softParticle', startTime: 0.4, duration: 0.4, color: '#d9f9ff', secondaryColor: '#6caaff', scale: 0.16, count: 6, speed: 0.84, rise: 0.54, spread: 1, opacity: 0.84, blending: 'additive', reducedGraphicsMultiplier: 0.44 },
      { type: 'lightPulse', anchor: 'target', texture: 'magicGlow', startTime: 0.34, duration: 0.42, color: '#d6f8ff', secondaryColor: '#77b6ff', scale: 1.36, opacity: 0.5, reducedGraphicsMultiplier: 0.6 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.44, duration: 0.14, scale: 0.2, reducedGraphicsMultiplier: 0.5 },
    ],
  },
  {
    id: 'bless_aura',
    label: 'Aura de bénédiction',
    duration: 0.68,
    impactTime: 0.31,
    tags: ['magic', 'support', 'bless'],
    particleBudget: 18,
    reducedGraphicsScale: 0.5,
    steps: [
      { type: 'spriteSheet', anchor: 'groundTarget', spriteSheet: 'buff_pulse', startTime: 0, duration: 0.58, scale: 1.55, opacity: 1, blending: 'normal', reducedGraphicsMultiplier: 0.76 },
      { type: 'groundRing', anchor: 'groundTarget', texture: 'ringGradient', startTime: 0.01, duration: 0.58, color: '#e1efff', secondaryColor: '#f6dc95', scale: 1.34, radius: 1.05, opacity: 0.7, reducedGraphicsMultiplier: 0.66 },
      { type: 'magicCircle', anchor: 'groundTarget', texture: 'magicCircle', startTime: 0.03, duration: 0.54, color: '#d1e5ff', secondaryColor: '#f5d47d', scale: 0.98, opacity: 0.5, rotation: 0.48, reducedGraphicsMultiplier: 0.58 },
      { type: 'sparkleBurst', anchor: 'groundTarget', texture: 'sparkle', startTime: 0.1, duration: 0.52, color: '#ffffff', secondaryColor: '#f5d683', scale: 0.14, count: 14, speed: 0.68, rise: 1.4, spread: 0.76, opacity: 0.94, reducedGraphicsMultiplier: 0.5 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.22, duration: 0.35, color: '#e4f2ff', secondaryColor: '#f3d07a', scale: 0.12, count: 4, speed: 0.5, rise: 0.84, spread: 0.44, opacity: 0.74, reducedGraphicsMultiplier: 0.5 },
      { type: 'lightPulse', anchor: 'target', texture: 'magicGlow', startTime: 0.17, duration: 0.42, color: '#e0efff', secondaryColor: '#f5da94', scale: 1.26, opacity: 0.45, reducedGraphicsMultiplier: 0.62 },
    ],
  },
  {
    id: 'curse_pulse',
    label: 'Pulsation maudite',
    duration: 0.7,
    impactTime: 0.34,
    tags: ['magic', 'debuff', 'shadow'],
    particleBudget: 15,
    reducedGraphicsScale: 0.44,
    steps: [
      { type: 'magicCircle', anchor: 'groundTarget', texture: 'magicCircle', startTime: 0.01, duration: 0.5, color: '#8b4fbd', secondaryColor: '#4bb6d3', scale: 1.2, opacity: 0.64, rotation: -0.7 },
      { type: 'shockwave', anchor: 'groundTarget', texture: 'ringGradient', startTime: 0.19, duration: 0.38, color: '#aa6bd1', secondaryColor: '#2d5a78', scale: 1.5, radius: 1.12, opacity: 0.8, count: 4, reducedGraphicsMultiplier: 0.52 },
      { type: 'particleBurst', anchor: 'groundTarget', texture: 'softParticle', startTime: 0.22, duration: 0.4, color: '#c17deb', secondaryColor: '#55b7d8', scale: 0.17, count: 12, speed: 0.92, rise: 0.58, spread: 1.14, opacity: 0.88, reducedGraphicsMultiplier: 0.46 },
      { type: 'smokePuff', anchor: 'groundTarget', texture: 'smokePuff', startTime: 0.26, duration: 0.4, color: '#2c2039', scale: 0.3, count: 3, speed: 0.4, rise: 0.62, spread: 0.64, opacity: 0.32, blending: 'normal', reducedGraphicsMultiplier: 0.34 },
      { type: 'lightPulse', anchor: 'target', texture: 'magicGlow', startTime: 0.2, duration: 0.38, color: '#a86bd0', secondaryColor: '#5db7cc', scale: 1.22, opacity: 0.46, reducedGraphicsMultiplier: 0.56 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.24, duration: 0.12, color: '#7a49a8', opacity: 0.08, reducedGraphicsMultiplier: 0.48 },
    ],
  },
  {
    id: 'status_curse_mark',
    label: 'Marque maudite',
    duration: 0.68,
    impactTime: 0.3,
    tags: ['status', 'debuff', 'curse', 'shadow'],
    particleBudget: 12,
    reducedGraphicsScale: 0.46,
    steps: [
      { type: 'spriteSheet', anchor: 'target', spriteSheet: 'curse_mark', startTime: 0, duration: 0.58, scale: 1.16, opacity: 1, blending: 'normal', reducedGraphicsMultiplier: 0.76 },
      { type: 'groundRing', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.08, duration: 0.45, color: '#9f63d7', secondaryColor: '#2c4a73', scale: 1.08, radius: 0.9, opacity: 0.62, reducedGraphicsMultiplier: 0.55 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.18, duration: 0.38, color: '#c487ff', secondaryColor: '#53bfd4', scale: 0.15, count: 10, speed: 0.82, rise: 0.58, spread: 0.82, opacity: 0.82, reducedGraphicsMultiplier: 0.46 },
      { type: 'smokePuff', anchor: 'targetGround', texture: 'smokePuff', startTime: 0.24, duration: 0.38, color: '#281d34', scale: 0.28, count: 2, speed: 0.34, rise: 0.46, spread: 0.5, opacity: 0.3, blending: 'normal', reducedGraphicsMultiplier: 0.34 },
    ],
  },
  {
    id: 'poison_bite',
    label: 'Morsure venimeuse',
    duration: 0.46,
    impactTime: 0.17,
    tags: ['physical', 'poison', 'creature'],
    particleBudget: 10,
    reducedGraphicsScale: 0.5,
    steps: [
      { type: 'slashArc', anchor: 'target', texture: 'slashArc', startTime: 0.04, duration: 0.2, color: '#eef49a', secondaryColor: '#8eb646', scale: 0.96, opacity: 0.9, rotation: -0.22 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.1, duration: 0.3, color: '#d3e96a', secondaryColor: '#dfa03e', scale: 0.15, count: 10, speed: 0.98, rise: 0.35, spread: 0.84, opacity: 0.88, reducedGraphicsMultiplier: 0.5 },
      { type: 'groundRing', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.12, duration: 0.3, color: '#b8cf56', secondaryColor: '#c18432', scale: 0.86, radius: 0.8, opacity: 0.58, reducedGraphicsMultiplier: 0.54 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.11, duration: 0.16, color: '#f5f9b3', secondaryColor: '#a9be46', scale: 0.74, opacity: 0.9 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.12, duration: 0.12, scale: 0.12, reducedGraphicsMultiplier: 0.55 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.12, duration: 0.045 },
    ],
  },
  {
    id: 'guard_barrier',
    label: 'Barrière de garde',
    duration: 0.68,
    impactTime: 0.3,
    tags: ['magic', 'support', 'barrier'],
    particleBudget: 14,
    reducedGraphicsScale: 0.5,
    steps: [
      { type: 'spriteSheet', anchor: 'targetGround', spriteSheet: 'barrier_shell', startTime: 0.02, duration: 0.58, scale: 1.62, opacity: 1, blending: 'normal', reducedGraphicsMultiplier: 0.76 },
      { type: 'groundRing', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.01, duration: 0.58, color: '#c8e7ff', secondaryColor: '#f5d995', scale: 1.26, radius: 0.98, opacity: 0.74, reducedGraphicsMultiplier: 0.66 },
      { type: 'magicCircle', anchor: 'targetGround', texture: 'magicCircle', startTime: 0.04, duration: 0.52, color: '#a7d8f7', secondaryColor: '#f5db98', scale: 0.9, opacity: 0.55, rotation: -0.38, reducedGraphicsMultiplier: 0.6 },
      { type: 'sparkleBurst', anchor: 'targetGround', texture: 'sparkle', startTime: 0.12, duration: 0.48, color: '#f0faff', secondaryColor: '#f3d687', scale: 0.13, count: 10, speed: 0.62, rise: 1.22, spread: 0.64, opacity: 0.9, reducedGraphicsMultiplier: 0.52 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.2, duration: 0.34, color: '#d8f0ff', secondaryColor: '#f3d996', scale: 0.12, count: 4, speed: 0.42, rise: 0.76, spread: 0.38, opacity: 0.74, reducedGraphicsMultiplier: 0.5 },
      { type: 'lightPulse', anchor: 'target', texture: 'magicGlow', startTime: 0.16, duration: 0.42, color: '#bce6ff', secondaryColor: '#f4d996', scale: 1.3, opacity: 0.46, reducedGraphicsMultiplier: 0.62 },
    ],
  },
  {
    id: 'boss_slam',
    label: 'Écrasement colossal',
    duration: 0.9,
    impactTime: 0.31,
    tags: ['boss', 'physical', 'ground', 'aoe'],
    particleBudget: 24,
    reducedGraphicsScale: 0.4,
    steps: [
      { type: 'spriteSheet', anchor: 'targetGround', spriteSheet: 'leap_impact', startTime: 0.02, duration: 0.58, scale: 2.08, opacity: 1, blending: 'normal', reducedGraphicsMultiplier: 0.7 },
      { type: 'magicCircle', anchor: 'sourceGround', texture: 'magicCircle', startTime: 0, duration: 0.34, color: '#8e412a', secondaryColor: '#e59a48', scale: 1.55, opacity: 0.44, rotation: 0.32, reducedGraphicsMultiplier: 0.46 },
      { type: 'shockwave', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.18, duration: 0.5, color: '#ffd080', secondaryColor: '#84432d', scale: 1.9, radius: 1.7, opacity: 0.9, count: 6, reducedGraphicsMultiplier: 0.5 },
      { type: 'particleBurst', anchor: 'targetGround', texture: 'softParticle', startTime: 0.22, duration: 0.55, color: '#f5c477', secondaryColor: '#73503a', scale: 0.26, count: 19, speed: 1.65, rise: 0.76, spread: 1.75, opacity: 0.84, blending: 'normal', reducedGraphicsMultiplier: 0.42 },
      { type: 'smokePuff', anchor: 'targetGround', texture: 'smokePuff', startTime: 0.27, duration: 0.58, color: '#6b5244', scale: 0.44, count: 5, speed: 0.5, rise: 0.76, spread: 1.18, opacity: 0.35, blending: 'normal', reducedGraphicsMultiplier: 0.34 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.23, duration: 0.24, color: '#fff4cf', secondaryColor: '#ea7b3b', scale: 1.55, opacity: 0.98 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.24, duration: 0.15, color: '#e9974c', opacity: 0.14, reducedGraphicsMultiplier: 0.48 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.23, duration: 0.35, scale: 0.62, reducedGraphicsMultiplier: 0.5 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.24, duration: 0.11 },
    ],
  },
  {
    id: 'critical_hit',
    label: 'Impact critique',
    duration: 0.34,
    impactTime: 0.08,
    tags: ['impact', 'critical'],
    particleBudget: 12,
    reducedGraphicsScale: 0.5,
    steps: [
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0, duration: 0.18, color: '#ffffff', secondaryColor: '#ffda68', scale: 1.25, opacity: 1 },
      { type: 'slashArc', anchor: 'target', texture: 'slashArc', startTime: 0.01, duration: 0.19, color: '#fff9d5', secondaryColor: '#f6bd32', scale: 1.24, opacity: 0.9, rotation: 0.6 },
      { type: 'particleBurst', anchor: 'target', texture: 'sparkle', startTime: 0.02, duration: 0.28, color: '#ffffff', secondaryColor: '#ffca42', scale: 0.16, count: 12, speed: 1.42, rise: 0.66, spread: 1.08, opacity: 0.98, reducedGraphicsMultiplier: 0.5 },
      { type: 'lightPulse', anchor: 'target', texture: 'magicGlow', startTime: 0, duration: 0.22, color: '#fff7c7', secondaryColor: '#ffd052', scale: 1.34, opacity: 0.58, reducedGraphicsMultiplier: 0.62 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.03, duration: 0.1, color: '#fff6c2', opacity: 0.15, reducedGraphicsMultiplier: 0.52 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.03, duration: 0.18, scale: 0.31, reducedGraphicsMultiplier: 0.52 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.03, duration: 0.085 },
    ],
  },
  {
    id: 'kill_spark',
    label: 'Éclat de victoire',
    duration: 0.72,
    impactTime: 0.09,
    tags: ['impact', 'knockout', 'reward'],
    particleBudget: 18,
    reducedGraphicsScale: 0.5,
    steps: [
      { type: 'groundRing', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.01, duration: 0.58, color: '#f8dc86', secondaryColor: '#9ddff0', scale: 1.2, radius: 0.98, opacity: 0.68, reducedGraphicsMultiplier: 0.62 },
      { type: 'sparkleBurst', anchor: 'target', texture: 'sparkle', startTime: 0, duration: 0.55, color: '#fffbe0', secondaryColor: '#8cddff', scale: 0.16, count: 14, speed: 0.86, rise: 1.58, spread: 0.86, opacity: 0.96, reducedGraphicsMultiplier: 0.5 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.02, duration: 0.44, color: '#fbe18d', secondaryColor: '#8bd9ec', scale: 0.13, count: 4, speed: 0.64, rise: 0.96, spread: 0.54, opacity: 0.8, reducedGraphicsMultiplier: 0.5 },
      { type: 'lightPulse', anchor: 'target', texture: 'magicGlow', startTime: 0, duration: 0.42, color: '#fbe28d', secondaryColor: '#9be4f5', scale: 1.3, opacity: 0.5, reducedGraphicsMultiplier: 0.62 },
      { type: 'screenFlash', anchor: 'screen', startTime: 0.04, duration: 0.1, color: '#fae59a', opacity: 0.08, reducedGraphicsMultiplier: 0.5 },
    ],
  },
  {
    id: 'support_regen_aura', label: 'Aura de régénération', duration: 0.72, impactTime: 0.3,
    tags: ['support', 'regen'], particleBudget: 12, reducedGraphicsScale: 0.56,
    steps: [
      { type: 'spriteSheet', anchor: 'targetGround', spriteSheet: 'regen_aura', startTime: 0.01, duration: 0.62, scale: 1.48, opacity: 0.98, blending: 'normal', reducedGraphicsMultiplier: 0.8 },
      { type: 'groundRing', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.04, duration: 0.57, color: '#9bf2b3', secondaryColor: '#2c9b6b', scale: 1.2, radius: 1.02, opacity: 0.65, reducedGraphicsMultiplier: 0.62 },
      { type: 'sparkleBurst', anchor: 'target', texture: 'sparkle', startTime: 0.12, duration: 0.48, color: '#e8ffe9', secondaryColor: '#68dd99', scale: 0.13, count: 8, speed: 0.55, rise: 1.04, spread: 0.62, opacity: 0.9, reducedGraphicsMultiplier: 0.52 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.2, duration: 0.38, color: '#c2ffcf', secondaryColor: '#4ecb79', scale: 0.12, count: 4, speed: 0.42, rise: 0.72, spread: 0.46, opacity: 0.76, reducedGraphicsMultiplier: 0.5 },
      { type: 'lightPulse', anchor: 'target', texture: 'magicGlow', startTime: 0.16, duration: 0.4, color: '#b9ffca', secondaryColor: '#5bd78d', scale: 1.18, opacity: 0.42, reducedGraphicsMultiplier: 0.58 },
    ],
  },
  {
    id: 'support_revive_pillar', label: 'Pilier de résurrection', duration: 0.9, impactTime: 0.44,
    tags: ['support', 'revive', 'holy'], particleBudget: 16, reducedGraphicsScale: 0.54,
    steps: [
      { type: 'spriteSheet', anchor: 'targetGround', spriteSheet: 'revive_pillar', startTime: 0, duration: 0.82, scale: 1.74, opacity: 1, blending: 'normal', reducedGraphicsMultiplier: 0.8 },
      { type: 'groundRing', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.04, duration: 0.72, color: '#fff2b8', secondaryColor: '#8edcff', scale: 1.4, radius: 1.12, opacity: 0.76, reducedGraphicsMultiplier: 0.62 },
      { type: 'magicCircle', anchor: 'targetGround', texture: 'magicCircle', startTime: 0.06, duration: 0.68, color: '#fff6ca', secondaryColor: '#83dbff', scale: 1.08, opacity: 0.58, rotation: 0.32, reducedGraphicsMultiplier: 0.58 },
      { type: 'sparkleBurst', anchor: 'target', texture: 'sparkle', startTime: 0.19, duration: 0.54, color: '#ffffff', secondaryColor: '#ffd96e', scale: 0.15, count: 12, speed: 0.7, rise: 1.45, spread: 0.76, opacity: 0.96, reducedGraphicsMultiplier: 0.52 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.3, duration: 0.38, color: '#dff5ff', secondaryColor: '#f6d679', scale: 0.13, count: 4, speed: 0.5, rise: 0.92, spread: 0.42, opacity: 0.82, reducedGraphicsMultiplier: 0.5 },
      { type: 'lightPulse', anchor: 'target', texture: 'magicGlow', startTime: 0.23, duration: 0.48, color: '#fff6ce', secondaryColor: '#91ddff', scale: 1.34, opacity: 0.56, reducedGraphicsMultiplier: 0.62 },
    ],
  },
  {
    id: 'support_holy_aura', label: 'Aura sacrée', duration: 0.76, impactTime: 0.33,
    tags: ['support', 'holy', 'aura'], particleBudget: 12, reducedGraphicsScale: 0.56,
    steps: [
      { type: 'spriteSheet', anchor: 'targetGround', spriteSheet: 'holy_aura', startTime: 0.01, duration: 0.65, scale: 1.52, opacity: 0.98, blending: 'normal', reducedGraphicsMultiplier: 0.8 },
      { type: 'groundRing', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.05, duration: 0.59, color: '#d4f6ff', secondaryColor: '#f7dc86', scale: 1.24, radius: 1.02, opacity: 0.68, reducedGraphicsMultiplier: 0.62 },
      { type: 'magicCircle', anchor: 'targetGround', texture: 'magicCircle', startTime: 0.04, duration: 0.6, color: '#c6f4ff', secondaryColor: '#f6d77a', scale: 1.02, opacity: 0.54, rotation: -0.28, reducedGraphicsMultiplier: 0.58 },
      { type: 'sparkleBurst', anchor: 'target', texture: 'sparkle', startTime: 0.16, duration: 0.46, color: '#ffffff', secondaryColor: '#9ce8ff', scale: 0.13, count: 8, speed: 0.58, rise: 1.02, spread: 0.62, opacity: 0.9, reducedGraphicsMultiplier: 0.52 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.24, duration: 0.34, color: '#e6fbff', secondaryColor: '#f5d987', scale: 0.12, count: 4, speed: 0.45, rise: 0.7, spread: 0.44, opacity: 0.76, reducedGraphicsMultiplier: 0.5 },
    ],
  },
  {
    id: 'support_boost_aura', label: 'Aura d’élan', duration: 0.68, impactTime: 0.28,
    tags: ['support', 'boost', 'aura'], particleBudget: 10, reducedGraphicsScale: 0.58,
    steps: [
      { type: 'spriteSheet', anchor: 'targetGround', spriteSheet: 'boost_aura', startTime: 0.01, duration: 0.57, scale: 1.4, opacity: 0.98, blending: 'normal', reducedGraphicsMultiplier: 0.82 },
      { type: 'magicCircle', anchor: 'targetGround', texture: 'magicCircle', startTime: 0.04, duration: 0.52, color: '#b8f6ff', secondaryColor: '#4dc8e4', scale: 0.98, opacity: 0.48, rotation: -0.38, reducedGraphicsMultiplier: 0.58 },
      { type: 'sparkleBurst', anchor: 'target', texture: 'sparkle', startTime: 0.12, duration: 0.42, color: '#efffff', secondaryColor: '#66dff2', scale: 0.12, count: 8, speed: 0.58, rise: 0.88, spread: 0.58, opacity: 0.86, reducedGraphicsMultiplier: 0.52 },
      { type: 'particleBurst', anchor: 'target', texture: 'softParticle', startTime: 0.18, duration: 0.32, color: '#c9fbff', secondaryColor: '#55cee6', scale: 0.11, count: 2, speed: 0.42, rise: 0.64, spread: 0.36, opacity: 0.76, reducedGraphicsMultiplier: 0.5 },
      { type: 'lightPulse', anchor: 'target', texture: 'magicGlow', startTime: 0.14, duration: 0.36, color: '#b6f6ff', secondaryColor: '#55cce5', scale: 1.12, opacity: 0.42, reducedGraphicsMultiplier: 0.58 },
    ],
  },
  {
    id: 'move_smoke_burst', label: 'Écran de fumée', duration: 0.48, impactTime: 0.14,
    tags: ['movement', 'smoke', 'tactical'], particleBudget: 8, reducedGraphicsScale: 0.6,
    steps: [
      { type: 'spriteSheet', anchor: 'targetGround', spriteSheet: 'smoke_burst', startTime: 0, duration: 0.42, scale: 1.44, opacity: 0.86, blending: 'normal', reducedGraphicsMultiplier: 0.82 },
      { type: 'smokePuff', anchor: 'targetGround', texture: 'smokePuff', startTime: 0.04, duration: 0.38, color: '#29323b', secondaryColor: '#576a70', scale: 0.34, count: 5, speed: 0.52, rise: 0.62, spread: 0.8, opacity: 0.48, blending: 'normal', reducedGraphicsMultiplier: 0.56 },
      { type: 'particleBurst', anchor: 'targetGround', texture: 'softParticle', startTime: 0.1, duration: 0.3, color: '#9eb1b3', secondaryColor: '#536167', scale: 0.12, count: 3, speed: 0.54, rise: 0.48, spread: 0.58, opacity: 0.58, blending: 'normal', reducedGraphicsMultiplier: 0.5 },
    ],
  },
  {
    id: 'shape_cone_blast', label: 'Souffle conique', duration: 0.78, impactTime: 0.38,
    tags: ['shape', 'cone', 'impact'], particleBudget: 0, reducedGraphicsScale: 0.6,
    steps: [
      { type: 'spriteSheet', anchor: 'source', targetAnchor: 'groundTarget', sheetMode: 'projectile', spriteSheet: 'cone_blast', orientation: 'align_cone', startTime: 0.02, duration: 0.64, scale: 1.68, opacity: 1, blending: 'additive', reducedGraphicsMultiplier: 0.76 },
      { type: 'groundRing', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.18, duration: 0.46, color: '#ffdb86', secondaryColor: '#e67336', scale: 1.36, radius: 1.1, opacity: 0.5, reducedGraphicsMultiplier: 0.54 },
      { type: 'lightPulse', anchor: 'target', texture: 'magicGlow', startTime: 0.31, duration: 0.24, color: '#fff3b5', secondaryColor: '#e8843e', scale: 1.34, opacity: 0.52, reducedGraphicsMultiplier: 0.54 },
    ],
  },
  {
    id: 'impact_explosion_large', label: 'Grande explosion', duration: 0.88, impactTime: 0.42,
    tags: ['explosion', 'area', 'impact'], particleBudget: 0, reducedGraphicsScale: 0.56,
    steps: [
      { type: 'spriteSheet', anchor: 'targetGround', spriteSheet: 'explosion_large', startTime: 0.02, duration: 0.76, scale: 1.95, opacity: 1, blending: 'additive', reducedGraphicsMultiplier: 0.74 },
      { type: 'groundRing', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.12, duration: 0.56, color: '#ffe0a3', secondaryColor: '#ed6c36', scale: 1.58, radius: 1.22, opacity: 0.58, reducedGraphicsMultiplier: 0.52 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.4, duration: 0.16, scale: 0.2, reducedGraphicsMultiplier: 0.55 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.4, duration: 0.05 },
    ],
  },
  {
    id: 'boss_apocalypse_v2', label: 'Champ apocalypse', duration: 1.2, impactTime: 0.64,
    tags: ['boss', 'apocalypse', 'field'], particleBudget: 0, reducedGraphicsScale: 0.42,
    steps: [
      { type: 'spriteSheet', anchor: 'targetGround', spriteSheet: 'apocalypse_field', startTime: 0.02, duration: 1.04, scale: 2.24, opacity: 1, blending: 'additive', reducedGraphicsMultiplier: 0.72 },
      { type: 'magicCircle', anchor: 'targetGround', texture: 'magicCircle', startTime: 0.08, duration: 0.9, color: '#b074ff', secondaryColor: '#351449', scale: 1.94, opacity: 0.64, rotation: -0.5, reducedGraphicsMultiplier: 0.5 },
      { type: 'groundRing', anchor: 'targetGround', texture: 'ringGradient', startTime: 0.18, duration: 0.78, color: '#d59cff', secondaryColor: '#5a1c63', scale: 2.04, radius: 1.5, opacity: 0.62, reducedGraphicsMultiplier: 0.5 },
      { type: 'lightPulse', anchor: 'target', texture: 'magicGlow', startTime: 0.48, duration: 0.36, color: '#efd4ff', secondaryColor: '#7b358c', scale: 1.7, opacity: 0.62, reducedGraphicsMultiplier: 0.52 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.6, duration: 0.2, scale: 0.28, reducedGraphicsMultiplier: 0.52 },
      { type: 'hitStop', anchor: 'screen', startTime: 0.61, duration: 0.065 },
    ],
  },
  {
    id: 'thrust_line', label: 'Percée de lance', duration: 0.5, impactTime: 0.24,
    tags: ['physical', 'thrust', 'line'], particleBudget: 5, reducedGraphicsScale: 0.6,
    steps: [
      { type: 'spriteSheet', anchor: 'source', targetAnchor: 'target', spriteSheet: 'thrust_line', sheetMode: 'projectile', orientation: 'source_to_target', startTime: 0.02, duration: 0.38, scale: 1.2, opacity: 1, blending: 'normal', reducedGraphicsMultiplier: 0.72 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.22, duration: 0.18, color: '#fff9db', secondaryColor: '#dca34e', scale: 0.9, opacity: 0.96 },
      { type: 'particleBurst', anchor: 'target', texture: 'sparkle', startTime: 0.23, duration: 0.2, color: '#fff5d0', secondaryColor: '#d79c4e', scale: 0.11, count: 5, speed: 0.86, rise: 0.32, spread: 0.56, opacity: 0.78, reducedGraphicsMultiplier: 0.48 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.24, duration: 0.1, scale: 0.14, reducedGraphicsMultiplier: 0.55 },
    ],
  },
  {
    id: 'teleport_burst', label: 'Translation runique', duration: 0.46, impactTime: 0.2,
    tags: ['move', 'teleport'], particleBudget: 0, reducedGraphicsScale: 0.66,
    steps: [
      { type: 'spriteSheet', anchor: 'groundTarget', spriteSheet: 'teleport_burst', startTime: 0, duration: 0.43, scale: 1.2, opacity: 1, blending: 'normal', reducedGraphicsMultiplier: 0.76 },
      { type: 'magicCircle', anchor: 'groundTarget', texture: 'magicCircle', startTime: 0.03, duration: 0.34, color: '#b79aff', secondaryColor: '#70e5ed', scale: 1.02, opacity: 0.46, rotation: 0.38, reducedGraphicsMultiplier: 0.56 },
    ],
  },
  {
    id: 'holy_strike', label: 'Frappe sacrée', duration: 0.56, impactTime: 0.24,
    tags: ['holy', 'physical', 'impact'], particleBudget: 0, reducedGraphicsScale: 0.62,
    steps: [
      { type: 'spriteSheet', anchor: 'target', spriteSheet: 'slash_arc', orientation: 'source_to_target', startTime: 0.02, duration: 0.34, scale: 1.42, opacity: 1, blending: 'additive', reducedGraphicsMultiplier: 0.74 },
      { type: 'spriteSheet', anchor: 'target', spriteSheet: 'holy_aura', startTime: 0.1, duration: 0.42, scale: 1.12, opacity: 0.86, blending: 'additive', reducedGraphicsMultiplier: 0.68 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.22, duration: 0.19, color: '#fffde6', secondaryColor: '#f4ca62', scale: 1.04, opacity: 1 },
    ],
  },
  {
    id: 'leap_impact', label: 'Impact de saut', duration: 0.58, impactTime: 0.28,
    tags: ['move', 'landing', 'impact'], particleBudget: 0, reducedGraphicsScale: 0.64,
    steps: [
      { type: 'spriteSheet', anchor: 'groundTarget', spriteSheet: 'leap_impact', startTime: 0.04, duration: 0.48, scale: 1.38, opacity: 1, blending: 'normal', reducedGraphicsMultiplier: 0.74 },
      { type: 'shockwave', anchor: 'groundTarget', texture: 'ringGradient', startTime: 0.2, duration: 0.32, color: '#f6d28b', secondaryColor: '#92633b', scale: 1.16, radius: 0.9, count: 3, opacity: 0.7, reducedGraphicsMultiplier: 0.5 },
      { type: 'screenShake', anchor: 'camera', startTime: 0.25, duration: 0.12, scale: 0.2, reducedGraphicsMultiplier: 0.55 },
    ],
  },
  {
    id: 'caster_roar', label: 'Onde de commandement', duration: 0.54, impactTime: 0.2,
    tags: ['support', 'debuff', 'caster'], particleBudget: 0, reducedGraphicsScale: 0.66,
    steps: [
      { type: 'spriteSheet', anchor: 'sourceGround', spriteSheet: 'shockwave_ring', startTime: 0.02, duration: 0.42, scale: 1.28, opacity: 0.9, blending: 'additive', reducedGraphicsMultiplier: 0.72 },
      { type: 'shockwave', anchor: 'sourceGround', texture: 'ringGradient', startTime: 0.08, duration: 0.36, color: '#f0ba67', secondaryColor: '#9b5338', scale: 1.2, radius: 1, count: 3, opacity: 0.65, reducedGraphicsMultiplier: 0.52 },
      { type: 'lightPulse', anchor: 'source', texture: 'magicGlow', startTime: 0.05, duration: 0.28, color: '#ffd982', secondaryColor: '#ff785b', scale: 0.92, opacity: 0.42, reducedGraphicsMultiplier: 0.56 },
    ],
  },
  {
    id: 'arrow_rain', label: 'Pluie de flèches', duration: 0.76, impactTime: 0.44,
    tags: ['ranged', 'area', 'multi-impact'], particleBudget: 7, reducedGraphicsScale: 0.58,
    steps: [
      { type: 'spriteSheet', anchor: 'source', targetAnchor: 'groundTarget', spriteSheet: 'projectile_shot', sheetMode: 'projectile', orientation: 'source_to_target', startTime: 0.03, duration: 0.54, scale: 1.06, opacity: 1, blending: 'normal', reducedGraphicsMultiplier: 0.74 },
      { type: 'projectile', anchor: 'source', targetAnchor: 'groundTarget', texture: 'projectileCore', orientation: 'source_to_target', startTime: 0.1, duration: 0.3, color: '#fdf7d8', secondaryColor: '#dc9f51', scale: 0.2, count: 3, opacity: 0.9, reducedGraphicsMultiplier: 0.5 },
      { type: 'impactStar', anchor: 'target', texture: 'impactStar', startTime: 0.4, duration: 0.18, color: '#fffbe7', secondaryColor: '#d9a151', scale: 0.84, opacity: 0.92 },
      { type: 'particleBurst', anchor: 'targetGround', texture: 'sparkle', startTime: 0.42, duration: 0.2, color: '#ffe2a1', secondaryColor: '#a8723a', scale: 0.1, count: 4, speed: 0.72, rise: 0.22, spread: 0.52, opacity: 0.72, reducedGraphicsMultiplier: 0.44 },
    ],
  },
] as const satisfies readonly VfxPreset[];

const completePresetPack = [...presets, ...PREMIUM_VFX_PRESETS] as const satisfies readonly VfxPreset[];

export const VFX_PRESETS: Readonly<Record<string, VfxPreset>> = Object.freeze(
  Object.fromEntries(completePresetPack.map((preset) => [preset.id, preset])),
);

export const VFX_PRESET_IDS = Object.freeze(completePresetPack.map((preset) => preset.id));

export function getVfxPreset(id: string): VfxPreset | undefined {
  return VFX_PRESETS[id];
}
