/**
 * Phase 4C-GLM — Character Registry & Roster Census
 *
 * Authoritative census of all playable/core characters derived from
 * repository data (game catalog + asset manifest).  Preview captions are
 * never used — only repository data is authoritative.
 */

import type { OptionCCharacterIdentity, OptionCArtStatus } from './OptionCCharacterSchema';

// ---------------------------------------------------------------------------
// Roster census entry (Section 8)
// ---------------------------------------------------------------------------

export interface OptionCRosterCensusEntry {
  readonly characterId: string;
  readonly canonicalAssetPath: string;
  readonly displayName: string;
  readonly role: string;
  readonly weapon: string;
  readonly combatArchetype: string;
  readonly silhouetteTraits: string;
  readonly headgearMaskHair: string;
  readonly primaryPalette: readonly string[];
  readonly secondaryEquipment: string;
  readonly currentRuntimeUsage: string;
  readonly currentCombatUsage: string;
  readonly currentTableauUsage: string;
  readonly animationNeeds: string;
  readonly optionCStatus: OptionCArtStatus;
}

// ---------------------------------------------------------------------------
// Census — derived from src/game/catalog.ts + src/render/assetManifest.ts
// ---------------------------------------------------------------------------

export const PLAYABLE_ROSTER_CENSUS: readonly OptionCRosterCensusEntry[] = Object.freeze([
  {
    characterId: 'warrior',
    canonicalAssetPath: '/assets/characters/pixel/full/alistair.png',
    displayName: 'Alistair',
    role: 'Frontline knight / tank',
    weapon: 'greatsword',
    combatArchetype: 'knight',
    silhouetteTraits: 'Frontline knight, wide defensive stance',
    headgearMaskHair: 'Steel helm with Lion crest',
    primaryPalette: ['emerald', 'steel', 'gold'],
    secondaryEquipment: 'Heavy plate armor, greatsword, tower shield',
    currentRuntimeUsage: 'Production portrait + dialogue actor',
    currentCombatUsage: 'Default clan member (warrior), melee range 1',
    currentTableauUsage: 'Staged as PLAYER_COMPANY listener opposite Kestrel',
    animationNeeds: 'idle, dash, attack (heavy swing), skill (whirl/charge)',
    optionCStatus: 'ART_PENDING_CODEX',
  },
  {
    characterId: 'white_mage',
    canonicalAssetPath: '/assets/characters/pixel/full/marian.png',
    displayName: 'Marian',
    role: 'Healer / support caster',
    weapon: 'crosier',
    combatArchetype: 'cleric',
    silhouetteTraits: 'Sacred cleric with staff and protective robes',
    headgearMaskHair: 'White hood / veil with gold circlet',
    primaryPalette: ['white', 'gold', 'silver'],
    secondaryEquipment: 'Crosier staff, flowing robes',
    currentRuntimeUsage: 'Production portrait + dialogue actor',
    currentCombatUsage: 'Default clan member (white_mage), heal/support',
    currentTableauUsage: 'Staged in group scenes as PLAYER_COMPANY',
    animationNeeds: 'idle, dash, attack (staff strike), cast (heal/sanctuary)',
    optionCStatus: 'ART_PENDING_CODEX',
  },
  {
    characterId: 'dark_mage',
    canonicalAssetPath: '/assets/characters/pixel/full/elara.png',
    displayName: 'Elara',
    role: 'Arcane damage caster',
    weapon: 'grimoire',
    combatArchetype: 'mage',
    silhouetteTraits: 'Arcane caster with pointed hat and glowing staff',
    headgearMaskHair: 'Pointed wizard hat',
    primaryPalette: ['arcane blue', 'cyan', 'gold'],
    secondaryEquipment: 'Grimoire tome, glowing staff',
    currentRuntimeUsage: 'Production portrait + dialogue actor',
    currentCombatUsage: 'Default clan member (dark_mage), ranged magic',
    currentTableauUsage: 'Staged in group scenes as PLAYER_COMPANY',
    animationNeeds: 'idle, dash, attack (bolt), cast (meteor/flame wave)',
    optionCStatus: 'ART_PENDING_CODEX',
  },
  {
    characterId: 'archer',
    canonicalAssetPath: '/assets/characters/pixel/full/kestrel.png',
    displayName: 'Kestrel',
    role: 'Mobile ranged scout',
    weapon: 'longbow',
    combatArchetype: 'archer',
    silhouetteTraits: 'Mobile hooded archer',
    headgearMaskHair: 'Forest hood',
    primaryPalette: ['forest green', 'leather brown', 'night blue'],
    secondaryEquipment: 'Longbow, quiver, light leather armor',
    currentRuntimeUsage: 'Production portrait + dialogue actor + Phase 4B animated proof',
    currentCombatUsage: 'Default clan member (archer), ranged 4, min 2',
    currentTableauUsage: 'Phase 4B tableau proof: LEFT/RIGHT/CENTER speaker',
    animationNeeds: 'idle, dash, attack, skill — ALL VALIDATED (8 frames each)',
    optionCStatus: 'GOLD_REFERENCE',
  },
  {
    characterId: 'rogue',
    canonicalAssetPath: '/assets/characters/pixel/full/cedric.png',
    displayName: 'Cedric',
    role: 'Stealth scout / backline DPS',
    weapon: 'dagger',
    combatArchetype: 'rogue',
    silhouetteTraits: 'Nomad scout, lighter than Kestrel',
    headgearMaskHair: 'Light hood / scarf',
    primaryPalette: ['sand', 'muted green', 'light leather'],
    secondaryEquipment: 'Daggers, light leather',
    currentRuntimeUsage: 'Production portrait + dialogue actor (optional recruit)',
    currentCombatUsage: 'Optional recruit (rogue), melee range 1, high crit',
    currentTableauUsage: 'Optional in group scenes',
    animationNeeds: 'idle, dash, attack (backstab), skill (trap/tumble)',
    optionCStatus: 'ART_PENDING_CODEX',
  },
  {
    characterId: 'lancer',
    canonicalAssetPath: '/assets/characters/pixel/full/lancer.png',
    displayName: 'Garen',
    role: 'Reach melee / spearman',
    weapon: 'long_spear',
    combatArchetype: 'knight',
    silhouetteTraits: 'Young Lion militiaman with spear and shield',
    headgearMaskHair: 'Light helm / cap',
    primaryPalette: ['steel', 'emerald', 'gold'],
    secondaryEquipment: 'Long spear, round shield',
    currentRuntimeUsage: 'Production portrait + dialogue actor (optional recruit)',
    currentCombatUsage: 'Optional recruit (lancer), melee range 2',
    currentTableauUsage: 'Optional in group scenes',
    animationNeeds: 'idle, dash, attack (thrust), skill (griffon jump)',
    optionCStatus: 'ART_PENDING_CODEX',
  },
  {
    characterId: 'paladin',
    canonicalAssetPath: '/assets/characters/pixel/full/aldric.png',
    displayName: 'Aldric',
    role: 'Holy knight / hybrid',
    weapon: 'holy_mace',
    combatArchetype: 'knight',
    silhouetteTraits: 'Paladin knight with holy aura and shield',
    headgearMaskHair: 'Holy helm with aura',
    primaryPalette: ['gold', 'ivory', 'steel'],
    secondaryEquipment: 'Holy mace, shield, holy aura',
    currentRuntimeUsage: 'Production portrait + dialogue actor (optional recruit)',
    currentCombatUsage: 'Optional recruit (paladin), melee range 1, hybrid magic',
    currentTableauUsage: 'Optional in group scenes',
    animationNeeds: 'idle, dash, attack (mace strike), cast (holy judgement)',
    optionCStatus: 'ART_PENDING_CODEX',
  },
  {
    characterId: 'dark_knight',
    canonicalAssetPath: '/assets/characters/pixel/full/morvan.png',
    displayName: 'Morvan',
    role: 'Dark melee / life-steal',
    weapon: 'scythe',
    combatArchetype: 'knight',
    silhouetteTraits: 'Dark knight wielding cursed blade',
    headgearMaskHair: 'Dark helm / cowl',
    primaryPalette: ['dark gold', 'black', 'wine'],
    secondaryEquipment: 'Scythe, dark armor',
    currentRuntimeUsage: 'Production portrait + dialogue actor (late recruit)',
    currentCombatUsage: 'Late recruit (dark_knight), melee range 2, life steal',
    currentTableauUsage: 'Late-game group scenes, high story importance',
    animationNeeds: 'idle, dash, attack (scythe sweep), cast (cursed blade/eclipse)',
    optionCStatus: 'ART_PENDING_CODEX',
  },
  {
    characterId: 'red_mage',
    canonicalAssetPath: '/assets/characters/pixel/full/lyra.png',
    displayName: 'Lyra',
    role: 'Hybrid melee/magic duelist',
    weapon: 'rapier',
    combatArchetype: 'mage',
    silhouetteTraits: 'Red mage hybrid casting both steel and spells',
    headgearMaskHair: 'Crimson hat / feather',
    primaryPalette: ['crimson', 'silver', 'gold'],
    secondaryEquipment: 'Rapier, spell focus',
    currentRuntimeUsage: 'Production portrait + dialogue actor (late recruit)',
    currentCombatUsage: 'Late recruit (red_mage), melee/magic range 2',
    currentTableauUsage: 'Late-game group scenes',
    animationNeeds: 'idle, dash, attack (rapier lunge), cast (scarlet circle)',
    optionCStatus: 'ART_PENDING_CODEX',
  },
  {
    characterId: 'enchanter',
    canonicalAssetPath: '/assets/characters/pixel/full/eldwin.png',
    displayName: 'Eldwin',
    role: 'Support enchanter / debuffer',
    weapon: 'wand',
    combatArchetype: 'cleric',
    silhouetteTraits: 'Enchanter scholar with runes and seals',
    headgearMaskHair: 'Scholar cap / hood',
    primaryPalette: ['teal', 'parchment', 'silver'],
    secondaryEquipment: 'Wand/scepter, runes, seals',
    currentRuntimeUsage: 'Production portrait + dialogue actor (late recruit)',
    currentCombatUsage: 'Late recruit (enchanter), support range 1',
    currentTableauUsage: 'Late-game group scenes',
    animationNeeds: 'idle, dash, attack (rune bolt), cast (binding seal)',
    optionCStatus: 'ART_PENDING_CODEX',
  },
  {
    characterId: 'ninja',
    canonicalAssetPath: '/assets/characters/pixel/full/talon.png',
    displayName: 'Talon',
    role: 'Silent assassin / ranged rogue',
    weapon: 'shuriken',
    combatArchetype: 'rogue',
    silhouetteTraits: 'Ninja guardian with silent step and venom blade',
    headgearMaskHair: 'Mask / cowl',
    primaryPalette: ['midnight', 'silver', 'violet'],
    secondaryEquipment: 'Shuriken, venom blade, smoke bombs',
    currentRuntimeUsage: 'Production portrait + dialogue actor (late recruit)',
    currentCombatUsage: 'Late recruit (ninja), ranged 3, double strike',
    currentTableauUsage: 'Late-game group scenes',
    animationNeeds: 'idle, dash, attack (shuriken throw), cast (shadow step)',
    optionCStatus: 'ART_PENDING_CODEX',
  },
  {
    characterId: 'artillerist',
    canonicalAssetPath: '/assets/characters/pixel/full/gunnar.png',
    displayName: 'Gunnar',
    role: 'Ranged AoE / siege',
    weapon: 'hand_cannon',
    combatArchetype: 'archer',
    silhouetteTraits: 'Artillerist with crossbow and explosive ordnance',
    headgearMaskHair: 'Steel cap / goggles',
    primaryPalette: ['steel', 'olive', 'copper'],
    secondaryEquipment: 'Hand cannon, explosives',
    currentRuntimeUsage: 'Production portrait + dialogue actor (late recruit)',
    currentCombatUsage: 'Late recruit (artillerist), ranged 4, AoE',
    currentTableauUsage: 'Late-game group scenes',
    animationNeeds: 'idle, dash, attack (cannon fire), cast (artillery barrage)',
    optionCStatus: 'ART_PENDING_CODEX',
  },
]);

// ---------------------------------------------------------------------------
// Identity specs (Section 9) — one per core character
// ---------------------------------------------------------------------------

export const CHARACTER_IDENTITY_SPECS: readonly OptionCCharacterIdentity[] = Object.freeze([
  {
    id: 'warrior',
    displayName: 'Alistair',
    canonicalSource: '/assets/characters/pixel/full/alistair.png',
    weapon: 'greatsword',
    archetype: 'knight',
    silhouetteClass: 'heavy_frontline',
    bodyClass: 'heavy',
    headProfile: 'Steel helm with Lion crest, broad shoulders',
    maskProfile: 'Open-faced helm, no mask',
    paletteFamily: ['emerald', 'steel', 'gold'],
    equipmentProfile: 'Heavy plate armor, greatsword, tower shield',
    tableauRequirements: 'LEFT or RIGHT standing pose, wide stance, facing speaker',
    strategicRequirements: 'Frontline grid position, heavy silhouette readable at distance',
    combatStageRequirements: 'Melee range 1, heavy swing arc, shield block pose',
    animationStates: ['idle', 'dash', 'attack', 'skill'],
  },
  {
    id: 'white_mage',
    displayName: 'Marian',
    canonicalSource: '/assets/characters/pixel/full/marian.png',
    weapon: 'crosier',
    archetype: 'cleric',
    silhouetteClass: 'robed_caster',
    bodyClass: 'robed',
    headProfile: 'White hood/veil with gold circlet, serene expression',
    maskProfile: 'Veil/hood, no mask',
    paletteFamily: ['white', 'gold', 'silver'],
    equipmentProfile: 'Crosier staff, flowing white robes',
    tableauRequirements: 'LEFT or RIGHT standing pose, staff visible, calm posture',
    strategicRequirements: 'Backline grid position, robed silhouette distinct from armored units',
    combatStageRequirements: 'Staff cast animation, heal VFX alignment at staff tip',
    animationStates: ['idle', 'dash', 'attack', 'cast'],
  },
  {
    id: 'dark_mage',
    displayName: 'Elara',
    canonicalSource: '/assets/characters/pixel/full/elara.png',
    weapon: 'grimoire',
    archetype: 'mage',
    silhouetteClass: 'robed_caster',
    bodyClass: 'robed',
    headProfile: 'Pointed wizard hat, arcane glow',
    maskProfile: 'Hat shadow, no mask',
    paletteFamily: ['arcane blue', 'cyan', 'gold'],
    equipmentProfile: 'Grimoire tome, glowing staff',
    tableauRequirements: 'LEFT or RIGHT standing pose, staff glowing, hat readable',
    strategicRequirements: 'Backline grid position, pointed hat distinguishes from Marian',
    combatStageRequirements: 'Grimoire open cast animation, magic VFX from tome',
    animationStates: ['idle', 'dash', 'attack', 'cast'],
  },
  {
    id: 'archer',
    displayName: 'Kestrel',
    canonicalSource: '/assets/characters/pixel/full/kestrel.png',
    weapon: 'longbow',
    archetype: 'archer',
    silhouetteClass: 'lithe_ranged',
    bodyClass: 'lithe',
    headProfile: 'Forest hood, sharp eyes',
    maskProfile: 'Hood, no mask',
    paletteFamily: ['forest green', 'leather brown', 'night blue'],
    equipmentProfile: 'Longbow, quiver, light leather armor',
    tableauRequirements: 'LEFT/RIGHT/CENTER, hooded silhouette, bow visible',
    strategicRequirements: 'Mobile grid position, lithe silhouette, range 4',
    combatStageRequirements: 'Bow draw animation, arrow release VFX, dash mobility',
    animationStates: ['idle', 'dash', 'attack', 'skill'],
  },
  {
    id: 'rogue',
    displayName: 'Cedric',
    canonicalSource: '/assets/characters/pixel/full/cedric.png',
    weapon: 'dagger',
    archetype: 'rogue',
    silhouetteClass: 'lithe_melee',
    bodyClass: 'lithe',
    headProfile: 'Light hood/scarf, lean face',
    maskProfile: 'Scarf/hood partial',
    paletteFamily: ['sand', 'muted green', 'light leather'],
    equipmentProfile: 'Daggers, light leather',
    tableauRequirements: 'LEFT or RIGHT, lighter silhouette than Kestrel',
    strategicRequirements: 'Flanking grid position, small silhouette',
    combatStageRequirements: 'Backstab animation, trap placement, tumble dodge',
    animationStates: ['idle', 'dash', 'attack', 'skill'],
  },
  {
    id: 'lancer',
    displayName: 'Garen',
    canonicalSource: '/assets/characters/pixel/full/lancer.png',
    weapon: 'long_spear',
    archetype: 'knight',
    silhouetteClass: 'medium_frontline',
    bodyClass: 'medium',
    headProfile: 'Light helm/cap, young face',
    maskProfile: 'Cap/helm, no mask',
    paletteFamily: ['steel', 'emerald', 'gold'],
    equipmentProfile: 'Long spear, round shield',
    tableauRequirements: 'LEFT or RIGHT, spear visible, shield readable',
    strategicRequirements: 'Frontline grid position, spear reach distinguishes from warrior',
    combatStageRequirements: 'Thrust animation, griffon jump skill, shield block',
    animationStates: ['idle', 'dash', 'attack', 'skill'],
  },
  {
    id: 'paladin',
    displayName: 'Aldric',
    canonicalSource: '/assets/characters/pixel/full/aldric.png',
    weapon: 'holy_mace',
    archetype: 'knight',
    silhouetteClass: 'heavy_holy',
    bodyClass: 'heavy',
    headProfile: 'Holy helm with aura, radiant',
    maskProfile: 'Helm, no mask',
    paletteFamily: ['gold', 'ivory', 'steel'],
    equipmentProfile: 'Holy mace, shield, holy aura',
    tableauRequirements: 'LEFT or RIGHT, aura glow, imposing stance',
    strategicRequirements: 'Frontline grid position, aura distinguishes from Alistair',
    combatStageRequirements: 'Mace strike, holy judgement cast, interpose block',
    animationStates: ['idle', 'dash', 'attack', 'cast'],
  },
  {
    id: 'dark_knight',
    displayName: 'Morvan',
    canonicalSource: '/assets/characters/pixel/full/morvan.png',
    weapon: 'scythe',
    archetype: 'knight',
    silhouetteClass: 'heavy_dark',
    bodyClass: 'heavy',
    headProfile: 'Dark helm/cowl, menacing',
    maskProfile: 'Cowl/helm shadow',
    paletteFamily: ['dark gold', 'black', 'wine'],
    equipmentProfile: 'Scythe, dark armor',
    tableauRequirements: 'LEFT or RIGHT, dark imposing silhouette, scythe visible',
    strategicRequirements: 'Frontline grid position, dark palette distinguishes from all',
    combatStageRequirements: 'Scythe sweep attack, cursed blade cast, void step dash',
    animationStates: ['idle', 'dash', 'attack', 'cast'],
  },
  {
    id: 'red_mage',
    displayName: 'Lyra',
    canonicalSource: '/assets/characters/pixel/full/lyra.png',
    weapon: 'rapier',
    archetype: 'mage',
    silhouetteClass: 'medium_hybrid',
    bodyClass: 'medium',
    headProfile: 'Crimson hat/feather, duelist expression',
    maskProfile: 'No mask',
    paletteFamily: ['crimson', 'silver', 'gold'],
    equipmentProfile: 'Rapier, spell focus',
    tableauRequirements: 'LEFT or RIGHT, rapier visible, crimson palette',
    strategicRequirements: 'Mid-grid position, hybrid melee/magic',
    combatStageRequirements: 'Rapier lunge attack, scarlet circle cast, rune step dash',
    animationStates: ['idle', 'dash', 'attack', 'cast'],
  },
  {
    id: 'enchanter',
    displayName: 'Eldwin',
    canonicalSource: '/assets/characters/pixel/full/eldwin.png',
    weapon: 'wand',
    archetype: 'cleric',
    silhouetteClass: 'robed_scholar',
    bodyClass: 'robed',
    headProfile: 'Scholar cap/hood, thoughtful',
    maskProfile: 'No mask',
    paletteFamily: ['teal', 'parchment', 'silver'],
    equipmentProfile: 'Wand/scepter, runes, seals',
    tableauRequirements: 'LEFT or RIGHT, wand visible, scholarly posture',
    strategicRequirements: 'Backline grid position, teal palette distinguishes from Marian',
    combatStageRequirements: 'Rune bolt attack, binding seal cast, transpose dash',
    animationStates: ['idle', 'dash', 'attack', 'cast'],
  },
  {
    id: 'ninja',
    displayName: 'Talon',
    canonicalSource: '/assets/characters/pixel/full/talon.png',
    weapon: 'shuriken',
    archetype: 'rogue',
    silhouetteClass: 'lithe_stealth',
    bodyClass: 'lithe',
    headProfile: 'Mask/cowl, hidden face',
    maskProfile: 'Full mask',
    paletteFamily: ['midnight', 'silver', 'violet'],
    equipmentProfile: 'Shuriken, venom blade, smoke bombs',
    tableauRequirements: 'LEFT or RIGHT, masked silhouette, dark palette',
    strategicRequirements: 'Flanking grid position, smallest humanoid silhouette',
    combatStageRequirements: 'Shuriken throw, shadow step dash, smoke bomb cast',
    animationStates: ['idle', 'dash', 'attack', 'cast'],
  },
  {
    id: 'artillerist',
    displayName: 'Gunnar',
    canonicalSource: '/assets/characters/pixel/full/gunnar.png',
    weapon: 'hand_cannon',
    archetype: 'archer',
    silhouetteClass: 'medium_ranged',
    bodyClass: 'medium',
    headProfile: 'Steel cap/goggles, stocky',
    maskProfile: 'Goggles, no mask',
    paletteFamily: ['steel', 'olive', 'copper'],
    equipmentProfile: 'Hand cannon, explosives',
    tableauRequirements: 'LEFT or RIGHT, cannon visible, stocky silhouette',
    strategicRequirements: 'Backline grid position, cannon distinguishes from Kestrel bow',
    combatStageRequirements: 'Cannon fire attack, artillery barrage cast, explosive retreat',
    animationStates: ['idle', 'dash', 'attack', 'cast'],
  },
]);

// ---------------------------------------------------------------------------
// Registry lookup helpers
// ---------------------------------------------------------------------------

const CENSUS_BY_ID = new Map(PLAYABLE_ROSTER_CENSUS.map((entry) => [entry.characterId, entry]));
const IDENTITY_BY_ID = new Map(CHARACTER_IDENTITY_SPECS.map((spec) => [spec.id, spec]));

export function getCensusEntry(characterId: string): OptionCRosterCensusEntry | undefined {
  return CENSUS_BY_ID.get(characterId);
}

export function getIdentitySpec(characterId: string): OptionCCharacterIdentity | undefined {
  return IDENTITY_BY_ID.get(characterId);
}

export function getAllPlayableCharacterIds(): readonly string[] {
  return PLAYABLE_ROSTER_CENSUS.map((entry) => entry.characterId);
}

export function getGoldReferenceCharacterId(): string {
  return 'archer'; // Kestrel
}
